DFE-Digital/get-help-with-tech

app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, spec/features/feature_flags/static_guidance_only_feature_flag_spec.rb
Matches:
https://design-system.service.gov.uk/patterns/page-not-found-pages/
https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/
=> Update 404 and 500 pages to match design system

app/views/pages/guidance.html.erb, config/locales/en.yml, spec/features/feature_flags/http_basic_auth_spec.rb, spec/features/feature_flags/static_guidance_only_feature_flag_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/features/view_pages_spec.rb
Latest version of guidance, rolling out to real users today
=> Update guidance to approved version for rollout

app/helpers/view_helper.rb, app/views/mno/recipients/index.html.erb, app/webpacker/styles/pagination.scss, config/initializers/pagination.rb, config/locales/en.yml
* Add missing page title
* Show "Requests 1-20 of 100" as heading above requests table
* Put pagination inline with "set status" form
* Use correct link colour for sortable table headings
=> Usability tweaks

config/routes.rb, spec/features/signing_in_as_different_types_of_user_spec.rb
We want a more descriptive guidance URL.
- amend the slug
- put in a redirect
=> Amend the guidance slug

README.md
- add Docker to pre-requisites
- Treat the deployment process as a pipeline
=> Improvements to deployment process documentation

app/helpers/view_helper.rb, app/views/layouts/application.html.erb
=> The feedback link should be a mailto

app/controllers/pages_controller.rb, app/views/pages/_eligibility.html.erb, app/views/pages/guidance.html.erb, app/views/pages/suggested_email_to_schools.html.erb, app/webpacker/styles/application.scss, config/locales/en.yml, config/routes.rb
We want to provide trusts and local authorities with suggested comms to explain the offer to their schools.
This page will be deep-linked to from the Notify comms that we send out.
=> Comms to schools

README.md
None of us knew how to do it straight away.
Document how to get to the rails console in the README.
=> Document how to launch 'rails console' on PaaS

app/views/errors/forbidden.html.erb
You guys think your so fancy with our pen-test and STI PRs ... well here's one for ya! ;)
Fix typo.
=> fix mis-typed permisisions

app/views/guide_to_collecting_mobile_information/privacy.html.erb
=> For education, not of education

app/views/devices_guidance/4g_user_guidance.md, app/views/devices_guidance/google_domain_for_care_leavers_and_children_with_social_worker.md
The review of #151 flagged a couple of content issues.
- fix one erroneous link
- remove unnecessary italics
=> Devices guidance: fixes

README.md
It should be helpful for new team-members to know how the devices guidance can be changed, if it needs to be, without having to reverse-engineer the Ruby code.
- document the amends process in README.md
=> Document the devices guidance amend process in README.md

config/locales/en.yml
Changed order of devices content (all Google guidance together)
=> Re-order the devices guidance pages

app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md
Added info to fix Windows localadmin bug
=> Devices guidance: problems logging in to Windows devices

config/locales/en.yml
=> Reordered devices guidance

app/views/pages/about_bt_wifi.html.erb, app/views/pages/about_increasing_mobile_data.html.erb
Based on changes made in https://docs.google.com/document/d/1-K-Nj0JWEUgceYFA2dPL17NAtcj3plXQIp645kMYAkk/edit
https://trello.com/c/7pq5Yt9a/358-content-updates-to-static-guidance
=> Update How it works sections in guidance

app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb
=> Update EE offer date

config/locales/en.yml
=> Updated index to change tense in description

app/views/devices_guidance/index.html.erb
=> Updated devices description

app/views/devices_guidance/support_and_maintenance.md
=> Removed duplicate paragraph - support and maintenance

app/views/devices_guidance/allocation_and_specification.md
=> Removed phase 2 mentions

app/views/devices_guidance/about_the_offer.md
=> Removed phase 2 references

app/views/devices_guidance/about_the_offer.md
=> About: Updated phase 2 for PM release

app/views/devices_guidance/allocation_and_specification.md
=> Allocation: Updated phase 2 for PM release

app/views/devices_guidance/support_and_maintenance.md
=> Removed XMA phone number

app/views/devices_guidance/support_and_maintenance.md
=> Fixed formatting issue

app/models/school.rb, db/migrate/20200812140013_create_schools.rb, db/schema.rb
[Trello card](https://trello.com/c/hn9VkKnK/417-import-list-of-all-schools-their-responsible-bodies-from-gias)
Import schools
=> Create schools model

app/models/school.rb, app/models/school_data_file.rb
[Trello card](https://trello.com/c/zjrtM0LT/479-tweak-which-schools-are-imported) Adjust school import condition filters to allow Nurseries, City Technology Colleges and an academy on the Isles of Scilly to be added to the system.
Prevent exclusion of `City technology college` type, `Nursery` phase and the LA of Isles of Scilly.
Additional Schools should be imported during import process
=> Enabled Nurseries, City Tech Colleges and Isles of Scilly to onboard

app/views/devices_guidance/preparing_4g_wireless_routers.md
=> Updated 4G data allowance

app/views/layouts/application.html.erb, config/locales/en.yml
We are bringing the devices and connectivity work into one service. We need a single name across the whole lot.
Use a single service name everywhere.
=> Change to a consistent service name: Get help with technology

app/views/pages/start.html.erb, config/locales/en.yml, config/routes.rb
The start page will be used both for connectivity and devices offers.
Content amends on the start page.
=> Update the start page to cater to both devices and connectivity

db/schema.rb
Not sure why this is an issue but when i ran `rake db:migrate` it changed this file.
=> Uncommited DB schema changes

app/views/responsible_body/devices/schools/index.html.erb
It's only a list of maintained schools if it's a local authority.
=> Fix missing schools help text for trusts

app/views/devices_guidance/how_to_order.html.erb, app/webpacker/styles/components/_step-by-step-nav.scss
- Fix html id's
- Fix spacing issues with inset text
=> Fix minor issues with "How to order devices" page

app/controllers/responsible_body/home_controller.rb, app/controllers/sign_in_tokens_controller.rb, app/models/user.rb, app/views/responsible_body/home/privacy_notice.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200827125505_add_privacy_notice_seen_at_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/features/responsible_body/home_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/models/user_spec.rb
Show the privacy notice to first-time RB users.
=> Show privacy notice to responsible body users

app/views/layouts/application.html.erb
We reintroducing the privacy polices on the home page until we have a better solution to having two different policies that may or not relate to parts of the programme.
=> Re-introduce privacy policies on home page

Rakefile, app/webpacker/packs/application.js, app/webpacker/packs/warn-on-unsaved-changes.js, app/webpacker/packs/warn-on-unsaved-changes.test.js, lib/tasks/jest.rake, package.json, yarn.lock
- Don't let users partially fill in a form then click away (we've seen this happen in research)
- Run this on any form with a textarea or radio button
- Adds jest for JS unit tests
Functionality largely ported from Apply:
https://github.com/DFE-Digital/apply-for-teacher-training/pull/1824
=> Show JS warning if users try to leave a page with unsaved changes

lib/tasks/import_responsible_bodies.rake
=> add missing csv_uri: param

app/components/school_details_summary_list_component.rb, app/views/devices_guidance/device_allocations.md, app/views/responsible_body/devices/home/show.html.erb, spec/components/school_details_summary_list_component_spec.rb
=> Add links to query allocations

app/views/pages/accessibility.md
=> Update SLA on accessibility page

app/controllers/responsible_body/users_controller.rb, config/locales/en.yml
Show a green success banner after inviting someone
=> Add a flash message after successful invite

app/views/support/devices/responsible_bodies/index.html.erb, app/views/support/devices/responsible_bodies/show.html.erb, app/views/support/devices/service_performance/_preorder_information.html.erb, app/views/support/devices/service_performance/index.html.erb, app/views/support/internet/responsible_bodies/index.html.erb, app/views/support/internet/responsible_bodies/show.html.erb, app/views/support/internet/service_performance/index.html.erb, app/webpacker/styles/_card.scss, config/locales/en.yml
=> Initial tweaks to devices performance dasboard

app/controllers/responsible_body/users_controller.rb, app/models/invite_event.rb, app/services/feature_flag.rb, config/locales/en.yml
Allow us to see if and when RBs are inviting new users
```A user from CASTLE SCHOOL EDUCATION TRUST has invited someone to the service```
=> Send a Slack notification when an RB invites someone

app/views/responsible_body/devices/home/show.html.erb
- Bring RB guidance inline with proposed school journey
- Talk about "ordering a full allocation" rather than not being able to order
- Give the 2 examples of when devices can be requested
=> Include guidance about requesting devices

app/controllers/responsible_body/devices/home_controller.rb, app/views/responsible_body/devices/home/request_devices.html.erb, app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/devices/home/tell_us.html.erb, app/views/responsible_body/devices/schools/index.html.erb, config/locales/en.yml, config/routes.rb, spec/features/responsible_body/devices_setup_spec.rb
Responsible body users need to know how to request devices in special circumstances
* introduce a new 'Devices' homepage
* introduce a new 'Request devices in special circumstances' page
* update breadcrumbs and specs to match
=> New responsible body devices homepage, and a page for requesting devices in special circumstances

app/controllers/responsible_body/devices/home_controller.rb, app/controllers/school/home_controller.rb, app/views/school/home/show.html.erb, app/views/shared/devices/request_devices.html.erb, config/locales/en.yml, config/routes.rb, spec/features/school/request_devices_spec.rb
School users need to know how to request devices in special circumstances.
- display the guidance on requesting devices in special circumstances to school users
- link to the guidance from the schools homepage
Additionally:
- fix the heading font sizes on the schools home page
=> School users are informed about how to request devices

app/models/support/devices/service_performance.rb, app/views/support/devices/service_performance/_preorder_information.html.erb, config/locales/en.yml
- Show total devolved to, and total managed centrally
- Show overall total of schools
=> Clarify performance dashboard numbers

app/views/sign_in_tokens/sent.html.erb
=> Add missing full stop on the Check your Mail page

app/components/responsible_body/school_details_summary_list_component.rb, app/views/devices_guidance/device_allocations.md, app/views/devices_guidance/how_to_order.html.erb, spec/components/responsible_body/school_details_summary_list_component_spec.rb
* Add yr groups to guidance about allocation calculations
* tweak "Can't order yet" text on school details pages
=> Content tweaks

app/views/devices_guidance/preparing_chromebooks.md
COVID.TECHNOLOGY@education.gov.uk added as the contact method.
=> Support updates in devices guidance (1/3)

app/views/devices_guidance/support_and_maintenance.md
Updating password process and COVID.TECHNOLOGY@education.gov.uk added as the contact method.
=> Support updates in devices guidance (2/3)

app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md
Password process updates and COVID.TECHNOLOGY@education.gov.uk added as the contact method.
=> Support updates in devices guidance (3/3)

app/views/devices_guidance/device_allocations.md, app/views/devices_guidance/how_to_order.html.erb, app/views/school/details/show.html.erb, app/views/school/welcome_wizard/allocation.html.erb
It's years 3 to 11, not 3 to 10
https://trello.com/c/bz6NaLNm/620-devices-eligibility-should-be-years-3-11-not-3-10
=> Update the allocation age range to the correct one

app/views/responsible_body/devices/home/tell_us.html.erb, app/views/school/devices/cannot_order.html.erb, app/views/school/welcome_wizard/order_your_own.html.erb, app/views/shared/devices/_who_to_request_for.html.erb, app/views/shared/devices/_who_to_request_for_list.html.erb, app/views/shared/devices/request_devices.html.erb
- Clarify when evidence is needed, relating to shielding and geographical regions
- Specify that we need to know the year groups
- Highlight that devices can be for any year group
- Move text into shared partial
https://trello.com/c/I2YoCXcE/624-clarify-guidance-on-shielding
=> Update guidance on requesting devices

app/views/school/devices/cannot_order.html.erb, app/views/shared/devices/_who_to_request_for_list.html.erb
Update guidance to match policy
=> Clarify guidance on living with someone who's shielding

app/components/school/school_details_summary_list_component.rb, app/views/school/details/show.html.erb, app/views/school/welcome_wizard/allocation.html.erb, spec/components/school/school_details_summary_list_component_spec.rb
- Indicate that allocations can change on the school wizard
- Add missing "Query allocation" link
=> Update guidance on how allocations can change

README.md
You'd probably want to first see what the current settings are, before going to change them.
=> Update README: how to display feature flags

app/views/support/devices/responsible_bodies/show.html.erb, app/views/support/devices/schools/show.html.erb
- Make tables full width
- Remove headings and simplify table captions
- Fix link colour
=> Improve readability of RB and school support pages

app/views/school/welcome_wizard/techsource_account.html.erb, config/locales/en.yml, spec/features/school/navigate_school_welcome_wizard_spec.rb
We will be sending instructions now.
@benilovj Are the instructions in our emails already?
=> Remove reference to TechSource invitation email

app/views/support/devices/schools/results.html.erb, spec/features/support/devices/searching_schools_spec.rb, spec/page_objects/support/devices/schools/results_page.rb, spec/page_objects/support/devices/schools/search_page.rb
=> [750] Add feature spec for school search

app/views/layouts/_cookie_banner.html.erb
=> Fix spacing at bottom of cookie banner

app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/internet_access.html.erb, app/views/responsible_body/home/show.html.erb, app/views/responsible_body/internet/home/show.html.erb, app/views/shared/_pilot_mno_offer_eligibility.html.erb
- Remove MNO criteria about accessing a hotspot
- Switch offers around in guidance and service
=> Tweak connectivity offer positions in guidance and service

app/views/devices_guidance/how_to_order.html.erb
- some paragraphs were missing css class names
=> Fixes broken vertical line between task numbers

app/views/devices_guidance/device_distribution_and_ownership.md
=> Ownership policy update - Update device_distribution_and_ownership.md

app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md
=> reconfiguring devices - Update preparing_microsoft_windows_laptops_and_tablets.md

config/locales/en.yml
=> Updated description for distribution page

config/environments/test.rb
- Not sure why classes aren't cached in the test environment
- Cache class in test environment
- Possible speed improvement?
- Prevents the tests from failing if code is changed during a test run on local development environments
- Tests should continue to pass
=> Cache files in test environment

app/views/school/details/show.html.erb
- https://trello.com/c/OA5aqG8T/928-appeals-process
- Add extra copy on school details page
- Login as school user
- Check school details
- Should see additional new copy
=> [928] Add about allocations to school details

app/helpers/view_helper.rb, app/views/school/welcome_wizard/order_your_own.html.erb, config/locales/en.yml, spec/features/school/navigate_school_welcome_wizard_spec.rb
- https://trello.com/c/OA5aqG8T/928-appeals-process
- Update copy on order your own page in wizard
- Login as a new school user
- Go through the wizard
- Should see new copy on order your own page
=> [928] Tweak copy on order you own wizard page

docs/support/add_missing_school.md, docs/support/add_missing_trust.md, docs/support/move_school.md
[Trello card](https://trello.com/c/F6geZ1M1/939-schools-and-trusts-gias-updates-document-existing-tech-process)
Add some lightweight docs to describe some of the support process around changes to schools and trusts.
Added support docs.
=> 939 schools and trusts gias updates document existing tech process

app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md
=> Fixed broken link

app/views/devices_guidance/preparing_4g_wireless_routers.md
=> Fixed a bad link

app/services/feature_flag.rb, app/views/devices_guidance/how_to_order.html.erb, app/views/responsible_body/devices/orders/cannot_order_yet.html.erb, app/views/school/devices/cannot_order.html.erb
The flag is off on production.
=> Remove the half-term feature flag as half-term has come and gone

app/services/feature_flag.rb, app/views/shared/_start_ordering_on_techsource.html.erb
~Depends on #771~ ✅ 
The flag is disabled in production.
=> Remove ipad/chromebook feature flag

app/views/guide_to_collecting_mobile_information/asking_for_network.html.erb, app/views/guide_to_collecting_mobile_information/index.html.erb, app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb, app/views/shared/_pilot_mno_offer_eligibility.html.erb
- Update eligibility
- Remove networks not in new offer
- Update network details of those in offer
=> Update collecting mobile information guide

spec/features/school/extra_mobile_data_requests_spec.rb
I introduced this failure because I merged without rebasing.
=> Fix extra mobile data spec

app/components/responsible_body/school_details_summary_list_component.rb, app/views/pages/how_request_4g_routers.html.erb, app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/devices/home/tell_us.html.erb, app/views/responsible_body/devices/orders/_some_schools_can_order.html.erb, app/views/responsible_body/devices/orders/specific_circumstances.html.erb, app/views/responsible_body/devices/who_to_contact/_nominate_another_contact.html.erb, app/views/responsible_body/internet/home/show.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb, app/views/school/devices/cannot_order_as_reopened.html.erb, app/views/school/home/show.html.erb, app/views/school/internet/mobile/extra_data_requests/guidance.html.erb, app/views/school/welcome_wizard/what_happens_next.html.erb, app/views/shared/_privacy_notice_text.html.erb, app/views/shared/devices/_who_to_request_for_list.html.erb, app/views/support/schools/devices/order_status/collect_urns_to_allow_many_schools_to_order.html.erb, config/locales/en.yml, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/responsible_body/ordering_devices_spec.rb, spec/features/support/enabling_orders_for_a_school_spec.rb
During a national lockdown "local restrictions" do not apply.
=> Change "local restrictions" to "reported closures"

app/views/pages/choosing_help_with_internet_access.html.erb, app/views/pages/how_request_4g_routers.html.erb, app/views/school/internet/home/show.html.erb, config/locales/en.yml, config/routes.rb
=> Add "Choosing help with internet access" page

app/views/devices_guidance/preparing_4g_wireless_routers.md
=> Updated contract length section with MN copy

app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/home_page.html.erb, app/views/pages/internet_access.html.erb
- Indicate that MNO pilot is open for a few schools
- BT pilot is closed
=> Update Get internet access page

app/views/layouts/multipage_guide.html.erb, config/locales/en.yml
=> Add "Home" to start of device guidance breadcrumbs

app/views/pages/how_request_4g_routers.html.erb, app/views/school/internet/mobile/extra_data_requests/guidance.html.erb, app/views/shared/devices/_who_to_request_for_list.html.erb
Update our phrasing to match GOV.UK (eg https://www.gov.uk/coronavirus-shielding-support)
=> Clinically extremely, not extremely clinically

app/views/responsible_body/users/index.html.erb
- Fix breadcrumb
- Remove reference to BT vouchers
=> Small fixes to responsible body manage users page

app/models/computacenter/api/cap_usage_update.rb, spec/models/computacenter/api/cap_usage_update_spec.rb
- https://trello.com/c/xdUha5ih/926-fix-number-of-ordered-devices-including-over-orders
- When CC makes call to update `devices_ordered`
- If is a cancellation (reduction of `devices_ordered`)
- We might contact user/school/rb they can order if they are in the correct state to be able to order
- Make CC call
- If an increase does not send email
- If decrease should send email assuming school can order
=> [926] When CC logs cancellation maybe notify user

app/views/devices_guidance/support_and_maintenance.md
=> Removed outdated reference to 4G contract length

app/views/devices_guidance/preparing_ipads.md, config/locales/en.yml
Combine's @gemmaemoore 's 2 PRs #882 and #883, so that the new content shows up
(see context)
From the homepage, click "Get support guides for laptops, tablets and 4G wireless routers" > "Preparing iPads"
Screenshots:
=> Combine ipad guidance prs

app/views/devices_guidance/preparing_ipads.md
=> Email address fix

.github/workflows/build.yml, spec/rails_helper.rb
[Trello card #1131](https://trello.com/c/zTfOX6I9/1131-fix-intermittent-build-error-on-assetpackpath) - We're still getting intermittent build errors, of the form:
```
Failure/Error: <%= tag :meta, property: 'og:image', content: asset_pack_path('media/images/govuk-opengraph-image.png') %>
ActionView::Template::Error:
784: unexpected token at ''
(...)
```
I've been unable to replicate this issue locally, it only seems to occur on Github. So I've added a couple of bits of debug output to try and get more information,  and hopefully diagnose this issue.
1. We're using parallel tests, and the error only seems to occur partway through a run - so I've added a line to `rails_helper.rb` that will help us identify the exact per-process run order when a problem occurs (only if …
=> 1131 add debug build output to diagnose intermittent build error on assetpackpath

app/models/virtual_cap_pool.rb, spec/models/virtual_cap_pool_spec.rb
=> Only send CC updates when RB-level feature flag is enabled

app/models/school_device_allocation.rb, spec/models/school_device_allocation_spec.rb
=> Only send computacenter_cap when RB-level feature flag is set

app/controllers/techsource_launcher_controller.rb, app/helpers/view_helper.rb, app/models/computacenter/tech_source.rb, app/views/shared/_techsource_unavailable_banner.html.erb, spec/controllers/techsource_launcher_controller_spec.rb, spec/features/techsource_availability_for_responsible_body_spec.rb, spec/features/techsource_availability_for_school_spec.rb
There is an upcoming TechSource maintenance window. Also we want to make these updates easier to do.
- Extract a `TechSource` model for housing logic and data relating to maintenance windows
- Separate data and logic out
- Make the specs run independently of the maintenance window data
- Update the actual window data
Best reviewed by stepping through commit-by-commit.
=> TechSource maintenance: updates for Dec 2020 and DRY code

app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb
We are bringing EE into the MNO offer.
https://trello.com/c/mwOlRCrP/
=> Add EE offer text

app/controllers/responsible_body/internet/home_controller.rb, app/controllers/responsible_body/internet/mobile/extra_data_requests_controller.rb, app/views/responsible_body/internet/home/show.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/guidance.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/new.html.erb, app/views/school/internet/mobile/extra_data_requests/guidance.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb, app/views/school/internet/mobile/extra_data_requests/new.html.erb, app/views/shared/internet/_mno_guidance.html.erb, config/routes.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb
https://trello.com/c/BYOlFi13/1140-mno-rb-journey-build-the-request-data-page
https://ghwt-design-history.herokuapp.com/mno-for-rbs/
* Move MNO request guidance to shared partial and add RB specific parts
* Re-enable feature specs for RB MNO
* Fix page titles and back links for school MNO journey
=> Add request data guidance page to responsible body MNO jourey

app/models/computacenter/api/cap_usage_update.rb, spec/models/computacenter/api/cap_usage_update_spec.rb
We are occasionally returning errors to CC when they send us consumption updates. Here's what is happening:
1. They send us a consumed update
2. We save it against the allocation which triggers cap updates back to CC for the entire pool
3. At least one of these cap updates fails because the cap is below the devices ordered number
4. We return a 500 error back to them
1. Don't return a failure if a cascading cap update to CC fails
N.B. We already store failures in `CapUpdateCall` so I am not concerned that we are suppressing visibility of cap update failures.
=> Safely handle cap update failures triggered by a devices ordered update

app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/internet_access.html.erb
- Change to focus on all schools and responsible bodies, rather than a few select schools
- Add new networks
=> Update mobile scheme content

app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb
Tesco Mobile are joining the MNO offer
=> Add Tesco Mobile offer

config/locales/en.yml
We're staying open one day longer
=> Tweak Xmas closure date

app/views/devices_guidance/how_to_order.html.erb
=> Update how to order Christmas banner

app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb
=> Add Sky Mobile to MNO

app/views/devices_guidance/replace_a_faulty_device.md
=> Fix malformed HTML in 'replacing faulty device' guidance page

app/services/feature_flag.rb, app/views/shared/banners/_responsible_body.html.erb, app/views/shared/banners/_school.html.erb, config/locales/en.yml
=> Add a secondary mass testing banner

config/locales/en.yml
=> fix minor copy issue in banner

app/webpacker/scripts/select-all-or-none-checkboxes.js, app/webpacker/scripts/select-all-or-none-checkboxes.test.js
This unit test is needed to show that if there were more than one
SelectAllOrNone component on the page then this script will still work
and each component works in isolation.
=> fix skipped javascript unit test

app/services/feature_flag.rb, app/views/shared/_start_ordering_on_techsource.html.erb
We have no iPad stock but users can still order and we will ship when stock arrives.
=> Warn users about iPad stock

config/locales/en.yml
=> Minor copy tweak to the order page banner

app/controllers/support/schools_controller.rb, app/controllers/support/users/schools_controller.rb, app/form_objects/support/new_user_school_form.rb, app/form_objects/support/school_suggestion_form.rb, app/views/support/users/schools/index.html.erb, app/webpacker/packs/application.js, app/webpacker/scripts/__snapshots__/school-autocomplete.test.js.snap, app/webpacker/scripts/school-autocomplete.js, app/webpacker/scripts/school-autocomplete.test.js, config/locales/en.yml, config/routes.rb, spec/controllers/support/schools_controller_spec.rb, spec/features/support/changing_a_users_associated_organisations_spec.rb, spec/form_objects/support/new_user_school_form_spec.rb, spec/form_objects/support/school_suggestion_form_spec.rb, spec/page_objects/support/users/schools_page.rb
Support agents need to assign users to new schools.
- Add a JSON endpoint which returns schools based on a partial name or URN match
- Progressively enhance the school search box with an accessible autocomplete which uses the newly introduced JSON endpoint.
https://user-images.githubusercontent.com/23801/103418327-10884900-4b86-11eb-97ba-e992fa8c18c7.mp4
=> School autocomplete progressive enhancement

app/views/devices_guidance/how_to_order.html.erb, config/locales/en.yml, spec/views/devices_guidance/how_to_order.html.erb_spec.rb
=> Update secondary banner copy

config/settings/development.yml
=> Remove UAT reference

app/views/devices_guidance/device_distribution_and_ownership.md
Visit https://dfe-ghwt-pr-1032.herokuapp.com/devices/device-distribution-and-ownership#devices-for-social-care-care-leavers-children-and-families-with-a-social-worker check if "Guidance for safe internet use" takes the user to https://www.saferinternet.org.uk/
=> Fix link in guidance

app/form_objects/support_ticket/college_details_form.rb, app/form_objects/support_ticket/contact_details_form.rb, app/form_objects/support_ticket/school_details_form.rb, spec/controllers/support_ticket/college_details_controller_spec.rb, spec/form_objects/support_ticket/college_details_form_spec.rb, spec/form_objects/support_ticket/contact_details_form_spec.rb, spec/form_objects/support_ticket/school_details_form_spec.rb, spec/models/school_spec.rb
- Add email address format validation
- Add School URN validation to ensure its a 6 digit number
- Add College UKPRN validation to ensure its a 8 digit number
=> Add validations to get support forms

app/models/computacenter/outgoing_api/cap_update_request.rb, spec/models/computacenter/outgoing_api/cap_update_request_spec.rb
This is an extension of https://trello.com/c/JFczhXmY/1097-virtual-cap-force-the-orders-of-trusts-that-qualify-for-virtual-cap-and-have-multiple-chromebook-domains-into-the-techsource-man and https://github.com/DFE-Digital/get-help-with-tech/pull/927
There's a possibility that a school who is not centrally managed is within an RB that largely manages its schools. In that case and where there were multiple Chromebooks domains we are erroneously forcing devolved schools into the CC manual queue.
We need a check to determine whether the RB will order devices as well as checking if the RB has multiple Chromebook domains in managed schools before reducing the cap we send to CC. 
Don't force schools that are devolved in a centrally managed RB into the manual queue if the RB has multiple …
=> Add further constraints around lowering caps with RBs with multiple Chromebook domains

app/views/pages/start.html.erb, app/views/shared/banners/_parents_carers_pupils.html.erb, app/views/sign_in_tokens/email_not_recognised.html.erb, app/views/sign_in_tokens/sign_in_only.html.erb
=> Add notice for parents, carers and pupils

app/views/devices_guidance/support_and_maintenance.md, app/views/landing_pages/digital_platforms.md, app/views/layouts/application.html.erb, app/views/pages/accessibility.md, app/views/pages/home_page.html.erb, app/views/sign_in_tokens/email_not_recognised.html.erb, app/views/support_tickets/start.html.erb, app/views/support_tickets/thank_you.html.erb
=> Update SLA from 3 days to 4 days

app/services/feature_flag.rb, app/views/responsible_body/devices/orders/cannot_order_yet.html.erb, app/views/school/devices/cannot_order.html.erb, config/locales/en.yml, spec/features/responsible_body/ordering_devices_spec.rb, spec/features/school/order_devices_spec.rb
Schools:
Responsible bodies:
Draft until I've checked the content
=> Update content for schools who cannot order during lockdown

app/views/devices_guidance/support_and_maintenance.md
=> Fix mailto link to point to the correct email address

app/views/shared/_start_ordering_on_techsource.html.erb
=> Update iPad stock message

app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb, app/views/pages/about_increasing_mobile_data.html.erb
=> Content update

app/views/pages/start.html.erb
Internet access features are open to everyone now
=> Remove mention of pilot from start page

docs/support/add_school_to_virtual_cap_pool.md
Just a support note regarding adding a school to a responsible body's virtual pools manually.
Added support doc.
=> Added support doc for adding a school to a virtual pool manually

app/views/devices_guidance/preparing_ipads.md
=> Removed reference to Computacenter

app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb, app/views/pages/about_increasing_mobile_data.html.erb
=> Internet content update

app/views/shared/_start_ordering_on_techsource.html.erb
iPads and Chromebooks are available but in high demand
=> Update the iPad stock message

app/helpers/view_helper.rb, app/views/responsible_body/users/index.html.erb, app/views/school/users/index.html.erb, config/locales/en.yml
https://trello.com/c/pM0GyE4K/1164-add-support-portal-content-to-the-service
https://docs.google.com/presentation/d/19SeJeBdbCRjY9Y8eTJDPdHI_w16rfYMiTeMnPn-QO-A/edit
=> Mention access to Support Portal when managing users

app/views/devices_guidance/support_and_maintenance.md, config/locales/en.yml
=> Guidance update

app/views/devices_guidance/how_to_order.html.erb
=> Updated link to Apple support

app/views/support_tickets/check_your_request.html.erb
=> Remove unused line in contact form view

app/views/pages/accessibility.md, app/views/support_tickets/start.html.erb, app/views/support_tickets/thank_you.html.erb
=> Increase SLA from 4 days to 5 days

app/services/importers/fe_csv.rb
- https://trello.com/c/R2235yoT/1075-spike-adding-fe-institutions-to-the-service
- When an existing `School` in our system is converted to `FurtherEducationSchool` the type will also need updating
n/a
=> [1075] Update type when migrating existing Schools

app/views/devices_guidance/device_specification.md, config/locales/en.yml
=> Device specification

app/views/guide_to_collecting_mobile_information/index.html.erb, app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb, app/views/pages/about_increasing_mobile_data.html.erb, app/views/shared/_eligibility_points_across_bt_wifi_and_mno_offers.html.erb
=> Mno content update

Dockerfile
=> lock node version to prevent yarn conflicts

app/views/pages/internet_access.html.erb
=> Fix typo on internet access page

app/controllers/responsible_body/internet/mobile/extra_data_requests_controller.rb, app/controllers/school/internet/mobile/extra_data_requests_controller.rb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb
- https://trello.com/c/47NKpXOa/1332-add-pagination-to-school-and-rb-lists-of-mno-requests-100-per-page
- Add pagination to school viewing MNO requests
- Login as a school
- Create 100+ MNO requests for this school
- View the requests
- Pagination should be present at the bottom of the page
- Should be able to navigate between pages
=> [1332] Pagination for school viewing MNO requests

app/views/pages/choosing_help_with_internet_access.html.erb, app/views/pages/internet_access.html.erb
- Include FE
- Note age ranges
- Fix broken link to preparing wireless routers
https://trello.com/c/iXZ5Iero/1172-update-guidance-on-choosing-between-connectivity-offers
=> Update comparison of internet offers

app/components/responsible_body/school_details_summary_list_component.rb, app/components/school/school_details_summary_list_component.rb, app/models/further_education_school.rb, app/models/school.rb, app/views/responsible_body/devices/schools/_school_states_table.html.erb, app/views/school/details/show.html.erb, app/views/school/welcome_wizard/what_happens_next.html.erb, app/views/shared/_school_without_allocation.html.erb, app/views/support/responsible_bodies/show.html.erb, app/views/support/schools/results.html.erb, config/locales/en.yml, spec/models/further_education_school_spec.rb, spec/models/school_spec.rb
- removes a flag that shows conditional content for FE providers as we're showing the same content to all users
- adds FE settings for places where we need to show the type of education organisation
- change button text for users with multiple schools to show org name instead of the word 'school'
=> Removing flag for fe and setting types

app/views/support_tickets/academy_details.html.erb, app/views/support_tickets/check_your_request.html.erb, app/views/support_tickets/college_details.html.erb, app/views/support_tickets/contact_details.html.erb, app/views/support_tickets/describe_yourself.html.erb, app/views/support_tickets/local_authority_details.html.erb, app/views/support_tickets/school_details.html.erb, app/views/support_tickets/support_details.html.erb, app/views/support_tickets/support_needs.html.erb
=> Users should not be able to submit a form multiple times

app/views/responsible_body/home/show.html.erb, app/views/responsible_body/internet/home/show.html.erb, app/views/school/home/show.html.erb
- Add note about where to find data requests
- Add link to Choosing help with internet, for responsible bodies
=> Note about requests

app/views/devices_guidance/how_to_order.html.erb
Change from yr1 and 2 only to all year groups (and to include yr 13)
=> CEV devices are for all year groups

app/services/feature_flag.rb, app/views/shared/banners/_responsible_body.html.erb, app/views/shared/banners/_school.html.erb, config/locales/en.yml, spec/views/responsible_body/home/show.html.erb_spec.rb, spec/views/school/home/show.html.erb_spec.rb, spec/views/support/home/feature_flags.html.erb_spec.rb, spec/views/support/responsible_bodies/show.html.erb_spec.rb, spec/views/support/schools/show.html.erb_spec.rb
- Remove feature flag
- Remove banner
- Remove specs
=> Remove Christmas banner feature

app/form_objects/bulk_upload_form.rb, app/form_objects/mno/csv_status_update_form.rb
=> Log bulk upload content-type at INFO level

app/views/devices_guidance/replace_a_faulty_device.md
=> Removed delivery time - urgent

app/views/devices_guidance/device_allocations.md
=> Latest content

app/views/shared/mno_offer_details/_bt_mobile.html.erb, app/views/shared/mno_offer_details/_ee.html.erb, app/views/shared/mno_offer_details/_lycamobile.html.erb, app/views/shared/mno_offer_details/_o2.html.erb, app/views/shared/mno_offer_details/_vodafone.html.erb
More networks now have active users processing requests, remove lines about delays and replace with 14 day period.
https://trello.com/c/FIkhEwJO/
=> Update details of when networks will process requests

app/views/pages/how_request_4g_routers.html.erb, app/views/shared/mno_offer_details/_bt_mobile.html.erb
https://trello.com/c/JflXi0wM
https://trello.com/c/EWUWmmFT
=> Connectivity update

app/views/devices_guidance/4g_user_guidance.md, app/views/devices_guidance/about_the_offer.md, app/views/devices_guidance/device_distribution_and_ownership.md, app/views/devices_guidance/device_specification.md, app/views/devices_guidance/enrol_chromebooks_with_user_logins.md, app/views/devices_guidance/enrol_chromebooks_without_user_logins.md, app/views/devices_guidance/getting_started_with_your_google_chromebook.md, app/views/devices_guidance/getting_started_with_your_microsoft_windows_device.md, app/views/devices_guidance/google_domain_for_care_leavers_and_children_with_social_worker.md, app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/index.html.erb, app/views/devices_guidance/preparing_4g_wireless_routers.md, app/views/devices_guidance/preparing_ipads.md, app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md, app/views/devices_guidance/replace_a_faulty_device.md, app/views/devices_guidance/safeguarding_for_device_users.md, app/views/devices_guidance/support_and_maintenance.md, app/views/errors/internal_server_error.html.erb, app/views/guide_to_collecting_mobile_information/privacy.html.erb, app/views/landing_pages/digital_platforms.md, app/views/landing_pages/edtech_demonstrator_programme.md, app/views/pages/home_page.html.erb, app/views/pages/how_request_4g_routers.html.erb, app/views/shared/_start_ordering_on_techsource.html.erb, app/views/sign_in_tokens/email_not_recognised.html.erb, config/locales/en.yml, spec/features/session_behaviour_spec.rb, spec/features/support/deleting_a_user_spec.rb, spec/page_objects/devices_guidance/how_to_order_page.rb
https://trello.com/c/X7yZI5zs/1220-template-style-consistency
There are a number of small inconsistencies across the service in layout and wording.
Makes layouts more consistent. Also fixes a few other things I noticed and removes unnecessary uses of 'please'.
Fixes cover almost every guidance page. (I checked the signed-in view, but nothing needed fixing)
=> Makes templates consistent and fixes some other wording

app/services/timeline/school.rb
- https://github.com/DFE-Digital/get-help-with-tech/pull/1257 introduced performance issues on the support view a school page
- This converts a SQL query from using an OR to a UNION
- n/a
=> [1434] Optimize support school timeline query

app/views/devices_guidance/device_allocations.md
Reverts DFE-Digital/get-help-with-tech#1279
=> Revert "Update device_allocations.md"

app/controllers/responsible_body/internet/mobile/manual_requests_controller.rb, app/validators/gsuite_domain_validator.rb, spec/models/batch_job_spec.rb, spec/models/school_welcome_wizard_spec.rb, spec/models/user_spec.rb
Review each commit in isolation
=> Fix deprecation warnings & tidy up the test logging

app/views/devices_guidance/replace_a_faulty_device.md
=> Please put live at 4pm!

app/views/school/home/show.html.erb, spec/features/school/donated_devices_spec.rb
=> Only show opt-in link when devolved

app/controllers/responsible_body/donated_devices/interest_controller.rb, app/form_objects/responsible_body/donated_device_school_scope_form.rb, app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/donated_devices/interest/about.html.erb, app/views/responsible_body/donated_devices/interest/all_or_some_schools.html.erb, app/views/responsible_body/donated_devices/interest/device_types.html.erb, app/views/responsible_body/donated_devices/interest/interest_confirmation.html.erb, app/views/responsible_body/donated_devices/interest/new.html.erb, app/views/responsible_body/donated_devices/interest/not_interested.html.erb, app/views/responsible_body/donated_devices/interest/queue.html.erb, app/views/school/home/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/responsible_body/donated_devices_spec.rb, spec/features/school/donated_devices_spec.rb
=> DM: Add initial RB pages

app/views/support/schools/results.html.erb, spec/features/support/searching_schools_spec.rb
- Support school search results csv download is broken
- Fix school search results csv download
- Add coverage to prevent regression
- Search for schools via multiple urns
- Download search results in csv form
- Should see csv
- Should not explode
=> Fix school seach results download

app/form_objects/donated_device_selection_form.rb, app/models/donated_device_request.rb, app/views/responsible_body/donated_devices/interest/about.html.erb, app/views/responsible_body/donated_devices/interest/all_or_some_schools.html.erb, app/views/responsible_body/donated_devices/interest/interest_confirmation.html.erb, app/views/responsible_body/donated_devices/interest/queue.html.erb, app/views/school/donated_devices/interest/about.html.erb, app/views/school/donated_devices/interest/address.html.erb, app/views/school/donated_devices/interest/check_answers.html.erb, app/views/school/donated_devices/interest/device_types.html.erb, app/views/school/donated_devices/interest/disclaimer.html.erb, app/views/school/donated_devices/interest/how_many_devices.html.erb, app/views/school/donated_devices/interest/interest_confirmation.html.erb, app/views/school/donated_devices/interest/opted_in.html.erb, app/views/school/donated_devices/interest/queue.html.erb
=> Update DM breadcrumbs and copy

config/locales/en.yml
New privacy policy for Computer for Kids wasn't saved to the main PR. This added the title.
Adds title for Computers for Kids privacy policy
=> Added privacy policy heading to locale file

app/views/responsible_body/donated_devices/interest/address.html.erb, app/views/responsible_body/donated_devices/interest/disclaimer.html.erb, app/views/school/donated_devices/interest/address.html.erb, app/views/school/donated_devices/interest/disclaimer.html.erb, app/views/school/home/show.html.erb, app/views/shared/_donated_devices_disclaimer.html.erb, config/locales/en.yml
Daily Mail scheme content fixes from review on dev/staging by Pritesh.
Various fixes to content
=> Changes from Pritesh's review

app/views/shared/_stock_levels.html.erb
=> Stock levels 2

app/views/guide_to_collecting_mobile_information/index.html.erb, app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/choosing_help_with_internet_access.html.erb, app/views/pages/internet_access.html.erb, app/views/shared/internet/_mno_guidance.html.erb, app/views/shared/internet/_mno_information.html.erb
[Trello card - Update GHWT content to reflect inclusion of FE students in MNO offer](https://trello.com/c/5kFVBWvI/1574-update-ghwt-content-to-reflect-inclusion-of-fe-students-in-mno-offer)
MNO offer now includes FE students
Update guidance about who is eligible to for MNO to include FE students.
Guidance:
Signed-in pages:
=> updates guidance on MNO offer to include FE students

app/views/pages/about_increasing_mobile_data.html.erb
=> FE MNO copy tweaks

app/views/shared/mno_offer_details/_giffgaff.html.erb, app/views/shared/mno_offer_details/_o2.html.erb, app/views/shared/mno_offer_details/_smarty.html.erb, app/views/shared/mno_offer_details/_three.html.erb
- FE MNO network exclusion copy for accordion
=> FE MNO add exlusions to accordion copy

app/views/devices_guidance/index.html.erb, app/views/shared/_device_list.html.erb
=> Tablet stock update

app/views/mno/extra_mobile_data_requests/_extra_mobile_data_request.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb, config/initializers/time_and_date_formats.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb
Use recommended GOV.UK date formatting, add helpers for consistency
=> Remove ordinals from dates in MNO requests tables

app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb
We do not want personally identifiable information in our support system
=> [1585] Suggest support requests use IDs not personal data

app/views/shared/_link_to_survey.html.erb
=> fix css class name

app/models/computacenter/tech_source.rb, app/views/shared/_techsource_unavailable_banner.html.erb, spec/features/techsource_availability_for_responsible_body_spec.rb, spec/features/techsource_availability_for_school_spec.rb
- Updated the date/time and the copy
=> TechSource is going offline for maintenance over the weekend

app/models/computacenter/tech_source.rb, app/views/shared/_techsource_unavailable_banner.html.erb, spec/features/techsource_availability_for_responsible_body_spec.rb, spec/features/techsource_availability_for_school_spec.rb
Reverts DFE-Digital/get-help-with-tech#1382
=> Revert "TechSource is going offline for maintenance over the weekend"

app/views/pages/privacy.md
- https://trello.com/c/0Exrdoub/1601-update-https-get-help-with-techeducationgovuk-privacy-to-be-inclusive-of-fe
- Copy change to include FE to privacy page
- Visit privacy page
- Copy should be updated
=> [1601] Update privacy page to include FE

app/views/guide_to_collecting_mobile_information/index.html.erb
https://trello.com/c/fp4cH3AN/1350-add-link-to-boost-your-broadband-ofcom-site-to-mno-guidance-pages
=> [1350] Add link to boosting broadband

app/views/devices_guidance/support_and_maintenance.md, app/views/pages/accessibility.md, app/views/shared/_stock_levels.html.erb, app/views/support_tickets/start.html.erb, app/views/support_tickets/thank_you.html.erb
=> SLA update

app/controllers/responsible_body/donated_devices/interest_controller.rb, spec/features/responsible_body/donated_devices_spec.rb, spec/features/school/donated_devices_spec.rb
[Trello card](https://trello.com/c/Q8GNbhRI/1682-daily-mail-tidy-up)
[Original PR](https://github.com/DFE-Digital/get-help-with-tech/pull/1317)
The Daily Mail scheme was added under a tight deadline so opportunity to address PR review comments had to be deferred. 
Refactor the RB controller for the journey to make it clearer and more DRY.
Fix some naming issues in specs.
=> Daily Mail PR cleanup

app/views/shared/mno_offer_details/_giffgaff.html.erb, app/views/shared/mno_offer_details/_o2.html.erb
- Requests are now being processed more quickly
- Fix bug where brand wasn't showing for networks not supporting over 16s
https://trello.com/c/PmZoRF6X/1705-update-o2-accordion-on-telling-them-about-the-offer-page
=> Update O2 offer text

app/form_objects/donated_device_interest_form.rb, app/form_objects/support_ticket/describe_yourself_form.rb, app/views/devices_guidance/device_specification.md, app/views/pages/home_page.html.erb, app/views/pages/how_request_4g_routers.html.erb, app/views/sign_in_tokens/token_is_valid_but_expired.html.erb, app/views/support_tickets/academy_details.html.erb, app/views/support_tickets/check_your_request.html.erb, app/views/support_tickets/college_details.html.erb, app/views/support_tickets/contact_details.html.erb, app/views/support_tickets/describe_yourself.html.erb, app/views/support_tickets/local_authority_details.html.erb, app/views/support_tickets/parent_support.html.erb, app/views/support_tickets/school_details.html.erb, app/views/support_tickets/start.html.erb, app/views/support_tickets/support_details.html.erb, app/views/support_tickets/support_needs.html.erb, app/views/support_tickets/thank_you.html.erb, docs/computacenter_api.md
Use:
- smart quotes throughout
- "Continue" not "Next"
- standard page title sizes without the repeated caption
- standardise "check your answers" heading and button
- descriptive link text
Move full-stops out of links.
=> Design pass on the support form

config/locales/en.yml
=> Remove hello world from en.yml

app/components/device_count_component.html.erb, app/components/device_count_component.rb, app/components/responsible_body/pooled_device_count_component.html.erb, app/components/responsible_body/pooled_device_count_component.rb, app/helpers/view_helper.rb
- Fix typo in method name
- Fix link class for link in support
=> Fix typo and link class

app/components/nav_component.rb
=> RB/School users should see "Your account" in head nav"

app/views/shared/mno_offer_details/_lebara_mobile.html.erb, db/migrate/20210319142213_set_lebara_mobile_to_participating.rb, db/schema.rb
[Trello card](https://trello.com/c/0ZT5m1Ns/1718-add-lebara-to-the-service) - the Lebara Mobile offer is ready to put live
Set Lebara's participation flag to 'yes'
Add a partial display template for their offer details
Add an entry to the validation list in the template spreadsheet
=> [1718] add Lebara Mobile as a participating mobile network

app/views/devices_guidance/device_specification.md, app/views/devices_guidance/how_to_order.html.erb, app/views/pages/about_increasing_mobile_data.html.erb
The start page is being deprecated
https://trello.com/c/GY33SmHs/
=> Update links to /start

app/views/support/home/schools.html.erb, app/views/support/schools/devices/allocation/collect_urns_and_allocations_for_many_schools.html.erb, app/views/support/schools/devices/order_status/collect_urns_to_allow_many_schools_to_order.html.erb, app/views/support/schools/search.html.erb, config/locales/en.yml
- Locale collision causing incorrect copy to show up
- Fix locale collision
- Sign in as support
- Visit `/support/schools`
- Should see correct h1
=> Fix locale collision

app/views/devices_guidance/getting_started_with_your_microsoft_windows_device.md, app/views/devices_guidance/preparing_ipads.md, app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md, app/views/devices_guidance/safeguarding_for_device_users.md, app/views/pages/dfe_windows_privacy_notice.html.erb
=> Correct service name capitalisation so that its consistent

app/components/start_page_banner_component.html.erb, app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/home_page.html.erb, config/locales/en.yml, spec/features/start_journey_spec.rb
View https://dfe-ghwt-pr-1441.herokuapp.com/ to see the new design/copy
=> 1728 Update the home page copy

app/controllers/devices_guidance_controller.rb, app/models/multipart_guidance.rb, app/views/devices_guidance/_page_link_and_description.html.erb, app/views/devices_guidance/index.html.erb, app/views/layouts/guidance_pages.html.erb, config/locales/en.yml, spec/models/multipart_guidance_spec.rb, spec/views/layouts/guidance_pages.html.erb_spec.rb
- Updates the device guidance page design and copy
- Removes next/previous links at the bottom of the guidance pages
- Refactor how the device guidance page is built using key/value from en.yml
Visit https://dfe-ghwt-pr-1498.herokuapp.com/devices and view a couple of the links
=> Update device guidance page

docs/support/add_missing_further_education_college.md
=> add missing further education college

docs/support/add_missing_further_education_college.md
=> add url links for school lookup websites

app/form_objects/support/request_completions_form.rb, app/models/support/service_performance.rb, spec/features/support/viewing_service_performance_spec.rb
The dashboard was using UTC instead of local timezone.
=> Fix time display on performance dashboard

docs/updating_allocations.md
Handover documentation ticket: https://trello.com/c/NgbvvTnc
Markdown documentation for updating allocations
=> Ref 001 updating allocations documentation

app/concerns/school_type.rb, app/controllers/school/welcome_wizard_controller.rb, app/models/la_funded_place.rb, app/models/local_authority.rb, app/models/school.rb, app/models/user.rb, app/policies/la_funded_place_policy.rb, app/services/interstitial_picker.rb, app/views/interstitials/_la_funded_user.html.erb, spec/factories/schools.rb, spec/factories/users.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/services/interstitial_picker_spec.rb
Provide independent schools (ISS) context for LA funded places
Addition of LA Funded Type and interstitial LA Funded page when user logs in
The login user journey has been changed in 
app/controllers/school/welcome_wizard_controller.rb 
app/models/user.rb
app/services/interstitial_picker.rb
The LA Funded place follows the journey given in the prototype: https://ghwt-prototype.herokuapp.com/school/welcome
=> [1770] LA funded places

docs/zendesk.md
As part of the handover from AdRoc to Investigo, Alistair Laing gave us a talk on our app's Zendesk integration
on 12 Apr 21. 
Add Markdown documentation summarising the talk's content.
=> Documentation for Alistair Laing's Zendesk talk on 12 Apr 21.

.github/workflows/promote-build.yml
The final make task step also needs the `CF_DOCKER_USERNAME` / `CF_DOCKER_PASSWORD` env vars
Add the env vars
=> 1855 fix promote build step

app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md, app/views/devices_guidance/resolve_issues_with_laptops_and_tablets.md, config/locales/en.yml
- Removes content from preparing Microsoft Windows laptops and tablets page
- Creates a new "Resolve issues with laptops and tablets" page
Visit https://dfe-ghwt-pr-1558.herokuapp.com/devices and see a new "Resolve issues with laptops and tablets" link under the "Manage devices" section
Visit https://dfe-ghwt-pr-1558.herokuapp.com/devices/resolve-issues-with-laptops-and-tablets, page loads as expected
=> New resolve issues  with laptops and tablets page

app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb
Visit https://dfe-ghwt-pr-1563.herokuapp.com/ and signed in as each of these users
- `school.user.1@example.com`
- `trust.user.1@example.com`
The users home page title should be "Your account"
=> Make school/trust home page consistent

app/views/devices_guidance/device_specification.md, app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md
=> Restricted expiry

docs/sending_communications_via_notify.md
Writing up notes from session with @jamesrose on the morning of 19 Apr 21 relating to sending communications from
our app via the Notify service.
https://trello.com/c/hxOaForX
Add Markdown documentation for the process
=> Add notes for communication templates

docs/updating_allocations.md
Handover of changing allocations and caps and sending of bulk e-mails.
Updating text following handover session on morning of 19 Apr 21 with @jamesrose 
https://trello.com/c/I157nE87
Update text after having another read through and make e-mail sending description clearer
=> Update text to reflect 19 Apr 21 handover session

app/models/computacenter/tech_source.rb
Third maintenance window from https://trello.com/c/HTbLpJG3
Add maintenance window for 6pm on Friday 23 April to 8pm on Sunday 25 April
=> Add next TechSource maintenance window

app/services/exporters/mno_requests_csv.rb
- https://trello.com/c/zFRf8jdL/1885-mno-csv-report-performance-issue
- CSV export of `ExtraMobileDataRequest` is taking too long to generate causing a timeout
- Fixes a performance issue by eager loading association which should fix n+1 causing CSV generation to take a long time
- Visit http://localhost:3000/support/performance#mno
- Download CSV
- CSV should generate as normal as before
=> [1885] Eager load completion_events for csv export

app/views/pages/internet_access.html.erb
- https://trello.com/c/oRJGt9OZ/1880-typo-fix-sign-in-view-your-requests
- fixes typo
- visit http://localhost:3000/internet-access
- typo should be fixed
=> [1880] fix typo

app/views/devices_guidance/device_specification.md
- https://trello.com/c/2rGmfvqf/1888-upload-device-content-for-persona-i
- Update device guidance to container higher spec device specifications
- Visit https://dfe-ghwt-pr-1596.herokuapp.com/devices/device-specification
- See updated content and table about higher spec device
=> [1888] Add higher spec device to guidance

README.md
Add information about parallel test execution which greatly speeds up the spec suite run
Add relevant command to README
=> Add line about quicker parallel test execution

docs/reporting_allocations.md, docs/updating_allocations.md
Writing up documentation from @nigel-lowry's session with @jamesrose on the morning of 22 Apr 21.
https://trello.com/c/HYNngevs
https://trello.com/c/lhJROn9k
Added new document and changed older document to reflect @asmega's recent PR which added a Web UI for common
allocation operations (https://github.com/DFE-Digital/get-help-with-tech/pull/1540)
=> Ref 011 and 012 reporting allocations

app/models/computacenter/tech_source.rb
https://trello.com/c/lBq6ZCee
Add new maintenance window
=> Add new maintenance window for 1 May 2021 10am--6pm

docs/mobile_network_operator_report_queries.md
As part of a meeting between Alistair Davidson, Mark Allen and Nigel Lowry on morning of 27 Apr 21 to address https://trello.com/c/P8etQAxi, notes were produced on the process of MNO report queries.
Document to describe general process of MNO queries from wider business
=> Add document to describe MNO report query process

spec/jobs/allocation_job_spec.rb
Checking we can reduce allocations which wasn't previously tested.
https://trello.com/c/xFxgUms1
Add specs for negative application deltas
=> Add specs to check negative allocation deltas are accepted

app/controllers/computacenter/responsible_body_changes_controller.rb, app/models/computacenter/responsible_body_urns.rb, spec/features/computacenter/responsible_body_changes_spec.rb
Query needed fixing to show CC changes for RBs
Fixed query
=> Fix query for CC change view for RBs

app/services/personas/la_funded_place.rb
Fixed LA funded persona and set it up for ordering (but still need to set `techsource_account_confirmed_at` to actually order)
Fix to persona
=> Fix LA funded place persona

app/views/devices_guidance/device_specification.md, app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/replace_a_faulty_device.md, app/views/devices_guidance/resolve_issues_with_laptops_and_tablets.md, app/views/school/la_funded_places/order.html.erb, app/views/shared/_stock_levels.html.erb
=> Stock update 050421

app/models/computacenter/tech_source.rb
Next TechSource maintenance window is 15 May 21 8am--10pm
Add maintenance window
=> Add 15 May 21 TechSource maintenance window

app/views/pages/accessibility.md
- It's not a pilot any more
- It's not the summer
=> Tweak accessibility statement

app/form_objects/support_ticket/support_needs_form.rb, app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md
=> Rename remote education platforms – 040521 3

app/components/link_to_survey_component.html.erb, app/components/link_to_survey_component.rb, app/components/organisation/organisation_component.html.erb, app/components/organisation/organisation_component.rb, app/controllers/school/la_funded_places_chromebooks_controller.rb, app/models/school.rb, app/services/personas/scl_provisioned_user.rb, app/views/devices_guidance/device_specification.md, app/views/devices_guidance/how_to_order_laptops_for_independent_special_schools.html.erb, app/views/devices_guidance/how_to_order_laptops_for_social_care_leavers.html.erb, app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb, app/views/school/home/show_la_funded_place.html.erb, app/views/school/la_funded_places/_chromebook_ordering_for_care_leavers.html.erb, app/views/school/la_funded_places/laptop_types.html.erb, app/views/school/la_funded_places/order.html.erb, app/views/school/la_funded_places/show.html.erb, app/views/school/la_funded_places_chromebooks/edit.html.erb, app/views/schools/index.html.erb, app/views/support_tickets/thank_you.html.erb, config/locales/en.yml, lib/tasks/import_personas.rake, spec/components/link_to_survey_component_spec.rb, spec/components/organisation/organisation_component_spec.rb, spec/features/ordering_for_la_funded_devices_spec.rb, spec/models/school_spec.rb, spec/support/view_component.rb
Content changes for social care leavers
Content changes as described by @ralph-hawkins on 6 May 21
***All screenshots are out of date. Haven't had time to update them***
Screenshots from this branch:
=> Make changes for SCL users

app/models/computacenter/tech_source.rb
This week's outage has been abandoned so putting in next one for 29 May
=> Change outage window (current one abandoned)

app/views/devices_guidance/google_domain_for_care_leavers_and_children_with_social_worker.md, app/views/devices_guidance/how_to_order_laptops_for_independent_special_schools.html.erb, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, spec/features/responsible_body/ordering_devices_in_pool_spec.rb
=> G suite update

app/views/devices_guidance/device_specification.md, app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/preparing_a_standard_windows_device.md, app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md, app/views/devices_guidance/safeguarding_for_device_users.md, config/locales/en.yml, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/sign_in_token_behaviour_spec.rb
=> Standard restricted checks

app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md
Duplicate heading has appeared
Remove duplicate heading
=> removes duplicate heading

docs/support/add_iss_provision.md
Documentation regarding the creation of an ISS Provision
Documentation only
Follow the steps to confirm accuracy
=> Add doc for creating an ISS provision

app/views/devices_guidance/device_specification.md
We added some comments, but those comments show in the page.
Remove the comments.
Visit /devices/device-specification
=> removes comments because they rendered in the page

app/views/guide_to_collecting_mobile_information/asking_for_network.html.erb, app/views/guide_to_collecting_mobile_information/index.html.erb, app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb, app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/choosing_help_with_internet_access.html.erb, app/views/pages/how_request_4g_routers.html.erb, app/views/pages/internet_access.html.erb, config/locales/en.yml
=> 190521 connectivity

app/views/devices_guidance/device_specification.md, app/views/school/la_funded_places/laptop_types.html.erb, app/views/shared/_stock_levels.html.erb
=> 200521 stock content

app/views/devices_guidance/4g_user_guidance.md, app/views/devices_guidance/preparing_4g_wireless_routers.md, app/views/devices_guidance/resolve_issues_with_4g_wireless_routers.md
=> 4G guidance updates for resets

app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md, app/views/devices_guidance/replace_a_faulty_device.md, app/views/guide_to_resetting_windows_laptops_and_tablets/apply_your_own_settings.html.erb, app/views/guide_to_resetting_windows_laptops_and_tablets/index.html.erb
=> Names 210521

app/models/computacenter/chromebook_details.rb, spec/factories/preorder_information.rb, spec/models/computacenter/chromebook_details_spec.rb
https://trello.com/c/sFkh8Mw5/2024-investigate-why-brighton-and-hove-arent-appearing-on-the-manual-chromebook-process
=> List yes and i_dont_know schools in the chromebooks.csv

app/models/computacenter/chromebook_details.rb, spec/models/computacenter/chromebook_details_spec.rb
Revert this back to only listing will_need_chromebooks=yes, not a full revert, keeping the extra tests.
=> CSV Chromebook details should only list will_need_chromebooks=yes

app/views/devices_guidance/how_to_order_laptops_for_independent_special_schools.html.erb, app/views/devices_guidance/how_to_order_laptops_for_social_care_leavers.html.erb
=> Add date 020621

app/components/start_page_banner_component.html.erb
This has been bothering me for months
=> Fixes apostrophe

app/views/pages/what_to_do_if_you_cannot_get_laptops_tablets_or_internet_access_from_dfe.html.erb
A link was added, it didn't have a destination
Put the destination in
Visit https://get-help-with-tech.education.gov.uk/what-to-do-if-you-cannot-get-laptops-tablets-or-internet-access-from-dfe
=> fixes link that didn't have a destination

Dockerfile, app/views/mno/extra_mobile_data_requests/search_results.html.erb, babel.config.js, config/initializers/session_storage.rb, package.json, spec/views/school/home/show.html.erb_spec.rb, yarn.lock
<https://trello.com/c/MlnYp2ry/2069-fix-various-code-deprecations>
As we've updated various libraries / dependencies over the last few months, a few code deprecations have come up. We should fix these in due time as future upgrades could remove these deprecations (as is usual) and cause code breakages.
See individual commits for details.
=> [2069] Fix various deprecations

app/views/devices_guidance/reset_your_wireless_router.md
=> fixes indent on screenshot so numbered list maintains sequence

app/controllers/school/internet/home_controller.rb, spec/controllers/school/internet/home_controller_spec.rb
https://sentry.io/organizations/dfe-get-help-with-tech/issues/2445769847/?project=5320558&referrer=slack
Assign `@responsible_body` controller variable
=> Assign `@responsible_body`

app/views/pages/internet_access.html.erb
DCMS/DoE request to signpost users to Ofcom's webpage that outlines the different social tariff offers available.
Added a link to Ofcom's webpage.
=> Add_link_broadband_tariffs_internet_access

app/views/pages/internet_access.html.erb
=> Removes full-stop

app/views/shared/mno_offer_details/_asda_mobile.html.erb, app/views/shared/mno_offer_details/_bt_mobile.html.erb, app/views/shared/mno_offer_details/_ee.html.erb, app/views/shared/mno_offer_details/_giffgaff.html.erb, app/views/shared/mno_offer_details/_id_mobile.html.erb, app/views/shared/mno_offer_details/_iq_mobile.html.erb, app/views/shared/mno_offer_details/_lycamobile.html.erb, app/views/shared/mno_offer_details/_o2.html.erb, app/views/shared/mno_offer_details/_sky_mobile.html.erb, app/views/shared/mno_offer_details/_smarty.html.erb, app/views/shared/mno_offer_details/_tesco_mobile.html.erb, app/views/shared/mno_offer_details/_virgin_mobile.html.erb, app/views/shared/mno_offer_details/_vodafone.html.erb
=> MNO deadline

app/models/computacenter/tech_source.rb
Add TechSource outage for Sat 19 Jun 21, 8am to 10pm
Add this maintenance window
=> Add TechSource outage window 19 Jun, 8am to 10pm

app/views/shared/_start_ordering_on_techsource.html.erb
https://sentry.io/organizations/dfe-get-help-with-tech/issues/2446391298/?project=5320558&referrer=slack
Add another `nil` safety
=> Add nil check

app/views/pages/about_increasing_mobile_data.html.erb, app/views/shared/mno_offer_details/_lebara_mobile.html.erb
=> Lebara 160621

app/models/computacenter/tech_source.rb
https://trello.com/c/AyDcaYim
Latest TechSource outage Saturday 26th June  from 09:00 to 13:00 BST
Change outage window
=> Add latest TechSource maintenance window

app/views/guide_to_collecting_mobile_information/_guide_contents.html.erb, app/views/pages/internet_access.html.erb
<https://trello.com/c/Foplspxv/2151-update-guidance-content-internet-access>
=> [2151] Update guidance content: /internet-access

app/components/school_user_summary_list_component.rb, app/views/school/users/index.html.erb, app/views/shared/_privacy_notice_text.html.erb, config/locales/en.yml, spec/features/school/manage_users_spec.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb
https://trello.com/c/9pMYw1nY
Turns out this is only content changes (it looks like it's changing the attribute it operates on but Patrick Allum's said that isn't the case)
Text changes only
=> 2153 manage users

app/views/support_tickets/start.html.erb
<https://trello.com/c/5eHj83k5/2156-update-guidance-content-get-support>
=> [2156] Update guidance content / Get-Support

app/components/start_page_banner_component.html.erb, app/views/pages/home_page.html.erb
<https://trello.com/c/MsPMWUsC/2157-update-guidance-content-ghwt-homepage>
=> [2157] Update guidance content / GHwT homepage

app/controllers/application_controller.rb, app/controllers/school/base_controller.rb, app/services/interstitial_picker.rb, app/views/interstitials/_school_user.html.erb, config/routes.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/services/interstitial_picker_spec.rb
Skip over privacy notice whilst users cannot order
https://trello.com/c/dLLYzzB7
=> 2146 updated welcome page

app/views/support_tickets/start.html.erb
Follow on from https://github.com/DFE-Digital/get-help-with-tech/pull/1832
=> Tweak wording on the Get Support page

app/views/devices_guidance/about_the_offer.md
=> removes typo, unnecessary "is"

app/views/responsible_body/users/index.html.erb, app/views/responsible_body/users/new.html.erb
=> 2160 manage rb users

app/helpers/huawei_router_passwords_helper.rb, app/views/huawei_router_passwords/new.html.erb, spec/features/huawei_password_spec.rb, spec/helpers/huawei_router_passwords_helper_spec.rb
=> 2167 huawei password breadcrumb

app/views/shared/_invite_someone_who_can.html.erb
@Lloyd-K and I corrected this as part of the pausing service update but should be in the service asap.
=> updates content on who we share user data with

app/views/sign_in_tokens/email_not_recognised.html.erb
Text change: https://trello.com/c/4QK2JYeT
=> 2173 email not recognised page

app/views/support_tickets/support_details.html.erb
<https://trello.com/c/tCrTOaoA/2171-update-guidance-content-get-support-how-can-we-help-you>
=> [2171] Update guidance content (Get Support - How can we help you?)

app/views/devices_guidance/about_the_offer.md, app/views/devices_guidance/device_allocations.md, app/views/devices_guidance/device_specification.md, app/views/pages/what_to_do_if_you_cannot_get_laptops_tablets_or_internet_access_from_dfe.html.erb, config/locales/en.yml
Simple content changes
Todo:
- ~~Further content 5 content changes requested but need further clarification from Kate~~
=> Quick content changes

app/views/shared/_guide_navigation.html.erb
<https://trello.com/c/Foplspxv/2151-update-guidance-content-internet-access>
Reinstated the partial that was mistakenly deleted in https://github.com/DFE-Digital/get-help-with-tech/pull/1844
=> [2151] Update guidance content: /internet-access – part 3

app/views/responsible_body/devices/schools/index.html.erb, spec/features/responsible_body/viewing_your_schools_spec.rb
UI changes requested by Pritesh
=> Remove "Order devices" and "Is this list wrong?"

app/views/devices_guidance/4g_user_guidance.md, app/views/devices_guidance/preparing_4g_wireless_routers.md, app/views/devices_guidance/reset_your_wireless_router.md, app/views/devices_guidance/resolve_issues_with_4g_wireless_routers.md, app/views/pages/internet_access.html.erb, config/locales/en.yml
=> 4g data extension

app/views/devices_guidance/replace_a_faulty_device.md
=> Dannychadburndfe patch 14

docs/secrets_management.md
Blurb around secrets management investigation
Add doc to repo
=> Adding Secrets Managment Doc

app/form_objects/school_search_form.rb, spec/form_objects/school_search_form_spec.rb
In Support search for schools multiple urn search to include ISS/SCL provision_urn field
=> Add ISS/SCL provision_urn to multiple search

app/views/interstitials/_school_user.html.erb, app/views/responsible_body/home/_closed_banner.html.erb, app/views/school/home/_closed_banner.html.erb, spec/features/responsible_body/home_spec.rb, spec/features/school/view_school_details_spec.rb
=> Remove the 4G 31 July blurb for signed in pages

app/views/school/home/show.html.erb, spec/features/school/view_school_details_spec.rb
=> Hide Order History title if no links below it

app/views/pages/internet_access.html.erb
=> Remove 4g text

config/settings.yml, lib/encryption_service.rb, spec/lib/encryption_service_spec.rb
Rails 7 is going to add database encryption but is not released yet. We'll probably upgrade to Rails 7 fairly soon after 
release, so we'll use a lightweight solution in the meantime before then.
https://trello.com/c/fZFmCWR2
=> Add class to encrypt/decrypt strings (for database fields)

app/controllers/assets_controller.rb, app/models/asset.rb, app/views/assets/index.html.erb, app/views/assets/show.html.erb, config/routes.rb, db/migrate/20210810155945_create_assets.rb, db/schema.rb, lib/encryption_service.rb, spec/controllers/assets_controller_spec.rb, spec/factories/assets.rb, spec/lib/encryption_service_spec.rb, spec/models/asset_spec.rb
https://trello.com/c/JpWLP8n9
Adds `Asset`s to the application to view their passwords, etc.
This is an early commit to test `Asset` creation performance on production.
=> 2306 display assets

app/jobs/computacenter_historical_asset_import_job.rb, spec/jobs/computacenter_historical_asset_import_job_spec.rb
Fix typo and put some specs round more code
=> Fix typo for job for importing CC assets

app/jobs/computacenter_historical_asset_import_job.rb, spec/jobs/computacenter_historical_asset_import_job_spec.rb
Fixed another problem (by taking the time to run locally)
=> Fix failing job

app/controllers/support/gias/schools_to_add_controller.rb, app/controllers/support/gias/schools_to_close_controller.rb, app/mailers/sign_in_token_mailer.rb, app/views/support/gias/schools_to_add/show.html.erb, spec/controllers/support/gias/home_controller_spec.rb, spec/controllers/support/gias/schools_to_add_controller_spec.rb, spec/controllers/support/gias/schools_to_close_controller_spec.rb, spec/services/school_update_service_spec.rb
After the daily import from GIAS we persist staged schools but we still need to create 'real' schools in the system.
See [user story: GIAS - Open/Close schools (RFQ-11)](https://trello.com/c/kMNBvf1r)
The code was there already. I have included minor changes and:
- Tests for the 3 controllers involved.
- Some missing tests for existing methods in SchoolUpdateService that returns the potential staged schools suitable to be added/closed.
- Manual test locally worked as expected.
=> 2216: open close schools

app/services/trust_update_service.rb
Some Trusts can't be closed at GIAS csv processing time because support user haven't closed/moved all the associated schools yet.
Auto-close Trusts with associated DataStage::Trust closed which have lost all their schools since last GIAS csv run.
Make TrustUpdateService check ALL the closeable staged trusts rather than only those updated in the previous run. 
[GIAS - Ability to close trusts that failed to auto-close (RFQ-12)](https://trello.com/c/0t7htmIv)
=> 2314: auto close any trust that meet all the requirements

app/models/asset.rb, app/views/assets/index.html.erb, spec/factories/assets.rb, spec/models/asset_spec.rb
In response to feedback when shown to the DfE
https://trello.com/c/JpWLP8n9
=> Only provide link when at least one of admin password, BIOS password or hardware hash is available

app/jobs/anonymise_extra_mobile_data_requests_job.rb, app/models/extra_mobile_data_request.rb, spec/jobs/anonymise_extra_mobile_data_requests_job_spec.rb
https://trello.com/c/wEcGu5yE
Anonymise data by using Faker. The same customer name/phone number gets the same anonymised value to preserve information about repeat requests.
=> 2203 anonymise data

app/concerns/csv_value_sanitiser.rb, app/concerns/exportable_as_csv.rb, app/controllers/assets_controller.rb, app/models/asset.rb, app/policies/asset_policy.rb, app/views/assets/index.html.erb, app/views/assets/show.html.erb, spec/concerns/csv_value_sanitiser_spec.rb, spec/controllers/assets_controller_spec.rb, spec/models/asset_spec.rb, spec/models/extra_mobile_data_request_spec.rb, spec/policies/asset_policy_spec.rb
https://trello.com/c/gKdKsd5W
Original CSV sanitiser wasn't actually making CSVs safe (if they're exported into Microsoft Excel) so rewrote that.
=> Add CSV export for `Asset`s

app/views/responsible_body/home/_summary_reset_devices.html.erb, app/views/school/home/_summary_reset_devices.html.erb
=> Add user link to assets path

app/controllers/assets_controller.rb, app/views/assets/index.html.erb
Stretch requirement from Patrick to remove ability to download CSV when searching
=> Remove ability to download when searching

app/components/start_page_banner_component.html.erb, app/views/devices_guidance/device_distribution_and_ownership.md, app/views/devices_guidance/device_specification.md, app/views/devices_guidance/preparing_a_standard_windows_device.md, app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md, app/views/devices_guidance/safeguarding_for_device_users.md, app/views/guide_to_resetting_windows_laptops_and_tablets/apply_your_own_settings.html.erb, app/views/guide_to_resetting_windows_laptops_and_tablets/get_local_admin_and_bios_passwords.html.erb, app/views/guide_to_resetting_windows_laptops_and_tablets/index.html.erb, app/views/guide_to_resetting_windows_laptops_and_tablets/reset_the_bios_password.html.erb, app/views/guide_to_resetting_windows_laptops_and_tablets/reset_the_device.html.erb, app/views/guide_to_resetting_windows_laptops_and_tablets/unlock_recovery_mode.html.erb, app/views/pages/home_page.html.erb
=> Update copy to remove dates and references to support portal

app/views/devices_guidance/preparing_chromebooks.md
=> Service reopening small text changes

app/components/school_user_summary_list_component.rb, app/views/devices_guidance/preparing_chromebooks.md, app/views/interstitials/_school_user.html.erb, app/views/responsible_body/users/index.html.erb, app/views/school/users/index.html.erb, app/views/shared/_invite_someone_who_can.html.erb, app/views/shared/_school_user_form.html.erb, config/locales/en.yml, db/migrate/20210914112651_change_user_orders_devices_default.rb, db/schema.rb, spec/features/school/manage_users_spec.rb, spec/features/support/inviting_school_users_spec.rb, spec/models/school_welcome_wizard_spec.rb, spec/page_objects/support/users/invite_new_user_page.rb
https://trello.com/c/pdwz4eNc
This contains an *irreversible* migration
=> 2434 remove more support portal mentions

app/models/asset.rb
Just checking for presence of encrypted values, rather than decrypting first.
Good spot by @kenfodder
=> Optimise `has_secret_information?`

app/controllers/assets_controller.rb, app/models/asset.rb, app/views/assets/index.html.erb, lib/search_serial_number_parser.rb, spec/controllers/assets_controller_spec.rb, spec/lib/search_serial_number_parser_spec.rb, spec/models/asset_spec.rb
https://trello.com/c/FCa5LPRb
Allow searching for multiple serial numbers (for support users only). Patrick Allum has confirmed there's no limit to the number they can search for.
=> Allow searching for multiple serial numbers

app/controllers/pages_controller.rb, app/views/pages/finding_out_about_internet_access_needs.html.erb, app/views/pages/internet_access.html.erb, config/locales/en.yml, config/routes.rb
=> Update Internet access text

app/views/devices_guidance/preparing_ipads.md
=> Update iPad text

app/controllers/application_controller.rb, app/controllers/school/base_controller.rb, app/services/interstitial_picker.rb, app/views/interstitials/_school_user.html.erb, config/routes.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/services/interstitial_picker_spec.rb
School user sign in journey
Re-enable the sign in wizard flow from https://github.com/DFE-Digital/get-help-with-tech/pull/1822/files
=> Ressurect welcome wizard

app/controllers/assets_controller.rb, spec/controllers/assets_controller_spec.rb
Attempt to improve database query which was causing a timeout when downloading the `Asset` CSV
=> Improve Assets database query

app/views/landing_pages/digital_platforms.md
=> Requested content changes

app/views/school/la_funded_places_chromebooks/edit.html.erb, app/views/shared/_chromebook_information_form.html.erb, config/locales/en.yml, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/components/school/school_details_summary_list_component_spec.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/support/editing_chromebook_details_for_a_school_spec.rb
https://trello.com/c/I75UKrFP
https://trello.com/c/AltAzrth
Covers both RBs and Schools. I've shown Wes other text that'll need to change but we'll come to that later.
=> Change Chromebooks question text

spec/models/school_spec.rb
=> fix no stub test

package.json, yarn.lock
=> Bring `main` changes into `reopening`

app/components/school_user_summary_list_component.rb, app/components/user_summary_list_component.rb, app/views/responsible_body/home/show.html.erb, app/views/responsible_body/users/index.html.erb, app/views/responsible_body/users/new.html.erb, app/views/school/users/index.html.erb, app/views/shared/_school_user_form.html.erb, config/locales/en.yml, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/support/inviting_school_users_spec.rb, spec/models/school_welcome_wizard_spec.rb, spec/page_objects/support/users/invite_new_user_page.rb
https://trello.com/c/bSQx9YtK
https://trello.com/c/m6jnyqXK
=> 2378 and 2324 who order schools and RBs

app/components/conditional_school_preorder_status_tag_component.html.erb, app/components/conditional_school_preorder_status_tag_component.rb, app/form_objects/responsible_body/devices/who_to_contact_form.rb, app/views/responsible_body/devices/schools/_school_states_table.html.erb, app/views/responsible_body/devices/schools/index.html.erb, spec/features/responsible_body/devices_setup_spec.rb, spec/features/responsible_body/viewing_your_schools_spec.rb
- Reinstate "Order devices" call to action on "Your schools and colleges" page
- Reinstate the conditional status tag
- Fix the who to contact form
- Unskip spec for viewing your schools
=> 2326 your schools colleges

app/components/start_page_banner_component.html.erb, app/views/pages/home_page.html.erb
=> 2429 sign in page

app/views/devices_guidance/preparing_chromebooks.md, config/locales/en.yml
=> Content changes for chromebook setup guide

app/views/pages/how_to_access_the_get_help_with_technology_service.html.erb
=> Content changes for accessing the service

app/models/computacenter/api/cap_usage_update.rb, app/models/computacenter/api/cap_usage_update_batch.rb, app/services/feature_flag.rb, spec/models/computacenter/api/cap_usage_update_spec.rb
=> add feature flag for cap used decreases

app/controllers/responsible_body/devices/who_to_contact_controller.rb
=> load missing schools data

app/views/shared/internet/_home.html.erb
https://trello.com/c/4E3LZl6U
Agreed with Oren to show these links to all logged-in users
=> Bring router links back

db/migrate/20211105224402_replace_raw_cap_fields_from_schools.rb
=> cannot_order schools do not change cap persisted data

db/migrate/20211102150517_cap_changes_for_over_ordered_schools.rb
=> fix migration bug

app/jobs/computacenter_asset_job.rb
Change needed to get this running on production
=> Get job running correctly

app/jobs/calculate_vcap_job.rb, app/models/responsible_body.rb, spec/factories/schools.rb, spec/jobs/calculate_vcap_job_spec.rb
Bug: We also need to update router vcaps when processing  Allocation jobs!
=> 2560: recompute router vcaps on CalculateVcapJob

app/jobs/computacenter_asset_job.rb, spec/jobs/computacenter_asset_job_spec.rb
Trying with `serial_number` as matching ID for comparison
=> 2503 assets job

app/jobs/computacenter_asset_job.rb, spec/jobs/computacenter_asset_job_spec.rb
Adding more logging to see if helps
=> Add logging and see if matches agree (using `xit` on specs for now)

app/jobs/computacenter_asset_job.rb, spec/jobs/computacenter_asset_job_spec.rb
Annoying code change needed to job
=> Make small fix to job

app/jobs/computacenter_asset_job.rb, spec/jobs/computacenter_asset_job_spec.rb
Add more logging and fix messages about encrypted fields changing
=> Asset update job logging and message fix

app/controllers/computacenter/multi_domain_chromebooks_controller.rb, app/controllers/computacenter/multi_domain_chromebooks_iss_scl_controller.rb, app/models/computacenter/chromebook_details.rb, app/models/computacenter/ledger.rb, app/services/allocations_exporter.rb, app/services/device_supplier/export_allocations_service.rb, app/services/device_supplier/export_users_service.rb, app/services/donated_device_requests_exporter.rb, app/services/exporters/mno_requests_csv.rb, app/services/responsible_body_exporter.rb, app/services/school_data_exporter.rb, app/services/zendesk_macro_export_service.rb, spec/models/computacenter/ledger_spec.rb
[Malicious Input Executed in CSV Export (Risk: medium)](https://trello.com/c/99F40RGA)
=> 2570: sanitise generated csv values

app/jobs/computacenter_asset_job.rb, spec/jobs/computacenter_asset_job_spec.rb
Deal with assets which aren't found in the database, or where there are conflicting matches
Removed some code which was used to generate statistics for dry run
=> Implement strategy for adding problematic Asset rows

app/components/responsible_body/school_details_summary_list_component.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/support/enabling_orders_for_a_school_spec.rb
=> Change text to be less specific

app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb, app/views/shared/_summary_reset_devices.html.erb, spec/features/responsible_body/home_spec.rb, spec/features/school/view_school_details_spec.rb
=> Change text and visual styling of device reset information

app/views/devices_guidance/preparing_a_standard_windows_device.md, config/locales/en.yml
=> Update guidance text for preparing devices

app/controllers/assets_controller.rb, app/views/assets/index.html.erb, config/routes.rb, spec/controllers/assets_controller_spec.rb
https://trello.com/c/qPl8SHGf
Merged `search` into `index` action to reduce code duplication
=> Allow CSV download of asset search results

app/helpers/view_helper.rb, app/views/shared/_chromebook_information_form.html.erb, spec/helpers/view_helper_spec.rb
=> Content changes regarding multiple Chromebook domains

app/components/computacenter/tech_source_maintenance_banner_component.rb, spec/components/previews/computacenter/tech_source_maintenance_banner_component_spec.rb
=> Fix where supplier outage banner text wasn't showing

app/components/allocation_component.html.erb, app/components/allocation_component.rb, spec/components/allocation_component_spec.rb, spec/features/ordering_for_la_funded_devices_spec.rb
=> Change text to cover case where they've ordered but not received devices yet

app/views/interstitials/_scl_provision_user.html.erb
=> Text changes for social care leavers

config/computacenter/api/schema/CapUsage.xsd, docs/computacenter_api.md, spec/controllers/computacenter/api/cap_usage_controller_spec.rb, spec/features/api/cap_usage_bulk_update_spec.rb
Validate length and format of the payloadId, also check the shipTo is a number.
=> Validate payloadId from CC bulk update

app/views/devices_guidance/device_distribution_and_ownership.md, app/views/devices_guidance/operation_warm_welcome.md, app/views/pages/home_page.html.erb, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, app/views/responsible_body/devices/schools/order_devices.html.erb, app/views/responsible_body/home/show.html.erb, app/views/school/devices/can_order.html.erb, app/views/school/home/show.html.erb, app/views/shared/_operation_warm_welcome_ordering.html.erb, config/locales/en.yml
https://trello.com/c/jnvWY3xH
https://trello.com/c/sM3BTRgw
=> Content changes for Operation Warm Welcome

app/views/shared/_operation_warm_welcome_ordering.html.erb
=> Remove link to form

app/controllers/school/home_controller.rb, app/views/school/home/show.html.erb, spec/features/school/change_chromebook_information_spec.rb
[2527](https://trello.com/c/u1JWp9mw)
=> 2527: add policy check to display or not school details link

app/views/shared/_operation_warm_welcome_ordering.html.erb
=> Reinstate link to form

app/components/display_allocation_component.html.erb, app/components/display_allocation_component.rb, app/controllers/responsible_body/devices/schools_controller.rb, app/views/responsible_body/devices/schools/_school_states_table.html.erb, app/views/responsible_body/devices/schools/index.html.erb, spec/components/display_allocation_component_spec.rb, spec/controllers/responsible_body/devices/schools_controller_spec.rb, spec/page_objects/responsible_body/schools_page.rb
[Correct allocation not showing on "Your schools and colleges page"](https://trello.com/c/RutKoauw)
=> 2552: display allocation and devices ordered for non vcap rbs

app/views/guide_to_resetting_windows_laptops_and_tablets/get_local_admin_and_bios_passwords.html.erb
=> Change text to reflect actual link text

db/migrate/20211126135609_change_type_of_urn_on_allocation_batch_jobs.rb, db/schema.rb, spec/form_objects/support/bulk_allocation_form_spec.rb
=> convert AllocationBatchJob#urn to string

app/views/devices_guidance/how_to_order.html.erb
=> SCL content change

app/helpers/view_helper.rb
=> fix bug when looking for a school with provision_urn string

app/views/devices_guidance/device_specification.md, app/views/devices_guidance/preparing_chromebooks.md
=> Content changes to be deployed on 1 Dec 21

app/views/pages/internet_access.html.erb
=> Change content for Internet Access page on 5pm 30 Nov 21

Dockerfile
=> Try pinning yarn version to fix Node upgrade for deployment

Dockerfile
=> Remove version numbers from Dockerfile

app/views/devices_guidance/about_the_offer.md, app/views/landing_pages/digital_platforms.md
=> Change content for service change on 5pm 30 Nov 21

lib/tasks/release.rake
=> fix rake task

app/jobs/allocation_email_job.rb, app/models/computacenter/api/cap_usage_update.rb, app/models/school.rb, app/models/school_can_order_devices_notifications.rb, app/services/cap_update_notifications_service.rb, spec/jobs/allocation_email_job_spec.rb, spec/models/school_can_order_devices_notifications_spec.rb
[2058](https://trello.com/c/TzKtp4sY)
Refactor SchoolCanOrderDevicesNotifications and make clear what is notified at anytime
=> 2058: refactor SchoolCanOrderDevicesNotifications

docs/computacenter_incoming_api.md, docs/computacenter_outgoing_api.md, docs/updating_allocations.md, docs/virtual_cap_pools.md, docs/who_will_order_devices.md
[Card](https://trello.com/c/RcB0P6qF)
=> 2521: update documentation about allocations

app/components/organisation_vcap_tag_component.html.erb, app/components/organisation_vcap_tag_component.rb, app/controllers/application_controller.rb, app/views/layouts/application.html.erb, app/views/support/responsible_bodies/show.html.erb, config/locales/en.yml, spec/components/organisation_vcap_tag_component_spec.rb, spec/components/previews/organisation_vcap_tag_component_preview.rb, spec/features/support/viewing_responsible_body_info_spec.rb
[Indicate to support users whether or not an rb is managing a vcap](https://trello.com/c/KDiXodi3)
=> 2619 highlight vcaps

app/components/responsible_body/school_details_summary_list_component.rb, app/models/computacenter/devices_ordered_update.rb, app/models/school.rb, config/settings.yml, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/factories/devices_ordered_updates.rb, spec/models/school_spec.rb
This [card](https://trello.com/c/Q8MVGUSR)
=> 2535: display devices ordered in previous waves

app/views/responsible_body/home/_summary_order_history.html.erb, app/views/school/home/_summary_order_history.html.erb
=> Greybox enclose Order History links

app/controllers/support/allocation_batch_jobs_controller.rb, app/form_objects/support/bulk_allocation_form.rb, app/helpers/support/allocation_batch_jobs_helper.rb, app/jobs/bulk_allocation_job.rb, app/views/support/allocation_batch_jobs/show.html.erb, db/migrate/20220114153735_add_index_to_allocation_batch_jobs.rb, db/schema.rb, spec/controllers/support/allocation_batch_jobs_controller_spec.rb, spec/controllers/support/schools/devices/order_status_controller_spec.rb, spec/features/support/schools/bulk_upload_allocation_spec.rb, spec/form_objects/support/bulk_allocation_form_spec.rb, spec/jobs/bulk_allocation_job_spec.rb, spec/page_objects/support/allocation_batch_jobs/show_page.rb
See card [Scale bulk allocation updates](https://trello.com/c/5Jp9XHdx)
=> 2674 scale bulk allocation updates

app/jobs/bulk_allocation_job.rb
=> 2674: do not rescue silently from errors on processing a tranche

app/form_objects/support/bulk_allocation_form.rb
=> 2674: assume bucket has been automatically created by the service

app/form_objects/support/bulk_allocation_form.rb, app/jobs/bulk_allocation_job.rb, app/views/support/allocation_batch_jobs/show.html.erb, config/initializers/aws_s3.rb, spec/support/aws_s3_helper.rb
- Add warning copy next to 'Send notifications' button
- Rename constants 
-  Clean unused code
=> 2674: add disclaimer next to Send notifications button

app/components/support/email_audit_list_component.html.erb, app/components/support/user_search_result_component.html.erb
Missed a couple of bits for the v3 to v4 upgrade of govuk-frontend
=> Explicit option when there are no actions

app/components/allocation_component.html.erb, app/components/allocation_component.rb, app/components/allocation_component_factory.rb, spec/components/allocation_component_factory_spec.rb, spec/components/allocation_component_spec.rb
See [card](https://trello.com/c/B32yYmb8)
=> 2690: add devices available to order to allocation grey boxes

app/components/allocation_component.html.erb, app/components/allocation_component.rb, spec/components/allocation_component_spec.rb
See [card](https://trello.com/c/B32yYmb8)
=> 2690: new design

app/components/allocation_component.html.erb, app/components/allocation_component.rb, spec/components/allocation_component_spec.rb
=> 2690 add devices available to allocation grey boxes 3

app/views/pages/internet_access.html.erb
[Card](https://trello.com/c/c3gcgmde)
Minor content change
=> 2693: update end date

app/views/devices_guidance/preparing_ipads.md
[card](https://trello.com/c/LtRcAXaK)
=> 2734: preparing ipads copy change

app/models/support/service_performance.rb, app/views/support/service_performance/_devices.html.erb, app/views/support/service_performance/_routers.html.erb, config/locales/en.yml, spec/factories/schools.rb, spec/features/support/viewing_service_performance_spec.rb, spec/models/support/service_performance_spec.rb
[Card](https://trello.com/c/WObDY3mf)
=> 2632: add total over orders to dashboard and fix other totals labels

app/services/interstitial_picker.rb
[Card](https://trello.com/c/Xw2axoIi)
=> 2762: only display user organisation name when there is one

app/views/devices_guidance/device_allocations.md
[Card](https://trello.com/c/M8qYLzOs)
=> 2777: add copy changes to the allocations page

app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb
=> 2788: remove last bullet point on Order Devices section

app/components/allocation_component.rb, spec/components/allocation_component_spec.rb
[Card](https://trello.com/c/ouxyyqqs)
Add missing full stop.
=> 2789: add missing full stop

app/views/interstitials/_school_user.html.erb
[Card](https://trello.com/c/R5ThLwJB)
More changes to remove devices ordering on sign-in journeys
=> 2784: change first sign-in page

app/models/school_welcome_wizard.rb
[Card](https://trello.com/c/R5ThLwJB)
Fix bug when transitioning steps in welcome wizard
=> 2784: fix bug when transitionning steps in welcome wizard

app/components/school_user_summary_list_component.rb
[Card](https://trello.com/c/R5ThLwJB)
More content removed
=> 2784: remove more content about ordering

app/components/responsible_body/school_details_summary_list_component.rb, config/locales/en.yml, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/responsible_body/devices_setup_spec.rb, spec/features/responsible_body/viewing_your_schools_spec.rb, spec/features/support/changing_who_will_order_devices_for_a_school_spec.rb, spec/features/support/enabling_orders_for_a_school_spec.rb
[Card](https://trello.com/c/R5ThLwJB)
More content removed
=> 2784: more changes to remove ordering from sign-in journeys

Gemfile, app/controllers/support/schools/devices/order_status_controller.rb, app/views/support/home/schools.html.erb, spec/controllers/support/schools/devices/order_status_controller_spec.rb, spec/features/support/schools/bulk_upload_allocation_spec.rb
[Card](https://trello.com/c/nrWGO8OJ)
=> 2819: disable bulk allocations uploads

app/views/support/home/schools.html.erb
Re-enable allocations export. It was disabled in previous PR by mistake.
[Card](https://trello.com/c/nrWGO8OJ)
=> 2819: do not disable allocations export

app/views/devices_guidance/preparing_chromebooks.md, app/views/devices_guidance/replace_a_faulty_device.md, app/views/pages/how_to_access_the_get_help_with_technology_service.html.erb
=> 2836: last changes to guidance pages

app/models/asset.rb, spec/models/asset_spec.rb
[Fix assets with no school/rb associated](https://trello.com/c/PERqI66m)
=> 2837: fix assets with department_id following pattern SCxxx

app/jobs/computacenter_asset_job.rb, spec/jobs/computacenter_asset_job_spec.rb
[Card](https://trello.com/c/Ipuh1V9v)
Update the job to upload assets to the new csv structure received from CC
=> 2780: upload winter assets

package.json, yarn.lock
=> bump jest to 28.0.2

app/jobs/apply_staged_attribute_changes_to_trusts_job.rb
=> 2929: pausing ApplyStagedAttributeChangesToTrustsJob

Gemfile.lock, app/models/asset.rb, app/models/computacenter/order.rb, app/models/computacenter/raw_order.rb, app/models/responsible_body.rb, app/models/school.rb, app/services/computacenter/associate_settings_to_assets_service.rb, app/services/computacenter/associate_settings_to_orders_service.rb, db/migrate/20220510215126_add_setting_to_assets.rb, db/schema.rb, lib/tasks/asssociate_settings.rake
=> 2955: add rake tasks to associate settings to orders and assets

app/services/computacenter/associate_settings_to_assets_service.rb, app/services/computacenter/associate_settings_to_orders_service.rb
=> 2955: check presence of values in associate_settings rake tasks

app/services/computacenter/associate_settings_to_assets_service.rb, db/migrate/20220512185917_add_index_on_computacenter_reference_to_schools.rb, db/schema.rb
=> 2955: refine setting-assets association logic

app/jobs/bulk_restricted_device_password_emailing_job.rb, app/jobs/restricted_device_password_emailing_for_setting_job.rb, app/mailers/restricted_device_passwords_mailer.rb, app/models/asset.rb, app/models/responsible_body.rb, app/models/school.rb, app/models/user.rb, config/settings.yml, db/migrate/20220519092557_add_restricted_devices_comms_opt_out_to_users.rb, db/schema.rb, spec/controllers/assets_controller_spec.rb, spec/factories/assets.rb, spec/features/assets/export_csv_spec.rb, spec/features/assets/index_spec.rb, spec/jobs/bulk_restricted_device_password_emailing_job_spec.rb, spec/jobs/restricted_device_password_emailing_for_setting_job_spec.rb, spec/mailers/restricted_device_passwords_mailer_spec.rb, spec/models/asset_spec.rb, spec/models/responsible_body_spec.rb, spec/models/school_spec.rb
We need to email all school and rb users with DfE restricted devices the passwords of their devices.
Use GovUK Notify service to send the emails including a link to a file stored in Notify containing all their password information.
=> 2923: job to email restricted device passwords to all users

app/jobs/restricted_device_password_emailing_for_setting_job.rb, spec/jobs/restricted_device_password_emailing_for_setting_job_spec.rb
=> 2923: only include DfE-restricted devices
