Makefile
In the `deploy` make task, if the `cf push` fails for any reason, the temporary `manifest.yml` symlink will remain, making any subsequent `deploy` fail until it's manually removed.
in the deploy task, test to see if manifest.yml exists, and unlink it if it does
=> on deploy, remove any existing manifest.yml symlink

app/webpacker/packs/application.js, package.json, spec/features/mno/mno_recipients_spec.rb, yarn.lock
Testing showed that after clicking a pagination link, the all/none links were shown rather than the checkbox. Investigation showed that the `$(document).ready` event was not firing after clicking a link, but was fine when you refresh the page.
Fix the problem by removing turbolinks
=> Fix issue with all/none links showing instead of checkboxes on paginated pages

app/controllers/application_controller.rb, app/services/feature_flag.rb, app/views/layouts/_nav.html.erb, config/routes.rb, spec/features/static_guidance_only_feature_flag_spec.rb
Since hitting the headlines last week & soft-launching a pilot, we are getting an increasing number of mails to support. We need to be able to launch some static guidance on a live URL ASAP, and that URL should not change later when the full app is launched. 
In order to minimize the risk of putting an application live that has not yet gone through the full governance cycle, we need to have a feature flag mechanism that allows us to ensure that only the static guidance page is reachable on prod.
1. Add FeatureFlag service with an MVP backend based around environment variables
2. Add `static_guidance_only` feature flag that disables all URLs except the guidance page.
3. Add feature spec to make sure this behaviour works as intended
1. Start your local Rails server with the environment …
=> Add FeatureFlag service & implement static_guidance_only feature flag

app/views/mno/recipients/index.html.erb, app/views/shared/_next_page.html.erb, app/views/shared/_pagination.html.erb, app/views/shared/_prev_page.html.erb, app/webpacker/styles/pagination.scss, spec/features/mno/mno_recipients_spec.rb
The default pagination provided by Pagy's helpers looks very ... default pagination, and not in -keeping with other gov.uk sites like Find Postgraduate Teacher Training (and gov.uk itself)
Make pagination look like other gov.uk sites
Before:
After:
The default number of items per page is 20. You'll need to create more than 20 recipients for your MNO user (with `FakeDataService.generate!`) and/or pass a lower number as a param (say `&items=4`)
=> Make pagination look like Find  / gov.uk

README.md, app/services/feature_flag.rb, app/views/layouts/application.html.erb, spec/features/feature_flags/show_debug_info_spec.rb
We've been using an env var SHOW_DEBUG_INFO as a temporary way to render the session & sign-in links into the footer during development. Now we have an actual FeatureFlag implementation, it should use that.
1. replace the SHOW_DEBUG_INFO with a show_debug_info FeatureFlag
2. add feature_flag spec for the behaviour
3. add a section to the README about FeatureFlags and how to set them locally and on PaaS
=> port SHOW_DEBUG_INFO behaviour to use a FeatureFlag

README.md, app/concerns/sign_in_with_token.rb, app/services/session_service.rb, db/migrate/20200620124213_add_sign_in_token_expires_at_to_user.rb, db/schema.rb, spec/features/sign_in_token_behaviour_spec.rb
See [Trello card](https://trello.com/c/3tRtyZrZ/121-make-signintokens-time-limited)
Make sign_in_tokens expire after 10 mins by default. 
Add option to set a different expiry period via env var
Add spec for expiry/non-expiry behaviour
1. Generate a sign-in token by clicking 'Sign in' and entering your email address. Copy the sign-in URL from the footer
2. From the console, check that `sign_in_token_expires_at` is set correctly (`User.where(email_address: '...').sign_in_token_expires_at`)
3. Wait until that expires (or update it from the console), and then try and use the sign-in token URL - it should not work
4.
=> Make sign_in_tokens expire after 30 mins by default

app/controllers/application_controller.rb, app/controllers/mno/base_controller.rb, app/controllers/sessions_controller.rb, app/helpers/application_helper.rb, app/models/session.rb, app/services/session_service.rb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/layouts/_nav.html.erb, app/views/pages/guidance.html.erb, config/locales/en.yml, db/migrate/20200622133205_create_sessions.rb, db/schema.rb, spec/controllers/allocation_request_forms_controller_spec.rb, spec/features/feature_flags/http_basic_auth_spec.rb, spec/features/feature_flags/static_guidance_only_feature_flag_spec.rb, spec/features/session_behaviour_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/features/submitting_an_allocation_request_form_spec.rb, spec/features/view_pages_spec.rb
Currently browser-cookie-based sessions will expire when and only when the user closes their browser window. This means a session could potentially last forever.
We should expire sessions when the user has not visited a page after a certain time - say, 1hr by default. This should also be configurable by env var.
Create a session record in the DB so that we can track last visit time reliably on the server
Refactor the SessionService to take more of the management of sessions out of the controllers
Add specs for desired behaviour
1. Start the server with an env var `SESSION_TTL_SECONDS` set to a short value - say, 5 (for example, `SESSION_TTL_SECONDS=5 FEATURES_show_debug_info=active bundle exec rails server`)
2. Sign in the usual way (magic link in footer)
3. Wait at least …
=> Expire sessions

app/controllers/application_controller.rb, spec/features/feature_flags/static_guidance_only_feature_flag_spec.rb
The privacy notice page doesn't show when 'static guidance only' feature flag is enabled.
Show all static guidance, not just one particular route.
=> Show all static pages when the 'static guidance only' feature flag is on

app/views/pages/guidance.html.erb, spec/features/feature_flags/static_guidance_only_feature_flag_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/features/view_pages_spec.rb
This makes it easier to change if we need to.
=> Use the service name as a translation wherever possible

app/services/fake_data_service.rb
Since #24 Recipients will not be seen by MNOs until the user who created them is approved.
So we need the ability to specify the user when generating fake data.
Add `created_by_user_id:` keyword arg to `FakeDataService.generate!`
From the console:
`FakeDataService.generate!(recipients: 5, created_by_user_id: ... )
Recipient.last(5).pluck(:created_by_user_id)`
The 5 created_by_user_id's should be exactly the value you gave.
=> allow generated fake recipients to have a created_by_user_id

Dockerfile, Makefile, app/controllers/monitoring_controller.rb, app/services/healthcheck_service.rb, config/application.rb, config/routes.rb, spec/controllers/monitoring_controller_spec.rb
It will be very helpful to be able to see which version is running on which environment ([Trello card](https://trello.com/c/GO9yEnZz/188-add-a-healthcheckjson-endpoint-that-includes-the-git-sha))
Bake git commit / branch into the Docker container as env vars
Add healthcheck.json endpoint which reports them alongside overall status and status of backing services
Check out the endpoint on dev: 
To test locally, provide `GIT_COMMIT_SHA` and `GIT_BRANCH` as env vars to the rails server (for instance `GIT_COMMIT_SHA=abc123 GIT_BRANCH=my-branch bundle exec rails s`) and then hit /healthcheck.json
=> Add healthcheck.json endpoint to report health, backing service health, and git commit/branch info

config/initializers/secure_cookies.rb, lib/middleware/secure_cookies.rb
Our pentest has flagged that the cookies are not marked as secure.
See https://makandracards.com/makandra/53693-rails-flagging-all-cookies-as-secure-only-to-pass-a-security-audit
Add middleware to mark all cookies as secure
=> mark all cookies as secure

config/initializers/canonical_rails.rb, config/initializers/content_security_policy.rb
We don't have a Content Security Policy header. We should - the pen testers reported this as an issue.
Add a suitable CSP
Point this online checker at dev: https://csp-evaluator.withgoogle.com/
BEFORE:
AFTER:
(note that the Rails DSL doesn't yet support the `require-trusted-types-for` flag. Not a biggie.)
=> Add content security policy

Makefile, README.md
Making different docker images for dev, staging and prod can be useful when you want to deploy different versions - but not when you want to promote a particular image between environments. You don't get the comfort of knowing that it's the _exact same_ image.
Add a `make (target env) promote FROM=(source env)` task, and update the README.
This task pulls the (source env) image from dockerhub, tags it for the target-env, and then calls `make (target env) push deploy` as normal
Try deploying a new dev image (`make dev build push deploy`), then promoting it to staging with `make staging promote FROM=dev`
If you then hit compare the dev and staging healthcheck endpoints (https://get-help-with-tech-dev.london.cloudapps.digital/healthcheck.json and …
=> add promote Makefile task

app/controllers/mno/recipients_controller.rb, app/models/recipient.rb, config/initializers/content_security_policy.rb, spec/controllers/allocation_request_forms_controller_spec.rb, spec/controllers/mno/recipients_controller_spec.rb, spec/features/mno/recipients_spec.rb, spec/features/session_behaviour_spec.rb, spec/features/submitting_an_allocation_request_form_spec.rb, spec/features/submitting_an_application_form_spec.rb, spec/rails_helper.rb, spec/support/capybara_helper.rb, spec/support/controller_helper.rb, spec/support/sign_in_as.rb
The pentest identified that a malicious user could modify the `recipient_ids` parameter in a bulk_update and modify the status of recipients for other MNOs
Fix the loophole that allowed users to do that.
Add tests for this scenario
From the root directory in a shell, `rspec spec/controllers/mno/recipients_controller_spec.rb --format doc`
You should see output similar to this:
```
Mno::RecipientsController
PUT /bulk_update
with recipient_ids from the same MNO as the user
updates all the recipients
redirects_to recipients index
with some recipient_ids from another MNO
updates the recipients from the same MNO as the user
does not update the recipient from the other MNO
redirects_to recipients index
when the given status is not valid
does not update the statusses
responds with …
```
=> Fix ability to modify bulk_update params & update recipients from other MNOs

app/concerns/exportable_as_csv.rb, spec/models/recipient_spec.rb
The pentest found it was possible to inject content into an exported CSV file via starting a user-inputted field with a =,+,-, or @ - the [CSV Injection vulnerability](https://owasp.org/www-community/attacks/CSV_Injection)
Fix the issue by prepending a single '.' to any field in an exported CSV that starts with one of those characters
1. Sign in as an approved user
2. Submit a 'Tell us about an eligible person' form for a mobile network to which you have a login, and make the account holder name or device phone number something like `'=(1 + 2)'`
3. Sign in as the mobile network user, and download the CSV file
4. Open the CSV file in the spreadsheet program of your choice (Google spreadsheets, Open Office, Libre Office, Numbers, Excel)
5. Make sure that the field which had started with an …
=> fix CSV code injection vulnerability

app/controllers/allocation_request_forms_controller.rb, app/controllers/application_forms_controller.rb, app/models/user.rb, config/routes.rb, spec/controllers/allocation_request_forms_controller_spec.rb, spec/controllers/application_forms_controller_spec.rb, spec/factories/allocation_requests.rb
The pentest found that if a user could guess the ID of another users' form submission, they could see the success page for it, which exposed the submitting users' email address (details in the [Trello card](https://trello.com/c/HROXHQ6u/205-username-email-enumeration-issue) )
Fix the issue by including created_by_user_id criteria in the success page query
Tidy up "TODO" issue with correct parameter names
Add specs
1. Sign-in as a regular user
2. Submit one of each kind of form. Copy the URL of the success page (e.g. `/allocation_request_forms/2/success`)
3. Sign-in as a different user
4. Enter the URL of the previous user's success page into your browser's address bar
5. Before, you would be able to see that users' email address. Now, you should only see a 404
=> fix for pentest issue - user can view success pages for submissions from other users

Gemfile, Gemfile.lock, app/models/get_information_about_schools.rb, app/models/local_authorities_in_england_register.rb, app/models/local_authority.rb, app/models/responsible_body.rb, app/models/trust.rb, app/services/import_responsible_bodies_service.rb, db/migrate/20200630142716_create_responsible_bodies.rb, db/schema.rb, lib/tasks/import_responsible_bodies.rake, spec/models/get_information_about_schools_spec.rb, spec/models/local_authorities_in_england_register_spec.rb, spec/services/import_responsible_bodies_service_spec.rb, spec/spec_helper.rb
Responsible bodies (trusts and local authorities) will use the service.
- create an STI `ResponsibleBody` model, with `LocalAuthority` and `Trust` subclasses
- add a Rake task to fetch local authority data from the [Local authorities in England register](https://www.registers.service.gov.uk/registers/local-authority-eng)
- add a Rake task to fetch trusts from the [Get information about schools service](https://get-information-schools.service.gov.uk/)
=> Add responsible bodies

app/models/user.rb, config/locales/en.yml
~Depends on #130. Rebase after that one's merged.~ Ready for review.
For all other models apart from `User`, their bespoke error messages have been moved into `en.yml`.
Move `User` model error messages into `en.yml` for consistency.
=> Move user validation messages to i18n file

app/views/responsible_body/extra_mobile_data_requests/index.html.erb, app/views/responsible_body/extra_mobile_data_requests/new.html.erb, app/views/shared/_use_the_mobile_guide.html.erb
- Move error summary on mobile data request above title
- Move guidance link from right column to be inline
- Hide guidance on requests index once a request is made
- Add a missing page title
- Remove an inline style to fix a CSP warning
=> Small UI fixes

app/views/guide_to_collecting_mobile_information/privacy.html.erb, app/views/responsible_body/extra_mobile_data_requests/new.html.erb
- Indicate PAYG can be under 18
- Highlight that the privacy statement should be read aloud
=> Content tweaks following research

.gitignore, Dockerfile, app/views/errors/too_many_requests.html.erb, config/initializers/rack_throttle.rb, lib/tasks/release.rake, public/429.html
As the rate-limiting is done in Rack middleware, it does not have access to the regular Rails rendering pipeline - so when the rate limit is hit the default behaviour is to just return the string 'Too many requests' as `text/plain` content. 
User testing showed that when this limit was hit, the raw nature of the error was jarring and confusing. The user did not know what to do and said they would contact support. A consistently-branded error message would help reassure the user that they just needed to wait a few seconds and try again.
* add a rake task to pre-render a govuk-styled 'Too many requests' error page into the `public/` folder
* call the rake task as part of the Docker build
* add `Rack::Throttle` config to read that file on startup, pass the contents to the middleware as …
=> Make the Too Many Requests error be a statically-pre-rendered page

app/services/create_user_service.rb, lib/tasks/create_user.rake, spec/services/create_user_service_spec.rb
We're getting support requests from responsible bodies to authorise access for additional people. Currently these are being done via the Rails console 😬 .
Add a rake task as a stepping stone to adding this functionality to the support interface.
It's more convenient that running the commands on the Rails console.
=> Add a rake task for creating new responsible body users

app/views/responsible_body/extra_mobile_data_requests/new.html.erb, config/locales/en.yml
As in the [Trello Card](https://trello.com/c/JISmia3v/248-review-mobile-phone-number-hint-error-message-wording), the wording around entering a mobile phone number could be better.
Apply updates from content designer 
Before:
After:
=> updated mobile phone number hint and error message

config/settings.yml
[Trello card](https://trello.com/c/XiwnxBea/327-increase-default-rate-limit-to-4-per-ip-per-second-for-all-gets)
Update the default number of requests per second permitted to 4 for all cases.  Currently token related endpoints are set to 1 request per second.
Update `config/settings.yml` to change the default values.
=> Updated default settings to 4 requests per second

Makefile
See [Trello card 333](https://trello.com/c/EKp7m63i/333-support-cf-cli-v7-as-well-as-v6) - Tony was not able to do a release as he has installed CF V7, which has just recently been made Generally Available.
Add a few lines to the `Makefile` which conditionally add the required 'v3-' prefix to some commands if the user is running CF V6. 
Please check that you are able to run `make dev ssh` and `make dev deploy`. 
You *don't* need to see the deploy right through to the end, if it's going to fail it will fail within a few seconds with:
```
'(something)-apply-manifest' is not a registered command. See 'cf help -a'
make: *** [deploy] Error 1
```
As long as you see a line starting with `Applying manifest`, you can CTRL+C it to quit, and that counts as a success.
Please confirm with a comment, …
=> 333 support cf cli v7 as well as v6

Makefile
See [Trello card 338](https://trello.com/c/q52ePQep/338-we-are-not-seeing-valid-user-agent-strings-in-logit) - while investigating issues with sign-in tokens, we found that all user-agent fields in Logit were empty. Turns out the default set up for the  cdn-route  service (which is how you get custom domains to work in Gov.UK PaaS) is to only forward the Host header to your app: https://docs.cloud.service.gov.uk/deploying_services/use_a_custom_domain/#forwarding-headers
Add a Makefile task to tell the cdn-route service to forward all headers.
The change is already made on prod, this is more just a record of what I did, so that it can be done again in future if needed
=> add Makefile task to setup the cdn-route to forward all headers

app/controllers/sign_in_tokens_controller.rb, app/services/session_service.rb, app/views/sign_in_tokens/you_are_signed_in.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/sign_in_tokens_controller_spec.rb, spec/factories/users.rb, spec/features/session_behaviour_spec.rb, spec/features/sign_in_token_behaviour_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/support/capybara_helper.rb
Some responsible bodies appear to have link checkers that follow email links. This causes a problem for the single-use magic links that we use to authenticate the users of our service, because:
1. The link checker follows the link, thus invalidating the token
2. When the user tries to follow the magic link for real, they're told that their token is not recognised and they need a new magic link.
3. Rinse and repeat.
Part of the problem comes from having a destructive operation (token invalidation) happen on a GET.
Change the sign-in flow so that:
- The magic link takes users to an interstitial page:
- At this point, the user is signed-in but the token is still valid (as discussed on Slack)
- As soon as the user clicks 'Continue', their token is invalidated. We are assuming that link …
=> Interstitial for magic links

app/views/sign_in_tokens/you_are_signed_in.html.erb, config/routes.rb
Follow-on from #149.
Change 'destroy token' route to be a DELETE, so the routes are more RESTful.
=> Change 'destroy token' route to be a DELETE

spec/controllers/sign_in_tokens_controller_spec.rb
#152 changed the method of the destroy token action to `:delete` - but not the controller spec.
Make the controller spec use :delete too
=> make controller spec use delete method too

Makefile, etc/logstash-filter.conf
see [Trello card 267](https://trello.com/c/vOQREk0V/267-make-the-logit-stack-more-comprehensible)
Update the Logstash filter to copy the `router.response_time` field to `router_response_time_sec` and convert it to a float. This is now present in the '*-*' index pattern.
Add a makefile task to setup the logit log-shipping
Have a look at the [GHWT Prod Dashboard in Logit](https://kibana.logit.io/app/kibana#/dashboard/8ba14770-c27b-11ea-831c-410f90b17e14)
We also have staging shipping logs to the same stack - you can filter on `cf.app` to choose which environment, or  use the saved query "Prod-only, no static assets" (click the disk icon next to the query box)
screenshot:
=> add router_response_time_sec to Logstash filter & Makefile task to setup Logit

Gemfile, Gemfile.lock, app/controllers/responsible_body/extra_mobile_data_requests_controller.rb, app/services/notify_extra_mobile_data_account_holder_service.rb, config/routes.rb, config/settings.yml, config/settings/test.yml, spec/controllers/responsible_body/extra_mobile_data_requests_controller_spec.rb, spec/factories/extra_mobile_data_requests.rb, spec/features/mobile_privacy_notice_spec.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb, spec/rails_helper.rb, spec/services/notify_extra_mobile_data_account_holder_service_spec.rb, spec/support/data/notify_success_body.json, spec/support/notify_helper.rb
[Trello card](https://trello.com/c/nNKhfK4c/305-text-message-for-all-mno-extra-mobile-data-requests)
Addition of sending an sms message to an account holder on creation of a extra mobile data request via GOV.UK Notify service.  One of two messages can be sent, depending on whether the chosen mno is participating in the data scheme or not.
Happy path only. Currently not persisting the response Id from Notify and no implementation of a background process to verify success or failure of delivery.
=> Added notifying extra mobile data account holder by sms

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/layouts/single_page.html.erb, app/views/pages/accessibility.md, config/locales/en.yml, config/routes.rb
The service needs an accessibility statement.
- add a static markdown-powered accessibility statement
- link to it from the footer
Adding static guidance using Markdown is nice...
=> Add a static Markdown page for the accessibility statement

lib/v_cap_services_config.rb, spec/lib/v_cap_services_config_spec.rb
Maybe because Rubocop insisted I rename them to these names? The issue was not detected in tests because the VCapServicesConfig class only gets instantiated if `ENV['VCAP_SERVICES']` is present (i.e. on Gov.uk PaaS)
Restore the missing files
=> Somehow these files didn't get added to #343

Gemfile.lock
Running `bundler` on the main branch yields changes in `Gemfile.lock` – I'm guessing there was a mismatch between `Gemfile` and `Gemfile.lock` in #165.
* Re-align Gemfile.lock with Gemfile
=> Re-align Gemfile.lock with Gemfile

app/views/pages/index.html.erb
It's not just children's devices
=> Remove "children's" from heading

app/webpacker/styles/_styled-content.scss, lib/action_view/template/handlers/markdown.rb, lib/govuk/markdown_renderer.rb, spec/lib/action_view/template/handlers/markdown_spec.rb, spec/lib/govuk/markdown_renderer_spec.rb
This service contains a lot of guidance, and has a few content designers who are (or will be) working on it.
Some of the pages are already authored using Markdown, e.g. the devices guidance. However, the current approach is limited by inability to use Rails partials (e.g. for shared snippets) or do any kind of Ruby interpolation (e.g. to avoid hard-coding URLs all over the place).
1. Allow using ERB interpolation within Markdown documents. For example, this becomes possible now:
```markdown
<%= render partial: 'shared/bt_wifi_eligibility' %>
...
```
2. Reduce the need for custom CSS by introducing a custom Markdown renderer that spits out GOV.UK-flavoured HTML. This means that the produced HTML is compatible with the GOV.UK Design System and uses its styles by default.
There are still a …
=> Markdown rendering improvements

.github/workflows/build-push-and-deploy-container.yml, Makefile, app/services/healthcheck_service.rb, spec/controllers/monitoring_controller_spec.rb
The healthcheck endpoint allows us to see what Git SHA was used to build the app, but not the actual image id of the Docker container. Adding this allows us to diagnose any issues more quickly by isolating exactly which version is where.
In the Makefile, extend the `deploy` task to add an extra post-push step for setting the DOCKER_IMAGE_ID as an env var. We must do this _after_ a successful push, not before.
In the github action, install `cf-cli` from a binary distribution rather than apt-get - cuts down execution time by about 45s
Add docker -> image_id to the info element in the `/healthcheck.json` endpoint
`make dev deploy` - then hit `/healthcheck.json`
=> 215 add docker image id to the healthcheck endpoint

app/services/fake_data_service.rb, spec/services/fake_data_service_spec.rb
The fake data service can be useful during development, in order to have some extra mobile data requests locally. However it was broken by some past data migrations.
- fix the `FakeDataService` by removing obsolete attributes from it
- add a spec to prevent future regressions
=> Fix the fake data service

app/views/support/service_performance/_mobile_data_requests.html.erb, spec/features/support/viewing_service_performance_spec.rb
#156 introduced the service performance dashboard. Some issues with it only became apparent when it was used with live data.
- include cancelled MNO requests in the stats
- show MNO requests in "requested" as "new"
More tweaks that will follow in subsequent PRs.
=> Service performance tweaks part i

app/views/layouts/_nav.html.erb
If the nicely-styled 500 error page throws an error, Rails detects this and renders a plain-text 500 fallback message. In this case, it was due to `SessionService.is_signed_in?` checking `session[:user_id]`, but code in that `if...` block assuming that means that `@user` is present. For the vast majority of cases that will be true, but in this particular case it is not, and the nav on the error page throws an error.
Add an explicit test for @user to the `is_signed_in?` clause in the nav
see steps to reproduce in the [Trello card](https://trello.com/c/5RxQPFRH/335-users-seeing-unstyled-500-page-when-an-error-occurs) - you might also want to set `config.consider_all_requests_local = false` so that the error page shows locally.
=> Fix unstyled 500 error when the current user is deleted

app/controllers/application_controller.rb, app/controllers/sign_in_tokens_controller.rb, spec/features/session_behaviour_spec.rb
When we're testing the system, it's quite common for us to sign in as one person (say, a responsible body user), do something (like submit a request), then sign in as someone else (say, an MNO user, to see that the request has come through). Since #144 this hasn't worked - the new session is ignored (see [Trello card](https://trello.com/c/FipwUPrE/371-signing-in-as-a-new-user-when-already-signed-in-doesnt-sign-you-in) )
Restore this behaviour
=> [371] Allow signing in as a different user when already signed in

.github/workflows/build-push-and-deploy-container.yml
[Trello Card](https://trello.com/c/B8gTg0RU/369-update-the-automatic-govuk-push-to-run-off-the-main-branch)
Change the GitHub automated workflow so that the `main` branch is used for deployment to GOV.UK PaaS.
As `main` is protected, we can use the `push` trigger on the `main` branch instead of the `pull_request` trigger.
This will then act on the `main` branch.
I have a simple test repo that I used to check the behaviour: [Test repo](https://github.com/tonyheadford/actions-test)
=> Updated github deployment workflow to run on pushes to main branch

app/controllers/support/responsible_bodies_controller.rb, app/views/layouts/_nav.html.erb, app/views/support/responsible_bodies/index.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/bt_wifi_vouchers.rb, spec/features/support/viewing_onboarded_responsible_bodies.rb, spec/page_objects/support/responsible_bodies_page.rb
It's useful to see a list of responsible bodies in the support area of the service, so that:
- DfE ops users can see engagement stats around both pilots
- There is a jump-off points for further operations on the responsible bodies (e.g. managing users)
- Add a list of responsible bodies in the support area, only accessible to DfE staff
- Display some basic engagement stats per responsible body
Is the table layout appropriate?
* pros: can be copied directly into Excel for further manipulation
* cons: not very compact or scannable
Does the microcopy make sense?
(I intend to add the extra mobile data requests later when the data model has been improved for reporting.)
=> Responsible bodies in support

spec/controllers/responsible_body/mobile/bulk_requests_controller_spec.rb, spec/controllers/responsible_body/mobile/manual_requests_controller_spec.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb, spec/models/extra_mobile_data_request_spec.rb, spec/rails_helper.rb, spec/services/extra_data_request_spreadsheet_importer_spec.rb, spec/services/extra_mobile_data_request_account_holder_notification_spec.rb, spec/support/sidekiq.rb
Some of the current specs change the ActiveJob queue adapter before and after the spec. This makes the specs noisier than they need to be.
Introduce suite-wide defaults about which ActiveJob queue adapter to use:
- feature specs use the real inline adapter by default
- all other specs use the test adapter by default
This can be overridden by setting `sidekiq: true|false` in the spec.
This change allows to remove some repeated setup/teardowns in some specs.
This was inspired by a similar setup in the [Apply for Teacher Training repo](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training).
=> Run feature specs with sidekiq

app/views/layouts/application.html.erb, public/429.html
The header toggle is broken and nothing happens when you click on the "Menu" link/mobile hamburger button. It's likely never worked in this repo because it was [already broken (and now fixed)](https://github.com/DFE-Digital/govuk-rails-boilerplate/pull/286) in the [`govuk-boiler-template`](https://github.com/DFE-Digital/govuk-rails-boilerplate) repository.
The issue related to a CSS class rename in v3.0.0 of govuk-frontend:
https://github.com/alphagov/govuk-frontend/blob/master/CHANGELOG.md#update-css-class-names
Bring the class name in the layout in line with `govuk-frontend` v3.0.0 and later.
=> Fix the header toggle

app/controllers/responsible_body/mobile/manual_requests_controller.rb, app/helpers/application_helper.rb, app/models/extra_mobile_data_request.rb, app/presenters/extra_mobile_data_request_presenter.rb, app/services/extra_data_request_spreadsheet_importer.rb, app/views/responsible_body/mobile/manual_requests/confirm.html.erb, config/locales/en.yml, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/responsible_body/submitting_a_spreadsheet_request_spec.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb, spec/models/extra_mobile_data_request_spec.rb
[Trello card](https://trello.com/c/Tx9RTGFF/330-add-unavailable-status)
This change adds `unavailable` to the status enum for the `ExtraMobileDataRequest` model. The status should be set to `unavailable` if the mobile network is not yet participating.  This status should be displayed in the list of requests for the user.
There is also altered messaging during submission to indicate that the network is not yet in the service and that the request has been saved rather than submitted.
=> 330 add unavailable status

config/locales/en.yml
I18n translation error when creating a new `ExtraMobileDataRequest` manually.
Fix a typo in the name of the string in the `en.yml` file
Add a manual extra mobile data request with a MNO that is not currently in the service. On complete the success message should be `Your request has been saved`
=> Fix typo in i18n name

app/services/fake_data_service.rb
The fake data service generates extra mobile data requests in queried status that don't have a `problem` set.
Fix the data inconsistency.
=> Fake data service should generate consistent data for queried requests

app/controllers/application_controller.rb, app/controllers/sign_in_tokens_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, spec/features/session_behaviour_spec.rb, spec/features/sign_in_token_behaviour_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb
[Trello card](https://trello.com/c/ylCz6nEW/360-dont-show-nav-links-on-the-interstitial-youre-signed-in-and-check-your-email-pages) - hide nav menus from users on the 'You're signed in' and 'Check your email' pages during sign-in process
Make rendering of nav (and mobile menu link) conditional based on `controller_name` and `action_name` to prevent rendering where not required.
Nav menu should not be visible on the 'You're signed in' and 'Check your email' pages but visible as expected elsewhere.
=> Hide nav menu on you're signed in and check your email

app/models/school_device_allocation.rb, config/locales/en.yml, db/migrate/20200812155338_add_school_device_allocation.rb, db/schema.rb, spec/factories/school_device_allocations.rb, spec/models/school_device_allocation_spec.rb
We need to add a model for allocations of devices to schools, so that we can build a provisional API endpoint for computacenter to hit when an order is placed
=> add school device allocations model, migration and factory

app/views/computacenter/home/show.html.erb, config/locales/en.yml
First part of [Trello card 408](https://trello.com/c/fsNGK22g/408-spin-up-first-api-end-point-to-share) - spin up a first draft API endpoint for Computacenter to notify us of orders placed
* Add `/computacenter` namespaced `base_` and `home_` controllers
* Add distinguishing of computacenter users based on their email address
* Add basic placeholder computacenter homepage
* Restrict computacenter-namespaced controllers to computacenter users
=> 408 add computacenter namespace

package.json, yarn.lock
We got a security alert from Github Dependabot, telling us to bump `serialize-javascript` to 3.1.0 or later, due to [CVE-2020-7660](https://github.com/advisories/GHSA-hxcc-f52p-wc94)
Bump `serialize-javascript` to 3.1.0 or later
=> bump serialize-javascript to >=3.1.0 as per security advisory

app/models/local_authorities_in_england_register.rb, db/migrate/20200813205300_remove_closed_local_authorities.rb, db/schema.rb, spec/models/local_authorities_in_england_register_spec.rb
The local authority importer was previously importing local authorities that were no longer existed. This led to two records called 'Buckinghamshire'.
* Change the importer code to skip any LA register records that have an `end-date`
* Add a migration which deletes all the closed LAs from the data
=> Store only active local authorities

app/models/get_information_about_schools.rb, spec/models/get_information_about_schools_spec.rb, spec/services/import_responsible_bodies_service_spec.rb
As of August 2020, the Get Information About Schools (GIAS) service includes both open and closed trusts in its data export. We don't need the closed ones in our DB.
Similar to #228.
* Only import open trusts from GIAS
We don't appear to have the closed trusts on production, which suggests that the closed ones were added some time after we did our initial import 🤷 . Consequently, this PR doesn't include any clean-up migration.
=> Trusts: only import open ones from GIAS

app/controllers/responsible_body/mobile/extra_data_requests_controller.rb, app/models/extra_mobile_data_request.rb, app/models/responsible_body.rb, db/migrate/20200809151453_backfill_responsible_body_on_extra_mobile_data_requests.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/models/extra_mobile_data_request_spec.rb, spec/support/capybara_helper.rb
Currently, when a responsible body user creates an extra mobile data request (MNO request), other users within the RB don't see the request. However we think of MNO requests as being on RB level, and they should really work like that.
On the data level, `extra_mobile_data_requests.responsible_body_id` isn't being set when a request is created, making it harder to query total MNO requests per RB.
- populate `extra_mobile_data_requests.responsible_body_id` when an MNO request is created, taking the RB from the user who made the request
- on the RB side, change MNO request visibility from user- to RB-level
- add a database migration which back-fills `extra_mobile_data_requests.responsible_body_id` for existing MNO requests
After this change is rolled out, it will be possible to make …
=> Move MNO requests to be at responsible body-level, not at user level

README.md, docs/computacenter_api.md
See [Trello card 408](https://trello.com/c/fsNGK22g/408-spin-up-first-api-end-point-to-share). We need to provide some documentation for the CC API, that we can point the Computacenter developers at. 
Add some API docs. Rather than send all this information in an email, it seemed sensible to write it up as a markdown file on our repo.
Read [the docs](https://github.com/DFE-Digital/get-help-with-tech/blob/6fa0898aff84c0688a941a7e8eb6f1ed4312b684/docs/computacenter_api.md)!
=> 408 add cc api docs

README.md, docs/computacenter_api.md
The API docs in #235 didn't have any explanation of why a CapUsage update batch may fail
Add one
=> 408 add failure reasons to api docs

.gitignore
There was no `log/` directory in the repo, which meant running `rake db:setup` on a fresh install failed with an error `Errno::ENOENT: No such file or directory @ rb_sysopen - log/mail.log`.
Make the .gitignore directive more specific and add an empty `log/placeholder.txt` file, to make the repo contain a `log/` dir
=> fix "No such file or directory" error on first setup

lib/tasks/import_schools.rake
We have a set of existing tasks in the `import` namespace for importing responsible bodies, each of which calls a method on the `ImportResponsibleBodiesService`.
We have a `ImportSchoolsService` with a method to import_schools - but no rake wrapper
Add a simple one-liner rake task for importing schools, so that it's consistent
```bash
$ rake --tasks import
rake bt_wifi:import_voucher_allocations[csv_url]  # Import BT Wifi voucher allocations
rake bt_wifi:import_vouchers[csv_url]             # Import BT Wifi vouchers
rake import:dfe_as_a_responsible_body             # Import DfE as a responsible body for direct connectivity distribution
rake import:local_authorities_in_england          # Import local authorities in England
rake import:responsible_bodies                    # Populate the …
```
=> add rake task for importing schools, for consistency

app/models/school_data_file.rb, spec/models/school_data_file_spec.rb, spec/support/csv_file_helper.rb
Trusts were not getting associated with schools during the school import process, only LAs were being associated.
Checks whether the school is a single or multi-academy trust establishment and then uses that trust name specified in the GIAS file as the responsible body.
Any schools already imported will need to be cleared down first. As there are references to school records you'll need to execute something like this `School.connection.execute('TRUNCATE schools RESTART IDENTITY CASCADE')` from the Rails console. **NOTE: this will remove any device allocations!!** - hopefully this isn't live yet 😬 
Once the schools have been cleared down, run `ImportSchoolsService.new.import_schools` from the Rails console to bring in the latest school data from GIAS.
=> Correctly associate schools with trusts when present during import

app/services/responsible_body_exporter.rb, app/services/school_data_exporter.rb, lib/tasks/export_data.rake, spec/services/responsible_body_exporter_spec.rb, spec/services/school_data_exporter_spec.rb
[Trello card](https://trello.com/c/Hz5xNtqi/407-provide-bulk-schools-upload-file-initial-to-cc) - Provide CSV export files for Responsible Bodies and Schools, primarily for CC.
Add exporters to create CSV files.
Data can be exported via console or rake task `bundle exec rails export:responsible_bodies` and `bundle exec rails export:schools` will generate csv files in the current directory.
=> 407 provide bulk schools upload file initial to cc

app/controllers/responsible_body/internet/bt_wifi_vouchers_controller.rb, app/controllers/responsible_body/internet/mobile/bulk_requests_controller.rb, app/controllers/responsible_body/internet/mobile/extra_data_requests_controller.rb, app/controllers/responsible_body/internet/mobile/manual_requests_controller.rb, app/views/layouts/_nav.html.erb, app/views/responsible_body/home/_bt_wifi_offer.html.erb, app/views/responsible_body/home/_extra_mobile_data_offer.html.erb, app/views/responsible_body/internet/bt_wifi_vouchers/download.html.erb, app/views/responsible_body/internet/mobile/bulk_requests/new.html.erb, app/views/responsible_body/internet/mobile/bulk_requests/summary.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/new.html.erb, app/views/responsible_body/internet/mobile/manual_requests/confirm.html.erb, app/views/responsible_body/internet/mobile/manual_requests/new.html.erb, config/routes.rb, spec/controllers/responsible_body/internet/bt_wifi_vouchers_controller_spec.rb, spec/controllers/responsible_body/internet/mobile/bulk_requests_controller_spec.rb, spec/controllers/responsible_body/internet/mobile/extra_data_requests_controller_spec.rb, spec/controllers/responsible_body/internet/mobile/manual_requests_controller_spec.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/responsible_body/submitting_a_spreadsheet_request_spec.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb, spec/features/session_behaviour_spec.rb
As a precursor to implementing the "Get devices" workflow for responsible bodies, we need to move the existing "Get the internet" workflows under a namespace that can sit alongside it (see [Trello card 455](https://trello.com/c/iWLnm5mC/455-move-bt-mno-pilot-screens-into-url-namespace))
Move all controllers, views and specs relating to the "Get the internet" journey for responsible bodies under a new internet namespace
i.e. `responsible_body/(mobile_|bt_)` -> `responsible_body/internet/(mobile_|bt_)`
Update all references to a `responsible_body_(.*)_path` correspondingly
=> move existing RB user mobile/BT interface code under a new internet namespace

db/migrate/20200818165121_add_responsible_body_in_devices_pilot.rb, db/schema.rb
We need to be able to roll out the devices pilot incrementally.  
Add a boolean flag (default `false`) to the responsible_bodies table to indicate whether they are in the devices pilot or not
`bundle exec rails db:migrate`
=> add in_devices_pilot flag to RB

db/migrate/20200818170851_add_responsible_body_in_connectivity_pilot.rb, db/schema.rb
Add a boolean flag (default `false`) to the responsible_bodies table to indicate whether they are in the connectivity pilot or not
`bundle exec rails db:migrate`
=> add in_connectivity_pilot flag to RB

app/services/event_notifications_service.rb, spec/services/event_notifications_service_spec.rb
The Slack messages upon sign-in could be a bit clearer, namely:
- the timestamp is in UTC (so looks like it's off-by-one hour at first glance when it's BST)
- event name is camel-cased
- remove the timestamp altogether (it's possible to see when the event happened based on the Slack timestamp)
- print the event class with spaces and removing the module part
```ruby
[1] pry(main)> Computacenter::CapTypeConverter.name.demodulize.underscore.humanize
=> "Cap type converter"
```
=> Clearer slack notifications

app/controllers/responsible_body/devices/base_controller.rb
We are adding new screens to support the devices work.
Add a new base controller that ensures access is only given to responsible bodies which are in the devices pilot.
No specs for the base controller, I'm assuming that the subclasses will be tested.
=> ResponsibleBody::Devices::BaseController which only allows RBs in device pilot

app/models/school.rb, app/models/school_data_file.rb, app/services/import_schools_service.rb, db/migrate/20200819082723_add_phase_and_establishment_type_to_schools.rb, db/schema.rb, spec/models/school_data_file_spec.rb, spec/services/import_schools_service_spec.rb, spec/support/csv_file_helper.rb
[Trello card](https://trello.com/c/mB4EMZMP/445-pull-in-phase-of-school-from-gias-primary-secondary) Add phase of education and establishment type to `School` model from GIAS data.
Add migration for `:phase` and `:establishment_type`.
Create `enum`s for both attributes and map during import
`:phase` values are `primary`, `secondary`, `all_through`, `sixteen_plus` and `phase_not_applicable`
`:establishment_type` values are `academy`, `free`, `local_authority`, `special` and `other_type`
School importer will now update the attributes of matching school records, not just create new ones.  It cannot yet determine if imported schools have closed, been removed or have changed URN.
Prevented `Nursery` and `City technical college` types from being imported.
There are additional filters in this so …
=> Added phase and type to schools

app/models/computacenter/cap_type_converter.rb, spec/models/computacenter/cap_type_converter_spec.rb
`Computacenter::CapTypeConverter` was only returning first character of matched device types. This was causing `500 internal server error` responses on their API
Fix it to return the full match
Add a spec to explicitly test this behaviour
=> Fix issue with generating Computacenter cap types in outgoing API

db/migrate/20200819123617_change_responsible_body_in_connectivity_pilot_default_to_false.rb, db/schema.rb
PR #247 introduced a flag to ResponsibleBody called `in_connectivity_pilot`, and set the default to `true`.
In discussion with @benilovj it later became clear that this is not accurate, and we should instead default it to false, only setting it to true for those RBs who have at least one user.
* Add a migration to do the above
=> 478 set RB.in_connectivity_pilot default to false

app/controllers/computacenter/api/base_controller.rb
Computacenter are experiencing an issue on staging that we can't replicate based on the information available to us. 
When they POST a cap usage update to the computacenter API, they get a `500 Internal Server Error` - based on the [info in Sentry](https://sentry.io/organizations/dfe-get-help-with-tech/issues/1846682979/?project=5320558&query=is%3Aunresolved#exception) it looks like the server is trying to interpret it as a HTML request and failing when looking for a HTML template to render. This happens even though Sentry says they're supplying a correct `"Content-Type: application/xml"` header.
Add some explicit verbose logging so that we can see in the logs exactly what they're supplying in terms of headers & body.
=> add verbose explicit logging of computacenter api requests

app/models/local_authorities_in_england_register.rb, app/services/import_responsible_bodies_service.rb, db/migrate/20200819215502_remove_local_authorities_that_dont_maintain_schools.rb, db/schema.rb, spec/models/local_authorities_in_england_register_spec.rb, spec/services/import_responsible_bodies_service_spec.rb
We have a large number of local authorities that don't actually maintain schools, as evidenced by no schools being associated with them within Get Information About Schools. These LAs are also not involved in the connectivity pilots or have any users:
```ruby
[1] pry(main)> LocalAuthority.where(organisation_type: %w[combined_authority non_metropolitan_district strategic_regional_authority], in_connectivity_pilot: true).count
=> 0
[2] pry(main)> LocalAuthority.where(organisation_type: %w[combined_authority non_metropolitan_district strategic_regional_authority]).select {|la| la.users.count > 0 }
=> []
```
- remove those LAs from the database
- don't import them from the LAs in England register in the first place
=> Remove local authorities that don't maintain schools

app/models/computacenter/api/cap_usage_update_batch.rb, spec/controllers/computacenter/api/cap_usage_controller_spec.rb
The Cap update is failing when there's only one cap update being sent. The investigation showed that this stems from differences in how the XML to Ruby conversion works, depending on whether it's one or multiple records in the payload.
- don't use stubs in the CapUsageController specs because they were obscuring the failure
- fix the bug and and add spec coverage for that case
=> Fix cap update endpoint when only one record present

app/views/responsible_body/home/show.html.erb, config/locales/en.yml, spec/features/signing_in_as_different_types_of_user_spec.rb
We changed the responsible body homepage copy but forgot to change the heading.
Align heading with content, add responsible body name.
Before:
After:
=> Bring the responsible body homepage heading in line with the content

app/models/responsible_body.rb, app/models/school.rb, app/views/responsible_body/devices/schools/show.html.erb, spec/features/responsible_body/devices_setup_spec.rb, spec/models/responsible_body_spec.rb
Responsible body users potentially need to process a large number of schools quickly. We want to save them having to click and search.
Add a link to the school details page to go to the next school alphabetically.
=> Next school link

app/models/preorder_information.rb, db/migrate/20200823233442_disallow_null_preorder_information_status.rb, db/schema.rb, spec/models/school_spec.rb
There's no good reason for `PreorderInformation#status` to ever be null. It would introduce lots of conditional complexity if we allowed this to creep into the data.
- infer the status when `PreorderInformation` is initialised
- validate `status` in the AR model
- disallow `status` to be null in the DB
We don't need a data migration because these records haven't been created anywhere yet.
=> Set initial status on PreorderInformation and disallow it to be null

app/models/preorder_information.rb, db/migrate/20200823134357_add_contact_reference_to_preorder_information.rb, db/schema.rb
When device ordering has been devolved to the school, the responsible body is asked to nominate a contact for that school. We need to store this information somewhere (on the preorder information record).
Added DB migration and ActiveRecord associations.
=> Add school contact to preorder information

config/webpacker.yml
Without this change, running specs printed out loads of warnings:
The resolved_paths option has been deprecated. Use additional_paths instead.
=> Update deprecated option in webpacker config

docs/computacenter_api.md
In testing with Computacenter, they found that their requests were being processed as `text/html`, despite supplying the `Content-type: application/xml` header. Adding an `Accept: application/xml` header as well, fixed it
Add an instruction to include the `Accept: application/xml` header too
=> Add Accept header to computacenter_api.md

app/components/summary_list_component.html.erb, app/components/summary_list_component.rb, spec/components/summary_list_component_spec.rb
When some-but-not-all rows of a summary list had `change_path` given, the Change links would appear outside the extent of the divider lines, like this:
Fix the issue above, so that it now looks like this:
=> fix styling issue when only some rows of a summary list had Change links

app/components/school_details_summary_list_component.rb, app/components/school_preorder_status_tag_component.rb, app/controllers/responsible_body/devices/schools_controller.rb, app/controllers/responsible_body/devices/who_to_contact_controller.rb, app/form_objects/responsible_body/devices/who_to_contact_form.rb, app/models/preorder_information.rb, app/models/school.rb, app/views/responsible_body/devices/who_to_contact/_who_to_contact_form.html.erb, app/views/responsible_body/devices/who_to_contact/new.html.erb, config/locales/en.yml, config/routes.rb, spec/components/school_details_summary_list_component_spec.rb, spec/factories/school_contacts.rb, spec/factories/schools.rb, spec/features/responsible_body/devices_setup_spec.rb
Responsible bodies want to nominate school contacts for managing device orders. These contacts can either be someone they already work with or a headteacher who might be able to identify the right person within the school.
Add a form for capturing the school contact.
=> Choosing contacts for schools

app/controllers/pages_controller.rb, app/views/pages/request_a_change.html.erb, config/locales/en.yml, config/routes.rb
When we've not built the self-serve functionality for stuff that users want to change, we will point them to support instead.
Add a static page that can be linked to from the UI, when a user clicks a change link.
=> Add a page which points users to our support inbox

app/components/school_details_summary_list_component.rb, app/controllers/responsible_body/devices/change_who_will_order_controller.rb, app/helpers/view_helper.rb, app/models/preorder_information.rb, app/views/responsible_body/devices/change_who_will_order/edit.html.erb, config/locales/en.yml, config/routes.rb, db/schema.rb, spec/components/school_details_summary_list_component_spec.rb, spec/features/responsible_body/devices_setup_spec.rb, spec/features/responsible_body/providing_a_schools_preorder_information_spec.rb
[Trello card](https://trello.com/c/tzMqOCU1/510-allow-responsible-bodies-to-change-who-will-order-for-a-school) Enable a responsible body to change who orders devices after the initial choice (mostly centralised/school) has been made
Additional forms and choices, journey has deviated from prototype following discussion with @benilovj
=> 510 allow responsible bodies to change who will order for a school

app/components/school_details_summary_list_component.rb, spec/components/school_details_summary_list_component_spec.rb
The `<br>` was being eaten and so the contact details ran into each other as one long string.
Escape the user-generated content but mark the `<br>` tags as safe.
Before:
After:
=> Fix display of school contacts

app/controllers/sign_in_tokens_controller.rb, app/controllers/support/base_controller.rb, app/models/user.rb, app/views/layouts/_nav.html.erb, config/routes.rb, db/migrate/20200825080212_add_user_support_and_computacenter_flags.rb, db/schema.rb, lib/constraints/require_dfe_user_constraint.rb, spec/factories/users.rb, spec/models/user_spec.rb
We've been inferring whether users could access the support & computacenter interfaces based on their email domain.
This has worked OK, but it makes testing difficult - and especially for the external pentesting company, who haven't been able to test the support or computacenter interfaces yet as their email domain is their company.
Replace the `is_dfe?` and `is_computacenter?` methods on `User` with explicit boolean flags
*NOTE* I also changed `is_dfe?` to `is_support?` - as it's more reflective of reality, and better matches the application file structure.
=> replace is_dfe?/is_computacenter? methods with explicit user flags

app/components/school_details_summary_list_component.rb, app/controllers/responsible_body/devices/chromebook_information_controller.rb, app/models/preorder_information.rb, db/schema.rb, spec/features/responsible_body/providing_a_schools_preorder_information_spec.rb
[Trello card 528](https://trello.com/c/UwDJhUpJ/528-bug-school-preorder-info-status-should-update-to-ready-when-they-dont-need-chromebooks) In the RB interface, clicking 'No, they will not need chromebooks' + 'save' on a school should update its status to READY.
It was not doing that, because of Rails' auto-created methods & type inference meaning that `will_need_chromebooks?` was returning `true` when the field had a value of 'no' (because it's not `nil`, therefore '(attr_name)?' is true)
[Trello card 527](https://trello.com/c/IuWBUbSX/527-dont-show-chromebook-details-if-chromebooks-wont-be-ordered) - it was still showing the domain & recovery email fields when `will_need_chromebooks` was `no` 
Fix both bugs, and add explicit tests for this behaviour
=> [527, 528] fix bugs with preorder information around schools needing chromebooks

app/helpers/view_helper.rb, app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/devices/who_will_order/edit.html.erb, app/views/responsible_body/devices/who_will_order/show.html.erb, app/views/responsible_body/home/show.html.erb, config/locales/en.yml, spec/features/responsible_body/devices_setup_spec.rb
Match prototype. Remove mentions of outbreaks and lockdowns. Say "place orders" not "manage orders", favour "place order" over "ordering device".
=> Update content to latest version

app/components/school_preorder_status_tag_component.rb
The ready status badge is the wrong colour.
Adjust the badge class.
=> Correct the colour of the 'ready' status tag

app/views/layouts/_nav.html.erb, app/views/layouts/_service_link.html.erb, app/views/layouts/application.html.erb, app/webpacker/styles/overrides.scss
- Remove "Tell us who needs more data" link, it's not part of the design
- Fix cursor mouse over styles on Sign out button
- When signed in as a responsible body, make the service name link to the signed in home page
=> Tweaks to the primary navigation

app/views/computacenter/api_tokens/index.html.erb, app/views/layouts/_nav.html.erb
- Fix indenting of form, make it 2/3rds width
- Remove unnecessary wrapper from table
- Remove brackets from "No tokens yet" message
- Remove full stop from title
=> Layout fixes for Computacenter API screen

app/components/school_details_summary_list_component.html.erb, app/helpers/view_helper.rb, app/models/responsible_body.rb, app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/devices/who_will_order/edit.html.erb, spec/features/responsible_body/devices_setup_spec.rb, spec/page_objects/responsible_body/school_page.rb
Update design to match https://increasing-access-history.herokuapp.com/devolving-for-trusts/
For trusts we don't want to recommend any option – it will depend on how the trust is set up whether they devolve or manage centrally.
=> Show different guidance and options for multi-academy trusts

app/views/responsible_body/devices/who_to_contact/_nominate_another_contact.html.erb, app/views/responsible_body/devices/who_to_contact/_who_to_contact_form.html.erb, spec/features/responsible_body/devices_setup_spec.rb
[Trello card 523](https://trello.com/c/DdvhyD6D/523-handle-schools-without-a-headteacher-contact) - The app crashes on the school details page when trying to provide contacts for a school without a headteacher contact
When the headteacher contact is nil:
* show a hidden field `who_to_contact`, value: 'someone_else' instead of the radio buttons.
* show the 'nominate someone else' subform
Screenshot:
=> fix crash when no headteacher present

app/controllers/responsible_body/users_controller.rb, app/mailers/invite_responsible_body_user_mailer.rb, app/views/responsible_body/users/index.html.erb, config/settings.yml, db/schema.rb, spec/features/responsible_body/manage_users_spec.rb
[Trello card](https://trello.com/c/vZGLZ3do/452-manage-rb-users-invite-an-rb-user) Take adding RB users out from behind the FeatureFlag curtain and add the invite email to Notify.
Enabling the invite responsible body user functionality. Sending an invite email to the new user.
Invite button enabled and Invite a new user form/functionality accessible without enabling the `:rbs_can_manage_users` feature flag.
=> 452 manage rb users invite an rb user

app/models/allocation_data_file.rb, app/models/csv_data_file.rb, app/models/get_information_about_schools.rb, app/models/school_data_file.rb, app/services/import_device_allocations_service.rb, app/services/remote_file.rb, lib/tasks/import_device_allocations.rake, spec/factories/school_device_allocations.rb, spec/factories/schools.rb, spec/models/allocation_data_file_spec.rb, spec/services/import_device_allocations_service_spec.rb, spec/support/csv_file_helper.rb
[Trello card](https://trello.com/c/geNW8AEG/392-import-devices-allocations-into-the-service-from-an-online-csv)
Import school device allocations into the system from a private CSV file.  These are the `std_device` type allocations for years 3-10.  CSV data file is private so will be accessed via a URL held in `ALLOCATIONS_FILE_URL` environment variable.
Add importer for allocations data, refactor downloading of data files into separate `RemoteFile` module.
Importer will add or update existing device allocations on School records.
The importer creates a `WARN` level entry in the Rails logs for any schools specified in the allocations file that we do not currently have in the DB.
Assumes that Schools have already been imported and that you have the allocations csv data file.
Run …
=> Add device allocation importer

app/views/pages/accessibility.md, lib/govuk/markdown_renderer.rb, spec/lib/govuk/markdown_renderer_spec.rb
Make the statement more generic as it now applies to more than just the internet access section.
Includes a fix to prevent stray spaces appearing at the end of generated links.
`some link.` was becoming `some link .`
=> Update accessibility statement

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home_page.html.erb, config/routes.rb, spec/features/cookie_preferences_behaviour_spec.rb
First iteration of the Home page. 
The home page will be used to link up all the guidance from the various parts of the programme.
**Header** - We need to clearly define from "Guidance" link is for and be consistent with the links in the header across the programme.
**Footer** - In this PR we updated the support content in the footer. This will need to be updated across the service. Two policies have been removed from the home page footer as the home page does not request personal information. There is another piece of work going on to try bring the difference privacy policies together so that there is a single privacy policy across the programme. The same goes for accessibility link but this will be done at a later stage.
Visit https://ghwt-review-pr-272.herokuapp.com/
=> New home page for "Get help with Tech"

app/views/sign_in_tokens/email_not_recognised.html.erb, public/429.html
We recently update the support copy in the footer as part of PR #272. This PR updates any content in the service were we might have mentioned the support contact email, Monday-Friday and within 5 working days.
=> Update support content to match footer support details

app/models/computacenter/responsible_body_urns.rb, app/models/responsible_body.rb, app/services/import_computacenter_references_service.rb, app/services/import_local_authority_gias_ids_service.rb, app/services/import_responsible_bodies_service.rb, app/services/import_responsible_body_users_from_computacenter_csv_service.rb, config/local_authority_data.csv, db/migrate/20200826143548_add_rb_computacenter_reference.rb, db/migrate/20200826211506_add_gias_id_and_gias_group_uid_to_rbs.rb, db/schema.rb, lib/tasks/import_contacts.rake, lib/tasks/import_responsible_bodies.rake, lib/tasks/import_schools.rake, spec/factories/responsible_bodies.rb, spec/models/responsible_body_spec.rb, spec/services/import_computacenter_references_service_spec.rb, spec/services/import_local_authority_gias_ids_service_spec.rb, spec/services/import_responsible_bodies_service_spec.rb, spec/services/import_responsible_body_users_from_computacenter_csv_file_service_spec.rb, spec/services/import_responsible_body_users_from_computacenter_csv_service_spec.rb
We have some spreadsheets from Computacenter with the contacts they hold for each of their accounts from wave 1.
We need to import those contacts into the DB as users, but also make sure they're linked to the right Responsible Bodies.
The task is made more complex by the fact that the source data we have, uses Computacenter references & GIAS UIDs to link things together.
* Add db fields to store GIAS Id, GIAS Group UID, and computacenter_reference
* Add a new `ImportComputacenterReferencesService` to import Computacenter's 'SoldTo' (RB account ID) and `ShipTo` (school as shipping location) references to our schools & responsible_bodies
* Add a new `ImportLocalAuthorityGiasIdsService` to import GIAS Ids for Local Authorities from @benilovj 's manually-constructed CSV file
* Add  a new …
=> [490] Import wave 1 RB contacts from Computacenter CSV file

app/controllers/sign_in_tokens_controller.rb, spec/features/signing_in_as_different_types_of_user_spec.rb
For support users who want to test functionality as an RB should
be redirected to the RB homepage upon login, otherwise there's no way for them
to navigate to that page. If they want to access support functionality,
they can use the nav links.
If a support user is also something else (e.g. an RB or a CC user too), redirect to that other thing when signing the user in.
=> Redirect support users, who are also RB users, to RB homepage

app/views/responsible_body/devices/schools/index.html.erb
Problems can be more than just schools missing.
Schools might be showing that shouldn't.
Schools might have combined.
=> Tweak help text on schools list

app/controllers/responsible_body/devices/who_will_order_controller.rb, app/models/who_will_order_event.rb, app/services/feature_flag.rb, config/locales/en.yml
Send notifications to Slack when each local authority or trust decides that schools or themselves should manage orders.
Examples:
```
CASTLE SCHOOL EDUCATION TRUST has devolved ordering to schools
CASTLE SCHOOL EDUCATION TRUST will manage orders centrally
```
=> Send slack events when RBs make choices about who orders

app/views/responsible_body/devices/schools/index.html.erb, config/locales/en.yml, spec/features/responsible_body/devices_setup_spec.rb
The status for a school can be quite long and we don't want it to wrap.
Add a fixed width on the status column, as in the prototype.
Is the CSS defined in the right place?
Is the name right?
=> Explicitly style the status column on the schools table

app/components/nav_component.rb, app/views/layouts/application.html.erb
- Devices are now part of the service, we should show the guidance link and the sign in link.
- Add a home link to help signed in RBs find their way back to the signed in home page if they're lost (eg in guidance)
=> Use a common header across service

app/controllers/computacenter/api_tokens_controller.rb, app/controllers/responsible_body/devices/change_who_will_order_controller.rb, app/controllers/responsible_body/devices/who_will_order_controller.rb, spec/features/responsible_body/devices_setup_spec.rb
* replace `flash[:notice]` with `flash[:success]` (which is actually rendered in the layout)
* add a test that this message is shown 
screenshot:
=> Make sure success message is show when choosing who will order at RB level

config/locales/en.yml, config/routes.rb
#361 inadvertently broke the 'devices distribution' devices guidance subpage. This was because the page filename and its metadata didn't match, meaning users saw 500 errors when following the link.
Re-align the devices guidance subpage name with its metadata.
=> Make the 'devices distribution and ownership' page available again

.github/workflows/build.yml
PR #333 introduced Jest into the project as the test runner for JS tests. It is currently not being called as part of the GitHub Actions build.
- add a GH Actions step to run jest
=> Run jest as part of the GitHub Actions build

app/helpers/view_helper.rb, app/views/devices_guidance/device_allocations.md, app/views/devices_guidance/device_specification.md, app/views/devices_guidance/how_to_order.html.erb, app/views/responsible_body/devices/home/show.html.erb
Some absolute links were introduced during recent devices guidance changes. This makes it harder to test those pages because the links aren't relative and take you off to the production site.
- replace absolute links with relative links
- use Rails path helpers where possible (so that if content moves, the path doesn't break)
- fix some indentation issues that have crept in
- extract a view helper for generating links to devices guidance subpages
=> Devices guidance tweaks

app/components/user_summary_list_component.html.erb, app/components/user_summary_list_component.rb, app/controllers/school/base_controller.rb, app/controllers/school/home_controller.rb, app/controllers/school/users_controller.rb, app/controllers/sign_in_tokens_controller.rb, app/models/school.rb, app/models/user.rb, app/views/responsible_body/users/_user.html.erb, app/views/school/home/show.html.erb, app/views/school/users/_user.html.erb, app/views/school/users/index.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200831200056_user_can_belong_to_school.rb, db/schema.rb, spec/components/user_summary_list_component_spec.rb, spec/factories/users.rb, spec/features/school/manage_users_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/models/user_spec.rb, spec/page_objects/school/users_page.rb
School users should be able to:
- sign into the service
- see a list of other users (who can place orders) for their school
- Bring in the plumbing needed to allow school users to sign in (routes, updates to the user model, being able to associate users with schools)
- Introduce a school base controller
- Start building out the school home page
- Add a read-only school users page
Additionally:
- Extract a user summary list component that is shared between the RB and school areas of the service
- Fix the heading hierarchy on the RB users page
Best reviewed commit by commit.
=> School users can sign in and see who can order devices

app/views/responsible_body/home/privacy_notice.html.erb
Bulleted list on privacy notice was unstyled because I had forgotten the necessary CSS classes.
* Fix markup
=> Fix bullet styling on privacy notice

app/controllers/school/users_controller.rb, app/helpers/view_helper.rb, app/mailers/invite_school_user_mailer.rb, app/models/user.rb, app/views/school/users/_form.html.erb, app/views/school/users/index.html.erb, app/views/school/users/new.html.erb, config/locales/en.yml, config/routes.rb, config/settings.yml, db/migrate/20200901142852_add_orders_devices_to_users.rb, db/schema.rb, spec/controllers/school/users_controller_spec.rb, spec/factories/users.rb, spec/features/school/manage_users_spec.rb, spec/models/user_spec.rb
[Trello card](https://trello.com/c/sw0yu93Z/574-schools-manage-who-can-order-devices-add-users)
Enable schools to invite users
Journey to invite a new school user, choose whether the user can order devices and send the `School nominate contact` email to the new user.
`bundle exec rake db:migrate`
Users added via the form should be sent an email via notify
Enforces limit of 3 users per school that can order devices
=> 574 schools manage who can order devices add users

db/migrate/20200902105909_set_default_for_orders_devices_on_existing_school_users.rb, db/schema.rb
Adding `:orders_devices` without a default has meant that existing school users do not have a `:orders_devices` value and this prevents the users from signing in.
Migration that will set `:orders_devices` to `false` for existing school users that do not have a value already set.
Run the migration. Existing school users should now have `:orders_devices` set to `false` and are able to sign in.
=> Fix issue with orders_devices being null for existing school users

app/form_objects/responsible_body/devices/who_to_contact_form.rb, spec/controllers/responsible_body/devices/who_to_contact_controller_spec.rb, spec/factories/schools.rb
The 'who to contact' form was crashing if submitted empty.
[Sentry error](https://sentry.io/organizations/dfe-get-help-with-tech/issues/1858158448/?project=5320558&query=is%3Aunresolved)
- fix the crash by dealing with missing data in a more robust way
=> Fix crash when 'who to contact' form submitted empty

app/components/school/school_details_summary_list_component.rb, app/controllers/responsible_body/devices/schools_controller.rb, app/controllers/school/chromebooks_controller.rb, app/form_objects/chromebook_information_form.rb, app/views/responsible_body/devices/chromebook_information/edit.html.erb, app/views/responsible_body/devices/schools/show.html.erb, app/views/school/chromebooks/edit.html.erb, app/views/shared/_chromebook_information_form.html.erb, app/views/shared/_chromebook_information_intro.html.erb, config/locales/en.yml, config/routes.rb, spec/components/school/school_details_summary_list_component_spec.rb, spec/features/school/change_chromebook_information_spec.rb
In #367 we introduced a view-only UI for schools to check their details. This PR allows a school to change their Chromebook information. (Trello card [560](https://trello.com/c/l8h6foA9/560-check-your-school-details-change-whether-school-needs-to-order-chromebooks))
* Add UI for schools to edit their chromebook information
* Move the `responsible_body/devices/chromebook_information_form` object back to the top level, as it is now used in two contexts
Screenshots:
=> 560 Change whether school needs to order chromebooks

app/models/computacenter/outgoing_api/cap_update_request.rb, app/views/computacenter/outgoing_api/base/cap_update_request.xml.builder, db/migrate/20200902135234_add_allocation_cap.rb, db/schema.rb, spec/factories/school_device_allocations.rb, spec/models/computacenter/outgoing_api/cap_update_request_spec.rb
See [Trello card 475](https://trello.com/c/am1Ir4o7/475-separate-the-concept-of-device-allocations-and-cc-caps) - we need to separate the concept of allocations (the maximum amount of devices a school will be able to order in the event of a lockdown) from caps (how many they can order right now, and thus by inference, whether there is a lockdown affecting them at the moment)
* add a `cap` field to `SchoolDeviceAllocation`
* make the `NotifyComputacenterOfCapUpdateJob` send the `cap` field instead of `allocation`
=> [475] add a separate field for allocation cap

app/models/computacenter/ship_to_data_file.rb, app/models/computacenter/sold_to_data_file.rb, app/models/csv_data_file_importer.rb, spec/models/computacenter/ship_to_data_file_spec.rb, spec/models/computacenter/sold_to_data_file_spec.rb, spec/models/csv_data_file_importer_spec.rb
Relates to two Trello cards: [589-import-computacenter-shipto-identifiers-into-the-service](https://trello.com/c/Tz9AU70M/589-import-computacenter-shipto-identifiers-into-the-service) and [543-refactor-the-importer-services-based-on-tonys-new-abstractions](https://trello.com/c/oggGswho/543-refactor-the-importer-services-based-on-tonys-new-abstractions).
While working out a one-off import of computacenter IDs, it became clear that the simplest way to do it was actually to add a generic `CsvDataFileImporter` class that uses @tonyheadford's `CsvDataFile` abstraction. This makes the implementation code trivial, and also gives us a way to refactor most of the existing `(XYZ)Importer` classes to remove the boilerplate code and simplify them.
* add a `CsvDataFileImporter` class & spec
* add 2 …
=> add CsvDataFileImporter, and 2 implementations for computacenter imports

app/components/responsible_body/school_details_summary_list_component.rb, app/views/responsible_body/devices/who_to_contact/_who_to_contact_form.html.erb, app/views/responsible_body/devices/who_to_contact/new.html.erb, spec/components/responsible_body/school_details_summary_list_component_spec.rb
The school details page for responsible bodies has been redesigned.
- move the school details table below the 'who to contact' form
- reorder table rows
- add a link which shows how to request devices in specific circumstances
=> School details design changes

app/components/breadcrumb_component.html.erb, app/components/breadcrumb_component.rb, app/helpers/view_helper.rb, app/views/responsible_body/devices/home/show.html.erb, spec/components/breadcrumb_component_spec.rb
Breadcrumb markup is repetitive and hard to parse at a glance. We want to abstract it away to clean up view templates.
- Introduce a breadcrumb component and a view helper
- Apply it in the first view
Usage example:
```ruby
<%- content_for :before_content do %>
<% breadcrumb([
{ t('page_titles.responsible_body_home') => responsible_body_home_path },
title,
]) %>
<% end %>
```
Is the syntactic sugar sensible?
=> Breadcrumb component

app/controllers/school/welcome_wizard_controller.rb, app/models/school_welcome_wizard.rb, app/views/school/welcome_wizard/allocation.html.erb, config/locales/en.yml, config/routes.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
[Trello card](https://trello.com/c/QKBDBoXD/566-schools-wizard-allocations)
Add school allocation info page to wizard
Add school device allocation as the page following the privacy notice in the welcome wizard
As a new school user, when signing in you should be taken through the wizard. You should see the device allocation for the school on the page after the privacy notice.
=> [566] Add school device allocation wizard page

app/controllers/school/welcome_wizard_controller.rb, app/models/school_welcome_wizard.rb, app/views/school/welcome_wizard/order_your_own.html.erb, config/locales/en.yml, config/routes.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
[Trello card](https://trello.com/c/6i0L6qGQ/567-schools-wizard-order-your-own-page)
Add information about ordering devices page to wizard
Add 'order your own' page to wizard following the allocation page
=> [567] Add order your own page to wizard

app/controllers/support/devices/responsible_bodies_controller.rb, app/views/support/devices/responsible_bodies/show.html.erb, spec/features/support/devices/viewing_responsible_body_info_spec.rb, spec/page_objects/support/responsible_body_page.rb
Support users need to be able to see the allocations, caps and devices ordered for schools, when queries come in.
Add a schools table to the RB devices pilot support page.
=> Show schools in support

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, db/migrate/20200903101449_create_versions.rb, db/migrate/20200903101450_add_object_changes_to_versions.rb, db/schema.rb, spec/controllers/support/users_controller_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
- https://trello.com/c/Gi48TlNC/240-put-in-an-auditing-gem-like-audited-or-papertrail-for-the-users-table
- We want to be able to audit changes to the user model so diffs/deltas can be generated
- The `paper_trail` gem should meet our requirements and seems better maintained compared to `audited`
- Below is example of a version from the gem which should be good enough for us to generate deltas
```
pry(main)> u.versions.last
=> #<PaperTrail::Version:0x00007f9516c6e500
id: 9,
item_type: "User",
item_id: 1,
event: "update",
whodunnit: "User:1234",
object:
"---\nid: 1\n...YAML REPRESENTATION OF OBJECT",
created_at: Thu, 03 Sep 2020 10:35:37 UTC +00:00,
object_changes: "---\nupdated_at:\n- 2020-09-03 10:29:05.107686000 Z\n- 2020-09-03 10:35:37.829641000 Z\nis_support:\n- false\n- true\n">
``` …
=> [240] Add and setup paper trail gem

app/controllers/sign_in_tokens_controller.rb, app/models/user.rb, app/views/sign_in_tokens/click_to_sign_in.html.erb, config/locales/en.yml, spec/controllers/sign_in_tokens_controller_spec.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/session_behaviour_spec.rb, spec/features/sign_in_token_behaviour_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/models/user_spec.rb, spec/support/capybara_helper.rb, spec/support/controller_helper.rb
[Trello card 548](https://trello.com/c/aHrdHDJv/548-can-we-rejig-the-sign-in-process-to-fix-the-multiple-event-notifications-issue) (also many slack threads & Zendesk tickets) - For some users, we've been seeing multiple almost-simultaneous "A user from X has just signed in" notifications in Slack when they sign-in. We think this is due to their email software scanning links in emails for malicious behaviour before the user even sees them.
Rework the sign-in process slightly so that when the user clicks the magic link:
* it renders hidden fields for `token` & `identifier` in to the `DELETE` form 
* it does not actually sign the user in (and send the notification & clear the token, etc) until they click the button to sign in
Adjust the school wizard entry point slightly to fit
Adjust the …
=> rejig the sign-in behaviour to only actually sign the user in once they click the button

app/controllers/school/devices_controller.rb, app/models/school.rb, app/views/school/devices/cannot_order.html.erb, app/views/school/home/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/school/order_devices_spec.rb, spec/models/school_spec.rb
[Trello card](https://trello.com/c/hN0YNKbM/561-schools-order-devices-outside-lockdown)
* add school homepage section 'Order devices'
* add `can_order_devices?` method to school, with correct(?) logic
* add content page for "You cannot order devices yet" - always shown, until we've developed [the other branch of the user journey](https://trello.com/c/6SoAV292/562-schools-order-devices-in-lockdown)
* move existing `request_devices` method from `school/home_controller` to new `school/devices_controller`
=> add user journey for ordering devices outside of lockdown

app/views/support/devices/responsible_bodies/show.html.erb, spec/features/support/devices/viewing_responsible_body_info_spec.rb
It's useful to quickly find a school by its URN
Show the URN in the devices RB schools list in the support area.
=> Support: show the school URN in the responsible body schools list

app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/devices/home/tell_us.html.erb, app/views/responsible_body/devices/schools/index.html.erb, app/views/responsible_body/internet/bt_wifi_vouchers/download.html.erb, app/views/responsible_body/internet/home/show.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/responsible_body/users/index.html.erb, app/views/shared/devices/request_devices.html.erb
The breadcrumb should be clearer if the first page is marked as "Home", which is a familiar term and matches the heading.
“Get help with technology” was quoted as looking like a “A public guidance link”
It's also what GOV.UK does, for example: https://www.gov.uk/browse/births-deaths-marriages/register-offices
=> Use "Home" as the first breadcrumb item

app/controllers/school/welcome_wizard_controller.rb, app/models/school_welcome_wizard.rb, app/views/school/welcome_wizard/will_you_order.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200904141052_add_orders_devices_to_school_welcome_wizard.rb, db/schema.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
[Trello card](https://trello.com/c/37TI1qBj/568-schools-wizard-user-will-place-orders)
Page that requires the user to choose whether they will place orders for devices. This is only shown to the first user for a school (when there is only 1 user for the school).
The selected choice is saved both on the user and in the wizard model (as `:orders_devices`)
Whether the user is determined to be the 'first' user or not is recorded so the journey could be replayed / backed up at a later stage.
User must be the only user for that school to see the page
=> 568 schools wizard user will place orders

app/models/school_welcome_wizard.rb, app/views/school/welcome_wizard/techsource_account.html.erb, config/locales/en.yml, config/routes.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
[Trello card](https://trello.com/c/uhZJNNc8/607-schools-wizard-techsource-account)
Add page explaining that the user will receive an invite to techsource to the wizard. This page follows choosing 'Yes' the user will order devices.
=> 607 schools wizard techsource account

config/application.rb, spec/controllers/responsible_body/internet/bt_wifi_vouchers_controller_spec.rb, spec/features/sign_in_token_behaviour_spec.rb
All timestamps were showing as one hour earlier right now, as they were being displayed in UTC, not BST.
Set the default timezone to London, since all the users of this service are in England.
=> Show timestamps correctly in the service

app/models/school_contact.rb, app/models/user.rb, app/validators/email_address_validator.rb, config/locales/en.yml, spec/models/school_contact_spec.rb, spec/models/user_spec.rb, spec/validators/email_address_validator_spec.rb
Current email validation in the service is ... no validation at all. We've already seen cases where users have mistyped the address when inviting new users or setting school contacts, which breaks the journey for the user and creates extra ops and support effort for the service team.
This change introduces user email address validation. The approach uses a regular expression that matches what's used within GOV.UK Notify, thereby reducing the risk that we allow email addresses that we can't subsequently deliver emails to because they're rejected by Notify.
This code is lifted from [DfE's 'Apply for teacher training' service](https://github.com/DFE-Digital/apply-for-teacher-training), which is a mature, battle-tested service with a large development team that watches their errors very …
=> Introduce email validation

app/views/devices_guidance/support_and_maintenance.md
The link fragment doesn't quite match the id generated by the markdown converter, meaning the link doesn't work (at least in Chrome).
Fix the case of the link fragment.
=> Fix in-page links in support and maintenance devices guidance

app/controllers/school/welcome_wizard_controller.rb, app/models/school_welcome_wizard.rb, app/views/school/users/new.html.erb, app/views/school/welcome_wizard/will_other_order.html.erb, app/views/school/welcome_wizard/will_you_order.html.erb, app/views/shared/_school_user_form.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200907103146_add_invited_user_to_school_welcome_wizards.rb, db/schema.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
[Trello card](https://trello.com/c/EwtiVEL2/569-schools-wizard-user-wont-order-but-nominates-someone-else)
Gives the user the choice to add an additional user during the welcome wizard
Refactored school invite form to shared partial
User can add new school user via the wizard
School user must be the only (first) user for the school in the service
Selecting 'Yes' opens the invite user form
New user will be sent the School nominated contact email on creation
I've not implemented the "Back" link and I'm not sure how we'd handle this step at all if you'd already added a user and tried to go back - it would probably need to skip the page as the user would no longer be the only user for the school in the service - but additional content may be required.
The `id` of the new user is stored in the …
=> [569] Add additional user flow to wizard

app/controllers/school/welcome_wizard_controller.rb, app/models/school_welcome_wizard.rb, app/views/school/welcome_wizard/devices_you_can_order.html.erb, config/locales/en.yml, config/routes.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
School users, who are ordering devices for the first time, need to know what kind of devices they could potentially get.
Add a guidance page to the school wizard that covers the devices that can be ordered.
This PR will need rebasing after @tonyheadford merges in his work on the preceding page in the wizard.
=> Add 'devices you can order' page to school wizard

app/models/support/devices/service_performance.rb, spec/models/support/devices/service_performance_spec.rb
`needs_information` is always 0, as the actual status is `needs_info`
=> Use correct status for sums in dashboard

app/controllers/school/welcome_wizard_controller.rb, app/models/school_welcome_wizard.rb, app/views/school/welcome_wizard/chromebooks.html.erb, app/views/shared/_chromebook_information_form.html.erb, app/views/shared/_chromebook_information_intro.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/preorder_information.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
[Trello card](https://trello.com/c/5L2CpbJX/571-schools-wizard-chromebooks)
Ask if school needs Chromebooks
Adds page to wizard to ask if school needs Chromebooks
Assumes that if a school gets here that a `preorder_information`model has already been created - **I don't know if this is the case?**
Refactor of chromebook form object partials to conditionally add extra options and wording to cater for this view.
This page is only shown if `:will_need_chromebooks` is `nil` in the school's `preorder_information` model
=> [571] schools wizard chromebooks

app/controllers/school/welcome_wizard_controller.rb, app/models/school_welcome_wizard.rb, app/views/school/welcome_wizard/what_happens_next.html.erb, config/locales/en.yml, config/routes.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
**Depends on #404. rebase this once that PR is merged.**
After the school users have gone through the wizard, they need to know what else they can do on the service.
Add the final static page in the school wizard.
=> Add 'what happens next' page to school wizard

app/controllers/responsible_body/devices/change_who_will_order_controller.rb
A bug that Tom noticed during user testing.
Fix nesting on the flash message scope.
Before:
After:
=> Fix missing flash message when an RB changes who will order

app/models/computacenter/ledger.rb, app/models/computacenter/responsible_body_urns.rb, app/models/computacenter/user_change.rb, app/models/responsible_body.rb, app/models/user.rb, db/migrate/20200907114036_create_computacenter_user_changes.rb, db/schema.rb, spec/factories/users.rb, spec/models/computacenter/ledger_spec.rb, spec/models/responsible_body_spec.rb, spec/models/user_spec.rb
- https://trello.com/c/n9stv3jD/594-spike-can-we-generate-the-cc-user-changes-feed-using-papertrail
- Start point on figuring out how to generate data export for computacenter
- Add migration to form new table which will act as basis for future csv entries
- CSV generator which takes selected users and generates output csv
- Take some users and pass to csv generator
- `service = ComputacenterLedgerCsv.new(User.limit(3))`
- Generate the csv
- `service.to_csv`
- output csv should match agreed format
=> [594] CSV table

app/components/responsible_body/school_details_summary_list_component.rb, app/components/school/school_details_summary_list_component.rb, app/controllers/responsible_body/devices/schools_controller.rb, app/models/preorder_information.rb, app/views/responsible_body/devices/schools/show.html.erb, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/components/school/school_details_summary_list_component_spec.rb, spec/features/school/change_chromebook_information_spec.rb
[Trello card](https://trello.com/c/MTSFSrWS/622-cannot-add-chromebook-details-if-youve-said-i-dont-know)
[Trello card](https://trello.com/c/jZ0jqIW6/623-school-details-dont-show-chromebook-settings-if-youve-said-no-to-chromebooks)
Show chromebook details for RBs and Schools
Enable `Change` link on Chromebook details depending on whether the School or RB will be managing (managing entity sees the Change links)
Added 'Not yet known' as default text when `:will_need_chromebooks` hasn't been set
=> Chromebook details fix

app/controllers/computacenter/user_ledger_controller.rb, app/models/computacenter/ledger.rb, app/models/user.rb, app/views/computacenter/home/show.html.erb, config/routes.rb, spec/features/computacenter/download_user_changes_csv_spec.rb
[Trello card 631](https://trello.com/c/5xfhKBRT/631-add-ui-for-computacenter-to-generate-a-user-changes-csv) - first draft strawperson UI, no filtering, just a big green button. Refinements will come later.
* Add a big green `Download CSV` button that downloads the unfiltered user ledger as CSV
* move the `Computacenter::Ledger.headers` method to a public class scope - it's going to be the same for all instances, and this also allows it to be referenced in the test.
=> [631] add button for Computacenter to Download CSV of users

app/views/responsible_body/home/show.html.erb, app/views/responsible_body/users/index.html.erb, app/views/responsible_body/users/new.html.erb, config/locales/en.yml, spec/features/responsible_body/home_spec.rb
- Explicitly call out "add school contacts' in the Get devices section
- Change "Manage trust users" (trust users sound like people in schools) to "Manage trust administrators", so it sounds more central
- Add warnings about adding schools in the wrong place
=> Stop trusts from adding school users in wrong place

app/models/computacenter/ledger.rb, db/migrate/20200908094419_add_originals_to_computacenter_user_changes.rb, db/schema.rb, spec/models/computacenter/ledger_spec.rb
- https://trello.com/c/n9stv3jD/594-spike-can-we-generate-the-cc-user-changes-feed-using-papertrail
- Add extra columns to `computacenter_user_changes` as specified in the `v3` spreadsheet
- Add extra db columns to `computacenter_user_changes`
- CSV generator takes these extra columns into consideration
- Start service with users
- `service = Computacenter::Ledger.new(users: User.all)`
- Generate csv from service
- `service.to_csv`
- Should generate csv with extra columns
=> [594] Add extra cols to computacenter_user_changes

app/views/shared/_chromebook_information_form.html.erb
Specify that it must be the domain registered for G Suite for Education
=> Update Google domain label

app/components/responsible_body/school_details_summary_list_component.rb, app/views/responsible_body/devices/schools/show.html.erb, app/views/responsible_body/devices/who_to_contact/new.html.erb, spec/components/responsible_body/school_details_summary_list_component_spec.rb
Bring inline with design by:
- moving form questions to above the summary list
- fixing spacing
- making summary list full width
- making "Request devices" link consistent with other rows
=> Update responsible body school details page

app/models/school.rb, app/views/support/devices/responsible_bodies/show.html.erb, spec/factories/school_device_allocations.rb, spec/factories/schools.rb, spec/features/support/devices/viewing_responsible_body_info_spec.rb
The support interface needs to soon support the ability to manage allocations, caps and order counts for both devices and dongles. We start this process by displaying the current settings for these bits.
- display the device allocations/caps/order counts in one column
- display the 4G dongle allocations/caps/order counts as well
- set a column width on the 'Name and URN' column
=> Show 4G dongle allocations/caps/order counts in support

app/components/school_preorder_status_tag_component.rb, app/controllers/support/devices/responsible_bodies_controller.rb, app/controllers/support/devices/schools_controller.rb, app/models/preorder_information.rb, app/models/school.rb, app/models/school_contact.rb, app/views/support/devices/responsible_bodies/show.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200907224535_add_preorder_information_school_contacted_at.rb, db/schema.rb, spec/features/support/devices/inviting_schools_spec.rb, spec/models/preorder_information_spec.rb, spec/models/school_spec.rb
~**Includes #428, rebase once that PR is merged.**~ Done
We want to start bringing schools (who will be responsible for ordering devices) onto the service. We will initially do this via the support interface.
Add an 'invite' button for schools that are ready to be contacted. This button:
- adds the school contact as a user into the system
- emails them an invite
- updates the school's status
- only does something if it's possible to add the user (e.g. the user isn't already on the system for whatever reason)
Additionally, this PR updates the school statuses for the RBs so they're correct as the school users go through the welcome wizard.
=> Inviting schools onto the service via support

app/controllers/school/welcome_wizard_controller.rb, app/models/school_welcome_wizard.rb, app/views/school/welcome_wizard/allocation.html.erb, app/views/school/welcome_wizard/chromebooks.html.erb, app/views/school/welcome_wizard/devices_you_can_order.html.erb, app/views/school/welcome_wizard/order_your_own.html.erb, app/views/school/welcome_wizard/privacy.html.erb, app/views/school/welcome_wizard/techsource_account.html.erb, app/views/school/welcome_wizard/what_happens_next.html.erb, app/views/school/welcome_wizard/will_other_order.html.erb, app/views/school/welcome_wizard/will_you_order.html.erb, config/routes.rb, db/migrate/20200909080651_add_show_chromebooks_to_school_welcome_wizard.rb, db/schema.rb, spec/factories/school_welcome_wizards.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
[Trello card](https://trello.com/c/oB609ypc/629-allow-users-to-use-the-browsers-back-button-in-the-school-wizard)
Pass wizard step to update method to enable back button to work as expected
Invite additional user only available to "first" school user
Chromebooks page only shown to "first" school user
Will need a good check of the flows through the wizard and using the back button to repeat steps.  Check that the user journey still makes sense.
=> Enable moving backwards in wizard

app/views/layouts/application.html.erb
[Trello card 633](https://trello.com/c/PSJxsRIX/633-hide-the-service-content-from-google)
Add a `noindex` meta tag, as described on [Google webmasters question 93710](https://support.google.com/webmasters/answer/93710)
=> stop Google indexing content

app/models/computacenter/backfill_ledger.rb, spec/factories/users.rb, spec/models/computacenter/backfill_ledger_spec.rb
- https://trello.com/c/n9stv3jD/594-spike-can-we-generate-the-cc-user-changes-feed-using-papertrail
- Add service to backfill user changes table
- New service to backfill user changes table
- Should be idempotent so we can run multiple times to append to the table till we have a better mechanism in place
- We ignore users that have not read the privacy policy or can order devices 
- With some test users present in local database
- Call service with `Computacenter::BackfillLedger.new.call`
- Table should should ledger with new users dated in the past
=> [594] Add service to backfill user_changes

app/views/pages/internet_access.html.erb, config/locales/en.yml
Page title should be "Get internet access" rather than "Get help with technology"
=> Fix page title on Get internet access page

app/models/school_contact.rb, spec/models/school_spec.rb
This was incorrectly done in #429. There's a follow-up change to remove the techsource question from the school welcome wizard, but that's not in scope of this PR.
Change the default "orders_devices" setting for invited school users to 'true'.
=> Invited school contacts should be TechSource users by default

app/models/extra_mobile_data_request.rb, app/services/fake_data_service.rb, db/migrate/20200816154413_make_extra_mobile_data_requests_responsible_body_not_null.rb, db/schema.rb, spec/factories/extra_mobile_data_requests.rb, spec/services/fake_data_service_spec.rb
Had this branch knocking about for some time and wanted to get it in.
Enforce the existence of a responsible body on MNO requests at the DB level, for data consistency.
I've checked and there are no MNO requests without an RB on any of our environments, so no data migration is needed.
=> MNO requests should always have a responsible body

app/models/computacenter/backfill_ledger.rb, spec/models/computacenter/backfill_ledger_spec.rb
[Trello card 652](https://trello.com/c/owCzbO0A/652-make-computacenterbackfillledger-accept-a-users-param-so-that-we-can-backfill-one-set-of-users-at-a-time) - this will allow us to backfill the ledger one set of users at a time, avoiding a single big-bang rollout and testing as we go
* make the `Computacenter::BackfillLedger` optionally accept users as a parameter
=> make backfill_ledger accept users as a param

app/controllers/computacenter/user_ledger_controller.rb, app/models/computacenter/ledger.rb, spec/factories/user_changes.rb, spec/features/computacenter/download_user_changes_csv_spec.rb, spec/models/computacenter/ledger_spec.rb
[Trello card 644](https://trello.com/c/P0H2S7zf/644-update-csv-generator-to-take-feed-from-userchange-table) and (now archived) [645](https://trello.com/c/gYuHk1qK/645-change-the-computacenter-download-csv-ui-to-read-from-the-userchanges-table-al) - part of [larger ticket 594](https://trello.com/c/n9stv3jD/594-user-changes-feed-for-computacenter)
* make the `Computacenter::Ledger` class take its data from the `UserChanges` table rather than `Users`
* update the `Computacenter::UserLedgerController` to pass in `UserChanges`
* update the relevant specs to set up test data in the form of `UserChanges` rather than `Users`
* add factories for some anticipated `UserChanges` scenarios
=> make Computacenter::Ledger read from UserChanges rather than Users

app/models/school.rb, app/views/responsible_body/devices/schools/show.html.erb, app/views/responsible_body/devices/who_to_contact/new.html.erb, app/views/shared/_school_without_allocation.html.erb, spec/features/responsible_body/devices_setup_spec.rb, spec/models/school_spec.rb
Add guidance to match designs in https://increasing-access-history.herokuapp.com/schools-with-no-allocation/
=> Show no allocation guidance when 0 devices allocated

app/views/responsible_body/devices/schools/index.html.erb, spec/features/responsible_body/devices_setup_spec.rb
Display the school URN to RBs to avoid confusion around similar-sounding schools.
There are lots of St Joseph's schools.
Show school URN alongside the name.
Before:
After:
=> Display the school URN to RBs

.rubocop.yml, app/models/computacenter/user_change.rb, app/models/computacenter/user_change_generator.rb, app/models/user.rb, spec/factories/users.rb, spec/models/user_spec.rb
- https://trello.com/c/n9stv3jD/594-spike-can-we-generate-the-cc-user-changes-feed-using-papertrail
- This change updates the Computacenter::UserChange table as users are added/updated/deleted in our system to keep Computacenter in sync
- On creating, updating or destroy a user, write to Computacenter::UserChange table
- Only changes to certain fields will write to Computacenter::UserChange table
- User must pass a certain criteria otherwise does not write to Computacenter::UserChange table
- From Computacenter view a user is considered New if they have not seen the user before
- Association changes are attempted to be read to add to the Computercenter::UserChange table, if not found they will not be added
- If a user has been backfilled any changes should append to the ledger
- If a user …
=> [594] Callback to sync Computacenter::UserChange

app/models/computacenter/user_change.rb, app/services/feature_flag.rb, spec/models/user_spec.rb
- https://trello.com/c/n9stv3jD/594-user-changes-feed-for-computacenter
- Add feature flag to only append to user change table when enabled
- With feature off should never write to `Computacenter::UserChange`
- With feature on should write to `Computacenter::UserChange` when applicable
=> [594] Add feature flag for adding to user change

app/models/computacenter/backfill_ledger.rb, spec/models/computacenter/backfill_ledger_spec.rb
- https://trello.com/c/n9stv3jD/594-user-changes-feed-for-computacenter
- Backfilled records are not appearing at the bottom of the csv therefore Computacenter will not know to apply these changes
- When user is backfilled it takes the current time so when ordered in the ledger it appears at the bottom
- Backfill a user, `update_at_timestamp` should be the current time and not when the user was created
=> [594] Backfill now uses current time

app/models/computacenter/user_change_generator.rb, spec/models/user_spec.rb
- https://trello.com/c/n9stv3jD/594-user-changes-feed-for-computacenter
- Previously if a User was relevant to computer it would only be appended as New if they changed a monitored field too
- If a user is made Computacenter relevant they are immediately added as a new user to `Computacenter::ChangeUser`
- Find a user not relevant to Computacenter
- Update their `privacy_notice_seen_at` and `orders_devices` fields ONLY so they are now Computacenter relevant
- Should create `New` entry in `Computacenter::ChangeUser`
=> [594] Add ChangeUser if relevant to Computacenter

app/components/responsible_body/school_details_summary_list_component.rb, app/models/school.rb, db/migrate/20200913134728_add_school_order_state_to_schools.rb, db/schema.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb
**Depends on #458, rebase this PR after that one is merged.**
Schools and responsible bodies need to know when they can start ordering devices, and whether that's for specific circumstances or local coronavirus restrictions. This will be tracked on a per-school basis.
- Introduce an order state on the school's pre-order information.
- Update the responsible body's school details summary table to show appropriate guidance in the "Can place orders?" section.
It's awkward having the order state on the **pre**order information, but it feels like that's the right place for the information. It's worth considering whether we want to rename `PreorderInformation`, to reflect its increased scope, as a subsequent change.
Is the microcopy correct? cc @emmajhf
**Cannot order**
**Can order under local …
=> Introduce school order state

app/controllers/support/devices/schools_controller.rb, app/views/support/devices/responsible_bodies/show.html.erb, app/views/support/devices/schools/confirm_invitation.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/support/devices/schools_controller_spec.rb, spec/features/support/devices/managing_schools_spec.rb
Currently, when inviting a school, there's no way to see who you are inviting, in case you need to follow up with them for research.
- change the invite button to a link
- show an invitation confirmation page, which shows who will be invited
=> Support: show who will be invited from the school

app/components/responsible_body/school_details_summary_list_component.rb, app/components/support/school_details_summary_list_component.html.erb, app/components/support/school_details_summary_list_component.rb, app/views/support/devices/schools/show.html.erb, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/components/support/school_details_summary_list_component_spec.rb
~~**This PR builds upon #457, so merge that one first and rebase this one.**~~ ✅ 
Support agents need to see how far individual schools have gotten in the pre-order journey.
Display school details in support, but without any change links.
Provide a link to invite the school contact when that's appropriate.
Best reviewed commit-by-commit.
**When a school is ready to be invited**
**When the RB hasn't even made the decision to centralise or devolve orders**
=> Show school details in support

app/models/user.rb, spec/models/user_spec.rb
This service uses full names for users, as [per the GOV.UK Design System](https://design-system.service.gov.uk/patterns/names/). However downstream systems need this split into first and last names to work. We're working with imperfect data so the full name sometimes includes honorifics or is an email address.
- Strip out common honorifics when deriving a user's first and last name
- guess the first and last name from emails of the form `first.last@domain`
- guess the initial and last name from emails of the form `<initial>last@domain`
Not proud of this code, but it feels like the least worst solution to data mismatches between two systems.
=> Improve heuristics for splitting first and last name

Gemfile, Gemfile.lock, app/models/computacenter/outgoing_api/cap_update_request.rb, spec/models/computacenter/outgoing_api/cap_update_request_spec.rb
- https://trello.com/c/FBZnVdwk/502-handle-computacenter-returning-200-response-on-failed-capupdates
- For cap updates the computacenter response can return a 200 when there is an error
- To ensure there is no error we also parse the response body
- If there is an error it will be raised
- n/a
=> [502] Handle computacenter error on cap update

app/components/support/school_details_summary_list_component.rb, app/controllers/support/devices/order_status_controller.rb, app/form_objects/support/enable_orders_form.rb, app/models/application_record.rb, app/models/school_device_allocation.rb, app/views/support/devices/order_status/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/users.rb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb, spec/models/school_device_allocation_spec.rb, spec/page_objects/support/devices/school_details_page.rb
Trello card [672](https://trello.com/c/jcmxnwR1/672-support-users-can-set-the-order-state-cannot-order-can-order-specific-circumstances), as part of the larger ticket [664](https://trello.com/c/xUIUD6em/664-allow-disallow-ordering-and-set-caps-via-support)
Add just the initial user interface to allow support users to enable ordering of devices for schools.
This first version applies the updates from the form and redirects back to the school page - a subsequent PR will introduce the "Check and confirm" page.
Screenshots:
Change link and success message:
Form and validation errors:
=> [672] add first-draft UI for support users to enable orders

app/models/school_device_allocation.rb, config/locales/en.yml, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/controllers/computacenter/api/cap_usage_controller_spec.rb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb, spec/models/computacenter/api/cap_usage_update_spec.rb, spec/models/school_device_allocation_spec.rb, spec/models/school_spec.rb
- https://trello.com/c/xUIUD6em/664-allow-cap-changes-via-support
- Add backend validations to ensure caps, allocations and order_state are kept in valid states
- Validations ensure that devices_ordered <= cap <= allocation
- Changing order_state we check the cap and allocation values
- `SchoolDeviceAllocation.devices_ordered` must be lte `SchoolDeviceAllocation.cap`
- `SchoolDeviceAllocation.cap` must be lte `SchoolDeviceAllocation.allocation`
- Changing `School.order_state` to `can_order` can only happen if there is a non-zero cap
- Changing `School.order_state` to `can_order_for_specific_circumstances` can only happen if there is a non-zero allocation
=> [664] Cap and Allocation validations

app/controllers/support/devices/order_status_controller.rb, app/views/support/devices/order_status/edit.html.erb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb
The back link on that form is broken. The form doesn't pre-populate existing values from the school model.
Fix broken back link.
Populate the edit form with existing values.
=> Improvements to the 'Enable school orders' support form

app/controllers/responsible_body/devices/orders_controller.rb, app/helpers/view_helper.rb, app/models/responsible_body.rb, app/models/school.rb, app/models/school_device_allocation.rb, app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/devices/orders/_get_devices_early.html.erb, app/views/responsible_body/devices/orders/_heading.html.erb, app/views/responsible_body/devices/orders/_place_order_for_schools.html.erb, app/views/responsible_body/devices/orders/_some_schools_can_order.html.erb, app/views/responsible_body/devices/orders/cannot_order_yet.html.erb, app/views/responsible_body/devices/orders/order_devices.html.erb, app/views/responsible_body/devices/orders/specific_circumstances.html.erb, config/initializers/inflections.rb, config/locales/en.yml, config/routes.rb, config/settings.yml, db/schema.rb, spec/factories/schools.rb, spec/features/responsible_body/ordering_devices_spec.rb, spec/models/responsible_body_spec.rb, spec/models/school_spec.rb, spec/rails_helper.rb
[Trello card](https://trello.com/c/43443pu0/635-ordering-devices-centrally)
Add ordering devices for responsible body
See [https://increasing-access-history.herokuapp.com/ordering-devices-centrally/](https://increasing-access-history.herokuapp.com/ordering-devices-centrally/)
Add 'order devices' page for RBs in devices pilot
The order devices page is different depending on:
Any schools can order
Any centrally managed schools can order
Any schools that will order devices can order
There are a couple of changes to the design that have had to be worked in.  The designs assume that we are tracking allocation amounts i.e. 'You've ordered 1 of 4 devices' which isn't a thing currently so that text is missing.
@emmajhf has provided some copy for when there are schools that will order devices that …
=> [635] ordering devices centrally

app/controllers/responsible_body/devices/who_to_contact_controller.rb, app/form_objects/responsible_body/devices/who_to_contact_form.rb, spec/controllers/responsible_body/devices/who_to_contact_controller_spec.rb
- https://trello.com/c/w2vkKQQu/683-rbs-cant-update-a-headteacher-contact
- Users are trying to update contacts but the implementation tries to create a new record with duplicated data which fires a uniqueness constraint therefore raising an error
- On this form if another contact is added but uses an email of an existing contact it will update the existing contact
- I'm not sure how to actually navigate to the concerned page. This http://localhost:3000/responsible-body/devices/schools/100000/who-to-contact worked for me though
- Ensure a contact already exists
- Enter email address of existing contact
- All other inputs should be something else
- Existing contact should now be updated with the just entered data
=> [683] Who to contact form updates existing contact

app/controllers/support/internet/responsible_bodies_controller.rb, spec/features/support/internet/viewing_onboarded_responsible_bodies_spec.rb, spec/features/support/internet/viewing_responsible_body_users_spec.rb
When the connectivity pilot RB report in Support was conceived, we only had a limited number of RBs with users. Now that the devices work is also in the service, that assumption is no longer the case, so we need to filter the connectivity RB list
by participation in the connectivity pilot.
Only show RBs in the connectivity pilot for the support > internet > responsible bodies page.
=> Make the connectivity pilot RB report more useful

app/mailers/computacenter_mailer.rb, app/services/cap_update_service.rb, app/services/feature_flag.rb, config/settings.yml, spec/services/cap_update_service_spec.rb
[Trello card](https://trello.com/c/SsxJkncU/665-an-email-is-sent-to-computacenter-when-a-cap-is-updated)
An email notification is sent to Computacenter when a cap changes.
This is enabled using the feature flag `:notify_computacenter_of_cap_changes`
Addition of mailer for Computacenter with emails for devices and comms cap changes
Addition of feature flag to control whether email notification are sent
`CapUpdateService#update!` will trigger an email if the feature flag is activated.  This also attempts to send a SOAP request to computacenter (which failed on my dev environment) so may not be a safe way to test this?
=> [665] Added mail notification of cap changes to computacenter

Gemfile, Gemfile.lock, app/controllers/support/devices/contacts_controller.rb, app/controllers/support/devices/schools_controller.rb, app/views/support/devices/contacts/edit.html.erb, app/views/support/devices/schools/show.html.erb, config/routes.rb, spec/controllers/support/devices/contacts_controller_spec.rb, spec/features/support/devices/contacts_management_spec.rb, spec/page_objects/support/devices/contact_page.rb, spec/page_objects/support/devices/school_details_page.rb
- https://trello.com/c/mQs5Q3Jl/684-no-ability-to-edit-school-contacts-for-support-users
- Support agents are not able to update contacts
- Support can now see contacts on the school show page in support
- There is a link to a form to then update the contact
- Log in as support agent
- Find a school
- Should see contacts
- Click change link and update contact info
- Contact should now be updated
=> [684] Add contacts to school support page

app/views/support/devices/contacts/edit.html.erb, config/locales/en.yml
I may have overzealously merged #478, since the contact edit page didn't have any titles, headings or back link.
Add page furniture to the contact edit page.
Before:
After:
=> Add page furniture for contact edit screen in support

app/controllers/support/devices/contacts_controller.rb, app/models/school_contact.rb, app/views/support/devices/contacts/edit.html.erb, config/routes.rb, spec/controllers/support/devices/contacts_controller_spec.rb, spec/models/school_contact_spec.rb
- https://trello.com/c/mQs5Q3Jl/684-no-ability-to-edit-school-contacts-for-support-users
- Allow support to be able to select a contact and set the as the current contact
- In support added a secondary button to be able to set the contact on the page as the current contact. Only visible if the contact is not the current contact
- Find school with multiple contacts
- Go go edit contact of the current contact, should not see the `Set as current contact` button as they are already the current contact
- Go to another contact
- Set them as the current contact
- They should now be the current contact, visible on school show page
=> [684] Support can set current school contact

app/components/responsible_body/school_details_summary_list_component.rb, app/controllers/responsible_body/devices/who_to_contact_controller.rb, app/form_objects/responsible_body/devices/who_to_contact_form.rb, app/models/school.rb, app/views/responsible_body/devices/who_to_contact/_who_to_contact_form.html.erb, app/views/responsible_body/devices/who_to_contact/edit.html.erb, config/routes.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/controllers/responsible_body/devices/who_to_contact_controller_spec.rb, spec/form_objects/responsible_body/devices/who_to_contact_form_spec.rb
- https://trello.com/c/afX5ZJbs/682-no-ability-to-edit-school-contacts-rb-user
- Allow RBs to update the school contact
- Adds change link to edit contact on school show page
- If headteacher contact present radios will be visible, otherwise no radios will be visible
- It will preselect headteacher contact or someone else radio depending on the current contact on the preorder info record
- It will populate the someone else fields if an existing contact for the school exists
- Changing the radio will point the preorder info record to the correct contact
There are quite a few scenarios to play with
- A school with and without a headteacher contact
- A school with and without a preorder info record
- A school with and without a contact record set on the preorder record
- The preorder record …
=> [682] RBs can update the school contact

app/controllers/school/devices_controller.rb, app/views/responsible_body/devices/orders/_place_order_for_schools.html.erb, app/views/school/devices/order.html.erb, app/views/shared/_start_ordering_on_techsource.html.erb, app/webpacker/styles/_card.scss, spec/features/school/order_devices_spec.rb
[Trello card](https://trello.com/c/6SoAV292/562-schools-order-devices-in-lockdown)
Order devices page for schools
Add order devices page with link to TechSource
The trigger for displaying the order devices page is `School#can_order_devices?` which takes the `order_state` and whether there are any devices available to order into account - should this only consider the `order_state` so a school can see when they've used their allocation rather than see the 'You can't order devices yet' page once they've ordered their devices?
Currently kept the `You’ve ordered 0 of 2 devices` text although we don't track it and we decided not to show it on the RB order devices pages. We can only show "`devices_ordered` of `cap`" which may end up being confusing.
I extracted the text around the tech source …
=> Add school order devices page

app/controllers/responsible_body/users_controller.rb, db/migrate/20200918101304_data_rb_users_techsource_account.rb, db/schema.rb, spec/controllers/responsible_body/users_controller_spec.rb
- https://trello.com/c/9L3IQkh4/694-adding-or-editing-rb-users-should-force-setting-whether-the-user-needs-a-techsource-account-or-not
- https://trello.com/c/upShx5aS/693-all-existing-rb-users-should-be-eligible-for-a-techsource-account
- New RB users have `orders_devices` set to `true`
- Migration to set all existing RB users `orders_devices` to true
- Migration will fire activerecord lifecycle callbacks, ie. `PaperTrail::Version` records will be created and potentially `Computacenter::UserChange` records will be created
- Create new RB user
- New user `orders_devices` should be `true`
- All existing RB users `orders_devices` should be `true`
=> [693 / 694] RB users and orders_devices

app/components/support/school_details_summary_list_component.rb, app/controllers/support/devices/allocation_controller.rb, app/form_objects/support/allocation_form.rb, app/views/support/devices/allocation/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/features/support/devices/adjusting_a_schools_allocation_spec.rb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb
[Trello card 667](https://trello.com/c/IdY4UmgF/667-support-users-can-set-allocations-for-devices)
Add first-draft UI for adjusting device allocations. There was no design or prototype to work off, so all design suggestions very welcome.
Screens:
=> [667] add a first-draft UI to allow support users to adjust allocations

spec/services/cap_update_service_spec.rb
This spec failed [on an unrelated change](https://github.com/DFE-Digital/get-help-with-tech/runs/1130960364?check_suite_focus=true) because:
- the factory used to set up the data assigns a random allocation
- that allocation can sometimes be less than the statically-defined cap
- this can cause the data setup to fail as the constructed object fail the validation that allocation >= cap
Affix the allocation data so it's consistent with the cap data.
=> Prevent flaky spec failure by specifying valid initial data

app/models/computacenter/user_change.rb, app/services/feature_flag.rb, spec/models/user_spec.rb
This feature has been running fine on production for a while, we won't be wanting to switch it off.
Remove the feature flag and guard around the functionality.
=> Remove the 'update_computacenter_user_change' feature flag

app/components/responsible_body/school_details_summary_list_component.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb
- https://trello.com/c/rOdSg6WL/688-show-how-many-devices-a-school-has-already-ordered-to-rbs-and-in-support
- Add devices ordered count to the school table
- Find a school without an allocation or allocation with `devices_order` set to `0`
- View the school eg http://localhost:3000/responsible-body/devices/schools/100000
- Should not see the row with `Devices ordered`
- Update the allocation with `devices_ordered` to any number
- Should now see new row with `Devices ordered` with whatever count you used
- Same behaviour should be exhibited for an RB user viewing the school
=> [688] Add devices ordered count to school table

app/controllers/computacenter/chromebooks_controller.rb, app/models/computacenter/chromebook_details.rb, app/views/computacenter/home/show.html.erb, config/routes.rb, spec/features/computacenter/download_csv_files_spec.rb, spec/models/computacenter/chromebook_details_spec.rb
[Trello card](https://trello.com/c/XMPFSbaA/692-computacenter-users-can-download-a-spreadsheet-with-google-chromebook-details)
Add downloading of chromebook details as CSV
Additional button to Computacenter home screen to download Chromebook details
Export of Chromebook details from `PreorderInformation`
I have adjusted some of the text on the Computacenter home page as there are now 2 files to download not a single CSV.
I have not changed the page title but that should be changed as it is for downloading TechSource users
=> 692 computacenter users can download a spreadsheet with google chromebook details

app/models/user.rb, spec/models/user_spec.rb
[Trello card](https://trello.com/c/j8FB0QnK/695-investigate-invalid-school-user-records-on-production)
A school user on production cannot sign-in. He is getting a 422 on sign-in.
The school has 3 people that can order devices.
It appears that the validation for `orders_devices` is assuming that the validation applies to a new user being added.  When a user signs in their record is updated and this if failing in the validation for `orders_devices`.
Add extra condition logic to only apply the 3 user check when the record is new or if the `orders_devices` attribute has just been changed to true.
A school should have a limit of 3 users that can order devices but updating one of the attributes on those users should not cause it to fail the `:orders_devices_user_limit` validation.
=> Added fix for orders devices validation

app/controllers/support/users_controller.rb, spec/controllers/support/users_controller_spec.rb
- https://trello.com/c/9L3IQkh4/694-adding-or-editing-rb-users-should-force-setting-whether-the-user-needs-a-techsource-account-or-not
- Support users creating RB users sets `orders_devices` to `true`
- Create a new RB user
- New user should have `order_devices` set to `true`
=> [694] Support new RB users have order_devices true

app/controllers/sign_in_tokens_controller.rb, app/controllers/support/users_controller.rb, app/models/responsible_body.rb, app/models/user.rb, spec/controllers/sign_in_tokens_controller_spec.rb, spec/controllers/support/users_controller_spec.rb, spec/models/user_spec.rb
- https://trello.com/c/hlBiVAGh/697-responsible-bodies-with-only-one-school-should-see-the-school-journey
- On support adding user to RB if RB only has one school and this is the first user set them up as a hybrid user 
- Hybrid users belongs to both an RB and a school
- Hybrid setup also orchestrates a few things to put things in the correct state 
- Invite a new RB user - there must be no other RB users + RB must only have one school
- Logout and login as invited user
- Invited user should go thru school journey and no touch any RB screen
- Wizard should work and after sent user to school
- Logout and log back in
- Should be sent to school screens
- Preorder should be made for the school
- Preorder set `who_will_order_devices` to `school`
- Preorder should set …
=> [697] New RB users assigned to a school

app/controllers/responsible_body/devices/who_to_contact_controller.rb, config/locales/en.yml, spec/controllers/responsible_body/devices/who_to_contact_controller_spec.rb, spec/features/responsible_body/devices_setup_spec.rb
While we were gaining confidence in the school journey, we didn't send out the school invites automatically after responsible bodies picked school contacts. Instead, they were waiting to be transitioned as a dev task/through support. We now have enough confidence in the school journey to start sending these out automatically.
There is still an edge case when inviting the school contact fails: when the school contact is an existing user in the system (because we can't handle multi-org yet). Those schools will remain in the 'school will be contacted' state.
- Invite the school contact as soon as they're picked by the RB
- Leave schools that can't be invited in the 'school will be contacted' state
- Make it really explicit that in `WhoToContactController`, the `create` and `edit` actions do …
=> Invite school contacts as soon as they're picked by the RB

app/controllers/responsible_body/users_controller.rb, app/controllers/school/users_controller.rb, app/controllers/support/users_controller.rb, app/models/user.rb, app/services/create_user_service.rb, spec/services/create_user_service_spec.rb
See [Trello card 698](https://trello.com/c/Yn0xKhWJ/698-refactor-user-creation-to-a-service)
* Add a separate `CreateUser` service, with methods `invite_responsible_body_user` and `invite_school_user`
All behaviour should be unchanged
=> 698 refactor user creation to a service

app/models/computacenter/user_change_generator.rb, spec/models/user_spec.rb
- https://trello.com/c/XdP5HkHe/710-hybrid-user-computauserchange
- For hybrid users we need to exclude school info for Computacenta
- If the user is a hybrid user remove school from computacenta user changes
- Below is example of hybrid user being onboarded 
```ruby
#<Computacenter::UserChange:0x00007f87f7a1aa50
id: 14,
user_id: 11,
first_name: "hybrid",
last_name: "user",
email_address: "hybrid4@example.com",
telephone: nil,
responsible_body: "THE SCHOOL",
responsible_body_urn: "t1111111",
cc_sold_to_number: nil,
school: nil,
school_urn: nil,
cc_ship_to_number: nil,
updated_at_timestamp: Mon, 21 Sep 2020 17:11:23 BST +01:00,
type_of_update: "New",
original_email_address: nil,
created_at: Mon, 21 Sep 2020 17:11:23 BST +01:00,
updated_at: Mon, 21 Sep 2020 17:11:23 BST +01:00, …
```
=> [710] Hybrid users exclude school for UserChange

app/models/event.rb, app/models/invite_event.rb, app/models/sign_in_event.rb, app/models/who_will_order_event.rb, app/services/feature_flag.rb
We have 3 separate feature flags for enabling/disabling individual types of Slack event.
It's very unlikely we'd ever want to switch individual notifications on or off in a given environment. We've been wanting it on or off globally for any given env.
Have just one feature flag around slack notifications, delete the rest.
=> Reduce the number of slack-related feature flags to just one

app/form_objects/chromebook_information_form.rb, app/services/gsuite.rb, app/validators/gsuite_domain_validator.rb, config/locales/en.yml, spec/features/responsible_body/providing_a_schools_preorder_information_spec.rb, spec/features/school/change_chromebook_information_spec.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
[Trello card](https://trello.com/c/r20L12bz/586-add-validation-for-chromebook-settings)
Added G Suite domain validator
Added validations for Chromebook details in the`ChromebookInformationForm` model.
Validate `:school_or_rb_domain` with G Suite domain validator
Use EmailAddressValidator for `:recovery_email_address`
Added method to check for a service login which catches all of the domains that the MX check does and more. I've switched to using this for the validator.
The domain and email address validations are triggered when `:will_need_chromebooks` is set to 'yes'.
The domain must now be a valid G Suite domain.
Domains can be checked from the rails console with `Gsuite.is_gsuite_domain?('some-domain.com')` which returns `true` or `false` - this uses the service login check.
You can …
=> 586 add validation for chromebook settings

Gemfile, Gemfile.lock
It's already pulled in by govuk-components
=> Remove explicit dependency on view_component gem

app/components/responsible_body/school_details_summary_list_component.rb, app/components/support/school_details_summary_list_component.rb, spec/components/support/school_details_summary_list_component_spec.rb
Because the school details table in support inherits from the responsible body school details table, a few broken links have snuck in.
Remove the broken links that point to the RB interface.
=> Fix broken links in support

app/controllers/responsible_body/devices/who_will_order_controller.rb, app/models/responsible_body.rb, app/models/user.rb, spec/controllers/support/users_controller_spec.rb, spec/models/user_spec.rb
The data for single-school responsible bodies should be consistent with the other RBs.
- set 'who will order devices' for single-school RBs
- don't explicitly override the PreorderInformation status, let it be derived automatically
Review each commit separately.
=> Single school journey fixes and improvements

app/models/user.rb, spec/factories/users.rb, spec/features/signing_in_as_different_types_of_user_spec.rb
- https://trello.com/c/w7jJ7Z4B/711-hybrid-user-post-login-screen
- When a hybrid user logs in show the school name and not the responsible body name
- Login as a hybrid user
- Should see school name on next page and not the responsible body name
=> [711] Fix hybrid user post login screen

app/controllers/responsible_body/base_controller.rb, spec/controllers/responsible_body/base_controller_spec.rb, spec/factories/users.rb
- https://trello.com/c/dohUsCM7/712-hybrid-users-should-not-be-able-to-access-responsible-body
- Hybrid users are shown forbidden page if they attempt to access `/responsible/body` 
- Login as a hybrid user
- Navigate to `/responsible-body`
- Should be shown 403 forbidden page
=> [712] Deny hybrid user access to /responsible-body

spec/models/user_spec.rb
This spec failed in the build:
https://github.com/DFE-Digital/get-help-with-tech/runs/1148408135
The spec makes assumptions about how the full name is split, but the name
is generated by faker and doesn't split nicely into first_name and last_name in all
cases.
By specifying an easy name to split, this should ensure that the spec doesn't flake.
=> Fix flaky unit test

app/components/nav_component.rb, app/controllers/support/devices/school_bulk_allocations_controller.rb, app/controllers/support/devices/schools_controller.rb, app/form_objects/support/bulk_allocation_form.rb, app/services/bulk_allocation_service.rb, app/views/support/devices/school_bulk_allocations/new.html.erb, app/views/support/devices/school_bulk_allocations/summary.html.erb, config/locales/en.yml, config/routes.rb, spec/features/support/devices/bulk_school_allocations_spec.rb, spec/services/bulk_allocation_service_spec.rb
[Trello card](https://trello.com/c/00jc11yP/702-bulk-put-schools-into-lockdown)
Give multiple schools their full allocation and enable them to order devices
Add support nav menu item 'Full allocations'
Add support page for entering and submitting school urns
Add service to handle request and call `CapUpdateService#update!` for each school found
Add summary page with results of request
As a support user you should see a 'Full allocations' nav menu item
This link takes you to the page where you can enter school urns, one per row
Submitting your urns will result in the schools being granted their full allocation and ability to order by the `CapUpdateService`
A summary page shows which schools were successfully given their allocation and displays any errors.
=> 702 bulk put schools into lockdown

app/models/user.rb, app/services/create_user_service.rb, app/services/onboard_single_school_responsible_body_service.rb, spec/controllers/support/users_controller_spec.rb, spec/models/user_spec.rb, spec/services/onboard_single_school_responsible_body_service_spec.rb
#499 was a first pass at allowing single-school responsible bodies onto the service. When trying to run it on production, I realised that the assumptions in that change we'd made were incorrect, namely many single-school RBs already have existing users from wave 1.
Iterate logic for onboarding single-school responsible bodies:
- Handle the case where an RB already has users
- Handle the case where the RB has no users but the school has a headteacher
- Remove the v1 logic as it's superseded
=> Single school RB onboarding: iteration

config/routes.rb
OCD / consistency.
Use dashes instead of underscores in support URL.
=> Use dashes instead of underscores in support URL

app/helpers/view_helper.rb, app/views/responsible_body/internet/mobile/manual_requests/confirm.html.erb
- replaces custom govuk_link_to with govuk-component govuk_link_to helper method ([source](https://github.com/DFE-Digital/govuk-components/blob/master/app/helpers/govuk_link_helper.rb#L2-L4))
There is only one major difference between govuk-component helper method implementation and the one in the service. The difference is that govuk-component helper method does not support passing in a block. I don't see this as a blocker as I could only see one instance where a block was used and I assume the reason it was a block was because it was using html markup and rails would have been escaping it. This could have been overcome by using html_safe.
=> Swap out govuk_link_to with govuk-component version

app/services/onboard_single_school_responsible_body_service.rb, spec/services/onboard_single_school_responsible_body_service_spec.rb
Having onboarded a handful of single academy trusts, the onboarding service had trouble with a single academy trust where one of the trust users was the headteacher. When the service tried to create the headteacher as the school contact, it triggered the email uniqueness validation.
Only create a new school contact if one matching the user doesn't already exist.
=> Onboard single-school RBs with users who are an existing school contacts

app/services/cap_update_service.rb, spec/features/support/devices/bulk_school_allocations_spec.rb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb, spec/services/cap_update_service_spec.rb
See [Trello card 720](https://trello.com/c/Fd0q7j4m/720-investigate-missing-cap-updates)
* Remove both FeatureFlags governing the behaviour of the CapUpdateService (one for whether to hit Computacenter's API, one for whether to send an email)
* Govern both behaviours based on whether the endpoint URL is present in Settings
* Minor tidy-up of the logic around it to be more DRY
=> remove both FeatureFlags governing Cap update notifications

app/models/computacenter/outgoing_api/cap_update_request.rb, app/services/cap_update_service.rb, db/migrate/20200923093949_add_cap_update_request_timestamp_and_payload_id_to_school_device_allocation.rb, db/schema.rb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb, spec/models/computacenter/outgoing_api/cap_update_request_spec.rb, spec/services/bulk_allocation_service_spec.rb, spec/services/cap_update_service_spec.rb
See [Trello card 720](https://trello.com/c/Fd0q7j4m/720-investigate-missing-cap-updates) - this will help us diagnose any future Cap Update issues
* When a successful CapUpdateRequest is made, record the timestamp & payload ID on each of its allocations
=> 720 record cap update request timestamp and payload

app/models/support/devices/service_performance.rb, app/views/support/devices/service_performance/_preorder_information.html.erb, config/locales/en.yml, spec/models/support/devices/service_performance_spec.rb
See [Trello card 724](https://trello.com/c/KVzUVXwc/724-check-numbers-on-devices-performance-dashboard) 
Include new PreorderInformation statuses in the Support / Devices / Service Performance dashboard
=> add new statuses to device perf dashsboard

app/services/onboard_single_school_responsible_body_service.rb, spec/services/onboard_single_school_responsible_body_service_spec.rb
We've onboarded 100 single-academy trusts using the `OnboardingSingleSchoolResponsibleBodyService` and encountered some edge-cases that created problems.
- Prevent the service from running on RBs already in the pilot
- Handle case where the school contact has upper case letters in it
- Spec coverage for various edge cases
Review commit-by-commit.
=> Harden the 'onboarding single-school responsible body' service

app/controllers/computacenter/techsource_controller.rb, app/form_objects/bulk_techsource_form.rb, app/services/confirm_techsource_account_created_service.rb, app/views/computacenter/home/show.html.erb, app/views/computacenter/techsource/new.html.erb, app/views/computacenter/techsource/summary.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200923115939_add_techsource_account_to_users.rb, db/schema.rb, spec/controllers/computacenter/techsource_controller_spec.rb, spec/form_objects/bulk_techsource_form_spec.rb, spec/services/confirm_techsource_account_created_service_spec.rb
- https://trello.com/c/1ZdxZJaL/721-form-for-allowing-cc-to-confirm-the-creation-of-techsource-accounts
- Adds pages to Computacenter area so they can bulk update users who have TechSource accounts
- Add migration to add column on user to track if user has a TechSource accounts, defaults to false
- Pauls changes are also included in this PR https://github.com/DFE-Digital/get-help-with-tech/pull/541 which update the computacenter home page
- Login as a computacenter user
- Should see section at bottom to bulk update users with TechSource accounts
- On form entering blank or not one email per row raise validation error
- Submitting the form should update found users to have a TechSource account
=> [721] CC can bulk update users with TechSource accounts

app/services/confirm_techsource_account_created_service.rb, db/migrate/20200924111409_add_techsource_account_confirmed_at_to_users.rb, db/schema.rb, spec/services/confirm_techsource_account_created_service_spec.rb
- https://trello.com/c/1ZdxZJaL/721-form-for-allowing-cc-to-confirm-the-creation-of-techsource-accounts
- This is to replace `has_techsource_account` with `techsource_account_confirmed_at`
- `has_techsource_account` is now useless and will be removed in a later change
- Perform bulk update of users with TechSource account
- Should see users have `techsource_account_confirmed_at` updated to current timestamp
- `has_techsource_account` should no longer be updated
=> [721] Timestamp when techsource account confirmed

app/views/responsible_body/devices/orders/_place_order_for_schools.html.erb, app/views/school/devices/cannot_order.html.erb, app/views/school/devices/order.html.erb, app/views/school/users/edit.html.erb, app/views/school/users/index.html.erb, app/views/school/users/new.html.erb, app/views/shared/_start_ordering_on_techsource.html.erb, app/views/shared/devices/request_devices.html.erb
- Now the invitation email is not being sent, we need to be explicit about how to sign in to TechSource the very first time
- Update 'Cannot order yet' page to match design
- Use "Home" as first breadcrumb title
=> Update order pages to match design, tweak TechSource guidance

db/migrate/20200924142403_remove_has_techsource_account_from_users.rb, db/schema.rb
- https://trello.com/c/1ZdxZJaL/721-form-for-allowing-cc-to-confirm-the-creation-of-techsource-accounts
- There was a change of mind so in the end one of the db columns in no longer needed
- remove db column from users `has_techsource_account` as it has been superceded by `techsource_account_confirmed_at`
- users `techsource_account_confirmed_at` column no longer exists
=> [721] Remove unused db column

app/controllers/techsource_launcher_controller.rb, app/helpers/view_helper.rb, app/views/responsible_body/devices/orders/order_devices.html.erb, app/views/school/devices/order.html.erb, app/views/shared/_start_ordering_on_techsource.html.erb, app/views/shared/_techsource_unavailable_banner.html.erb, app/views/techsource_launcher/unavailable.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/techsource_launcher_controller_spec.rb, spec/features/school/order_devices_spec.rb, spec/features/techsource_availability_for_responsible_body_spec.rb, spec/features/techsource_availability_for_school_spec.rb
[Trello card](https://trello.com/c/qXZ3BESe/689-inform-users-about-ccs-downtime-on-saturday-26th-sept)
Add warning banner and 'service unavailable' page on order devices pages
Add warning banner to devices ordering pages for RBs and Schools visible until Sunday 27 Sept.
Add service unavailable page that the 'Start now' button will send the user if clicked during maintenance window on Saturday 26 Sept.
=> 689 inform users about ccs downtime on saturday 26th sept

app/models/computacenter/user_change.rb, app/models/computacenter/user_change_generator.rb, app/models/user.rb, spec/models/computacenter/backfill_ledger_spec.rb, spec/models/user_spec.rb
A necessary precursor of [Trello card 718  - Handle multiple schools in an MVP way](https://trello.com/c/aYQOz3QB/718-spike-handle-multiple-schools-in-a-minimum-viable-way). This will enable us to trigger `Computacenter::UserChange` generation from a future `UserSchool` association. Also simplifies implementation of [700 - Send UserChanges to Computacenter's ServiceNow API](https://trello.com/c/mYNXeNHI/700-send-user-changes-to-computacenters-servicenow-api).
* Generate `Computacenter::UserChange` records directly, rather than from Papertrail versions
* Determine whether a UserChange is needed (and if so what type) by looking at existing UserChange records, rather than the previous state of the User record
* All expectations of the UserChange attributes stay the same as now, except for …
=> 718 refactor & simplify user_change generation

app/components/nav_component.rb, app/controllers/support/devices/schools_controller.rb, app/form_objects/bulk_urn_search_form.rb, app/views/support/devices/schools/results.html.erb, app/views/support/devices/schools/search.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/support/devices/schools_controller_spec.rb, spec/form_objects/bulk_urn_search_form_spec.rb
- https://trello.com/c/0RnBhnLD/737-lockdown-dashboard
- Add schools to nav header which links to school search
- Able to search for schools via list of URNS
- This has not been added to `index` as it needs to handle the form and the `POST` and use of query params I feel would have been a fiddly path to go down
- Click on schools in the nav
- Paste a list of URNs into search form with valid and invalid URNs
- Should see search results
=> [737] Support can search schools by URN

app/views/responsible_body/devices/orders/specific_circumstances.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb
Due to a merge conflict between #547 and #546, we are missing the TechSource downtime warning on the order for special circumstances pages.
Add the warning in.
=> Warn about techsource downtime when ordering for specific circumstances

app/views/responsible_body/devices/orders/specific_circumstances.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb
- Use the govuk_link_to helper so link is the right blue
- Make both messages say "contacted" rather than "emailed"
=> Fix link colour, make text consistent

app/views/responsible_body/devices/chromebook_information/edit.html.erb, app/views/responsible_body/devices/schools/show.html.erb, app/views/school/welcome_wizard/chromebooks.html.erb, app/views/school/welcome_wizard/devices_you_can_order.html.erb, app/views/shared/_chromebook_information_form.html.erb, app/views/shared/_chromebook_information_intro.html.erb, app/views/shared/_device_list.html.erb, config/locales/en.yml, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/responsible_body/devices_setup_spec.rb, spec/features/responsible_body/providing_a_schools_preorder_information_spec.rb, spec/features/school/change_chromebook_information_spec.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb
Apply the content changes from https://ghwt-design-history.herokuapp.com/chromebook-iteration
Part of https://trello.com/c/k7ItZJIp/729-indicate-what-devices-are-available-to-rbs
The main change is that we now list all the devices on the Chromebooks form.
=> Chromebook form content changes

app/models/computacenter/user_change.rb, app/services/confirm_techsource_account_created_service.rb, spec/services/confirm_techsource_account_created_service_spec.rb
- https://trello.com/c/8zERGQht/751-techsource-account-confirmation-fixes
- Handle a case where by a user has recently changed email. When sent an old email we do a look up with the user change table and find the current user.
- Handle case of a user that is no longer computacenter relevant by checking if they were last removed from the user change table
- Change a users email address
- Visit http://localhost:3000/computacenter/techsource
- Enter the users old email address
- User should now have `techsource_account_confirmed_at` set
- Delete a computercenter relevant user
- Visit http://localhost:3000/computacenter/techsource
- Enter the deleted users email address
- Should not show as unprocessed and should show email as processed
=> [751] TechSource confirmations handle extra cases

app/models/computacenter/user_change.rb, app/models/computacenter/user_change_generator.rb, app/models/school.rb, app/models/school_welcome_wizard.rb, app/models/user.rb, app/models/user_school.rb, app/services/confirm_techsource_account_created_service.rb, db/migrate/20200922130419_add_user_schools.rb, db/schema.rb, spec/factories/users.rb, spec/models/computacenter/backfill_ledger_spec.rb, spec/models/school_welcome_wizard_spec.rb, spec/models/user_spec.rb
See [Trello Card 718](https://trello.com/c/aYQOz3QB/718-spike-handle-multiple-schools-in-a-minimum-viable-way). We urgently need to support users who genuinely administer multiple schools, but the work involved in supporting that impacts lots of areas where the code and the interface implicitly assume that a user can have only one school. So we're iterating towards full support in several smaller steps which can be reviewed and merged independently.
This PR does the bare minimum needed to get the model changed to support multiple schools. There are no interface changes - those can come as a separate dedicated PR later.
* Replace `user belongs_to :school` with `user has_many :user_schools / has_many :schools, through: :user_schools`
* Add adapter methods `school / school=` and `school_id / …
=> 718 mvp multiple schools

app/components/support/school_user_summary_list_component.html.erb, app/components/support/school_user_summary_list_component.rb, app/models/user.rb, app/views/support/devices/schools/show.html.erb, spec/components/support/school_user_summary_list_component_spec.rb, spec/features/support/devices/managing_schools_spec.rb
DfE support users need to know when it's appropriate to ask users to go place orders.
- On the schools page in support, convert the users table to a list of summary lists. This is keeping with the user lists for responsible bodies and schools.
- Surface whether the user has everything necessary to order, and if not, then why not.
- Introduce a new view component for ease of testability
=> Show TechSource account confirmation in support

app/controllers/school/users_controller.rb, app/controllers/support/devices/users_controller.rb, app/services/create_user_service.rb, app/views/support/devices/schools/show.html.erb, app/views/support/devices/users/new.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/support/devices/users_controller_spec.rb, spec/services/create_user_service_spec.rb
- https://trello.com/c/T2A6JdPn/757-add-a-new-school-user-via-support
- New page in support to add new school users
- Tweaks to `CreateUserService` to remove overbearing overrides
- Navigate to a school via RB
- Should be a button below users table to add new users
- Click this button
- Should be taken to page to add new user to the school
- Fill it in incorrectly
- Should see errors
- Fix mistakes and submit
- Should create this new user on the school
- Should send email to new user
=> [757] Support can add new school users

app/views/pages/about_increasing_mobile_data.html.erb
These networks are now on board
=> Add Tesco Mobile and O2 to provider list

app/controllers/support/devices/users_controller.rb, spec/controllers/support/devices/users_controller_spec.rb, spec/features/support/devices/inviting_school_users_spec.rb, spec/page_objects/support/devices/school_details_page.rb, spec/page_objects/support/devices/schools/new_user_page.rb
- https://trello.com/c/T2A6JdPn/757-add-a-new-school-user-via-support
- Fixes support inviting a school user
- This was due to a change in association between school and user
- Also added additional coverage to prevent regression
- Login as a support user and find a school
- Invite a new user
- Should see user on the school page
- Should send out email to invited user
=> [757] Fixes support inviting a school user

Gemfile, Gemfile.lock
We used to use 'haml' but don't anymore.
Remove the gem so we don't have to keep upgrading it.
=> Remove the 'haml' gem as we're no longer using it

app/models/preorder_information.rb, app/services/create_user_service.rb, spec/features/support/devices/inviting_school_users_spec.rb, spec/models/preorder_information_spec.rb, spec/services/create_user_service_spec.rb
Before #560, the only way to add the first user to a school was to invite a school contact. It's now possible for support users to add the first user directly. The school status isn't being updated correctly in this case.
Update the school status inference logic to correctly calculate the status, irrespective of how the first user was added.
Ensure that the school status is recalculated when a school user is added.
=> Fix school status when school user added via support

app/jobs/notify_computacenter_of_latest_change_for_user_job.rb, app/models/computacenter/service_now_user_import_api/error.rb, app/models/computacenter/service_now_user_import_api/import_user_change_request.rb, app/models/computacenter/user_change_generator.rb, app/models/user.rb, config/settings.yml, db/migrate/20200929092315_add_cc_import_api_fields_to_user_change.rb, db/schema.rb, spec/features/school/manage_users_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/jobs/notify_computacenter_of_latest_change_for_user_job_spec.rb, spec/models/computacenter/service_now_user_import_api/import_user_change_request_spec.rb, spec/models/user_spec.rb, spec/services/onboard_single_school_responsible_body_service_spec.rb
[Trello card 700](https://trello.com/c/mYNXeNHI/700-send-user-changes-to-computacenters-servicenow-api)
* Add a class to encapsulate sending a ServiceNow Import API request for a given UserChange
* Add a job class to instantiate an API request with the latest UserChange for a given user, send it, and record the transaction against the UserChange
* Add a call to enqueue one of those jobs whenever a UserChange is generated, so long as the relevant endpoint is defined in Settings
The three additions above are done in order with the three commits in this PR - I suggest reviewing it commit-by-commit.
I've tested this against CC's test server, we don't have credentials for any other server yet, so no jobs will run on prod even if this merged and deployed.
=> 700 send user changes to Computacenters ServiceNow API

app/components/school_user_summary_list_component.html.erb
Failing build
```bash
1) Manage school users viewing the list of school users who can order devices
Failure/Error: <%= render SchoolUserSummaryListComponent.new(user: user) %>
ActionView::Template::Error:
Could not find a template file or inline render method for SchoolUserSummaryListComponent.
```
- This file can be removed once view_component is upgraded
- view_component cannot be upgraded as it is pinned by govuk-components
- This is the quickest fix to workround the issue
- See https://github.com/github/view_component/releases/tag/v2.19.0
- Checkout main
- Run `bundle exec rspec spec/features/school/manage_users_spec.rb`
- Tests will fail
- Checkout this branch 
- Run `bundle exec rspec spec/features/school/manage_users_spec.rb`
- Test suite should be green
=> Fix build due to component cant inherit template

app/models/school.rb, spec/models/school_spec.rb
See [Trello card 784](https://trello.com/c/zWvwYauu/784-add-a-helper-method-to-school-to-return-the-active-responsible-users)
* Add a convenience method that returns the users who have signed in at least once, and are responsible for this school on the system (school or responsible body users, depending on who will order devices)
=> add helper method to return active responsible users

app/views/school/details/show.html.erb, app/views/shared/_chromebook_information_form.html.erb
When users contact us for Chromebook help, we ask them to contact their IT support team. They do not need to contact us and we can advise them to go straight there.
=> Advise users to contact IT support for Chromebook details

app/controllers/school/before_can_order_controller.rb, app/controllers/school/chromebooks_controller.rb, app/controllers/sign_in_tokens_controller.rb, app/models/preorder_information.rb, app/views/school/before_can_order/edit.html.erb, app/views/school/chromebooks/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/preorder_information.rb, spec/features/signing_in_as_different_types_of_user_spec.rb
- https://trello.com/c/5mKpDVHB/752-build-a-before-you-can-order-page-to-show-to-schools-each-time-they-sign-in-until-chromebook-info-completed
- Adds a new page post login for schools users that will order
- The page is shown when users still need to supply chromebook answers
- Invite a new school user. The school should be ordering devices. Ideally first school user so clean slate
- Login as school user
- Should see standard school wizard, complete this but delay entering of chromebook details
- Logout and login back in
- After post login screen should see that there is a page prompting the user to enter chromebook details
=> [752] Add interstitial before you can order page

app/form_objects/chromebook_information_form.rb, spec/form_objects/chromebook_information_form_spec.rb
Some schools are inadvertently padding Chromebook domains and recovery emails with whitespace. This triggers a validation message and has caused them to get in touch with support.
Strip whitespace on entry for Chromebook domains and recovery emails.
=> Allow and strip whitespace in Chromebook details

app/models/school_welcome_wizard.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/models/school_welcome_wizard_spec.rb
- https://trello.com/c/KPN6ELXJ/730-not-showing-techsource-account-page-on-school-wizard-to-subsequent-users
- Welcome wizard shows TechSource page if user orders devices
- This is no longer based on whether they are the first user or not
- Regardless of first or nth school user
- If `orders_devices` is true should see techsource page
=> [730] Wizard shows TechSource if orders devices

app/views/school/devices/cannot_order.html.erb, config/locales/en.yml, spec/features/school/order_devices_spec.rb
- https://trello.com/c/vaC4fRyk/577-order-devices-screen-for-people-without-access-to-techsource
- Change the cannot order page
- Change titles
- Additional copy on they cannot place orders if applicable
- Login as school user that cannot `orders_devices`
- Make the school order devices but cannot order at the moment 
- Visit order devices page
- Should see techsource copy at the bottom of the page
- Change user so `orders_devices` is `true` and `techsource_account_confirmed_at` is `1.second ago`
- Reload the page
- Should not see techsource copy
=> [577] Tweak cannot order page 

app/controllers/school/devices_controller.rb, app/models/user.rb, app/views/school/devices/can_order_awaiting_techsource.html.erb, config/locales/en.yml, spec/features/school/order_devices_spec.rb, spec/models/user_spec.rb
- https://trello.com/c/mZTOpn2R/795-build-techsource-account-not-yet-ready-page
- Minor copy changes and ui tweaks
- Login as a school user who can `order_devices` `true` but `techsource_account_confirmed_at` `nil` 
- Make the school allowed to order devices
- As school user attempt to order devices
- Should see copy related to TechSource account will be ready soon
=> [795] School can order + awaiting on TechSource

app/controllers/school/devices_controller.rb, app/views/school/devices/school_can_order_user_cannot.html.erb, config/locales/en.yml, spec/controllers/school/devices_controller_spec.rb, spec/features/school/order_devices_spec.rb, spec/features/techsource_availability_for_school_spec.rb
- https://trello.com/c/FnEmqTN6/797-school-can-orders-devices-user-that-cant-order
- Handles scenario where the school can order but the user themselves cannot place order
- Login as school user
- Set user do `orders_devices` is `false`
- Set the school so it can order devices
- As this school user attempt to place an order
- Should see page explaining the school can place order but they themselves cannot place the order
=> [797] School can order but user cannot order page

app/controllers/responsible_body/internet/mobile/bulk_requests_controller.rb, app/controllers/responsible_body/internet/mobile/extra_data_requests_controller.rb, app/controllers/responsible_body/internet/mobile/manual_requests_controller.rb, app/services/feature_flag.rb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, spec/controllers/responsible_body/internet/mobile/bulk_requests_controller_spec.rb, spec/controllers/responsible_body/internet/mobile/extra_data_requests_controller_spec.rb, spec/controllers/responsible_body/internet/mobile/manual_requests_controller_spec.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/responsible_body/submitting_a_spreadsheet_request_spec.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb, spec/features/session_behaviour_spec.rb
Alternative to #587.
If the feature flag is deactivated:
- Remove new request button.
- Show 404 if trying to deep-link to the forms.
=> Add the ability to prevent new MNO requests via a feature flag

app/jobs/stage_trust_data_job.rb, app/models/data_stage/trust.rb, app/models/get_information_about_schools.rb, app/models/trust_data_file.rb, app/services/stage_trust_data.rb, config/sidekiq.yml, db/migrate/20201002105725_create_staged_trusts.rb, db/schema.rb, spec/factories/staged_trusts.rb, spec/models/trust_data_file_spec.rb, spec/services/stage_trust_data_spec.rb, spec/support/csv_file_helper.rb
[Trello card](https://trello.com/c/8AvaD8wz/777-gias-updates-stage-trust-data)
Import GIAS trusts to the data stage
Add import and parsing of trust data from GIAS (original import left in place for now).
Add job to schedule daily update of the import staging of the trust data (not sure if this actually needs to be daily?)
Running `StageTrustDataJob.perform_now` will download and import the latest Trust data from GIAS to the data stage.
View the imported Trust data via the `DataStage::Trust` model.
__Note:__ this does not affect the `Trust` data in the service as yet, those updates will come in future PRs.
=> 777 gias updates stage trust data

app/controllers/school/devices_controller.rb, app/models/school.rb, app/models/user.rb, app/views/school/devices/cannot_order_as_cap_reached.html.erb, config/locales/en.yml, spec/controllers/school/devices_controller_spec.rb, spec/models/school_spec.rb
- https://trello.com/c/tEnKg7FQ/732-build-all-devices-ordered-page-for-schools
- This is displayed instead of the cannot order page when the user can order but have reached their cap
- Login as a school user
- The school can order devices but cap == allocation
- Attempt to user
- Should see the new page instead of the cannot order page
=> [732] If all devices ordered page

app/controllers/application_controller.rb, app/controllers/privacy_notice_controller.rb, app/controllers/responsible_body/home_controller.rb, app/controllers/school/base_controller.rb, app/controllers/sign_in_tokens_controller.rb, app/controllers/users_controller.rb, app/models/school_welcome_wizard.rb, app/models/user.rb, app/views/privacy_notice/show.html.erb, config/routes.rb, db/migrate/20201005122245_change_default_wizard_step_to_allocation.rb, db/schema.rb, spec/controllers/sign_in_tokens_controller_spec.rb, spec/factories/school_welcome_wizards.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/models/school_welcome_wizard_spec.rb
As part of the larger ticket [649 - Support multiple schools per user](https://trello.com/c/lDAgx85e/649-handling-multiple-schools), we'll need to have one `SchoolWelcomeWizard` per user-and-school combination. This means we need to remove the privacy notice from the wizard workflow, and make it standalone (the privacy notice is effectively per user, not per school). A subsequent PR will actually add the school ID to the SchoolWelcomeWizard class and deal with the user journey implications.
In discussion with @fofr we agreed that the privacy notices for school users and responsible body users were the same and could be unified into one - which also means that this work is foundational for supporting multiple RBs per user in future too. 
* change the default step on `SchoolWelcomeWizard` …
=> [804] extract privacy page from wizard and make it a single unified standalone page

app/views/devices_guidance/how_to_order.html.erb, spec/features/devices_guidance/how_to_order_spec.rb
The title of the "How to order laptops and tablets" page on the devices guidance index was changed to "How **and when** to order laptops and tablets" in #595. However the title of the actual page wasn't updated at the same time.
Re-align the name of the page with the name in the index.
=> Align guidance page title with its title in the guidance index page

app/services/feature_flag.rb
The feature flag branching was removed in #532, but the flags themselves were left in.
Remove the unused feature flags.
=> Remove unused feature flags

db/migrate/20201005160200_drop_legacy_school_id_from_user.rb, db/schema.rb
This was a fallback column in case PR #551 had any issues on rollout. Looks like we're good, so we can drop this column now,
Drop the column
=> drop legacy_school_id from user

app/controllers/responsible_body/users_controller.rb, app/services/feature_flag.rb, app/views/responsible_body/users/_user.html.erb, app/views/responsible_body/users/index.html.erb, spec/controllers/responsible_body/users_controller_spec.rb, spec/features/responsible_body/manage_users_spec.rb
The feature allowing RBs to edit users has been on for a while, so the feature flag is no longer necessary.
Remove the feature flag.
=> Remove rbs_can_manage_users feature flag as it's fine in production

app/views/mno/extra_mobile_data_requests/_extra_mobile_data_request.html.erb
One auto-generated legend slipped through after the gem update in #594 😬  
Hide the default legend
Before:
After:
=> Stop from auto-generated legend appearing on MNO requests index

app/controllers/mno/extra_mobile_data_requests_controller.rb, spec/controllers/mno/extra_mobile_data_requests_controller_spec.rb
MNOs are inadvertently able to cancel MNO requests without providing a reason why. This shouldn't be possible via the MNO interface.
Remove the 'cancelled' status from the MNO status changer.
=> Prevent MNOs from cancelling extra mobile data requests via the interface

app/models/data_stage/trust.rb, app/models/trust_data_file.rb, app/services/trust_update_service.rb, db/migrate/20201006105307_add_address_to_responsible_bodies.rb, db/schema.rb, spec/models/trust_data_file_spec.rb, spec/services/stage_trust_data_spec.rb, spec/services/trust_update_service_spec.rb
[Trello card](https://trello.com/c/xuCqURSA/775-gias-updates-changes-to-trusts)
Update Trusts from the staged GIAS data
Adds address to responsible bodies
Basic mechanism is the same as updates to schools, the last update is recorded and changes made to the staging area since the last update are applied to the Trusts.
Use `TrustUpdateService.new.update_trusts` to process updates
=> 775 gias updates changes to trusts

app/helpers/view_helper.rb, app/views/mno/extra_mobile_data_requests/index.html.erb
We recently switched out the implementation of `govuk_link_to`, from
the one that was defined in the app, to a version that is defined in the
`govuk-components` gem.
This meant that the MNO requests table links weren't being generated quite correctly
and weren't getting the 'govuk-link' class applied to them.
This change hardcodes the path helper to the MNO request index path, so
I've changed the helper name to reflect that.
=> Fix links in the header of the MNO requests table

app/models/school_data_file.rb
Some schools that are Further Education establishments should be in the service. This allows them to come into the Data Stage where the permitted ones could be onboarded.
Remove 'Further Education' from the filter for the schools data file
Running `StageGiasDataJob.perform_now` should now bring schools with the 'EstablishmentType' of 'Further education'
=> Allow further education establishments

app/models/csv_data_file.rb
[Trello card](https://trello.com/c/gXzz8uYD/549-gias-data-import-encoding)
Use `CP1252` (Windows) encoding on incoming CSV files. Also no need to force encoding to UTF-8
Change encoding type when reading CSV data
Once imported, School and Trust names should now appear correctly if they contain extra characters such as accents.
e.g. `FIERTÉ MULTI-ACADEMY TRUST`
=> Set encoding for incoming csv data to CP1252

app/components/support/enable_orders_confirm_summary_list_component.rb, app/components/support/school_details_summary_list_component.rb, spec/features/support/devices/adjusting_a_schools_allocation_spec.rb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb
It's possible to define actions for summary list component rows, which adds visually hidden text to the change links. This hidden text is visible to screen readers and to Capybara.
In the support interface, define actions for the 'change' summary list links.
Defining the action on the change links means the capybara specs don't need
to be scoped to a particular element on the page, which makes the spec more brittle
and harder to follow.
=> Make the 'change' links in support more accessible

app/controllers/support/devices/order_status_controller.rb, app/mailers/can_order_devices_mailer.rb, app/models/can_order_devices_notifications.rb, app/models/school.rb, app/models/user.rb, app/models/user_can_order_event.rb, app/services/bulk_allocation_service.rb, app/services/feature_flag.rb, app/services/school_order_state_and_cap_update_service.rb, config/locales/en.yml, config/settings.yml, spec/models/can_order_devices_notifications_spec.rb, spec/services/school_order_state_and_cap_update_service_spec.rb
If a school cap is set, the order users need to know that they can go in and place their orders.
Out of scope for this PR:
- notifying an order user when their TechSource account has been confirmed (will be a follow-up PR)
- sending an automated email to CC (will be a follow-up PR)
- Inform the order users when the cap for their school has been set
- Feature flag the email, until we've let the feature run in production for a little bit and see from the Slack messages that it's triggering at the right point in time
=> [666] Order users are notified when a school order state allows ordering

app/mailers/computacenter_mailer.rb
Computacenter have requested extra info in the automated cap update email. This email is sent to them after every cap change.
Add extra school and RB fields into the personalisation of the email. These will be exposed in Notify when this change is released.
=> Add extra information to automated CC cap update email.

config/settings/test.yml, spec/features/support/devices/bulk_school_allocations_spec.rb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb, spec/models/computacenter/outgoing_api/cap_update_request_spec.rb, spec/services/school_order_state_and_cap_update_service_spec.rb, spec/support/computacenter_helper.rb
`Settings.computacenter.outgoing_api.endpoint` is a global setting. Specs
should ensure they don't modify this setting during setup and execution,
otherwise it affects the outcome of other specs.
As a rule, it should be on in the specs (like it is in production). Any resultant
network calls should be stubbed out via the newly introduced spec helper. If it's
necessary to change this setting, the spec should put it back to its original value.
=> Introduce a spec helper for stubbing the outgoing Computacenter API

spec/features/support/devices/enabling_orders_for_a_school_spec.rb
~**Note**: _depends on #630, rebase this PR after that one is merged._~ done ✅ 
~**Note**: _depends on #637, rebase this PR after that one is merged._~ done ✅ 
The nested spec style would have been useful while test-driving the functionality out, but the 'enabling orders' spec currently has 8 levels of nesting. This means it's harder to follow and change this spec than necessary, and causes a lot of repetition of the same steps/screens that makes execution time slow.
- Reword the spec descriptions/contexts, moving away from references to UI elements, and towards user intent.
- Pare down the number of scenarios by making some explicit specs implicit (e.g. checking that a link is present can be replaced by just trying to follow it – RSpec/Capybara print actionable failures when the link …
=> Improvements to the 'enabling orders' feature spec

app/services/school_order_state_and_cap_update_service.rb, spec/factories/users.rb, spec/features/support/devices/enabling_orders_for_a_school_spec.rb
Fix the notification for order users to place orders. It wasn't being sent due to objects going stale after updates.
=> Fix the notification for order users to place orders

Dockerfile
[Trello card 943](https://trello.com/c/4ZJe26dp/943-paging-broken-in-the-console-on-production) - Any console output that requires paging will break, since the move to Alpine linux.
This is an [issue with Pry's paging settings on any non-GNU-base linux less version](https://github.com/pry/pry/issues/1494)
* install GNU-base `less` 
* make sure `apk update` is called first, before adding new packages
=> [943] Fix paging of long output in the console in Docker container

app/mailers/can_order_devices_mailer.rb, app/models/school_can_order_devices_notifications.rb, config/settings.yml, spec/models/school_can_order_devices_notifications_spec.rb
- https://trello.com/c/jP4OIh88/930-send-an-automated-email-to-ghwt-support-when-a-school-is-closed-and-it-has-no-users-responsible-for-it
- Contact support if school can order but no one has been contacted as school or responsible body does not have any associated users
- Find a school that does not have users or a responsible body that does not have any users
- Ensure the school can order devices. ie has correct caps and allocations spaces then change to `can_order`
- Should send email to support regarding the fact the school can order but no one was contacted
=> [930] Notify support if school can order but no one contacted

app/models/preorder_information.rb, spec/features/responsible_body/ordering_via_a_school_spec.rb, spec/models/preorder_information_spec.rb
- https://trello.com/c/OYp10nrK/950-school-status-no-reflected-correctly
- There is a bug in `infer_status` where if the school cannot order but has devices available it would show as `school can order` when it should say `school ready` or `ready`
- Make he school `order_state` as `cannot_order` but the school should have devices available in an allocation
- Refresh
- Should see status of `School ready` if school is ordering or `ready` if RB orders
- Change the school `order_state` to `can_order`
- Should now say `school can order` if school orders or `responsible body can order`
=> [950] Fix school status

Dockerfile
[Trello card 965](https://trello.com/c/gKYLpzDv/965-users-last-sign-in-time-is-not-showing-or-being-stored-in-the-correct-time-timezone) There's an issue that means since the Daylight Savings Time switch back on Oct 24th 2020, Alpine linux by default is not reporting the DST status correctly. This filters through to [Ruby](https://discuss.rubyonrails.org/t/ruby-on-rails-daylight-saving-detection-does-not-work-in-recent-ruby-2-7-1-alpine-container/76399) and [Rails](https://github.com/rails/rails/issues/40427) via the [tzinfo](https://github.com/tzinfo/tzinfo/issues/120) gem, and means that datetimes are being stored with an incorrect UTC offset.
For more details, see this tzinfo issue [https://github.com/tzinfo/tzinfo/issues/120](https://github.com/tzinfo/tzinfo/issues/120): 
Hopefully …
=> [965] fix daylight savings time detection on Docker containers

app/controllers/school/home_controller.rb, app/views/school/home/show.html.erb, app/views/school/home/specific_circumstances.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/school/home_controller_spec.rb, spec/features/school/specific_circumstances_spec.rb
This is the first PR of https://trello.com/c/pualSpPd/955-update-content-around-mno-offer-on-school-journey
- Add a specific circumstances page
- Link to given page on the homepage if the school is within the MNO feature.
- Page links to existing 'devices' and 'extra data for mobile devices' request pages for circumstances, the latter of which will be updated in a subsequent PR. 
1. Login as user belonging to a school within the MMO feature
2. New page should be linked to from homepage
1. Login as user belonging to a school not within the MMO feature
2. New page should not be linked to from homepage
=> [995] Add specific circumstances page

app/models/extra_mobile_data_request.rb, app/models/support/service_performance.rb, app/views/support/service_performance/_mobile_data_requests.html.erb, spec/features/support/viewing_service_performance_spec.rb
- https://trello.com/c/wq16Tk5m/961-update-dashboard-to-track-connectivity-rollout-to-schools
- Add to connectivity dashboard
- Upper half is now related to requests from responsible bodies
- Lower half is now related to requests from schools
- Factory some data for mno request from responsible bodies and schools
- View connectivity dashboard
- Should see this data displayed correctly split by responsible body and school
=> [961] Add dashboard for school mno performance

app/views/school/home/show.html.erb, app/views/school/internet/home/show.html.erb, config/locales/en.yml, spec/features/school/extra_mobile_data_requests_spec.rb, spec/features/school/specific_circumstances_spec.rb, spec/features/school/wireless_router_requests_spec.rb, spec/views/school/home/show.html.erb_spec.rb
Part 2/3 of https://trello.com/c/pualSpPd/955-update-content-around-mno-offer-on-school-journey
- Rename Get the internet page to Get internet access
- Add request 4G wireless routers link to page
- Update request extra data for mobile devices guidance
1. Login as user belonging to a school within the MMO feature
2. Get internet access page should be linked to from homepage
3. Guidance should be updated on homepage
4. Guidance should be visible on Get internet access page
5. Request 4G routers link should be visible on Get internet access page 
---
1. Login as user belonging to a school not within the MMO feature
2. Get internet access page should not be visible
=> [995] Update guidance on Get Internet page

app/controllers/school/internet/mobile/extra_data_requests_controller.rb, app/views/school/internet/home/show.html.erb, app/views/school/internet/mobile/bulk_requests/summary.html.erb, app/views/school/internet/mobile/extra_data_requests/guidance.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/school/internet/mobile/extra_data_requests_controller_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb
This is the last part of https://trello.com/c/pualSpPd/955-update-content-around-mno-offer-on-school-journey
- Add an intermediate mobile data guidance page that links to new request and previous request pages
- Adjust titles and breadcrumbs of guidance and previous request pages
#769 updates the copy on the Get internet access page.
1. Login as user belonging to a school within the MMO feature
2. Get internet access page should be linked to from homepage
3. From there, you should be able to navigate to the request mobile data guidance page
4. The guidance page should link to the new request and existing request pages
=> [995] Separate 'Your Requests' from guidance on getting mobile data

app/models/responsible_body.rb, app/models/school.rb, spec/models/computacenter/user_change_generator_spec.rb, spec/models/school_can_order_devices_notifications_spec.rb
- https://trello.com/c/dcWNdAET/946-computacenter-arent-getting-soldtos-for-users-when-the-computacenterreference-is-added-to-the-rb-after-the-user-is-last-updated
- This fixes an issue where updating an RB or school does not generate a user change despite the new row would be different
- Updating a RB or school can generate user changes
- Create/Find an RB that does not have `computacenter_reference`
- Add a user to the RB that is computacenter relevant
- Note the `Computacenter::UserChange.count`
- Update the RB `computacenter_reference` to some value
- Should increment `Computacenter::UserChange.count` by 1
- This change should have populated the `cc_sold_to_number` 
- Should behave the same for a school update except should update `cc_ship_to_number`
=> [946] updating an RB or school can generate user changes

app/views/shared/devices/request_devices.html.erb, spec/features/school/request_devices_spec.rb
https://trello.com/c/pualSpPd/955-update-content-around-mno-offer-on-school-journey
Keep shorter breadcrumb on request devices for specific circumstances, but include the intermediary page when the school user is within the MNO feature.
1. View 'Request devices for specific circumstances' page within MNO feature
2. Intermediary page should be in breadcrumb
---
1. View 'Request devices for specific circumstances' page outside of MNO feature
2. Intermediary page should not be in breadcrumb
Inside feature:
Outside feature:
=> [995] Keep shorter breadcrumb on request devices for specific circumstances

app/helpers/view_helper.rb, app/views/devices_guidance/how_to_order.html.erb, app/views/responsible_body/devices/orders/cannot_order_yet.html.erb, app/views/school/devices/cannot_order.html.erb, app/views/school/home/specific_circumstances.html.erb
We link to the Education Settings Status Form in a few places. We sometimes user a view helper and sometimes it's hard coded. The link text is also inconsistent.
Use the view helper consistently, which also makes the view templates more concise.
=> Improve the link_to_ed_settings_form helper and use it consistently

app/controllers/support/responsible_bodies/users_controller.rb, app/controllers/support/responsible_bodies_controller.rb, app/controllers/support/schools/users_controller.rb, app/controllers/support/schools_controller.rb, app/form_objects/sign_in_token_form.rb, app/mailers/application_mailer.rb, app/models/computacenter/user_change_generator.rb, app/models/user.rb, app/views/support/responsible_bodies/users/edit.html.erb, app/views/support/schools/users/edit.html.erb, config/routes.rb, db/migrate/20201102124657_add_deleted_at_to_users.rb, db/schema.rb, spec/controllers/sign_in_tokens_controller_spec.rb, spec/controllers/support/responsible_bodies/users_controller_spec.rb, spec/controllers/support/schools/users_controller_spec.rb, spec/mailers/application_mailer_spec.rb, spec/mailers/can_order_devices_mailer_spec.rb, spec/models/user_spec.rb
- https://trello.com/c/QPKfn09A/878-allow-support-to-remove-user-access-from-dfe-and-cc-services
- Support can soft deletes users
- This simply sets the `deleted_at` on a user with the current timestamp
- These soft deleted users cannot login
- They are also no longer visible to support
- Soft deleted are sent to CC as if the user had been removed
- All mailers should no longer send to deleted users
- Find a user and delete them
- Support user should no longer see user
- Attempt to login as deleted user
- Should no longer be able to login
- If they were CC relevant the user changes should mark them as to be removed
- As support user attempt to mark the school as being able to order
- This user should not get the email notification
=> [878] Soft user delete

app/models/computacenter/user_change_generator.rb, spec/models/user_spec.rb, spec/services/confirm_techsource_account_created_service_spec.rb
[Trello card 981](https://trello.com/c/IZa6S3hI/981-stop-userchange-being-created-when-a-school-user-has-a-school-urn-but-no-shipto) - This closes a loophole that means a user thinks they can order, and our system thinks they're all set up, but the user can't actually be setup on TechSource because they are not linked to a `shipTo` reference on Computacenter's side.
stop `Computacenter::UserChangeGenerator` thinking a change is needed in this case (where a user has at least one school, but no corresponding `shipTo` number.... and they're not a `single_academy_trust_user`)
From the console:
```
> s = School.where(computacenter_reference: nil).first
=> <School: ....>
> u = User.create!(full_name: '...', email_address: '...', orders_devices: true, privacy_notice_seen_at: Time.now.utc)
=> …
```
=> [981] stop generating UserChanges for users with a school but no shipTo

Gemfile, Gemfile.lock, app/views/responsible_body/internet/mobile/manual_requests/confirm.html.erb
..to allow the upgrade to work
There's been a [dependabot PR that upgrades `govuk-components` from 0.4.0 to 0.5.0](https://github.com/DFE-Digital/get-help-with-tech/pull/629) for a while now, but it has a few specs that are failing.
* fix the `govuk_link_to ... do` calls that are failing, by changing them to non-block syntax
* bump the gem version
=> bump govuk-components to 0.5.0, and fix govuk_link_to calls with blocks

app/components/support/user_search_result_component.html.erb, app/components/support/user_search_result_component.rb, app/controllers/support/users_controller.rb, app/form_objects/support/user_search_form.rb, app/models/user.rb, app/views/support/home/show.html.erb, app/views/support/users/results.html.erb, app/views/support/users/search.html.erb, app/webpacker/styles/application.scss, config/locales/en.yml, config/routes.rb, spec/components/support/user_search_result_component_spec.rb, spec/factories/users.rb, spec/features/support/searching_for_school_or_rb_users_spec.rb, spec/models/user_spec.rb, spec/page_objects/support/users/results_page.rb, spec/page_objects/support/users/search_page.rb
When someone writes into the support mailbox, it's not always clear which organisation they belong to. The support agent often needs to figure this out using the sender's signature, email address or domain name.
Add a way for support agents to search for school and responsible body users, by the user's name or email address. This works case-insensitively and partial matches work too.
The search results list the matching users' email addresses and organisations they belong to, including links to the organisations' support pages.
The results are capped to 100 if the search term is too generic and matches too many users.
I'm sure the visual design could use some love.
=> Allow support users to search for school or responsible body users

app/controllers/support/schools/devices/allocation_controller.rb, app/services/allocation_updater.rb, spec/factories/schools.rb, spec/features/computacenter/closed_schools_spec.rb, spec/services/allocation_updater_spec.rb
- https://trello.com/c/bSKwhZUM/966-updating-the-allocation-should-update-cap-if-a-school-can-order
- If a school order state is `can_order` and allocation is updated, the cap is also increased to match the allocation
- Find a school that `can_order`
- Increase/decrease the allocation
- Cap value should match the allocation value entered
- Change school so they `can_order_for specific_circumstances` or `cannot_order`
- Update allocation value
- Cap value should not change and remain the same
=> [966] Match cap with allocation if can order

config/settings/development.yml
We have credentials for Computacenter's dev CapUpdateRequest endpoint, and devs need convenient access to them for testing - but if we put the endpoint URL in to env vars on _our_ dev server, it will start posting spurious unsolicited updates to them, which may not be welcome.  
* add a correct but commented-out value for the endpoint in `config/settings/development.yml`
=> add commented-out dev endpoint for Computacenters CapUpdate API

app/controllers/computacenter/closed_schools_controller.rb, app/views/computacenter/closed_schools/index.html.erb, app/views/computacenter/home/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/computacenter/closed_schools_spec.rb
PR #747 introduced a 'closed schools' report for Computacenter. This PR includes some tweaks some of the functionality and language in this report.
- Temporarily turn off pagination within the report
- It's my hunch that the CC ops team is going to use Ctrl+F to find school caps using the `URN`, `shipTo`, or `soldTo` numbers. Because of pagination, it's very unlikely that the school they're looking for is going to be on the first page and there's currently no other search functionality included.
- I've not actually removed the pagination, I've just made the pages contain 10,000 items. If my hunch is incorrect, then it's easy enough to change this back, or if it's correct, then some of the code can be removed in a subsequent PR.
- Fix an N+1 query problem in the controller (which becomes …
=> Tweaks to the 'closed schools' CC report

app/models/cap_update_call.rb, app/models/school_device_allocation.rb, app/services/school_order_state_and_cap_update_service.rb, db/migrate/20201110103917_create_cap_update_calls.rb, db/schema.rb, spec/services/allocation_updater_spec.rb, spec/services/school_order_state_and_cap_update_service_spec.rb
- https://trello.com/c/GAZWcXlU/972-cap-updates-are-being-logged-our-side-but-cc-dont-have-records
- When making calls to CC we now log the request and response in the DB against the allocation
- This is so we can determine what actually happens when something does not work as expected with evidence 
- Add settings to connect to CC test environment
- Update a cap that would initiate a call to CC
- The request and response should be logged against the allocation record
=> [972] Log Computacenter cap calls to DB

app/views/shared/devices/request_devices.html.erb, spec/features/responsible_body/request_devices_for_specific_circumstances_spec.rb
When a user is part of both a responsible body and a school, and tries to access the 'request devices for specific circumstances' page via the responsible body side of the service, an exception occurs:
https://sentry.io/organizations/dfe-get-help-with-tech/issues/2018379706/?environment=production&project=5320558&query=is%3Aunresolved
This is an edge-case and should be only affecting a small number of users.
Fix the crash
Is this edge case worth a spec? Not sure...
=> Bugfix for crash on the 'request devices for specific circumstances' page

app/views/responsible_body/devices/orders/_place_order_for_schools.html.erb, app/views/school/devices/can_order.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb, app/views/shared/_start_ordering_on_techsource.html.erb, spec/features/responsible_body/ordering_devices_spec.rb
Schools need to know their URN when they order through Computacenter, to make this easier for them we include it in the email and now also on the order page.
=> Show a school’s URN on the order page

app/components/support/school_details_summary_list_component.rb, app/controllers/support/schools/devices/chromebooks_controller.rb, app/views/shared/devices/request_devices.html.erb, app/views/support/schools/devices/chromebooks/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/support/editing_chromebook_details_for_a_school_spec.rb, spec/page_objects/support/school_details_page.rb
In the case that:
1. A school or RB user orders some Chromebooks
2. Post-ordering, Computacenter determine that the school's Chromebook details are missing or wrong
3. They inform the school/RB
4. If the school user writes back into support with their Chromebook details, instead of entering the details into the service
then the support agent has to explain the user to go enter it into the service themselves. This means wasted effort and a delay for the user.
Allow support agents to update Chromebook details (yes/no on whether the school needs Chromebooks, the domain and recovery email), in case they get a ticket with those details.
The wording is a bit off ("when you order", "we", etc) as a result of reusing partials from the RB and school parts of the service, but it felt like a …
=> Enable support users to edit a school's Chromebook details

app/controllers/pages_controller.rb, app/controllers/sign_in_tokens_controller.rb, spec/features/signing_in_as_different_types_of_user_spec.rb
Send users directly to their appropriate home page
In research we've observed signed in users reaching the "Sign in" and "Start" pages again, and unnecessarily going back through the sign in flow.
=> Redirect /start and /sign-in if user is already signed in

app/views/devices_guidance/how_to_order.html.erb, app/views/guide_to_collecting_mobile_information/_guide_contents.html.erb, app/views/pages/about_bt_wifi.html.erb, app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/choosing_help_with_internet_access.html.erb, app/views/pages/how_request_4g_routers.html.erb, app/views/pages/internet_access.html.erb, config/locales/en.yml
- Use breadcrumbs in the Get internet access section
- Simplify some of the longer page titles
=> Make it easier to navigate around connectivity pages

app/views/guide_to_collecting_mobile_information/_guide_contents.html.erb, app/views/guide_to_collecting_mobile_information/asking_for_account_holder.html.erb, app/views/guide_to_collecting_mobile_information/asking_for_network.html.erb, app/views/guide_to_collecting_mobile_information/index.html.erb, app/views/guide_to_collecting_mobile_information/privacy.html.erb, app/views/guide_to_collecting_mobile_information/telling_about_offer.html.erb, config/locales/en.yml
- Add numbers to pages of guide to highlight it's a multi-step process
- Remove references to spreadsheets, users might be recording in spreadsheet or directly (before they had to use the spreadsheet)
- Fix spreadsheet description, it does not need to be returned anywhere
- Don't emphasis "reading out" the privacy statement, a written version could be shared
=> Tweak collecting mobile information guide

app/views/layouts/application.html.erb
[Trello card 1005](https://trello.com/c/VySvmF3N/1005-remove-noindex-tag-from-all-pages), originally part of the checklist on [card 1005](https://trello.com/c/yTAIXkvu/1004-reindex-ghwt-site-on-search) - we need to un-block search engines from the site, and restore the public-facing pages to search engine results.
* remove the `noindex` meta tag from all pages
=> remove NOINDEX tag to restore public pages to Google

app/models/computacenter/responsible_body_urns.rb, app/services/school_to_sat_converter.rb, docs/support/convert_school_to_SAT.md, spec/services/responsible_body_exporter_spec.rb, spec/services/school_data_exporter_spec.rb, spec/services/school_to_sat_converter_spec.rb
[Trello card](https://trello.com/c/yK1dGT8m/999-convert-school-to-sat)
Add ability to convert a non-maintained school into a SAT
Adds `SchoolToSatConverter` that handles the conversion
Add support doc
Handle Trust without `:companies_house_number` in exports to computacenter
Intended to be run from the rails console in support ops.
`SchoolToSatConverter.new(School.find_by(urn: 123456)).convert_to_sat`
This will create a new single academy trust, using the name of the school and move the given school into it.
Trust name and companies house number are optional params to `convert_to_sat`
=> Added SAT converter for schools

app/controllers/devices_guidance_controller.rb, app/views/layouts/application.html.erb, app/views/layouts/multipage_guide.html.erb, config/locales/en.yml, spec/views/layouts/multipage_guide.html.erb_spec.rb
- https://trello.com/c/1uWqx6WZ/1008-apply-noindex-tag-to-specific-page
- Add ability to noindex a specific device guide page via the i18n strings
- visit http://localhost:3000/devices/google-domain-for-care-leavers-and-children-with-social-worker
- should see noindex in the source
- visit another guide page eg http://localhost:3000/devices/enrol-chromebooks-without-user-logins
- should not see noindex in the source
=> [1008] Add noindex to a specific guide page

app/components/support/school_details_summary_list_component.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/support/enabling_orders_for_a_school_spec.rb
- https://trello.com/c/eNgLhIpl/1006-show-mno-requests-per-school-in-support-dont-show-personal-info
- In support when viewing a school show extra mobile data request counts and breakdown
- Find a school with no extra data requests and view the school
- Should see 0 requests
- Find a school with extra data requests - or may have to setup this data
- Should see extra data request counts and breakdown
=> [1006] Support can see mno request counts

app/components/support/school_details_summary_list_component.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/support/enabling_orders_for_a_school_spec.rb
- https://trello.com/c/nlAkop98/1015-show-which-schools-have-get-the-internet-enabled-in-support-while-its-less-than-all-onboarded-schools
- In support dashboard add extra tab for schools in mno rollout
- Enable some schools with `mno_feature_flag` set to `true` on their `School`
- Should see these schools in the dashboard
=> [1015] Add schools in MNO rollout to dashboard

app/views/shared/devices/request_devices.html.erb
Shielding policy is now national, not based on areas. We do not need this evidence.
Originally removed in #762, but we did not need to remove all shielding references and that PR was closed.
=> Remove "if shielding not recommended in your area" text

Makefile, README.md
[Trello card #832](https://trello.com/c/q6ym64rf/832-make-it-much-easier-to-rollback-an-unsuccessful-release)
A recent incident involving a failed release led to a tense period of figuring out the best way to rollback (and in the end rolling forward a null migration), resulting in around 20 mins of total downtime. There was no way to rollback without re-building a new container image.
It would have been much better to have an easy way to re-release a previous version
* add new makefile tasks `timestamp-latest`, `rollback-to`, `push-tag` and `remote-docker-tags`
* add `timestamp-latest` as a dependency of `push` and `push-tag`, so that any future release will automatically 'back-up' the currently-deployed version before replacing it
* add explanatory 'If you need to rollback a release' and …
=> add Makefile tasks to aid rollback of releases, and update the README

config/manifests/dev-manifest.yml, config/manifests/prod-manifest.yml, config/manifests/staging-manifest.yml
The logstash set up has been shipping logs from the GOV.UK PaaS platform & routers to Logit, but not the Rails application logs. As PaaS only keeps the current day's application logs on the container (and even that's only if there are no releases in that period) this causes a problem if we need to look back in the application logs for any reason. 
Most of the configuration needed was already present, it just needed an environment variable (`RAILS_LOG_TO_STDOUT`) setting in all environments. 
Shout out to @saliceti for [this v. useful guide](https://dfedigital.atlassian.net/wiki/spaces/BaT/pages/2045870109/Configuring+Rails+logger+for+GOVUK+PaaS)
=> [1017] enable Rails app logs to be sent to Logit

app/models/computacenter/api/cap_usage_update.rb, app/models/computacenter/devices_ordered_update.rb, app/models/school.rb, db/migrate/20201116150859_create_devices_ordered_updates.rb, db/schema.rb, spec/models/computacenter/api/cap_usage_update_spec.rb
- https://trello.com/c/xdUha5ih/926-fix-number-of-ordered-devices-including-over-orders
- Add a new table and log CC devices ordered updates to this table
- Emulate a incoming CC request to update devices ordered
- Should see this now being logged to new table
=> [926] Log devices ordered updates against school

config/initializers/redirect_incorrect_start.rb, lib/middleware/redirect_incorrect_start.rb
An email was sent out that contained an incorrect link today. Due to the special character we weren't able to fix the redirect in the Rails routes but instead had to make a middleware to match on the path.
The traffic from the email will drop off very quickly so we will revert this PR in a few days.
=> Redirect a specific incorrect start link

app/models/preorder_information.rb, spec/models/preorder_information_spec.rb
We don't have an easy way to analyse when Chromebook details are changed, or whether anyone is changing whether school ordering is devolved or not.
https://trello.com/c/x4uZNNZ0/1042-switch-changing-who-can-order-devices-at-the-school-level-to-a-support-task
Add `paper_trail` to `PreorderInformation` – this will allow to easily track Chromebook detail changes, and `who_will_order_devices` information.
=> Add papertrail to PreorderInformation

app/components/support/school_details_summary_list_component.rb, app/views/support/responsible_bodies/show.html.erb, app/views/support/schools/confirm_invitation.html.erb, app/views/support/schools/show.html.erb, app/webpacker/styles/application.scss
- Make user lists and notifications full width to make content more readable
- Move invite user button to beneath the "Users" heading
- Tweak styling of details to match row height of summary list
- Remove "Devices pilot" caption
(Ignore whitespace when reviewing)
=> Support layout tweaks

app/models/responsible_body.rb, app/models/school_device_allocation.rb, app/models/school_virtual_cap.rb, app/models/virtual_cap_pool.rb, app/models/virtual_cap_pool_error.rb, app/services/feature_flag.rb, db/migrate/20201112160714_create_virtual_cap_pool.rb, db/migrate/20201119110109_add_index_to_virtual_cap_pool.rb, db/schema.rb, spec/factories/responsible_bodies.rb, spec/models/responsible_body_spec.rb, spec/models/school_device_allocation_spec.rb, spec/models/virtual_cap_pool_spec.rb, spec/services/school_order_state_and_cap_update_service_spec.rb
[Trello card](https://trello.com/c/Nj7Thku9/988-virtual-cap-calculate-virtual-cap)
Calculate virtual caps. This is a first iteration of a virtual pool for devices for us to kick about and poke holes in.
Adds `VirtualCapPool` model to hold `:cap` and `:devices_ordered` pooled amounts for specific a `:device_type`
Adds `SchoolVirtualCap` model as a join table between `SchoolDeviceAllocation` and `VirtualCapPool`
Implements accessors for `:cap` and `:devices_ordered` on `SchoolDeviceAllocation` that determine whether to return the pool values or the local object values
'Raw' accessor methods `:raw_cap` and `:raw_devices_ordered` added to access local model values so original values can be accessed when in a pool (e.g. for pool calculation)
Feature flagged using the virtual pool cap and …
=> Initial virtual pool implementation

app/controllers/responsible_body/devices/orders_controller.rb, app/controllers/responsible_body/devices/schools_controller.rb, app/controllers/support/responsible_bodies_controller.rb, app/form_objects/bulk_urn_search_form.rb, app/models/responsible_body.rb, spec/controllers/responsible_body/devices/orders_controller_spec.rb, spec/controllers/responsible_body/devices/schools_controller_spec.rb, spec/controllers/support/responsible_bodies_controller_spec.rb, spec/form_objects/bulk_urn_search_form_spec.rb, spec/models/responsible_body_spec.rb
- https://trello.com/c/XuWAZaBb/1040-hide-closed-schools-on-service
- Hide closed schools from views
- hidden from RB users and support users
- schools can still be accessed directly in url via urn
- but they are hidden from index views and support search
- Login as RB user viewing list of schools
- Close one of the schools
- School should no longer be visible to RB user
- Close a school
- School should no longer be return via urn search
- View the RB of the closed school
- Should no longer see school in list of school for RB
=> [1040] Hide closed schools

app/components/support/school_details_summary_list_component.rb, app/controllers/support/schools/devices/chromebooks_controller.rb, app/policies/chromebook_policy.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/controllers/support/schools/devices/chromebooks_controller_spec.rb, spec/policies/chromebook_policy_spec.rb
CC users need to be able to edit Chromebook details through the support interface.
Authorise Chromebook editing in the support interface for CC users, and show the link on the school details view.
=> Allow Computacenter to edit Chromebook details

app/components/nav_component.rb, app/controllers/computacenter/base_controller.rb, app/views/computacenter/home/show.html.erb, app/views/support/home/schools.html.erb, app/views/support/home/show.html.erb
#809 gave support console access to Computacenter users. However this PR:
- didn't include any links to the support console from the CC area
- still linked to/mentioned some functions that CC users don't have access to
- Add navigation and section links from the CC area to the support area
- Hide some functions in the support area if the user doesn't have those authorisations
**New nav link:**
----
**New 'Support home' section in the Computacenter home screen:**
----
**Support home no longer mentions enabling orders for schools to CC users:**
=> Computacenter Support access: fixes and tweaks

Gemfile.lock
- Revert semantic logger upgrade as seems to be hiding logs at least in dev mode
- This reverts commit 5bd265f19f0095bc461862ad91d7c72edba09fe6.
- Start server in dev mode
- Make some requests
- Should see dev logs and stdout fill up
=> Revert "Bump rails_semantic_logger from 4.4.4 to 4.4.5"

app/components/support/user_search_result_component.html.erb, app/components/support/user_search_result_component.rb, app/controllers/support/users/responsible_bodies_controller.rb, app/controllers/support/users/schools_controller.rb, app/controllers/support/users_controller.rb, app/form_objects/support/new_user_school_form.rb, app/form_objects/support/user_responsible_body_form.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/support/users/associated_organisations.html.erb, app/views/support/users/responsible_bodies/index.html.erb, app/views/support/users/results.html.erb, app/views/support/users/schools/index.html.erb, config/locales/en.yml, config/routes.rb, spec/components/support/user_search_result_component_spec.rb, spec/features/support/changing_a_users_associated_organisations_spec.rb, spec/page_objects/support/users/associated_organisations_page.rb, spec/page_objects/support/users/matching_responsible_bodies_page.rb, spec/page_objects/support/users/matching_schools_page.rb, spec/policies/user_policy_spec.rb
[Trello card 1021](https://trello.com/c/swcEUVuq/1021-allow-support-to-move-users-between-schools-and-or-rbs) - requests to change users' associated organisations are fairly regular now, and each time the support team member has to ask a dev to do it for them from the console.
* add UI to allow support users to make those changes themselves
This was very much a 'whatever works' UI, with more of an eye on speed of implementation rather than elegance. As such, it could really do with a checkover from @fofr or @ralph-hawkins 
Screenshots:
**Point of entry - new 'Change' link on (existing) user search results**
**New page - users' associated organisations**
**New page - finding a school to associate**
**New page - finding a responsible body to associate**
=> add facility for support users to move users between schools and RBs

app/models/school_device_allocation.rb, app/models/school_virtual_cap.rb, app/models/virtual_cap_pool.rb, db/migrate/20201120145136_add_allocation_to_virtual_pool.rb, db/schema.rb, spec/models/responsible_body_spec.rb, spec/models/school_device_allocation_spec.rb, spec/models/virtual_cap_pool_spec.rb
Add `:allocation` to virtual cap pool. This could help smooth out any potential issues with validations and devices_ordered appearing as being greater than the allocation at school level.
Add allocation to `VirtualCapPool`
Provide `allocation` accessor for `SchoolDeviceAllocation` that determines which value to use (pool/local) and is FeatureFlag-ged with `:virtual_caps`
Added unique constraint to ensure there is only one virtual cap pool per `device_type` for a responsible body (as suggested by @aldavidson in the previous PR).
Added an additional check so that a school must also be centrally managed to be added to a pool
=> add allocation to virtual cap pool

app/views/support/service_performance/_mno_rollout.html.erb, spec/features/support/viewing_service_performance_spec.rb
- https://trello.com/c/i4gRgvIv/1063-show-which-schools-are-making-mno-requests-on-dashboard-page
- Add request count per school to mno rollout dashboard 
- Enable a school with feature flag `mno_feature_flag`
- Make that school make mno requests
- Should see mno rollout dashboard updated with request count
=> [1063] Add request count to mno rollout dashboard

README.md
- README lacking on how to setup dummy data and first user to be able to login and start developing the service
- Updated readme
- Follow new readme steps
- Should end up `ResponsibleBody` and `School` data
- Also a new user can use to log in to the user service
=> Update README with how to setup dummy data

app/views/support/service_performance/_mno_rollout.html.erb
- Replace space with `nbsp`
- Under MNO rollout dashboard make a school or RB have a super long name
- Requests should never span over 2 lines
=> [1063] Fix request count spanning over 2 lines

app/controllers/support/performance_data/schools_controller.rb, spec/controllers/support/performance_data/schools_controller_spec.rb
The API at `/support/performance-data/schools.json` has so far only been showing `std_device` allocations/caps/devices_ordered numbers.
The analysts have requested the addition of `coms_device` numbers too. In [this slack thread]() we discussed implementation, and agreed on adding a simple prefix of `coms_` to the coms_device numbers.
Add coms_device numbers to the API
=> [1087] add coms_ numbers to support/performance_data API

app/helpers/view_helper.rb, app/views/shared/_techsource_unavailable_banner.html.erb, app/views/techsource_launcher/unavailable.html.erb, spec/controllers/techsource_launcher_controller_spec.rb, spec/features/techsource_availability_for_responsible_body_spec.rb, spec/features/techsource_availability_for_school_spec.rb
> Please be aware that there is a planned maintenance slot for the TechSource Ordering Portal on Saturday 28th November 2020 from 07:00 to 23:00 GMT, for the purposes of the deployment of the latest release.
Update the dates to reflect the maintenance window on Saturday.
Please check that the dates are correct.
=> [1032] Update TechSource unavailable banner to reflect upcoming maintenance window

app/models/data_stage/responsible_body.rb, app/models/data_stage/school.rb, app/services/school_update_service.rb, docs/support/add_missing_school.md
There is operational documentation on how to add missing schools from the data staging area into the main `schools` table.
Refactor some existing code to simplify/eliminate certain steps in the documentation, as a stepping stone to automating them with service objects.
Does it make sense for `DataStage::School` to be aware of `School`, even if it's just an association?
=> Improvements to the process of adding missing schools

app/controllers/support/responsible_bodies/users_controller.rb, app/mailers/invite_existing_user_to_responsible_body_mailer.rb, app/services/create_user_service.rb, config/locales/en.yml, config/settings.yml, spec/services/create_user_service_spec.rb
[Trello card 1071](https://trello.com/c/WQSvtsY2/1071-support-add-a-user-form-cant-add-an-existing-user-to-a-new-school) - although it was possible to add an existing user to an additional school, it was not possible to add an existing user to a Responsible Body.
* allow an existing user to be added to a Responsible Body from the support UI, as along as they are not already associated with a Responsible Body
* add a new email template (content approved by @emmajhf )
* if the entered email address _is_ already a Responsible Body user, show a more meaningful error message 
* go to Support > Support Home > Responsible Bodies
* click on a Responsible Body
* click on 'Invite user'
* enter an email address that already exists as a non-RB user - this should work
* enter an email address that …
=> [1071] allow existing non-RB-users to be invited to an RB

app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/devices/schools/index.html.erb, config/locales/en.yml, spec/features/responsible_body/devices_setup_spec.rb, spec/features/responsible_body/ordering_devices_spec.rb
Update to match https://ghwt-design-history.herokuapp.com/rbs-ordering-for-groups-of-schools/#simplified-schools-list
- ‘Get schools ready’ and ‘17 schools’ has been consolidated into a single title
- Title updated from ‘Get schools ready’ to 'List of schools' and an updated ‘use this section’ list
https://trello.com/c/MaiG7Jha/1084-virtual-cap-update-schools-list-page
https://trello.com/c/vsHiB2yY/1085-virtual-cap-update-get-laptops-and-tablets-page
=> Simplify schools list page

app/controllers/support/performance_data/schools_controller.rb, app/models/school_device_allocation.rb, spec/controllers/support/performance_data/schools_controller_spec.rb
[Trello card 1094](https://trello.com/c/IxhghLAA/1094-performance-data-api-now-takes-7min-to-render-and-download) - The `/support/support/performance-data/schools.json` endpoint has become unsustainably slow since the release of the [virtual cap pool work](https://github.com/DFE-Digital/get-help-with-tech/pull/843) and [expanding the endpoint's dataset to also include comms devices](https://github.com/DFE-Digital/get-help-with-tech/pull/860). It's now taking almost 7 minutes to render and stream the response on production. 
* re-implement the endpoint in raw SQL, to optimise query performance
* use `connection.select_all` to return the records. `select_all` returns results from the database as an array of Hashes, thus removing the need to instantiate ActiveRecord objects.
Results from …
=> [1094] re-do schools performance data endpoint in raw SQL, for huge speedup

app/models/computacenter/cap_change_notifier.rb, app/models/school_device_allocation.rb, app/models/school_virtual_cap.rb, app/models/virtual_cap_pool.rb, app/services/school_order_state_and_cap_update_service.rb, app/views/computacenter/outgoing_api/base/cap_update_request.xml.builder, spec/models/school_device_allocation_spec.rb, spec/models/virtual_cap_pool_spec.rb, spec/services/school_order_state_and_cap_update_service_spec.rb
[Trello card](https://trello.com/c/1mHZtH0E/990-virtual-cap-sending-virtual-cap-to-cc) Notify Computacenter of changes to caps in the virtual cap pool
Refactored Computacenter cap notifications out of `SchoolOrderStateAndCapUpdateService` and into a module
Added cap notifications for all ordering schools in the pool when changes occur to the VirtualCapPool
Added `computacenter_cap` accessor for `SchoolDeviceAllocation` and referenced this in the XML builder that constructs the payload for the Computacenter API.  When in a virtual cap pool this calculates the schools cap based on the available devices in the pool plus the local devices_ordered for that allocation. When not in a virtual pool this just returns the local cap.
School's are added to the pool as part of being enabled for …
=> Virtual pool caps for cc

config/initializers/assets_cache_header.rb
This commit adds cache headers to our assets so that a users browser does
not have to download the assets on every page refresh when the assets
have not changed.
Opening the preview app and looking at the network tab all our assets should have a cache-control response header
=> assets should be cached

app/models/responsible_body.rb, app/models/school_device_allocation.rb, db/migrate/20201130111700_add_vcap_feature_flag_to_responsible_body.rb, db/schema.rb, spec/factories/responsible_bodies.rb, spec/models/responsible_body_spec.rb, spec/models/school_device_allocation_spec.rb
Like the MNO offer, we would like to roll out virtual caps in small batches of RBs so that we limit the risk of the rollout. In addition to the global virtual cap feature flag we're adding a per-RB flag.
1. By default, all trusts are excluded from the virtual cap rollout, even if the global feature flag is enabled.
2. Only use the `SchoolVirtualCap` and `VirtualCapPool` is the global feature is on and the individual RB flag is enabled.
1. Find school
2. Toggle global virtual cap feature on: no change to cap/allocation/device_ordered
3. Toggle `vcap_feature_flag` enabled on its RB: virtual cap enabled for all the schools within that RB that are eligible
=> [1080] Add ability to flag specific RBs to have virtual cap enabled

app/views/responsible_body/devices/schools/show.html.erb, spec/features/responsible_body/ordering_via_a_school_spec.rb
[Trello card 1083](https://trello.com/c/2mIHtMV8/1083-virtual-cap-update-school-page) - as part of the [Virtual Cap Pools epic](https://trello.com/c/Blj9SZ65/1007-virtual-cap), we need to update the Responsible Body school page according to the [updated design](https://ghwt-design-history.herokuapp.com/rbs-ordering-for-groups-of-schools/#simplified-school-page).
* When the `virtual_caps` feature flag is enabled AND the current responsible body has the `vcap_feature_flag` attribute set to true, remove the panel which would normally show how many devices have been ordered from their cap.
This is because we cannot accurately know the numbers per school if the school is part of a pool, so we need to defer to a central place for ordering.  
* set the `:virtual_caps` feature flag to `'active'` …
=> [1083] replace devices ordered panel with 'Order devices now' link when VCaps are enabled

app/components/responsible_body/school_details_summary_list_component.rb, spec/features/responsible_body/ordering_via_a_school_spec.rb
Following on from [this Slack thread](https://ukgovernmentdfe.slack.com/archives/C01A7DVKE9J/p1606824548032000), another instance of 'Devices ordered' not catered for in the previous PR #877
Don't show the 'Devices ordered' line in the `ResponsibleBody::SchoolDetailsSummaryListComponent` if the Responsible Body has virtual caps enabled
Before:
After:
=> remove Devices ordered line from school details if RB has VirtualCaps enabled

.dockerignore
While building a Docker image locally, I encountered an error saying that node sass lacked a binding for the current environment.
On investigation, it's because [the asset precompilation stage is using the node_modules copied from the host](https://github.com/sass/node-sass/issues/2165), which may or may not be compatible with the 64-bit Alpine linux environment within the container. 
This isn't typically a problem when the container is built on CI, because that's run in a fresh container and there are no existing node_modules. But it could prevent a developer building the container locally (as it did with me).
Add node_modules to .dockerignore, so they are not copied into the container
`make dev build` should now work
=> [1096] fix local docker build, by ignoring local node_modules

app/services/school_order_state_and_cap_update_service.rb, spec/services/school_order_state_and_cap_update_service_spec.rb
@jamesrose found a wrongly named method that wasn't being exercised in the tests but was found locally as he had the virtual caps feature flag enabled.
Rename method from `is_in_virtual_pool?` to `is_in_virtual_cap_pool?` and added test that hits this.
=> Fix wrongly named virtual cap query method

spec/factories/schools.rb
When performing full test runs, we occasionally get collisions in the randomly-generated URNs for schools. These make the test run fail with an error like:
```
ActiveRecord::RecordNotUnique:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_schools_on_urn"
DETAIL:  Key (urn)=(441405) already exists.
```
Although we've always been able to successfully re-run the workflow, this is still a source of frustration and lost time.
Make schools URNs unique
Difficult to prove that you've fixed an intermittent PRNG collision..... :man_shrugging:
=> make FactoryBot school URNs unique in tests

spec/services/responsible_body_exporter_spec.rb, spec/services/school_data_exporter_spec.rb
While investigating [intermittent ActiveRecord::RecordNotUnique errors in our test suite](https://trello.com/c/KIkSSDVf/1122-fix-intermittent-duplicate-key-spec-failures), I isolated the problem down to test data leaking, specifically two examples which created their data in `around` hooks. 
This is outside of the per-test transaction scope, so DatabaseCleaner's `:transaction` strategy is unable to roll it back, and the record persists into all subsequent examples.
This can occasionally cause a unique constraint violation even on values created with Faker::(type).unique, as Faker does not
use the database for existence checking.
* restructure the two `around` hooks as `before`/`after` pairs
=> [1122] Fix intermittent duplicate-key spec failures

app/components/responsible_body/pooled_device_count_component.html.erb, app/components/responsible_body/pooled_device_count_component.rb, app/concerns/device_count.rb, app/concerns/device_type.rb, app/controllers/responsible_body/devices/orders_controller.rb, app/helpers/view_helper.rb, app/models/responsible_body.rb, app/models/school_device_allocation.rb, app/models/virtual_cap_pool.rb, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, app/views/responsible_body/devices/orders/order_devices.html.erb, spec/components/responsible_body/pooled_device_count_component_spec.rb, spec/features/responsible_body/ordering_devices_in_pool_spec.rb, spec/features/responsible_body/ordering_devices_spec.rb, spec/helpers/view_helper_spec.rb, spec/models/responsible_body_spec.rb, spec/models/virtual_cap_pool_spec.rb
Trello ticket: https://trello.com/c/VxiaDLtN/1082-virtual-cap-update-ordered-devices-page
Prototype page: https://ghwt-prototype.herokuapp.com/responsible-body/devices/order-lockdown
- Add a new 'Order devices' page for responsible bodies that are ordering centrally and are in the virtual cap feature
- This page shows regardless of whether RB has schools ordering for specific circumstances or not. We have added copy to explain where their device counts come from in each case: schools closed, schools with specific circumstances and a mix of both.
- Nothing should change for RBs ordering centrally outside of the feature.
To make sure nothing has changed with existing functionality:
1. Log in as RB ordering centrally
2. Set a school to `can_order`
3. Existing 'Order devices' page should be …
=> Update 'Order devices' page for virtual cap RBs

app/mailers/can_order_devices_mailer.rb, app/models/school_can_order_devices_notifications.rb, app/models/user_can_order_devices_notifications.rb, config/settings.yml, spec/mailers/can_order_devices_mailer_spec.rb, spec/models/school_can_order_devices_notifications_spec.rb, spec/models/user_can_order_devices_notifications_spec.rb
Trello: https://trello.com/c/HyeLDn5U/1102-virtual-caps-update-automatic-email-which-is-sent-when-a-trust-ordering-centrally-is-invited-to-order-when-a-school-reports-disr
> We currently send an automated email out when we raise the cap for a school having reported disruption. This sends a generic message inviting them to order which is the same for both schools ordering directly and trusts ordering on behalf of schools. 
> When we implement virtual caps we will no longer know if that school has received their allocation of devices only how many are remaining within the trusts 'virtual cap' as a result we need to adapt our communications for trusts ordering centrally to reflect this. 
Use a different email template when the RB of a school ready to order is ordering centrally _and_ in the …
=> Send different invite email when a RB ordering centrally is using virtual caps

app/components/responsible_body/pooled_device_count_component.rb, app/components/school_preorder_status_tag_component.rb, app/controllers/support/responsible_bodies_controller.rb, app/helpers/view_helper.rb, app/models/responsible_body.rb, app/models/virtual_cap_pool.rb, app/views/support/responsible_bodies/show.html.erb, config/locales/en.yml, spec/components/school_preorder_status_tag_component_spec.rb, spec/features/support/viewing_responsible_body_info_spec.rb, spec/helpers/view_helper_spec.rb, spec/models/responsible_body_spec.rb, spec/models/virtual_cap_pool_spec.rb, spec/page_objects/support/responsible_body_page.rb
Trello: https://trello.com/c/az8uLtni/1076-update-admin-app-for-virtual-caps
1. Update support area to show details of any centrally managed schools and virtual cap data
2. Hide cap and devices ordered data for schools within the virtual cap
1. Find RB without virtual cap enabled
2. Centrally managed section should not show
3. Table should show all data fields: allocation, cap and devices ordered
With 1 school in virtual cap:
1. Enable virtual cap and find RB
2. Add school to virtual cap
3. Centrally managed section should show with v-cap devices ordered and available, and a '1 of 2 schools' are centrally managed message
4. School within virtual cap should not show cap and devices ordered in table
With all schools in virtual cap:
1. Enable virtual cap and find RB
2. Add both schools to …
=> Update support responsible body page for virtual caps

app/components/conditional_school_preorder_status_tag_component.html.erb, app/components/conditional_school_preorder_status_tag_component.rb, app/components/display_allocations_component.html.erb, app/components/display_allocations_component.rb, app/components/responsible_body/school_details_summary_list_component.rb, app/controllers/responsible_body/devices/schools_controller.rb, app/views/responsible_body/devices/schools/_school_states_table.html.erb, app/views/responsible_body/devices/schools/index.html.erb, config/locales/en.yml, db/schema.rb, spec/components/display_allocations_component_spec.rb, spec/controllers/responsible_body/devices/schools_controller_spec.rb, spec/features/responsible_body/devices_setup_spec.rb, spec/features/responsible_body/ordering_devices_in_pool_spec.rb, spec/features/responsible_body/ordering_devices_spec.rb, spec/features/responsible_body/viewing_your_schools_spec.rb, spec/page_objects/responsible_body/schools_page.rb
[Trello card](https://trello.com/c/Gvsyoype/1108-virtual-cap-update-your-schools-page)
Update list of schools page for responsible body to support virtual caps.
Updated school list page to new content, 3 separate lists to split schools by order state.
Only show statuses for schools that are not ready to order or additionally, that have ordered in the case of devolved schools
Available devices pooled summary card only visible when responsible body orders centrally and feature flags for virtual caps enabled.
As a RB user, where the RB manages centrally, with a mix of schools that can order/can_order_for_specific_circumstances and cannot order. From the Responsible Body home page visit the Get laptops and tablets -> Your Schools links. You should then see a list of schools divided into 3 …
=> 1108 virtual cap update your schools page

app/components/responsible_body/school_details_summary_list_component.rb, app/models/school.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/models/school_spec.rb
Trello: https://trello.com/c/x4uZNNZ0/1042-switch-changing-who-can-order-devices-at-the-school-level-to-a-support-task
It is currently a developer task to back out of using virtual caps. We need to at least hide the link in the UI that allows RBs to change who will order when it is enabled.
Hide 'Change' link for RBs using virtual caps
1. Find RB using virtual caps and managing centrally
2. Navigate to school page
3. You should not see the 'Change' link for 'Who can order?'
---
1. Find RB with devolved ordering
2. Navigate to school page
3. You should see the 'Change' link for 'Who can order?'
=> Hide 'Who will order?' change link to RBs using virtual caps

app/views/devices_guidance/how_to_order.html.erb, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, app/views/responsible_body/devices/orders/specific_circumstances.html.erb, app/views/responsible_body/devices/schools/order_devices.html.erb, app/views/school/devices/can_order.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb
https://trello.com/c/oBmUnDoy/1101-update-delivery-content-to-reflect-new-approach-to-large-orders
Computacenter is starting to process large orders and have difficulty doing this within the 48 hours SLA and have experienced issues with schools accepting such large deliveries at short notice. As a result, they are adopting a new approach to fulfilling large orders. 
From the 7th December, where an order is placed on TechSource for 150 or more devices Computacenter will:
- Telephone the delivery contact to arrange delivery via a specialist courier
- Confirm via a ZenDesk email the date of the delivery, we will also explain that the courier link in the dispatch email will not work.
Everywhere delivery timeline is mentioned it's updated from '5 working days'  to '2 working days'. On the …
=> Updates delivery message

app/views/support/responsible_bodies/show.html.erb
Makes it clearer what this number means.
After Kate Thompson spoke to first-line it wasn't clear if 'available' meant 'available to order right now' (the sum of the allocation to schools who have reported disruption) or sum of all the schools had access to their allocation.
Add 'right now' to 'available to order'.
=> Adds 'right now' to 'available to order'

app/components/responsible_body/pooled_device_count_component.html.erb, app/components/responsible_body/pooled_device_count_component.rb, app/views/responsible_body/devices/schools/index.html.erb, spec/components/responsible_body/pooled_device_count_component_spec.rb, spec/features/responsible_body/viewing_your_schools_spec.rb
I missed the action functionality of the pooled device count component that I build as part of https://trello.com/c/VxiaDLtN/1082-virtual-cap-update-ordered-devices-page. The action is used on the schools page that was build as part of https://trello.com/c/Gvsyoype/1108-virtual-cap-update-your-schools-page
1. Add link to 'Order devices' for RBs that can order now within a virtual cap.
2. It takes you back to the previous page so that you can click through to order via TechSource.
=> Add 'Order devices' link to 'Your Schools' page when within the virtual pool

app/services/create_user_service.rb, spec/services/create_user_service_spec.rb
[Trello card 1115](https://trello.com/c/LXl2jWPJ/1115-devolve-ordering-to-schools-where-trust-decision-is-still-outstanding) - It's possible for a user to be invited to a school before their Responsible Body has made a decision on whether ordering will be central or devolved. As we've had several (> 200) RBs that have still not made a decision despite several 'nudge' emails, and there have been schools which needed devices but were unable to order them because of this, we've decided to let the schools go ahead and order.
However, if the RB has not made a decision, the school will have no `PreorderInformation` record, and this can cause the user journey to end in an error message if they choose to order Chromebooks and go as far as trying to enter the Chromebook domain information.
The fix …
=> [1115] When adding a school user, devolve ordering to schools if the RB has not decided

app/views/responsible_body/devices/orders/_place_order_for_schools.html.erb, app/views/responsible_body/devices/schools/_school_states_table.html.erb, app/webpacker/styles/application.scss
On the schools summary page for responsible bodies, we show multiple tables. If 1 some schools a table have a status and others don't, the tables are misaligned making them harder to read.
Add classes with percentage widths and add them all columns.
Before:
After:
=> makes table columns specified widths

app/models/virtual_cap_pool.rb, spec/models/virtual_cap_pool_spec.rb
Prevent the VirtualCapPool from generating Cap update API requests unless the total `:cap` or `:devices_ordered` has changed.
Check whether the `cap` or `devices_ordered` will be modified in `#recalculate_caps!` and only send notification if one or both have changed.
You may need to set the `GHWT__COMPUTACENTER__OUTGOING_API__ENDPOINT` env var to point to a dummy service to see the cap updates being generated.  Copy the following into a file and run it from the command line and set the env var to point to `http://localhost:8000`:
```ruby
require 'webrick'
​
server = WEBrick::HTTPServer.new Port: 8000
​
trap 'INT' do server.shutdown end
​
server.mount_proc '/' do |req, res|
res.body = '<CapAdjustmentResponse dateTime="2020-09-14T21:55:37Z" …
```
=> Prevent changes that don't affect cap or devices_ordered from generating cap updates

app/components/support/user_search_result_component.html.erb, app/components/support/user_search_result_component.rb, app/controllers/support/users_controller.rb, spec/components/support/user_search_result_component_spec.rb, spec/features/support/searching_for_school_or_rb_users_spec.rb
[Trello card 1077](https://trello.com/c/Bs8B6yIR/1077-support-find-rb-or-school-users-doesnt-return-users-with-no-associations) - At the moment it's possible for support users to remove all associated schools or responsible bodies from a user, but then be unable to find them again in order to re-associate them. 
Remove the restriction on the user search which limited it to only users already associated with a school or responsible body.
Support home > Find responsible body or school users 
Fill in a search term - there is no minimum length, so you can submit something like '@'. 
The search should:
* return the first 100 users matching the term, whether or not they have a responsible body / school
* respond quickly, even when searching the whole database (I've tested this locally against …
=> [1077] Extend support user search to include users with no associated schools or RBs

app/components/responsible_body/next_school_link_component.html.erb, app/components/responsible_body/next_school_link_component.rb, app/controllers/responsible_body/devices/chromebook_information_controller.rb, app/controllers/responsible_body/devices/schools_controller.rb, app/controllers/responsible_body/devices/who_to_contact_controller.rb, app/models/responsible_body.rb, app/views/responsible_body/devices/chromebook_information/edit.html.erb, app/views/responsible_body/devices/schools/index.html.erb, app/views/responsible_body/devices/schools/show.html.erb, app/views/responsible_body/devices/who_to_contact/new.html.erb, spec/controllers/responsible_body/devices/schools_controller_spec.rb, spec/features/responsible_body/devices_setup_spec.rb
A proposed alternative to #906 - please see that PR for @ralph-hawkins ' v. thorough explanation of the problem, and [this slack thread](https://ukgovernmentdfe.slack.com/archives/C01A7DVKE9J/p1607441294239600?thread_ts=1607440654.234200&cid=C01A7DVKE9J) for the team discussion in which this alternative version is proposed.
Make the 'go to next school' links consistent with the schools being grouped by order state.
These links are present in several places -
```
app/views/responsible_body/devices/chromebook_information/edit.html.erb
app/views/responsible_body/devices/schools/index.html.erb
app/views/responsible_body/devices/schools/show.html.erb
app/views/responsible_body/devices/who_to_contact/new.html.erb
```
- so I abstracted the logic into a new ViewComponent called …
=> Make 'go to next school' link consistent with schools grouped by status

Gemfile, Gemfile.lock, app/components/notification_banner.rb, app/services/feature_flag.rb, app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb, config/locales/en.yml, db/migrate/20201210140102_add_increased_allocations_feature_flag.rb, db/schema.rb, spec/views/responsible_body/home/show.html.erb_spec.rb, spec/views/school/home/show.html.erb_spec.rb
Card: https://trello.com/c/EGYSK7OO/1141-add-notification-banner-for-schools-and-rbs-telling-them-that-allocations-have-increased-also-show-no-xmas-ordering-banner-%F0%9F%8E%84-%F0%9F%8E%85
Add two global feature flags:
- christmas_banner
- increased_allocations_banner
The Christmas banner feature places a message on both RB and school pages.
The 'Increased allocations' banner places a message on the RB side, and adds a similar message to the school side _if_ the school itself _also_ has `increased_allocations_feature_flag` enabled.
RB (both features enabled):
School (Christmas only)
School (plus Increased allocations)
=> Increased allocation and Christmas messaging

app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb, app/views/shared/banners/_responsible_body.html.erb, app/views/shared/banners/_school.html.erb, app/views/support/responsible_bodies/show.html.erb, app/views/support/schools/show.html.erb, spec/views/support/responsible_bodies/show.html.erb_spec.rb, spec/views/support/schools/show.html.erb_spec.rb
- https://trello.com/c/EGYSK7OO/1141-add-notification-banner-for-schools-and-rbs-telling-them-that-allocations-have-increased-also-show-no-xmas-ordering-banner-%F0%9F%8E%84-%F0%9F%8E%85
- Support agents see banners that school or responsible body users would see
- Log in as support staff
- Enable/disable feature toggles
- See banners accordingly
=> [1141] Banners for support agents

app/models/responsible_body.rb, app/views/shared/banners/_responsible_body.html.erb, spec/models/responsible_body_spec.rb, spec/views/responsible_body/home/show.html.erb_spec.rb, spec/views/support/responsible_bodies/show.html.erb_spec.rb
An extension of https://trello.com/c/EGYSK7OO/1141-add-notification-banner-for-schools-and-rbs-telling-them-that-allocations-have-increased-also-show-no-xmas-ordering-banner-%F0%9F%8E%84-%F0%9F%8E%85
We previously decided to show this generic messaging to RBs regardless of whether they had their allocations increased. This ensures that they have at least one school where allocations were increased.
RB level messaging should only show when 1) the global feature flag is enabled, and 2) It has at least one school where we've increased allocations and toggled its flag.
=> Hide 'Increased allocations' banner at RB level when it has no schools that were increased

app/policies/dfe_policy.rb, spec/controllers/computacenter/responsible_body_changes_controller_spec.rb
#876 introduced an interface for adding sold_to and ship_to numbers to responsible bodies and schools that don't have them. That PR had a bug whereby trying to add a sold_to number to `DfE`, a special responsible body (used for test devices) failed.
Authorise Computacenter users to add a ship_to number to `DfE`.
=> Allow soldTo number to be added to DfE by adding Pundit policy

app/models/computacenter/responsible_body_urns.rb, spec/factories/responsible_bodies.rb, spec/features/computacenter/responsible_body_changes_spec.rb
#876 introduced the functionality to allow CC users to assign sold_to numbers to responsible bodies. We don't want this to be done for RBs which don't manage any schools, and there's quite of few of these in production.
Filter out RBs without schools when identifying 'changed RBs' for CC's benefit.
Also refactor the responsible body FactoryBot factory, to make the local authority and trust factories work much more consistently.
=> Don't try getting 'Sold To' numbers for RBs without schools

app/services/school_order_state_and_cap_update_service.rb, spec/services/school_order_state_and_cap_update_service_spec.rb
The code that guards against updates being handled only in the virtual cap pool is not considering the `:vcap_feature_flag` only the FeatureFlag :virtual_caps. This resulted in cap updates not being sent when a school that was in the virtual pool but was in a non ordering state, being enabled for ordering again.
Use both guard flags on code block.
Assume a means to observe cap update requests e.g. dummy api service
Given a school in a virtual pool with the `order_state: :cannot_order`
Change allocation and enable ordering via the `SchoolOrderStateAndCapUpdateService`.
Caps update requests should be seen when enabling a school to order.
=> Fix cap update issue

app/models/computacenter/cap_change_notifier.rb, app/services/school_order_state_and_cap_update_service.rb, db/migrate/20201214114914_add_failure_to_cap_update_calls.rb, db/schema.rb, spec/models/school_device_allocation_spec.rb, spec/models/virtual_cap_pool_spec.rb, spec/services/school_order_state_and_cap_update_service_spec.rb
Previously we were only creating a `CapUpdateCall` record once a cap update was successfully received. This PR adds a new `failure` column that will toggle on when we receive an error from CC.
=> Create CapUpdateCall records even when the cap update requests fails

app/components/school/school_details_summary_list_component.rb, app/controllers/support/schools/devices/allocation_controller.rb, app/views/support/responsible_bodies/show.html.erb, spec/components/school/school_details_summary_list_component_spec.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/support/adjusting_a_schools_allocation_spec.rb, spec/features/support/viewing_responsible_body_info_spec.rb
[Trello card](https://trello.com/c/azJIAHqC/1150-amend-allocation-on-support-console-for-schools-in-virtual-cap)
Schools are shown with virtual pool allocation amounts not individual allocation amounts in support interface
Use `raw_allocation` instead of `allocation` when displaying the allocation value for a school.
As a support user, whether a school is in a virtual pool or not, the allocation displayed in the support interface should be local school value not the aggregated pool value.
=> Use raw_allocation instead of allocation

app/models/school_device_allocation.rb, app/views/support/schools/devices/allocation/edit.html.erb, spec/models/school_device_allocation_spec.rb
1. When a school within a virtual pool has its state changed, we shouldn't imply the cap on the school allocation using the v-cap devices_ordered or allocation number.
2. Show raw allocation number on allocation edit screen
---
The tests are a duplicate of the previous cap_implied_by_order_state ones except the school is within a virtual cap with 2x the allocation.
=> Use raw allocation numbers when implying cap from order state

app/models/virtual_cap_pool.rb, app/services/school_order_state_and_cap_update_service.rb, spec/features/responsible_body/viewing_your_schools_spec.rb, spec/models/virtual_cap_pool_spec.rb
[Trello card](https://trello.com/c/CX6BQRF4/1153-allow-schools-that-cannot-order-in-virtual-cap)
Currently, one of the requirements for a school to be added to a virtual cap pool is that they are in an ordering state (`can_order` or `can_order_for_specific_circumstances`). This PR removes this requirement so taht schools in any order state can be added to their responsible body's virtual cap pool.
Remove order state from eligibility criteria
Given a responsible body that centrally manages and a centrally managed school that is not in an ordering state, you should be able to add the school to the responsible body's virtual cap pool with `responsible_body.add_school_to_virtual_cap_pool!(school)`
=> Allow schools in any order state to be added to virtual pools

app/controllers/application_controller.rb, app/controllers/responsible_body/internet/mobile/extra_data_requests_controller.rb, app/models/responsible_body.rb, app/views/responsible_body/home/show.html.erb, app/views/responsible_body/internet/home/_bt_wifi_offer.html.erb, app/views/responsible_body/internet/home/_extra_mobile_data_offer.html.erb, app/views/responsible_body/internet/home/show.html.erb, app/views/school/internet/home/show.html.erb, app/views/shared/internet/_mno_information.html.erb, config/locales/en.yml, spec/controllers/responsible_body/internet/mobile/extra_data_requests_controller_spec.rb, spec/features/responsible_body/home_spec.rb, spec/features/responsible_body/submitting_a_spreadsheet_request_spec.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb
First part of enabling MNO for RBs:
- Remove guidance on closed pilots for all users
- Show MNO feature for RBs when:
- feature flag enabled
- managing at least one school centrally
- are in connectivity pilot
- Rename internet page to "Get internet access"
https://trello.com/c/2WdDchuS/1138-mno-rb-journey-build-the-responsible-body-home-page
https://ghwt-design-history.herokuapp.com/mno-for-rbs/
=> Set up RB home page and internet pages for MNO offer

config/initializers/webmock.rb
[Trello card](https://trello.com/c/zTfOX6I9/1131-fix-intermittent-build-error-on-assetpackpath) - we've had a long-standing intermittent build failure, of this form:
```
Failure/Error: <%= tag :meta, property: 'og:image', content: asset_pack_path('media/images/govuk-opengraph-image.png') %>
ActionView::Template::Error:
784: unexpected token at ''
```
I haven't yet found the root cause, but I _have_ found someone else reporting the [same problem on Stack Overflow](https://stackoverflow.com/questions/58621271/actionviewtemplateerror-785-unexpected-token-at), and that it was [fixed with an initializer for Webmock](https://stackoverflow.com/a/59049650). I'm not totally sure that's the source of our error, but there's no harm in giving it a try
* add a test-only initializer that allows Webmock …
=> [1131] - add webmock initializer that allows localhost only

app/controllers/computacenter/multi_domain_chromebooks_controller.rb, app/models/computacenter/outgoing_api/cap_update_request.rb, app/models/responsible_body.rb, app/models/school.rb, app/views/computacenter/home/show.html.erb, app/views/computacenter/multi_domain_chromebooks/index.html.erb, app/views/computacenter/outgoing_api/base/cap_update_request.xml.builder, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, config/locales/en.yml, config/routes.rb, spec/features/responsible_body/ordering_devices_in_pool_spec.rb, spec/models/computacenter/outgoing_api/cap_update_request_spec.rb, spec/models/responsible_body_spec.rb
[Trello card](https://trello.com/c/JFczhXmY/1097-virtual-cap-force-the-orders-of-trusts-that-qualify-for-virtual-cap-and-have-multiple-chromebook-domains-into-the-techsource-man)
Handling of ordering of Chromebooks where multiple G Suite domains exist for responsible bodies managing centrally in virtual pools.  In these circumstances. when a responsible body places an order at TechSource, the order needs to be forced into a manual process in order to resolve which domain should be used for Chromebooks.
Provide an interface for CC to view (and download as CSV) which responsible bodies that manage centrally and have multiple chromebook domains.
Add additional copy to the "Order devices" page to inform the users that TechSource will be in touch.
During sending cap updates to CC, if the …
=> 1097 virtual cap force handle multiple chromebook domains

app/controllers/support/users_controller.rb, spec/controllers/support/users_controller_spec.rb, spec/factories/users.rb
The user search in the support console returns deleted users.
Hide deleted users from support console search results.
=> Don't return deleted users in the support console user search

app/views/support/users/associated_organisations.html.erb
This makes the navigation more consistent with the user editing page.
=> Change the breadcrumb to a back link on the 'Associated orgs' page

app/jobs/notify_mnos_job.rb, app/mailers/mno_mailer.rb, app/models/email_audit.rb, app/models/mobile_network.rb, app/models/user.rb, config/settings.yml, config/sidekiq.yml, spec/jobs/notify_mnos_job_spec.rb, spec/mailers/mno_mailer_spec.rb
- https://trello.com/c/TprR7Aph/1107-build-automatic-notification-for-mnos-when-they-receive-a-request
- Notify MNO users if they have new requests
- Emails are sent every weekday at 8am
- Ensure there is an MobileNetwork with a user
- Create a request for this mno
- Trigger job
- User should see email
=> [1107] Notify MNOs if there are new requests

app/services/feature_flag.rb, app/views/responsible_body/devices/orders/cannot_order_yet.html.erb, app/views/school/devices/cannot_order.html.erb, config/locales/en.yml, spec/features/responsible_body/ordering_devices_spec.rb, spec/features/school/order_devices_spec.rb
Ordering will be closed over Christmas. During this period a different order page is shown.
This PR assumes that all schools and RBs will be placed into the cannot order state during the festive period.
(Best reviewed by ignoring whitespace)
=> Add "Cannot order over Christmas" page

app/views/shared/banners/_responsible_body.html.erb, app/views/shared/banners/_school.html.erb, config/locales/en.yml
Let schools know when deliveries will run to.
=> Append content about deliveries to xmas banner

config/locales/en.yml
We were missing this Slack/event translation for virtual cap emails.
=> Add missing event translation

spec/factories/responsible_bodies.rb, spec/rails_helper.rb
`spec/features/computacenter/responsible_body_changes_spec.rb` has been failing intermittently on CI because it relies on the RB name being unique.
Change the Faker settings (used by the spec factories) to generate unique RB names within the context of a given spec.
=> Attempt to prevent intermittent spec failures by making RB names unique

app/models/batch_job.rb, app/models/batch_job_log_entry.rb, db/migrate/20201215120852_add_batch_job_log_entries.rb, db/migrate/20201216144840_add_indexes_to_batch_job_log_entries.rb, db/schema.rb, spec/models/batch_job_log_entry_spec.rb, spec/models/batch_job_spec.rb
See [Trello card](https://trello.com/c/QuI2b5kR/1168-spike-an-easier-way-of-batch-processing) for full context.
When running arbitrary ad-hoc code from the console (for instance, to raise allocations for a selection of schools) we often end up re-writing basic code to handle errors, report success & failures, etc. This is wasteful and error-prone, and means that our actual processing code is more difficult to debug.
* Add `BatchJob` and `BatchJobLogEntry` classes.
This is a first iteration to handle the basic error handling and status reporting for running an arbitrary block against a series of records.  
Use it as follows:
```
job = BatchJob.new(job_name: 'some helpful name to identify this job', records: [ ... ]
job.process! do |record|
end
```
Each new instance of `BatchJob` gets a …
=> [1168] spike an easier way of batch processing

app/controllers/support/users_controller.rb, spec/controllers/support/users_controller_spec.rb
Deleted users are filtered out in support search and various user lists, but it's still possible to get to the edit pages if you know the user's id.
Change the user management functionality to return 404 when they're applied to deleted users.
=> Don't allow support operations on deleted users

app/controllers/support/users_controller.rb, app/policies/user_policy.rb, app/views/support/users/confirm_destroy.html.erb, app/views/support/users/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/support/deleting_a_user_spec.rb, spec/policies/user_policy_spec.rb
Currently, deletion of a user in the support console happens immediately, as soon as a support agent clicks the button. Since this interaction is fairly rare and can only be undone by a developer, it's desirable to add a bit of friction to make sure it's really intended.
- Introduce an interstitial confirmation page prior to deletion.
- Add a feature spec covering the deletion scenario
The designs are analogous to [course deletion in Publish Teacher Training Courses](https://bat-design-history.netlify.app/publish-teacher-training-courses/deleting-and-withdrawing/).
=> Confirm when deleting a user in the support console

Gemfile, Gemfile.lock, app/form_objects/support/new_user_school_form.rb, app/models/school.rb, spec/form_objects/support/new_user_school_form_spec.rb, spec/models/school_spec.rb
The support console allows support agents to grant school access to users. When the agent types in part of a school name (or a school URN), the system returns schools that match the provided search term.
There's an ambition to extend this functionality to a more generalised schools auto-complete, to use in other places in the support console and in the user support form. This technical change is a step towards realising this ambition.
1. Introduce an upper limit to how many results the school suggest returns. A user can hit this limit if they enter a very short or common search term (e.g. `St`). Returning more than 50 suggestions isn't a useful user interaction – in that case, the user should refine their search.
2. Improve the quality of matched results by switching to the [`pg_search` …
=> School search: backend improvements

app/views/layouts/application.html.erb, app/webpacker/packs/mno/extra-mobile-data-requests.js
This has many benefits and follows good practices
- No need to use jquery `.ready()` method because the dom would be loaded
before the browser starts downloading the js and executing it.
- It will also help improve perceived performance by loading up and displaying
the content so the users gets to see the content first while the js is
being downloaded and executed.
=> Load JavaScript after the DOM has loaded

app/views/mno/extra_mobile_data_requests/index.html.erb
This issue would only have been picked up if javascript was disabled or failed to load.
The url being generated looked like this http://localhost:3000/mno/extra-mobile-data-requests?class%5B%5D=govuk-link&select=none.
As the css class was being rendered in the href, the links themselves
were not correctly styled.
=> Fix fallback all/none links for extra mno requests

app/views/mno/extra_mobile_data_requests/_extra_mobile_data_request.html.erb, app/views/mno/extra_mobile_data_requests/index.html.erb, app/webpacker/packs/application.js, app/webpacker/packs/mno/extra-mobile-data-requests.js, app/webpacker/packs/mno/extra-mobile-data-requests.test.js, config/webpack/environment.js, package.json, yarn.lock
This was in desperate need of being a refactor for the following reasons:
- jQuery: This relied on jQuery and seemed a bit of overkill to import and include it on every page. It also seemed to be included twice.
jQuery is no longer a dependency for this code to work.
- would only work for a single instance of this component. It now supports
multiple components
- The js was not scoped to just the component in question. For example,
when the page has loaded, any element that had a class of `js-only` or `non-js-only` would be
hidden/shown regardless of what our intentions were for those elements
when the page loaded.
- There was a lot of additional markup added just to add the feature.
The markup has now been cleaned up.
- No unit tests
I analyzed the bundles locally before & after the …
=> Refactor select all/none js functionality & remove jQuery

app/form_objects/support_ticket/academy_details_form.rb, app/form_objects/support_ticket/check_your_request_form.rb, app/form_objects/support_ticket/college_details_form.rb, app/form_objects/support_ticket/contact_details_form.rb, app/form_objects/support_ticket/describe_yourself_form.rb, app/form_objects/support_ticket/local_authority_details_form.rb, app/form_objects/support_ticket/school_details_form.rb, app/form_objects/support_ticket/support_details_form.rb, app/form_objects/support_ticket/support_needs_form.rb, spec/form_objects/support_ticket/academy_details_form_spec.rb, spec/form_objects/support_ticket/college_details_form_spec.rb, spec/form_objects/support_ticket/contact_details_form_spec.rb, spec/form_objects/support_ticket/describe_yourself_form_spec.rb, spec/form_objects/support_ticket/local_authority_details_form_spec.rb, spec/form_objects/support_ticket/school_details_form_spec.rb, spec/form_objects/support_ticket/support_details_form_spec.rb, spec/form_objects/support_ticket/support_needs_form_spec.rb
The breakup of #889 into smaller PR, these new form objects are not being used in the service at the moment as the views/controllers, etc will be part of another PR. If you want to view the user journey you can see it by visiting https://dfe-ghwt-pr-889.herokuapp.com/get-support
The form objects will be used by the form builder. We do not want to
store the user's query in the service which is why it's not using 
traditional ActiveModel implementation to store it in a database table.
=> [286] Add form objects needed for get support flow

app/models/computacenter/user_change_generator.rb, spec/models/computacenter/user_change_generator_spec.rb
Please see [Trello card 1190](https://trello.com/c/h1JfNld4/1190-investigate-issue-with-user-being-repeatedly-added-to-removed-from-techsource) for the full explanation - it's complex, so here I will just summarize as: we're incorrectly generating Add-type `UserChange` records for users who have been soft-deleted 
* fix the loophole in the logic, by adding a check on `user.soft_deleted?` to the `is_addition?`method in `Computacenter::UserChangeGenerator`
=> fix erronous generation of Add-type UserChanges for soft-deleted users

app/views/devices_guidance/how_to_order.html.erb, spec/views/devices_guidance/how_to_order.html.erb_spec.rb
Schools closed for mass testing can order their device allocation.
Adds a banner (as used to notify schools about Christmas ordering closure) to say schools closed for testing can order their device allocation on the how to order page.
Set 'secondary_mass_testing_banner' feature flag to active and visit devices/how-to-order.
=> adds banner for when schools closed for mass testing  can order

app/controllers/support/users/schools_controller.rb, app/policies/user_policy.rb, app/views/support/users/schools/index.html.erb, config/locales/en.yml, config/routes.rb, spec/features/support/changing_a_users_associated_organisations_spec.rb, spec/page_objects/support/users/schools_page.rb, spec/policies/user_policy_spec.rb
The support console allows removing and adding new schools for users of the system.
Streamline the design of the user's 'update schools' page by:
- not surfacing information that's unnecessary to removing a school, like the responsible body and the type of school (since support requests almost always mention the name of the school from which the user needs to be removed)
- allowing bulk removal (by unticking multiple schools), instead of having to do it one button at a time
**Before:**
**After:**
=> Support console: streamline the design of the user's 'update schools' page

app/controllers/support/users/responsible_body_controller.rb, app/form_objects/support/user_responsible_body_form.rb, app/views/support/users/responsible_body/edit.html.erb, app/webpacker/scripts/responsible-bodies-autocomplete.js, spec/features/support/changing_a_users_associated_organisations_spec.rb
The support console allows removing and adding new schools for users of the system.
Apply the same interaction patterns for:
- adding
- updating
- removing a user's responsible body
as are present in the school-user-facing parts of the app.
**Before:**
**After:**
**Before:**
**After:**
=> Support console: streamline the editing a user's responsible body

app/models/computacenter/outgoing_api/cap_update_request.rb, spec/models/computacenter/outgoing_api/cap_update_request_spec.rb
This change reverses the bulk of https://github.com/DFE-Digital/get-help-with-tech/pull/927 but leaves the reporting side of the change. The frequency of orders is making the process difficult on CC's side.
Some more context in [Slack](https://ukgovernmentdfe.slack.com/archives/C01A7DVKE9J/p1609862977045400)
=> Don't lower caps in RBs with multiple Chromebook domains

Gemfile, Gemfile.lock, README.md, app/controllers/support_ticket/check_your_request_controller.rb, app/form_objects/support_ticket/check_your_request_form.rb, app/services/zendesk_service.rb, config/settings.yml, spec/controllers/support_ticket/check_your_request_controller_spec.rb, spec/form_objects/support_ticket/check_your_request_form_spec.rb, spec/services/zendesk_service_spec.rb
Integrate Zendesk into the service so that we are able to log zendesk tickets through our service instead of users having to send us emails.
Before merging this PR, two new environment vars for zendesk username & token will be added to the production instance for API calls to work. We plan on testing get support forms and this integration before soft-launching it across the service.
=> [286] Add zendesk integration

app/form_objects/school_search_form.rb, spec/form_objects/school_search_form_spec.rb
[Trello card #1224](https://trello.com/c/vJ14NTGR/1224-exception-on-support-schools-search) - When in the support school search, if you searched by particular URNs and then clicked 'Download allocations as CSV' (new behaviour in #970), [an error was being thrown](https://sentry.io/organizations/dfe-get-help-with-tech/issues/2132906815/?environment=production&project=5320558&referrer=alert_email)
Fix the error, and add a test for this case
=> [1224] fix error when downloading a CSV of allocations for specified URNs

app/controllers/application_controller.rb, app/controllers/devices_guidance_controller.rb, app/controllers/guide_to_collecting_mobile_information_controller.rb, app/controllers/landing_pages_controller.rb, app/controllers/pages_controller.rb, app/views/devices_guidance/how_to_order.html.erb, app/views/layouts/application.html.erb, app/views/shared/banners/_global_notice_banner.html.erb
The banner should only be shown on specific public pages.
Eg.
- Home page
- all second level content pages
- all guidance pages
Should not display at all if the user is signed in (ie they are not a
parent/carer/pupil) or the user is on the following pages
- Cookie policy page
- Privacy policy page
- Accessibility statement page
- Sign in page
- Visit https://dfe-ghwt-pr-1048.herokuapp.com/ and visit a few pages within the service
- https://dfe-ghwt-pr-1048.herokuapp.com/start (no notification banner)
- https://dfe-ghwt-pr-1048.herokuapp.com/sign-in (no notification banner)
- https://dfe-ghwt-pr-1048.herokuapp.com/token/email-not-recognised (no notification banner)
-
=> Adds a parent/carer notice banner to public pages

config/manifests/prod-manifest.yml
Our traffic is up by well over 500% this week. Our response times are suffering, and our web instances are sometimes timing out when the PaaS healthcheck tries to hit the `healthcheck.json` endpoint. As a result, PaaS restarts the instances - which leads to more congestion on the remaining instance, etc etc 
Scale out by adding 2 more instances to the web process
=> add 2 more web instances to prod

app/views/layouts/application.html.erb, app/views/pages/home_page.html.erb
**DO NOT MERGE** - This PR needs to be reviewed and only merged in once the get support form has been tested by the team and we are confident in releasing the feature to our users.
- Adds a link to the get support form on the home page
- Adds a link to the get support form in the services footer
visit https://dfe-ghwt-pr-1035.herokuapp.com/ and you should see the links and the pages (You can go through the journey but it will not actually create zendesk ticket)
=> [286] Soft launch the get support form 

spec/rails_helper.rb
This reverts commit b44bacdede020f28c35dc98274bc149288e47afd.
Rails 6.1.1 has fixed this issue.
=> Revert "Work-around for the incompatibility between rspec-rails 4.0.2 and Rails 6.1"

config/environments/development.rb
This workaround was causing duplicate STDOUT entries on local
development.
Remove the workaround.
Timeline how this happened:
- rails_semantic_logger 4.4.5 introduced a regression with broke
logging to STDOUT in dev
- we put in a workaround to the problem in 1351601c8c73ded115b886d01740c2bbcc0715e1
- rails_semantic_logger 4.4.6 fixed the issue (https://github.com/rocketjob/rails_semantic_logger/commit/c3b906661c132e5a72db2deacde36f6d0cf815b2)
and when we upgraded in 18e2f0bcb805c3e1b4a09933b0d98d9f099d4f67 we
started seeming duplicate log entries
=> Remove workaround for rails_semantic_logger bug

app/views/responsible_body/devices/home/show.html.erb, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, app/views/responsible_body/devices/schools/index.html.erb, app/views/school/devices/can_order.html.erb, app/views/school/home/show.html.erb, app/views/school/welcome_wizard/techsource_account.html.erb, app/views/school/welcome_wizard/what_happens_next.html.erb, app/views/shared/_school_user_welcome_text.html.erb, config/locales/en.yml, spec/features/responsible_body/devices_setup_spec.rb, spec/features/responsible_body/viewing_your_schools_spec.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/page_objects/responsible_body/schools_page.rb
This essentially applies designs for push/proactive ordering:
https://ghwt-design-history.herokuapp.com/push/
https://github.com/DFE-Digital/get-help-with-tech-prototype/pull/28
Schools list:
=> Schools can order because of lockdown, update designs

app/form_objects/support_ticket/check_your_request_form.rb, spec/form_objects/support_ticket/check_your_request_form_spec.rb
When a ticket is created we build up the subject based on the options
a user selects from the get support contact form.
The subject seems to be formatted correctly for all users where they have
selected school, LA, a multi-academy trust, college but not when
"I'm none of the above" has been chosen. The subject was being created
as "ONLINE FORM -". This commit now makes sure that the subject is set to
"ONLINE FORM - Other"
=> Fix zendesk ticket subject output

app/views/pages/how_request_4g_routers.html.erb, app/views/shared/internet/_mno_information.html.erb
We're adding support for FE and need to add clarity on how this affects connectivity policy
- children in years 3 to 13 can have access to 4g routers, the guidance currently says 3 to 11
- children in years 3 to 11 can have access to MNO, but the guidance isn't explicit which years have access
Changes 'years 3 to 11' to 'years 3 to 13' in 4g router guidance.
Adds 'in years 3 to 11' to a description of what the MNO is for.
=> connectivity policy clarification

app/form_objects/support_ticket/check_your_request_form.rb, spec/form_objects/support_ticket/check_your_request_form_spec.rb
I attempted to fix the initial issue with the email subject being set as
"ONLINE FORM -" but what I hadn't realised was that we were setting the
user_type to the option key and not the label value which the user sees.
=> Fix email subject

app/webpacker/scripts/responsible-bodies-autocomplete.js
Support agents can search for schools in the support console by providing the responsible body. Currently this page element is a select box with > 1000 entries, which isn't very easy to use.
Progressively enhance the select box with an autocomplete.
=> Support console: add responsible body autocomplete to school search

Makefile, config/environments/production.rb, config/settings/production.yml, spec/features/static_asset_cache_headers_spec.rb
See [Trello card 1242](https://trello.com/c/Q0lJyeVV/1242-improve-our-use-of-caching-and-cloudfront) and [Trello card 1270](https://trello.com/c/sUYcBBYo/1270-fix-issue-with-cloudfront-not-caching-anything) - Cloudfront is currently forwarding _all_ headers to our app, which means that it's not actually caching anything. 
Change the Makefile task `setup_cdn_route` to forward just the set of headers that we know our application needs - 
`"Content-Type", "Host", "Set-Cookie", "X-Forwarded-Host", "Authorization"`
Note that this just changes the Makefile task, which by itself will not change anything until it is manually run.
We can (and should) run the task in a low-traffic period and manually test that all the header-sensitive points - authentication, API authentication, sessions, CSV …
=> 1270 fix issue with cloudfront not caching anything

app/controllers/support/users/schools_controller.rb, app/form_objects/support/school_suggestion_form.rb, app/views/support/users/schools/index.html.erb, app/views/support/users/schools/new.html.erb, app/views/support/users/schools/search_again.html.erb, app/webpacker/packs/application.js, spec/controllers/support/users/schools_controller_spec.rb, spec/features/support/changing_a_users_associated_organisations_spec.rb, spec/form_objects/support/school_suggestion_form_spec.rb, spec/page_objects/support/users/matching_schools_page.rb
Support agents can grant access to schools to existing users via the support console.
- Avoid showing the interstitial 'choose a school' page if the support agent picks a single school from the auto-complete or enters an exact name or URN match
- Strip down the 'choose a school' interstitial page and make searching again easier
- Add validation if the support agent inadvertently enters a school name that's too short (to avoid returning thousands of results)
https://user-images.githubusercontent.com/23801/103926416-cddbe900-5110-11eb-9b2c-5ce7e219d334.mp4
https://user-images.githubusercontent.com/23801/103926397-c61c4480-5110-11eb-8af3-1c91f8d80654.mp4
=> Support console: redesign the 'add school to a user' flow

app/models/user.rb, app/services/feature_flag.rb, app/services/interstitial_picker.rb, app/views/interstitials/_default.html.erb, app/views/interstitials/_increased_sixth_form_allocation.html.erb, app/views/interstitials/_school_user.html.erb, app/views/sign_in_tokens/click_to_sign_in.html.erb, spec/services/interstitial_picker_spec.rb
- https://trello.com/c/ThIADjmi/1251-increase-allocation-for-schools-with-sixth-form-students
- There is a click to sign in page after clicking the email link to login
- We want to use this page to show an interstitial page instead with context specific content
- Login as any user, experience should not be different
- Login as school user, same experience, should see extra text with list
- Login as school with sixth form that can order devices, should now see repurposed interstitial page
- Feature should only work when feature flag enabled
=> [1251] Click to sign in now an interstitial page

app/views/devices_guidance/4g_user_guidance.md, app/views/devices_guidance/device_distribution_and_ownership.md, app/views/devices_guidance/enrol_chromebooks_with_user_logins.md, app/views/devices_guidance/enrol_chromebooks_without_user_logins.md, app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/preparing_4g_wireless_routers.md, app/views/devices_guidance/preparing_chromebooks.md, app/views/devices_guidance/preparing_ipads.md, app/views/devices_guidance/preparing_microsoft_windows_laptops_and_tablets.md, app/views/devices_guidance/replace_a_faulty_device.md, app/views/devices_guidance/support_and_maintenance.md, app/views/landing_pages/digital_platforms.md, app/views/sign_in_tokens/email_not_recognised.html.erb
We are starting to roll out the new contact form. This doesn't cover all
references to the email address but it is a start. There are instances where we tag the email
subject with a particular reference and to ensure that we don't break any
zendesk macros/process, it was decided that we wouldn't touch this for the
time being. It might be better if we focus on building forms for those
pages where we can validate the information and then create specific
zendesk tickets from those requests.
- Replaces the majority of references to the email address with a link to our support start page
- Removes a few references to the SLA as its mentioned on the support start page
- There are none only 4 references to the SLA (1x Accessibility page, 2 x get support start page and 1 x "Thank you" page after …
=> Replace reference to the email address with link to contact form

app/models/school_device_allocation.rb, app/validators/cap_and_allocation_validator.rb, db/schema.rb, spec/models/school_device_allocation_spec.rb
[Trello card](https://trello.com/c/MUrYMTgO/1272-fix-device-allocation-validations)
Observed that _somehow_ in 30 instances `cap` is greater than `allocation` on the `SchoolDeviceAllocation` models. Attempting to fix this at the console proved difficult because the validators were preventing the updates to the local model while validating the broken virtual pool figures.  We don't need to do this. If we ensure that the device allocations are correct then the pool will also be correct.
Use the `raw_` cap and allocation values in the validators.
Attempting to make a cap > allocation update in a `SchoolDeviceModel` should fail with a validation error.
=> Use raw cap and allocation in validation

app/controllers/application_controller.rb
There's an intermittent, hard-to-reproduce issue where users with a valid session are v. occasionally seeing a 403 Forbidden page with a different users email address at the top. 
We need to capture more information in the logs to get to the cause.
Add a few non-personally-identifying tags to each controller log message to help us if it happens again.
I've tested this on staging, and the extra fields come through to Kibana fine (see screenshot)
=> [1277] add request_id, session id and user id to each controller log message

app/jobs/delete_old_sessions_job.rb, config/sidekiq.yml, spec/jobs/delete_old_sessions_job_spec.rb
While investigating [Trello card 1277](https://trello.com/c/uIDcEmGH/1277-mno-bug-for-providers), I found that there are many old sessions way still in the DB, way past their expiry - there has been no mechanism for clearing them. 
Add a job to run on the hour, every hour, to purge old sessions from the DB
=> add DeleteOldSessionsJob

config/initializers/pagination.rb, spec/features/mno/extra_mobile_data_requests_spec.rb
https://trello.com/c/0mRLaWzh/1286-mno-bulk-update-page-limit-of-requests-from-20-to-100
20 per page is not enough. MNOs have asked for more results per page so they can bulk update more at once.
Increase from 20 to 100.
=> Increase MNO pagination to 100 items

app/controllers/support_ticket/academy_details_controller.rb, app/controllers/support_ticket/base_controller.rb, app/controllers/support_ticket/check_your_request_controller.rb, app/controllers/support_ticket/college_details_controller.rb, app/controllers/support_ticket/contact_details_controller.rb, app/controllers/support_ticket/describe_yourself_controller.rb, app/controllers/support_ticket/local_authority_details_controller.rb, app/controllers/support_ticket/school_details_controller.rb, app/controllers/support_ticket/support_details_controller.rb, app/controllers/support_ticket/support_needs_controller.rb, spec/controllers/support_ticket/academy_details_controller_spec.rb, spec/controllers/support_ticket/check_your_request_controller_spec.rb, spec/controllers/support_ticket/college_details_controller_spec.rb, spec/controllers/support_ticket/contact_details_controller_spec.rb, spec/controllers/support_ticket/describe_yourself_controller_spec.rb, spec/controllers/support_ticket/local_authority_details_controller_spec.rb, spec/controllers/support_ticket/school_details_controller_spec.rb, spec/controllers/support_ticket/support_details_controller_spec.rb, spec/controllers/support_ticket/support_needs_controller_spec.rb
Issue https://sentry.io/organizations/dfe-get-help-with-tech/issues/2138267573/?project=5320558
I managed to replicate this error by going through the full "Get support" journey right up to the point where a zendesk ticket is created. After
I saw the "Thank you" page, I clicked on the browser back button and saw
this error.
What happens is as a user goes through the get support wizard we store the
form data in session (`session[:support_ticket]`) but once the zendesk api
has been used we clear the session. So using the back button or trying to
access other parts of the wizard may raise similar issues.
The solution I came up with is to add a `before_action` across all the
controllers which check if the `session[:support_ticket]` is present. if
it's not then we redirect the user back to the …
=> Fix issue where users use browser back buttons

app/models/computacenter/user_change_generator.rb, spec/models/user_spec.rb
See [Trello card 1275 - Multiple user changes with the same timestamp](https://trello.com/c/mKBnxiOK/1275-multiple-userchanges-being-generated-with-the-same-user-timestamp). Computacenter have reported an issue with receiving multiple userchanges for the same user, each of which has the same timestamp. This appears to be the code acting as designed - it currently uses the `user.updated_at` as the timestamp` - but it makes it difficult for them to see what the latest state is meant to be, when several changes are committed at once.
The original behaviour made sense when UserChange records were only triggered by updating the user record, but since then we've refactored and expanded functionality, to the point where they can be generated as a result of moving schools between …
=> make UserChange records use now as the timestamp, rather than user.updated_at

app/services/feature_flag.rb, app/services/interstitial_picker.rb, app/views/interstitials/_increased_fe_allocation.html.erb, app/views/school/details/show.html.erb, app/views/school/welcome_wizard/allocation.html.erb, app/views/school/welcome_wizard/what_happens_next.html.erb, app/views/shared/_school_without_allocation.html.erb, db/migrate/20210112164816_add_allocation_feature_flags_to_schools.rb, db/schema.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/services/interstitial_picker_spec.rb
- https://trello.com/c/TX4JVPVh/1280-interstitial-sign-in-page-for-fe-providers-who-are-already-using-the-service
- https://trello.com/c/ThIADjmi/1251-increase-allocation-for-schools-with-sixth-form-students
- My understanding is that there are 2 feature flags `increased_sixth_form_feature_flag` and `increased_fe_feature_flag`
- Depending on which is enabled for the school they get different interstitial screens
- It's implemented so if the user has both conditions it shows the sixth form version page
- There is then some conditional content in other places so if either condition is met then this is shown
- I have removed the global feature flag as it doesn't seem like its needed
- Enable feature `increased_sixth_form_feature_flag` for a school
- Ensure this school can order devices
- …
=> [1280] Increased allocations interstitials

app/views/responsible_body/devices/orders/cannot_order_yet.html.erb, app/views/school/devices/cannot_order.html.erb, config/locales/en.yml, spec/features/responsible_body/ordering_devices_spec.rb, spec/features/school/order_devices_spec.rb
A few schools, recently added, cannot order yet because we are waiting on data from Computacenter.
For these schools, tell them that ordering will be enabled ASAP.
=> Remove Jan 13 date, update to ASAP

app/services/session_service.rb
See [Trello card #1277 - MNO bug for providers](https://trello.com/c/uIDcEmGH/1277-mno-bug-for-providers). We've been seeing an occasional issue where a user who has a genuine valid session sometimes gets a 403 Forbidden page with another users' email address in the header. 
After much investigation, we found the potential culprit - the `SessionService.identify_user!` method is incorrectly using an instance variable in a class-scoped method. This is a potential race condition, as the class SessionService will be shared amongst the workers in the Puma threadpool.
It's conceivable that just occasionally, two threads are running this code with an offset of about 2 lines each.
- thread 1 reads current_user from user 1 's session, and sets `@current_user` to `User.find(1)`
- thread 2 reads …
=> [1277] fix race condition in SessionService

app/models/virtual_cap_pool.rb, spec/models/virtual_cap_pool_spec.rb
We allowed schools of any state to be added to virtual pools in https://github.com/DFE-Digital/get-help-with-tech/pull/945 Following that, this PR sends updates to CC for all schools within a pool regardless of their status.
=> Send virtual cap updates regardless of school status

app/models/extra_mobile_data_request.rb, spec/models/extra_mobile_data_request_spec.rb
PR https://github.com/DFE-Digital/get-help-with-tech/pull/1118 tightened up validation of device phone numbers so that some phone numbers (numbers starting with `07xxx` but which weren't mobile numbers) suddenly became invalid.
Because the validation triggered for updates as well, an MNO user wasn't able to update a request with an invalid phone number:
https://sentry.io/organizations/dfe-get-help-with-tech/issues/2154600108/?environment=production&project=5320558
Changes the device phone number validation to only fire on create.
=> Allow MNO requests with invalid phone numbers to be updated

app/controllers/responsible_body/internet/mobile/bulk_requests_controller.rb, spec/controllers/responsible_body/internet/mobile/bulk_requests_controller_spec.rb, spec/controllers/school/internet/mobile/bulk_requests_controller_spec.rb
A user reported seeing a 'missing translation' error when uploading an MNO requests spreadsheet that couldn't be processed.
There was an i18n string that was being used in two similar controllers. One controller was updated and the string moved, but I forgot to update the other controller, so users are seeing a 'missing translation' error.
I've added spec coverage around both controllers to prevent this from regressing in future.
=> Fix missing translation when a MNO request spreadsheet cannot be processed

app/models/extra_mobile_data_request.rb, app/models/extra_mobile_data_request_row.rb, app/presenters/extra_mobile_data_request_presenter.rb, spec/models/extra_mobile_data_request_row_spec.rb, spec/models/extra_mobile_data_request_spec.rb
School and responsible body users can upload MNO requests in an XLSX spreadsheet. Currently, if there's an unexpected value in the 'Pay monthly or PAYG', the entire upload fails, instead of just skipping the problematic line.
https://trello.com/c/axgYg1oL
Ensure that just the single row fails when the value in the 'Pay monthly or PAYG' is unexpected.
Refactor the mechanism of how errors are fed back to the user, so it just bubbles up the errors from the `ExtraMobileDataRequest` model directly.
=> Fix MNO request bulk upload crash when the contract type column contains an unexpected value

app/components/support/school_details_summary_list_component.rb, app/controllers/school/internet/mobile/bulk_requests_controller.rb, app/controllers/school/internet/mobile/extra_data_requests_controller.rb, app/controllers/school/internet/mobile/manual_requests_controller.rb, app/models/school.rb, app/views/school/home/show.html.erb, app/views/school/internet/home/show.html.erb, db/migrate/20210115140815_add_hide_mno_to_schools.rb, db/schema.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/controllers/school/internet/mobile/bulk_requests_controller_spec.rb, spec/controllers/school/internet/mobile/extra_data_requests_controller_spec.rb, spec/controllers/school/internet/mobile/manual_requests_controller_spec.rb
- https://trello.com/c/8lpCnlCn/1317-hide-mno
- We need to hide mno from certain schools
- We have a list of schools to hide mno from
- This list was determined by GIAS data where `StatutoryLowAge` was 16 or higher
- We currently do not have this data in our system so this is a stop gap implementation until we import this data 
- Login as a school with the `hide_mno` `true`
- Navigate to and `/schools/URN` and `/schools/URN/internet`
- Should not see references to MNO but should see 4G routers
=> [1317] Hide mno from certain schools

app/views/layouts/_service_link.html.erb, config/manifests/dev-manifest.yml, config/manifests/staging-manifest.yml, config/settings.yml, config/settings/development.yml, db/schema.rb
[Trello card 1314](https://trello.com/c/DY7lYtAT/1314-setup-staging-with-a-custom-domain) - we should have staging as prod-like as possible, which should include serving on a custom domain via Cloudfront.
The domain `staging-get-help-with-tech.education.gov.uk` has already been set up & validated (necessarily outside of this epo) and mapped to staging. I've tested it in a browser, but it's still sending emails with links pointing to the existing direct-to-paas URL 
* configure staging to use the new education.gov.uk subdomain as its main domain for links in emails
* to help reduce any user confusion between staging & prod, add a '(dev)' or '(staging)' suffix to the main header service name, only in those environments
=> make staging serve requests on custom domain

app/services/interstitial_picker.rb
- https://trello.com/c/ThIADjmi/1251-increase-allocation-for-schools-with-sixth-form-students
- User research has finished
- We now only show these interstitial screens if those school can order at the moment on login
- No new tests are it should already be covered, the commented out code loosened the requirement
- Login as a school with feature flag enabled but cannot order right now
- Should not see screen
- Login as a school with feature flag enabled AND can order right now
- Should see screen
=> [1251] Only show FE/6th form screens if can order

app/components/extra_mobile_data_request_status_component.html.erb, app/components/extra_mobile_data_request_status_component.rb, app/helpers/application_helper.rb, app/views/mno/extra_mobile_data_requests/_extra_mobile_data_request.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb, app/views/shared/_extra_mobile_data_request_status.html.erb, spec/components/extra_mobile_data_request_status_component_spec.rb
We show the status of MNO requests in 3 different places (MNO area, school are and RB area).
Extract an ExtraMobileDataRequestStatusComponent view component. This will make it easier to change the code, to test it and better follows our current patterns.
=> Extract an ExtraMobileDataRequestStatusComponent view component

app/models/computacenter/responsible_body_urns.rb, app/models/further_education_school.rb, spec/models/computacenter/responsible_body_urns_spec.rb
- https://trello.com/c/R2235yoT/1075-spike-adding-fe-institutions-to-the-service
- Prefix RB with `FE` to match CC
- This will match spreadsheets provided to CC
- Turns outs School does not need `computacenter_identifier` as a remnant of a previous spike as URN/UKPRN are used instead
n/a
=> [1075] Finalise CC IDs/references

app/components/extra_mobile_data_request_status_component.rb, app/controllers/mno/extra_mobile_data_requests_controller.rb, app/models/extra_mobile_data_request.rb, app/services/extra_mobile_data_request_status_migration_service.rb, app/views/mno/extra_mobile_data_requests/_extra_mobile_data_request.html.erb, app/views/mno/extra_mobile_data_requests/report_problem.html.erb, config/locales/en.yml, spec/components/extra_mobile_data_request_status_component_spec.rb, spec/controllers/mno/extra_mobile_data_requests_controller_spec.rb, spec/services/extra_mobile_data_request_status_migration_service_spec.rb
MNO requests currently have a `queried` status, and a separate `problem` attribute for storing the specific nature of the problem.
MNO users would like to be able to bulk-update requests with specific problems.
Trello: https://trello.com/c/5R2cI9PT
Introduce additional statuses on `ExtraMobileDataRequest`, which correspond to the existing 5 problem types.
Update the 'report a problem' form to use these problem types.
Make the new statuses appear in the bulk-change drop-down on the requests table.
=> Add problem statuses for MNO requests

app/controllers/mno/extra_mobile_data_requests_controller.rb, spec/controllers/mno/extra_mobile_data_requests_controller_spec.rb
- https://trello.com/c/ks3uY0pJ/1291-mno-bulk-update-correctly-handle-processing-when-no-request-is-selected
- If no requests are selected supply an empty collection so it duck types
- Login as mno user
- Make sure there are some requests
- Do not select any requests in the checkboxes
- Hit update
- Should not see error
- No records should be updated
=> [1291] Suppress MNO bulk update error

app/components/responsible_body/pooled_device_count_component.rb, app/controllers/responsible_body/devices/orders_controller.rb, app/views/responsible_body/devices/orders/cannot_order_anymore.html.erb, spec/components/responsible_body/pooled_device_count_component_spec.rb, spec/features/responsible_body/ordering_devices_in_pool_spec.rb, spec/features/responsible_body/viewing_your_schools_spec.rb
Follows the design history created by @fofr in https://github.com/DFE-Digital/get-help-with-tech-prototype/pull/33
Trello card: https://trello.com/c/E5WSVEwO/1226-build-design-for-when-rbs-have-ordered-all-devices
Show a new page when an RB using virtual caps has no more devices to order. Previously it would show the default 'Can order devices' page with links to TechSource.
This change brings the RB v-cap ordering journey inline with a similar page to one that schools see when ordering has been devolved to them.
1. Open 'Order now' page
2. Update devices ordered = cap
3. New page should show instead of 'Can order' page
=> Show a new page when RB has no devices left to order

app/models/extra_mobile_data_request.rb, app/models/support/service_performance.rb, app/views/support/service_performance/_mobile_data_requests.html.erb, spec/controllers/mno/extra_mobile_data_requests_controller_spec.rb, spec/factories/extra_mobile_data_requests.rb, spec/models/support/service_performance_spec.rb
#1135 introduced new statuses on MNO requests. The service dashboard needs to be aware of these statuses.
Update the service dashboard calculation code to handle MNO requests with `problem_*` statuses.
=> MNO requests: update service dashboard to support problem statuses

app/controllers/support_ticket/academy_details_controller.rb, app/form_objects/support_ticket/academy_details_form.rb, app/form_objects/support_ticket/local_authority_details_form.rb, app/views/support_tickets/academy_details.html.erb, app/views/support_tickets/local_authority_details.html.erb, app/webpacker/scripts/responsible-bodies-autocomplete.js
- Adds autocomplete to multi-academy trust page
- Adds autocomplete to Local Authority page
This feature is just an enhanced select list so if JS were to fail or not load for whatever reason the user would still see a list of options in a select list to choose from.
- Visit https://dfe-ghwt-pr-1122.herokuapp.com/get-support
- Attempt to create a ticket on behalf of Multi-academy trust user  (NO TICKET WILL ACTUALLY BE CREATED)
- Attempt to create a ticket on behalf of a local authority user
=> Add autocomplete to Multi-Academy Trust and Local Authority pages - Get support - 

README.md
The URLs listed for staging and prod in the README deployment section were out of date
Correct the URLs
=> Bring URLs in the README deployment bit up-to-date

app/controllers/support/schools_controller.rb, app/models/virtual_cap_pool.rb, app/policies/school_policy.rb, app/views/support/schools/_history.html.erb, app/views/support/schools/history.html.erb, config/routes.rb, spec/controllers/support/schools_controller_spec.rb
Currently we have to inspect the database to get historical information about a school and its related objects. This PR adds a page to see everything in one place. When viewing a school in support add `/history` to the URL.
It includes changes on:
- School
- Device allocations
- Virtual pools
- Cap updates
- Devices ordered updates
It's not linked to from anywhere because it's just for us, and testing is limited beyond 'does it render'.
🤫
=> Add page to view schools history

app/components/extra_mobile_data_request_status_component.rb, app/controllers/mno/extra_mobile_data_requests_controller.rb, app/models/extra_mobile_data_request.rb, config/locales/en.yml
MNO request statuses are presented to various users (school, RB and MNO users) and in various UI element contexts (on status tags, drop-downs and form options).
Add an explicit method which reflects which MNO request statuses are available to MNO users to use (they shouldn't be using `cancelled` and `unavailable` statuses).
DRY up how the various status labels are stored and retrieved, to make it easier if a label is missing or not.
This should help with #1150 and follow-up MNO improvements.
=> Refactoring of MNO request status labels and descriptions

app/controllers/support_ticket/base_controller.rb, app/controllers/support_ticket/check_your_request_controller.rb, app/models/support_ticket.rb, app/views/support_tickets/check_your_request.html.erb, app/views/support_tickets/college_details.html.erb, app/views/support_tickets/school_details.html.erb, spec/controllers/support_ticket/check_your_request_controller_spec.rb, spec/models/support_ticket_spec.rb
- Introduce a model to decorate the support ticket session values. Add sensible for each field so that we fail gracefully from missing values.
- URN and UKPRN fields should only accept numbers.
=> Add support ticket model so that we can better handle defaults

app/components/extra_mobile_data_request_status_component.rb, app/components/support/school_details_summary_list_component.rb, app/jobs/notify_mnos_job.rb, app/models/extra_mobile_data_request.rb, app/services/extra_mobile_data_request_status_migration_service.rb, app/views/support/service_performance/_mobile_data_requests.html.erb, config/locales/en.yml, spec/controllers/mno/extra_mobile_data_requests_controller_spec.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb, spec/models/extra_mobile_data_request_spec.rb, spec/services/extra_mobile_data_request_status_migration_service_spec.rb
When a new MNO request is made, the designs call for showing its status as 'Requested' to school and RB users, and as 'New' to MNO users.
#1150 is introducing CSV upload functionality for MNO users and we want to use `new` as the status there. This is going to be easier if the underlying status is called `new`.
Introduce a `new` status on MNO requests and make it the default.
Introduce a service class that can be run on production to migrate all `requested` statuses to `new`.
Once the data migration has been released and run on production, there will be a follow-up PR which will get rid of the `requested` status.
=> Introduce 'new' status on MNO requests

app/components/extra_mobile_data_request_status_component.rb, app/controllers/mno/extra_mobile_data_requests_controller.rb, app/models/extra_mobile_data_request.rb, app/views/mno/extra_mobile_data_requests/_extra_mobile_data_request.html.erb, config/locales/en.yml, spec/components/extra_mobile_data_request_status_component_spec.rb, spec/controllers/mno/extra_mobile_data_requests_controller_spec.rb
The MNO user interface is not in line with the designs.
MNO users should see newly raised MNO requests as 'New'. School and RB users still see them as 'Requested'.
MNO users shouldn't have the 'New' status in the dropdown below their table of requests.
**What the MNO users see**
**What school/RB users see**
=> MNO design tweaks

app/controllers/responsible_body/internet/mobile/extra_data_requests_controller.rb, app/controllers/school/internet/mobile/extra_data_requests_controller.rb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb
[Trello card #1340](https://trello.com/c/A3ZBD6ab/1340-add-requested-column-to-list-of-mno-requests-shown-to-schools-and-rbs-order-table-by-that-column-newest-to-oldest) - Add "Requested" column to list of MNO requests shown to schools and RBs, order table by that column (newest to oldest)
* add the 'Requested' column the list of extra mobile data requests for schools & RBs
* update the specs
Note: there's a fair bit of existing duplication between the school / RB code and specs around this. In the interests of keeping this PR small and focussed, plus speedy delivery, I haven't done anything to address it in this PR - but I will log another Tech Debt ticket to refactor this.
=> add "Requested" column to extra mobile data requests for schools & RBs

config/locales/en.yml, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/responsible_body/submitting_a_spreadsheet_request_spec.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb
"Manually" might be putting off users from using the form – in research we saw someone using a spreadsheet with only 1 row.
Make the two options more consistent, and say "One at a time, using a form"
=> Tweak language used for choosing single/bulk request

app/controllers/responsible_body/devices/change_who_will_order_controller.rb, app/form_objects/responsible_body/devices/who_will_order_form.rb, app/helpers/view_helper.rb, app/models/responsible_body.rb, app/models/who_will_order_event.rb, app/services/onboard_single_school_responsible_body_service.rb, app/services/school_to_sat_converter.rb, app/views/responsible_body/devices/who_will_order/show.html.erb, config/locales/en.yml, db/migrate/20210121111312_change_responsible_body_who_can_order.rb, db/schema.rb, spec/factories/responsible_bodies.rb, spec/features/responsible_body/devices_setup_spec.rb, spec/models/preorder_information_spec.rb, spec/services/onboard_single_school_responsible_body_service_spec.rb, spec/services/school_to_sat_converter_spec.rb
We have a mix of `schools` on RB and `school` on PreorderInformation. This brings both inline to be the singular `schools`.
Unfortunately we currently have a mix on production:
```
ResponsibleBody.group(:who_will_order_devices).count
=> {"school"=>433, nil=>2, "schools"=>2607, "responsible_body"=>616}
```
=> Use consistent who_will_order values

app/controllers/mno/extra_mobile_data_requests_csv_update_controller.rb, app/form_objects/mno/csv_status_update_form.rb, app/form_objects/mno/csv_status_update_summary.rb, app/models/extra_mobile_data_request.rb, app/models/extra_mobile_data_request_status_file.rb, app/services/extra_mobile_data_request_status_importer.rb, app/views/mno/extra_mobile_data_requests/index.html.erb, app/views/mno/extra_mobile_data_requests_csv_update/new.html.erb, app/views/mno/extra_mobile_data_requests_csv_update/summary.html.erb, config/locales/en.yml, config/routes.rb, db/schema.rb, spec/features/mno/extra_mobile_data_requests_csv_update_spec.rb, spec/services/extra_mobile_data_request_status_importer_spec.rb, spec/support/csv_file_helper.rb
[Trello card](https://trello.com/c/w80Ydy7m/1288-mno-bulk-allow-mno-users-to-upload-a-csv-of-requests-to-update-their-statuses) Enable MNOs to bulk update their request statuses.
Adds CSV upload and bulk update process with summary of changes made.
As a MNO with some `ExtraMobileDataRequest`s, sign in to the service and download your requests as CSV.
Update the status column of one or more and then upload the CSV through the new feature. Any valid changes to status will be saved to your requests and a summary of unchanged, updated and errors will be presented.
_Might need to update valid statuses and reflect these on the upload page as I think they might've changed since starting this?_
=> Mno extra mobile data requests bulk update status by csv

Dockerfile
Our docker was failing because yarn requested a later node version that wasn't compatible with our packages.json. This fixes yarn for now.
This is blocking production builds.
=> Fix yarn to 1.22.10

Dockerfile
Alpine 3.13 insists on a later version of node. Until we can properly upgrade node we need to fix to this version.
=> Fix alpine to 3.12

app/services/fake_data_service.rb
[Trello card 1358 - intermittent spec failure on invalid phone number](https://trello.com/c/jTAKotqZ/1358-fix-intermittent-spec-failure-due-to-mobile-phone-number-format) - we very occasionally get a build failure on CI due to Faker generating a mobile phone number that fails validation by phonelib. These errors usually go away after no more than a couple of retries, but they are annoying and a waste of time when they occur.
Detect when this happens, and retry up to 100 times within the `FakeDataService`
=> force retry of fake phone no. generation on failure

app/components/school/school_breadcrumbs_component.rb, app/controllers/application_controller.rb, app/controllers/responsible_body/base_controller.rb, app/controllers/schools_controller.rb, app/models/computacenter/user_change_generator.rb, app/models/responsible_body.rb, app/models/user.rb, app/services/interstitial_picker.rb, spec/controllers/responsible_body/base_controller_spec.rb, spec/controllers/sign_in_tokens_controller_spec.rb, spec/factories/users.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/models/user_spec.rb, spec/services/onboard_single_school_responsible_body_service_spec.rb
We have some code that narrows the views RB users have only a singular view of its school. We need to do the same thing for FE institutions so they see one school vs an index of schools.
- Update and rename `User#is_a_single_academy_trust_user?` to accommodate FE users so that they don't see the schools index view like normal RB users.
1. Log in as FE college user
2. See no list of schools, essentially looks as if you're a school user.
=> FE college users should have the same view as SAT users

app/models/extra_mobile_data_request.rb, config/locales/en.yml, spec/factories/extra_mobile_data_requests.rb, spec/models/extra_mobile_data_request_spec.rb
Card: https://trello.com/c/ZHeihTzs/1353-mnos-receiving-duplicate-requests
We were allowing duplicate requests via the manual entry method. This PR adds a validation to check whether a request is unique within the school or RB in which it is created.
=> Validate MNO request uniqueness within the same school or RB

app/views/school/welcome_wizard/allocation.html.erb
We've added FE and had a feature flag for some participants in user research on the content of this page.
Removes feature flag that confuses users when they see allocation description that doesn't apply.
=> removes feature flag as content applies to all education settings

Dockerfile, package.json
See [Trello card 1372](https://trello.com/c/pNhXwfHA/1372-revisit-build-hack-try-to-unlock-the-alpine-version) - a recent alpine version-bump meant the Docker build couldn't find a compatible pair of versions for node & yarn.
It turns out the version-lock was coming from inside the build(ing) all along
* bump alpine version to 3.13, and bump the version requirement for node in yarn's `package.json` from 12.x to 14.x 
`make dev build` should complete succeffully
=> fix version-lock on node/yarn/alpine-3.12

app/components/responsible_body/school_details_summary_list_component.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/features/responsible_body/ordering_via_a_school_spec.rb
[Trello card 1379](https://trello.com/c/DAEmCZ19/1379-only-hide-devices-ordered-on-a-school-if-the-school-is-actually-in-a-virtual-cap-pool) - In support/school/(urn), we're not showing the 'Devices ordered' row for a school if it belongs to an RB which has the virtual cap feature flags set - even if the school itself is not actually in a virtual cap pool.
This ticket came about as a result of investigating the support ticket [Ordered figure not showing at school level](https://get-help-with-tech-education.zendesk.com/agent/tickets/36094) in [Trello card 1374](https://trello.com/c/QxhXUEpk/1374-support-batch-tickets)
Change the criteria so that we only hide 'Devices ordered' if the specific school is actually in a virtual cap
=> [1379] Only hide 'Devices ordered' on a school if the school is actually in a virtual cap pool

app/mailers/can_order_devices_mailer.rb, app/models/school_can_order_devices_notifications.rb, app/models/user_can_order_devices_notifications.rb, config/locales/en.yml, config/settings.yml, db/migrate/20210122115602_add_new_fe_wave_to_responsible_body.rb, db/schema.rb, spec/factories/responsible_bodies.rb, spec/mailers/can_order_devices_mailer_spec.rb, spec/models/school_can_order_devices_notifications_spec.rb, spec/models/user_can_order_devices_notifications_spec.rb
Trello: https://trello.com/c/KhV0QWqj/1328-invite-to-order-email-fe-providers-build-logic-to-automate-email
We'd like to send out a slightly modified email to FE institutions when they can order. There are a mix of new and old FE institutions on the service now so I have introduced a new column called `new_fe_wave` on responsible bodies so that we can identify them.
Aside from that, this PR adds the new template and conditionally sends the new email when the new column is true.
---
Once deployed we need to ensure all new institutions have that column set to true.
=> Send distinct can order email to new FE institutions

app/components/extra_mobile_data_request_status_component.rb, app/controllers/mno/extra_mobile_data_requests_controller.rb, app/controllers/mno/extra_mobile_data_requests_csv_update_controller.rb, app/controllers/responsible_body/internet/mobile/extra_data_requests_controller.rb, app/controllers/school/internet/mobile/extra_data_requests_controller.rb, app/models/extra_mobile_data_request.rb, app/views/mno/extra_mobile_data_requests/_extra_mobile_data_request.html.erb, app/views/mno/extra_mobile_data_requests_csv_update/summary.html.erb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb, app/views/shared/internet/_help_with_statuses.html.erb, config/locales/en.yml, spec/components/extra_mobile_data_request_status_component_spec.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb, spec/page_objects/school/internet/your_requests_page.rb
Once an school or RB user makes an MNO request, the mobile network will either action it or provide feedback on it. It's not always obvious what each status means.
Display a table of statuses and descriptions to school and RB users.
=> Explain MNO request statuses to school and RB users

Makefile
[Trello card 1383](https://trello.com/c/MBZltdey/1383-rename-govuk-paas-org-dfe-teacher-services-dfe) On Monday 25th, around 3pm, the two Organisations in GOV.UK PaaS which are currently-named 'dfe-digital' and 'dfe-teacher-services' will merge into a single organisation called 'dfe'
We will need to change 'dfe-teacher-services' to 'dfe' in our release pipeline
Change the PaaS organisation name
DO NOT MERGE THIS until we are given the heads-up on Monday that the change has happened (or releases stop working :) )
=> [1383] rename the gov.uk paas organisation to dfe

app/components/support/school_details_summary_list_component.rb, app/models/school.rb, spec/components/support/school_details_summary_list_component_spec.rb
- https://trello.com/c/dsWURzNG/1244-allow-admin-users-to-see-the-address-of-a-school
- Add address to school view for support staff
- Should see adddress
=> [1244] Add address to school support view

app/controllers/mno/extra_mobile_data_requests_controller.rb, app/form_objects/mno/find_requests_form.rb, app/helpers/view_helper.rb, app/views/mno/extra_mobile_data_requests/_extra_mobile_data_requests_bulk_table.html.erb, app/views/mno/extra_mobile_data_requests/index.html.erb, app/views/mno/extra_mobile_data_requests/search_results.html.erb, config/routes.rb, spec/features/mno/find_extra_mobile_data_requests_by_telephone_number_spec.rb
[Trello card](https://trello.com/c/gQk4sysp/1289-mno-bulk-add-feature-to-search-for-multiple-requests)
Enable MNOs to search list of requests by telephone number
Add form to 'Your requests' page enabling MNO to add one phone number per line to search for.
Add 'results' page that has similar functionality to main 'Your requests' page - column sorting, bulk updates, download CSV etc.
From results page, downloading a CSV includes only matching requests
As a MNO user with some `ExtraMobileDataRequest`s, log in a view 'Your requests'
The 'Find requests by telephone number' form should now present.
Enter one or more phone numbers and click 'Find requests'.
Matching requests should be displayed.
You can interact with the requests the same as on the initial 'Your requests' page. The 'Find …
=> 1289 mno bulk add feature to search for multiple requests

app/form_objects/mno/csv_status_update_summary.rb, app/views/mno/extra_mobile_data_requests_csv_update/summary.html.erb, config/locales/en.yml, spec/features/mno/extra_mobile_data_requests_csv_update_spec.rb
[Trello card](https://trello.com/c/Noe2bGD1/1380-limit-number-of-requests-shown-to-mno-after-a-large-csv-upload)
When an MNO bulk updates `ExtraMobileDataRequest` statuses via CSV, restrict the output of summary data to 50 rows each for errors and updates.
Provide alternative heading summary when limiting output to 50
Limit summary table records to max of 50 per table
As an MNO, with more than 50 `ExtraMobileDataRequest`s upload a CSV with more than 50 status updates and/or more than 50 errors.
The summary displayed should be limited to max of 50 and provide a heading "Showing the first 50 of n requests containing errors" or "Showing the first 50 of n updated requests" indicating the results are truncated.
=> Limit summary output to 50 for updates and errors

app/controllers/support/schools_controller.rb, app/controllers/support/users/schools_controller.rb, app/form_objects/support/school_suggestion_form.rb, app/models/school.rb, app/views/support/users/schools/index.html.erb, app/views/support/users/schools/new.html.erb, app/views/support/users/schools/search_again.html.erb, app/webpacker/packs/application.js, config/locales/en.yml, spec/controllers/support/schools_controller_spec.rb, spec/controllers/support/users/schools_controller_spec.rb, spec/features/support/changing_a_users_associated_organisations_spec.rb, spec/form_objects/support/school_suggestion_form_spec.rb, spec/models/school_spec.rb, spec/page_objects/support/users/schools_page.rb
- https://trello.com/c/owl7cZGa/1419-cannot-add-users-to-fe-schools-as-autocomplete-does-not-search-by-ukprn
- When adding to users to schools can now search for schools by UKPRN
- Find a user
- Edit the user
- Add the user to a school by searching for a school by UKPRN
- Both JS autocomplete option and non-js option should work
- User should now be associated with the selected school
=> [1419] Can search by UKPRN when add user to school

app/controllers/support/schools_controller.rb, app/form_objects/school_search_form.rb, app/views/support/schools/results.html.erb, app/views/support/schools/search.html.erb, spec/controllers/support/schools_controller_spec.rb, spec/features/support/searching_schools_spec.rb, spec/form_objects/school_search_form_spec.rb, spec/page_objects/support/schools/search_page.rb
Support agents can search for schools by URNs, UKPRNs, responsible body and order state.
Split the 'search schools' form with radio button options.
This is to pave the way for adding a third option shortly. This also
reflects the fact that it doesn't make sense for a user to be trying to
find schools both by URN/UKPRN and their RB or state...
**Before:**
**After:**
Out of scope of this PR, will be done shortly as a follow-up PR:
- form validations (these are also currently missing so it's not a regression)
=> Add radio button options to school search in the support console

app/controllers/support_ticket/check_your_request_controller.rb, app/form_objects/support_ticket/check_your_request_form.rb, app/views/support_tickets/thank_you.html.erb, spec/controllers/support_ticket/check_your_request_controller_spec.rb, spec/form_objects/support_ticket/check_your_request_form_spec.rb
The "Thank you" page content was a bit confusing for some users and as it didn't give them a reference number there was no confidence that their issue was logged even though they would have received a confirmation email with the ticket reference.
What was happened is that when we posted the form data to Zendesk, Zendesk would respond to the post request with an "OK" status along with the newly created ticket information. We just didn't relay that information back to the user.
- Display the zendesk ticket reference number on the "Thank you" page
- Improve error handling if the action fails to create a ticket.
- visit https://dfe-ghwt-pr-1201.herokuapp.com/ 
- Create a new support ticket (For the shortest journey, select "I'm none of the above")
=> Display the zendesk ticket reference after a ticket has been created

app/controllers/support/schools_controller.rb, app/form_objects/school_search_form.rb, config/locales/en.yml, spec/controllers/support/schools_controller_spec.rb, spec/form_objects/school_search_form_spec.rb
The input on the school search form in the support console wasn't being validated.
Add validations to ensure consistency of input, to bring the form in line with all other forms in the service.
=> Validate form submissions for the school search form in support

app/views/support/schools/search.html.erb
I meant to include the the error summary on the school search form as part of #1214, but ended up forgetting to commit the line 😿 
Add missing view code to display the error summary.
=> Show error summary on the school search form in Support

config/locales/en.yml, spec/features/mno/extra_mobile_data_requests_csv_update_spec.rb
We were missing a translation for an error message when a MNO uploads an invalid CSV file. This PR adds the string and a test case.
=> Fix missing translation when uploading an invalid MNO requests file

config/initializers/mime_types.rb, spec/controllers/mno/extra_mobile_data_requests_csv_update_controller_spec.rb
[Trello card](https://trello.com/c/lCR0HN9W/1429-mnos-reporting-issue-uploading-csv)
Fix issue for MNO users on Microsoft Windows trying to upload CSV status files
Microsoft identify CSV files using their own `application/vnd.ms-excel` mime-type rather than the standard `text/csv`, this adds `application/vnd.ms-excel` as a synonym for the csv type.
As a MNO user upload a status update CSV file from a Windows PC with Excel installed. File should be accepted and not generate the 'Choose a CSV file` error message
=> Added microsofts csv mime type

app/controllers/support/responsible_bodies_controller.rb, app/form_objects/school_search_form.rb, app/views/support/schools/show.html.erb, spec/controllers/support/responsible_bodies_controller_spec.rb, spec/features/support/managing_schools_spec.rb, spec/form_objects/school_search_form_spec.rb
Trello: https://trello.com/c/DF6lRrlF/1437-support-improvement-be-clear-when-school-is-closed
A few months ago we decided to hide closed schools in the support console.
Since then schools users have been navigating to schools directly using the URN in the URL so that they can view details on closed schools. We do not show when a school is permanently closed so this is particularly confusing.
- This PR allows support users to navigate and search to schools that are marked as permanently closed by GIAS.
- It also adds a warning to the top of the school page to indicate if a school is closed.
- Search for closed school in the support console
- You should see results including the closed school
- Navigate to a responsible body with a closed school in support
- You should see the closed school …
=> Allow support users to find permanently closed schools

app/form_objects/school_search_form.rb, config/locales/en.yml, spec/form_objects/school_search_form_spec.rb
Card: https://trello.com/c/PxRskrDz/1387-display-friendly-error-when-somebody-searches-for-a-school-using-an-invalid-urn
Previously entering a non-integer URN/UKPRN in the support search form would raise an exception because Postgres was expecting us to search on an integer column using an integer.
This PR gracefully feeds back to the user if format of the input is incorrect.
=> Gracefully handle searching for non-integer URNs

app/controllers/support/schools_controller.rb, app/form_objects/school_search_form.rb, app/views/support/schools/results.html.erb, app/views/support/schools/search.html.erb, app/webpacker/packs/application.js, config/locales/en.yml, spec/controllers/support/schools_controller_spec.rb, spec/features/support/searching_schools_spec.rb, spec/form_objects/school_search_form_spec.rb, spec/page_objects/support/schools/search_page.rb
Support agents need a way to quickly find a school by its name.
Add an extra option to the school search in the support console, which has auto-complete and allows searching by a partial name, URN or UKPRN
https://user-images.githubusercontent.com/23801/106288458-fce10880-623f-11eb-9442-02f63a9b2a9e.mp4
=> Single school search in support

Gemfile.lock
1.4.1 is no longer available and was preventing `bundle install` from working
=> Bump msgpack to 1.4.2

app/services/extra_mobile_data_request_status_importer.rb, spec/services/extra_mobile_data_request_status_importer_spec.rb
[Trello card](https://trello.com/c/o92WCGO8/1466-help-reduce-the-errors-in-name-matching-for-mno-csv-bulk-upload)
MNO having issues uploading CSVs for extra mobile data requests where we validate the name is correct. There doesn't appear to be any need for us to do this, so to help reduce the errors that creep in from cut-n-paste formatting changes etc. that can occur from MS Office we remove the validation of the name and phone number.
Remove validation of account holder and device phone number.
Allow status updates as long as the status is valid and the `id` is for an `ExtraMobileDataRequest` belonging to the MNO.
As an MNO with some requests, export the requests as CSV, change one or more statuses and modify the account holder name and/or device phone number. The CSV should import …
=> Relax validation when importing csv

app/models/user.rb, spec/models/user_spec.rb
- https://trello.com/c/Lggm08t2/1435-support-improvement-automatic-removal-of-leading-and-trailing-spaces-when-searching-by-email-or-name
- Ignore whitespace padding on user search for support agents
- Search for existing user by name or email, add additional whitespace padding to the search query
- Should return user regardless of whitespace padding
=> [1435] Ignore whitespace padding on user search

app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/index.html.erb, app/views/guide_to_collecting_mobile_information/_guide_contents.html.erb, app/views/layouts/multipage_guide.html.erb, app/views/layouts/page_with_toc.html.erb, app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/choosing_help_with_internet_access.html.erb, app/views/pages/how_request_4g_routers.html.erb, app/views/pages/internet_access.html.erb, app/views/support_tickets/academy_details.html.erb, app/views/support_tickets/check_your_request.html.erb, app/views/support_tickets/college_details.html.erb, app/views/support_tickets/contact_details.html.erb, app/views/support_tickets/describe_yourself.html.erb, app/views/support_tickets/local_authority_details.html.erb, app/views/support_tickets/parent_support.html.erb, app/views/support_tickets/school_details.html.erb, app/views/support_tickets/start.html.erb, app/views/support_tickets/support_details.html.erb, app/views/support_tickets/support_needs.html.erb, app/views/support_tickets/thank_you.html.erb
Sometimes "Home" is interpreted as the signed in home page, which uses the same text and link.
Make the two link texts unique by renaming the signed out version.
=> Rename "Home" to "Get help with technology"

spec/controllers/support/users_controller_spec.rb
[Trello card 1469](https://trello.com/c/PBgytxRA/1469-intermittent-spec-failure-when-randomly-generated-name-contains-smith) - although `support/users_controller_spec.rb` is fixing the names of users in the specific cases it's testing for (all have surname Smith), it's leaving Faker to generate a random name for the user that the spec is signing in as. This works fine for most of the time, but just occasionally that name contains 'Smith' too - which causes a spec failure.
Fix the name of the `support_user` to be 'Jones'
=> [1469] fix occasional name collision in spec

app/form_objects/chromebook_information_form.rb, app/helpers/view_helper.rb, app/models/school_welcome_wizard.rb, app/views/shared/_chromebook_information_form.html.erb, config/locales/en.yml, spec/features/responsible_body/providing_a_schools_preorder_information_spec.rb, spec/features/school/change_chromebook_information_spec.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/support/editing_chromebook_details_for_a_school_spec.rb, spec/form_objects/chromebook_information_form_spec.rb, spec/helpers/view_helper_spec.rb
[Trello card 1375](https://trello.com/c/oaDQbQTn/1375-update-chromebook-question-and-validation) -  In user research, we saw users getting confused by what the G Suite for Education domain was. Improve the labelling to make it clearer.
* label the domain field appropriately using the `institution_type` and `responsible_body.humanized_type` where appropriate 
* new `chromebook_domain_label` method on `ChromebookInformationForm` to encapsulate the logic
* improve wording on error message when the domain is invalid
(see the Trello card and [Slack thread](https://ukgovernmentdfe.slack.com/archives/C01A7DVKE9J/p1611761686137200) for discussion)
When the school's responsible body is a Local Authority:
When it's a Further Education school:
=> 1375 update chromebook question and validation

app/controllers/support/users_controller.rb, app/models/school.rb, app/views/support/schools/show.html.erb, spec/controllers/support/users_controller_spec.rb, spec/models/school_spec.rb, spec/views/support/schools/show.html.erb_spec.rb
- https://trello.com/c/NPSW33Ku/1411-remove-support-functionality-to-add-users-to-school-when-rb-ordering-centrally
- Support agents cannot invite school users if RB orders
- Button is not displayed and controller access to the form is denied
- Find a school where RB orders
- Cannot invite new users to the school
- Find a school where school orders OR who will order has not been decided
- In both cases users can be invited to these schools
=> [1411] School users cannot be added if RB orders

app/components/responsible_body/school_details_summary_list_component.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb
This PR extends on work initially done in https://github.com/DFE-Digital/get-help-with-tech/pull/1179
On the school details summary component we conditionally hide the 'devices ordered' number if the school is in the virtual cap or if the number is zero. This is because at a school level this doesn't make sense within the context of a virtual cap - schools may physically receive devices that then sent on elsewhere.
Previously it was checking whether virtual cap feature flag was disabled. We changed it so that it checked the school wasn't in the pool. We actually need _both_ to effectively determine whether a school is in the virtual cap.
=> Hide 'Devices ordered' only if not in virtual pool and feature flag is not enabled

app/models/session.rb, app/services/session_service.rb, db/migrate/20210129105958_add_expires_at_to_sessions.rb, db/schema.rb, spec/services/session_service_spec.rb
- https://trello.com/c/MgxnyGhN/1433-support-improvement-increase-log-in-time-for-support-agents
- A two part change is needed to allow different users to have different session durations
- This creates `expires_at` on the session and populates it on next use
- It cannot be populated immediately as postgres does not allow for default values based on other data on the row hence a two part change
- Next change will modify `Session#expired?`, remove `ttl` from `Session`, update `DeleteOldSessionsJob`
- Signing in, out and expiration should behave as normal as no change has been made
- We are simply setting up new data to be added which be hooked on to later
=> [1433] Extend users session Part 1/2

app/views/pages/how_request_4g_routers.html.erb, app/views/responsible_body/internet/home/show.html.erb, app/views/school/internet/home/show.html.erb, app/views/shared/internet/_mno_information.html.erb, spec/features/school/wireless_router_requests_spec.rb
- current content implies that 4G routers can be ordered (we talk about using this section to 'request 4G wireless routers')
- users expect this service to be automated, similar to ordering devices
- current service adds to support burden (sending users to covid technology inbox, each request taking multiple support replies)
This causes delays for children who need internet access
Add links to google form that allows users to make a request and update content on:
- How to request 4G wireless routers
- Get internet access (for schools etc)
- Get internet access (for RBs)
Guidance page:
Get internet access (for schools etc)
Get internet access (for RBs)
=> Link to google form to request routers

app/components/support/school_details_summary_list_component.rb, app/controllers/support/addresses_controller.rb, app/models/user.rb, app/policies/school_policy.rb, app/views/support/addresses/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20210202111622_add_role_to_users.rb, db/schema.rb, spec/features/support/addresses_spec.rb, spec/page_objects/support/address_page.rb
- https://trello.com/c/P4uNQa6B/1470-limited-support-staff-can-change-addresses
- Add change link to school address if third line role
- Add page with form to update the school address
- Page has status if the address has been picked up by CC or not based off `school#computacenter_change`
- Added `role` column to `User` table
- Cannot see link to edit school address
- Or access page to edit school address
- Set user `role` to `third_line`
- Can see link to edit school address
- If school `computacenter_change` is `none`
- see status `ACTIVE` that CC has the current address
- update address and submit form
- click `Change` address again
- Should not see address status as `pending` as CC is yet to pickup address changes
=> [1470] Third line can update school address

config/initializers/mime_types.rb, spec/controllers/responsible_body/internet/mobile/bulk_requests_controller_spec.rb, spec/controllers/school/internet/mobile/bulk_requests_controller_spec.rb
Sometimes Chromebook will upload xlsx files as `application/octet-stream` instead of the default `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`.
This PR allows for uploads of that type.
Example request: https://kibana.logit.io/app/kibana#/discover/doc/8ac115c0-aac1-11e8-88ea-0383c11b333c/logstash-2021.02.02?id=FX6bY3cB_UZj64kqjsc9
=> Bulk request upload should should handle non-standard xlsx MIME types

app/views/school/devices/can_order_awaiting_techsource.html.erb
- Indicate to users waiting for an account how long deliveries are taking
- fix typo "check check device"
(Current delivery text: "Most devices will be delivered within 5 working days of an order being confirmed, subject to stock availability.")
=> Fix typo, add note about delivery timelines

app/jobs/delete_old_sessions_job.rb, app/models/session.rb, app/services/session_service.rb, app/views/cookie_preferences/new.html.erb, config/initializers/session_storage.rb, config/settings.yml, spec/features/session_behaviour_spec.rb, spec/jobs/delete_old_sessions_job_spec.rb, spec/models/session_spec.rb
- https://trello.com/c/MgxnyGhN/1433-support-improvement-increase-log-in-time-for-support-agents
- Whether or not a session has expired is based of the `expires_at` value
- `DeleteOldSessionsJob` now uses `expires_at` column to determine what records to delete
- Cookie expiration now set to max possible configurable TTL
- This now closes the loop and allows the support users to have longer session lengths
- Login as normal user
- Cookie expiration should be in 2 hours time
- DB session expiration in 1 hours time
- Cookie expiration should be in 2 hours time
- DB session expiration in 2 hours time
=> [1433] Session expiry based on expires_at field

Makefile
- I got bored of typing `env | grep -i log`
- Add variable unset to welcome/motd aff when ssh-ing into container
- This will prevent extraneous log messages from appearing in a rails console session
- Not sure if this can be tested locally?
- Will be tested in integration environments
=> Add log unset to ssh welcome motd

app/services/feature_flag.rb, app/views/responsible_body/devices/orders/order_devices.html.erb, app/views/school/devices/can_order.html.erb, app/views/shared/_half_term_delivery_suspension.html.erb
Users can continue to order throughout half term, but deliveries will not resume until Feb 22.
https://trello.com/c/jH7QlXDk/1460-prepare-the-service-for-pausing-deliveries-over-half-term
=> [1460] Note that deliveries are paused over half term

app/controllers/support/users_controller.rb, app/form_objects/support/user_search_form.rb, app/views/support/users/results.html.erb, spec/form_objects/support/user_search_form_spec.rb
- https://trello.com/c/MOZGgRVr/1452-support-improvement-return-emails-in-same-domain-if-user-doesnt-exist-on-service
- When searching for users if there are no results search for users on the same domain
- If parsing of the search term fails ie is not an email address but a name simply return no related results
- Find search for an existing user eg `user1@example.com`
- Should return user
- Search for non-existent user eg `user2@example.com`
- Should return `user1@example.com` as related user
- Searching for normal string that returns no results should not throw an error
- eg `rgioerjgierjgioerjgiejrg`
=> [1452] 0 users found returns users on same domain

app/views/layouts/_google_analytics.html.erb, spec/features/google_analytics_behaviour_spec.rb
[Trello card](https://trello.com/c/5GWA2q1W/1505-anonymise-ips-in-google-analytics) - IP addresses are considered Personally-Identifying Information. [Google Analytics supports an IP anonymisation setting](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization) which avoids individual IPs being recorded. We should be using that setting. 
* add the `'anonymize_ip': true` setting to GA config
=> anonymize IPs in Google Analytics

app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, app/views/responsible_body/devices/schools/order_devices.html.erb, app/views/school/devices/can_order.html.erb, app/views/shared/_start_ordering_on_techsource.html.erb
We’ve noticed that a few users are submitting their orders and then having to amend or cancel them.
- add a few lines to help users check device specification and invite others to order
- remove the 'Do not delay' message as this may be causing users to feel its better to place and order before they're certain of what they need
=> Adds guidance to on checking what to do and remove 'do not delay' message

app/models/extra_mobile_data_request.rb, spec/models/extra_mobile_data_request_spec.rb
[Trello card 1430](https://trello.com/c/A3xFg0VU/1430-update-unavailable-statuses-for-mno-requests-to-participating-networks) Many (several hundred) requests currently have status 'unavailable', even though their corresponding mobile network is `'participating_in_pilot'`. There are 2 possibilities - either the network was not participating at the time the request was submitted, and has since joined, or the network operators have not had a clear understanding of what 'unavailable' means (it was intended to indicate 'the offer is not available on this network') and have used it to mean that the offer is not being made available for this request for some other reason.
* Add PaperTrail auditing to `ExtraMobileDataRequest` so that for each request in future we can see what was changed, when, …
=> [1430] Add PaperTrail versionning for ExtraMobileDataRequests

db/migrate/20210208113843_set_all_unavailable_emdrs_to_new_for_participating_networks.rb, db/schema.rb
[Trello card 1430](https://trello.com/c/A3xFg0VU/1430-update-unavailable-statuses-for-mno-requests-to-participating-networks) - Many (several hundred) requests currently have status 'unavailable', even though their corresponding mobile network is 'participating_in_pilot'. These should be updated to `new` so that they can now be processed - except for Three, whom we will contact directly to discuss.
_NOTE_ although it's not essential, it would be good to merge this after #1263 so that we get a `PaperTrail::Version` for each updated record.
* Add a migration to set status to 'new' for all `ExtraMobileDataRequest`s which belong to a network that is `participating_in_pilot`
=> [1430] Update all unavailable requests to new, where the MNO is participating

app/controllers/support/performance_data/schools_controller.rb, spec/controllers/support/performance_data/schools_controller_spec.rb
[Trello card 1519](https://trello.com/c/WDUEYvUl/1519-add-whowillorder-to-performancedata-schools-api). When a ResponsibleBody orders centrally on behalf of their schools, they often ship devices to a single IT hub for subsequent redistribution, rather than directly to the individual schools. This can cause issues for the analysts, who are reliant on shipTo information from Computacenter for responding to FOI requests & Parliamentary questions concerning numbers of devices shipped to particular locations / areas / etc. 
In a private Slack discussion, we agreed that while we're not able to accurately determine per-school numbers when the ordering pattern is like this, we can at least add the `who_will_order_devices` field to the performance data API, which will allow the analysts to …
=> add who_will_order_devices to schools performance data API

app/components/support/email_audit_list_component.html.erb, app/controllers/support/schools_controller.rb, app/services/timeline/changeset.rb, app/services/timeline/school.rb, app/views/support/schools/_history.html.erb, app/views/support/schools/history.html.erb, app/views/support/schools/show.html.erb, config/locales/en.yml, spec/services/timeline/school_spec.rb, spec/views/support/schools/show.html.erb_spec.rb
- https://trello.com/c/XaACO5uV/1434-support-improvement-recent-history-for-each-school
- Add tabs to support viewing a school
- Add new `Timeline` tab/concept
- Timeline is chronological timeline (maybe it should be reverse chronological order?) of certain changesets at the moment. This can be expanded out to other changes or refined to show fewer changes useful for support
- `/history` has been changes so items in the same changeset share the same date with one table cell with rowspan set
- n/a
=> [1434] Support viewing school nav tabs

app/components/support/user_search_result_component.rb, app/views/devices_guidance/about_the_offer.md, app/views/devices_guidance/device_allocations.md, app/views/devices_guidance/device_distribution_and_ownership.md, app/views/devices_guidance/device_specification.md, app/views/devices_guidance/getting_started_with_your_google_chromebook.md, app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/index.html.erb, app/views/pages/choosing_help_with_internet_access.html.erb, app/views/pages/home_page.html.erb, app/views/pages/how_request_4g_routers.html.erb, app/views/pages/internet_access.html.erb, app/views/school/details/show.html.erb, app/views/school/welcome_wizard/allocation.html.erb, app/views/shared/_privacy_notice_text.html.erb, app/views/shared/banners/_global_notice_banner.html.erb, app/views/shared/banners/_parents_carers_pupils.html.erb, app/views/sign_in_tokens/email_not_recognised.html.erb, app/views/support/home/schools.html.erb, app/views/support/home/show.html.erb, app/views/support/schools/devices/order_status/collect_urns_to_allow_many_schools_to_order.html.erb, app/views/support/users/search.html.erb, config/locales/en.yml, spec/components/support/user_search_result_component_spec.rb, spec/features/devices_guidance/how_to_order_spec.rb, spec/features/support/enabling_orders_for_many_schools_spec.rb
[Trello card](https://trello.com/c/zZfi6hDM/1418-update-fe-content-with-approved-wording)
We've been asked to use 'further education institution' instead of 'further education provider'
Changes all instances of
- Further education provider
- Further education providers
- FE provider
- FE providers
to
- Further education institution
- Further education institutions
- FE institution
- FE institutions
=> Changes 'further education provider' to 'further education institution'

config/locales/en.yml
- https://trello.com/c/XaACO5uV/1434-support-improvement-recent-history-for-each-school
- Add missing translations for school timeline, otherwise shows raw enum values which aren't very user firendly
- Make a school order some devices
- Log in as support user
- View the timeline of the school
- Should see translations in use
=> [1434] Add missing timeline translations

app/components/support/user_preview_summary_list_component.rb, spec/components/support/user_preview_summary_list_component_spec.rb
- https://trello.com/c/XaACO5uV/1434-support-improvement-recent-history-for-each-school
- Show when user saw privacy notice
- Show when TechSource was confirmed
- Login as support user and view a user
- Change whether not user has seen privacy notice
- View should update accordingly
- Change whether or not TechSource account confirmed
- Timestamp of confirmation should show or disappear
=> [1434] Support viewing user tweaks

app/components/support/school_details_summary_list_component.rb, app/controllers/support/schools_controller.rb, app/policies/school_policy.rb, app/views/support/schools/edit.html.erb, config/routes.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/controllers/support/schools_controller_spec.rb
- https://trello.com/c/P3pygUFZ/1057-support-functionality-to-rename-schools
- Third line support can change school names
- Cannot see school name with change link in summary list
- Login as third line support
- Can see school name with change link in summary list
- Click change
- Can update school name
=> [1057] Third line can edit school name

app/views/shared/_half_term_delivery_suspension.html.erb
TechSource will stop deliveries over half-term
TechSource will have downtime Saturday 13 February
Update half-term banner content to let users know
half_term_delivery_suspension flag needs to be active
=> updates banner with half-term dates and techsource downtime message

.github/workflows/build.yml
We're seeing all builds fail in Github with:
```
rake aborted!
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /home/runner/work/get-help-with-tech/get-help-with-tech/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi_c.so
```
Looks like it's as a result of [GitHub bumping the ubuntu-latest image to Ubuntu 20.04](https://github.com/actions/virtual-environments/issues/1816)
* workaround the issue by reverting to ubuntu-18.04 until we have an actual fix for the issue on 20.04
If this build goes green, merge it :)
=> lock github action to ubuntu 18.04 as workaround for LoadError with FFI

app/controllers/support_ticket/contact_details_controller.rb, app/services/zendesk_service.rb, app/views/support_tickets/check_your_request.html.erb, spec/controllers/support_ticket/contact_details_controller_spec.rb, spec/services/zendesk_service_spec.rb
If a user is not signed in and they try to contact us using the contact form, they should not notice any changes.
If a user is signed in and they try to contact us using the contact form, they go through exactly the same journey as they would before except they will not be asked to provide their contact details.
=> Signed in users shouldn't need to complete "Contact details" page of "Get support" journey

db/migrate/20210201135621_add_rb_level_access_to_users.rb, db/schema.rb
[Trello card](https://trello.com/c/EWxSCmOl/1410-investigate-putting-an-rb-access-flag-on-all-sat-users)
Pass a flag to CC to indicate which users should have 'RB level' access at their end. This is the extra functionality granted to RB users which needs to be extended to SAT users.  This PR is the first part of the process to add a boolean `rb_level_access` flag to the `User` model.  This can then be populated before we wire up the attribute to the CC api.
Adds `rb_level_access` boolean attribute to the `User` model
=> 1410 rb access flag for cc part 1

app/controllers/computacenter/donated_device_requests_controller.rb, app/models/donated_device_request.rb, app/models/school.rb, app/services/donated_device_requests_exporter.rb, app/views/computacenter/home/show.html.erb, config/routes.rb, db/migrate/20210211163619_create_donated_device_requests.rb, db/schema.rb, spec/factories/donated_device_requests.rb, spec/features/computacenter/download_csv_files_spec.rb, spec/models/donated_device_request_spec.rb, spec/services/donated_device_requests_exporter_spec.rb
[Trello card](https://trello.com/c/sWfOU7rT/1530-donated-devices-ability-for-cc-to-download-a-export-of-opt-ins)
Provide facility for Computacenter to download donated device request opt-ins as a CSV file
Adds the `DonatedDeviceRequest` model
Adds download link to Computacenter home page
Adds `DonatedDeviceRequestExporter` service to produce CSV
Adds controller to send CSV to requester.
Add one or more `DonatedDeviceRequest`s
As a Computacenter user, visit the homepage.
Near the bottom will be a link to "Download donated device requests".
Clicking this will download a CSV containing all the `DonatedDeviceRequest` records in the service in ascending `:id` order.
=> 1530 donated devices download csv

.github/workflows/build.yml
Yesterday, [Github updated their `ubuntu-latest` image from 18.04 to 20.04](https://github.com/actions/virtual-environments/issues/1816)
20.04 only provides version 7 of `libffi`, which Ruby uses to provide native extensions facilities to gems. That causes problems for `rake parallel:setup`, which we use to setup test databases in CI  - [example failed build](https://github.com/DFE-Digital/get-help-with-tech/runs/1880926452?check_suite_focus=true) - and appears to have been built against libffi version 6
The error we see looks like this:
```
rake aborted!
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /home/runner/work/get-help-with-tech/get-help-with-tech/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi_c.so
```
I temporarily worked around the problem …
=> Fix build issue with libffi on Ubuntu 20.04

app/views/shared/_half_term_delivery_suspension.html.erb
The maintenance has passed so we can safely remove this message.
=> Remove TechSource maintenance notice

app/services/feature_flag.rb, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, app/views/school/devices/can_order.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb, app/views/shared/_start_ordering_on_techsource.html.erb, app/views/shared/_stock_levels.html.erb
https://trello.com/c/OUHwvuLx/1537-persona-d-stock-update-for-techsource-and-the-service-banners
There's low and out of stock devices.
We've relied on banners in the past, but as this is fairly constant we're adding a more permanent solution to the order page.
Note — I've fixed the capitalisation of Windows on 'Microsoft Windows Tablets'
=> Adds info on current out of stock and low stock devices

app/components/responsible_body/school_details_summary_list_component.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb
- Routers ordered is missing from summary list
- Add routers ordered to summary list
- Also tweaks ordering of these rows so devices and routers are grouped together
- login as support agent
- view a school
- make it have caps and devices orders for both devices and routers
- summary list should reflect numbers given
=> [1503] Show routers ordered in summary list

app/views/school/devices/cannot_order_as_cap_reached.html.erb, app/views/shared/_upcoming_allocation_increase_banner.html.erb, db/migrate/20210217114408_group_a_feature_flag.rb, db/schema.rb, spec/views/school/devices/cannot_order_as_cap_reached.html.erb_spec.rb
- https://trello.com/c/HF7CM3Kg
- Adds a feature flag to school table. defaults to false
- Adds partial if school has reached cap but will soon receive an uplift
- Login as school user
- Set school as can order but have 0 caps/allocations
- Attempt to order
- Should not see warning
- Enable feature flag for school
- Should now see warning
=> [1337] Allocation uplift feature flagged warning

app/components/extra_mobile_data_request_summary_list_component.rb, app/views/responsible_body/internet/mobile/extra_data_requests/index.html.erb, app/views/school/internet/mobile/extra_data_requests/index.html.erb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb
[Trello card 1570](https://trello.com/c/TN7vlRt6/1570-mno-display-requestid-in-table-of-requests-for-school-trust-users) - we want to move users towards using request ID to identify requests when contacting support, and away from name + mobile number  as they often do at the moment. This will help us minimise the number of places where Personally-Identifying Information is stored. A first step towards this is actually showing them the request IDs. Please see the Trello card for full context.
Show the request ID to school and responsible_body users when viewing `ExtraMobileDataRequest`s 
Screenshots:
=> 1570 show request id to school and rb users

app/views/responsible_body/donated_devices/interest/disclaimer.html.erb, app/views/school/donated_devices/interest/disclaimer.html.erb, app/views/shared/_donated_devices_disclaimer.html.erb
Link to privacy notice on disclaimer page should go to previous page ("address" page) which has the data sharing information,  not the "Computers for Kids" privacy policy
Change link to go to correct page.
In the donated devices journey for both school and RB users, the "privacy notice" link on the "Disclaimer" page should take you to the previous page.
=> Privacy link should go to previous page (Address)

app/components/support/extra_mobile_data_request_component.rb, app/controllers/support/extra_mobile_data_requests_controller.rb, app/form_objects/support/extra_mobile_data_request_search_form.rb, app/helpers/view_helper.rb, app/policies/extra_mobile_data_request_policy.rb, app/views/support/extra_mobile_data_requests/_search_form.html.erb, app/views/support/extra_mobile_data_requests/index.html.erb, app/views/support/home/show.html.erb, config/locales/en.yml, config/routes.rb, lib/string_utils.rb, spec/features/support/finding_extra_mobile_data_requests_spec.rb, spec/lib/string_utils_spec.rb, spec/page_objects/support/extra_mobile_data_requests/index_page.rb, spec/policies/extra_mobile_data_request_policy_spec.rb
[Trello card 1571](https://trello.com/c/3SK2pEbr/1571-iterate-support-console-for-mno-requests) - We need a way for support users to be able to find individual mobile data requests that they have been contacted about by the users, whilst not exposing personally-identifying information if it is at all possible to avoid doing so.
In discussion with @fofr we agreed to try a limited redaction that would just expose (say) the first character of account holder name, and the last 4 digits of the mobile number.  
* add a new top-level support section to find & list mobile data requests
* add a basic search form to allow filtering of the list
* add a policy to only allow support users to view this list - explicitly _excluding_ any Computacenter users who may also have read-only access to support
I …
=> 1571 iterate support console for mno requests

app/models/csv_data_file.rb, spec/controllers/mno/extra_mobile_data_requests_csv_update_controller_spec.rb, spec/fixtures/files/extra-mobile-data-request-utf8.csv, spec/fixtures/files/extra-mobile-data-request-windows-1252.csv
Three reported issues uploading CSV files of ExtraMobileDataRequest status updates. After quite a lot of investigation (see [Trello card 1588 - Three having issues uploading CSV](https://trello.com/c/2qAlEv4C/1588-three-having-issues-uploading-csv) ) it looks like a character encoding problem.
Full details are in the Trello card, but the TL;DR version - the CsvDataFile class assumes all CSV files are in windows-1252 character encoding. This normally just works and transcodes automatically, but Three's existing requests contain a particular record with a name containing several accented characters. These characters are correctly encoded on our database and in the generated CSV file in UTF-8, but have no valid representation in windows-1252. 
So if you try to download Three's data file and …
=> [1588] remove forcing of Windows-1252 character encoding in imported CSV files

spec/services/donated_device_requests_exporter_spec.rb
I saw an intermittent spec failure due to what looks like a time rounding issue:
```
1) DonatedDeviceRequestsExporter when given a filename includes the request information in the CSV file
Failure/Error: expect(record.school.created_at.to_s).to eq(request['created_at'])
expected: "2021-02-19 16:08:52 +0000"
got: "2021-02-19 16:08:51 +0000"
```
Although the error goes away on re-run, it shouldn't be happening in the first place
* change the comparison to use `be_within(1.second).of(...)` to allow for the very occasional rounding edge case
=> fix edge case in occasional spec fail

app/controllers/support/service_performance_controller.rb, app/policies/support/service_performance_policy.rb, app/services/exporters/mno_requests_csv.rb, app/views/support/service_performance/_mobile_data_requests.html.erb, config/routes.rb, spec/controllers/support/service_performance_controller_spec.rb, spec/services/exporters/mno_requests_csv_spec.rb
- https://trello.com/c/RyV99paX/1473-improve-mno-reporting-add-download-anonymised-request-data
- Add button in service performance dashboard - see screenshot
- This downloads a CSV of all mno requests minus any personally identifiable info
- Navigate to service performance dashboard and view connectivity tab
- Download csv
- CSV should show all mno requests
- CSV should not have any personally identifiable info
=> [1473] Add anonymised mno requests csv download

app/views/support/home/show.html.erb, spec/features/support/finding_extra_mobile_data_requests_spec.rb
When a user has permission to access support, but not to see `ExtraMobileDataRequests`, the support home page is showing a debug output statement.
Remove the output statement
Add a case to the feature spec to test the permissions
=> remove debug output

app/models/extra_mobile_data_request.rb, spec/models/extra_mobile_data_request_spec.rb
[Trello card 1478](https://trello.com/c/k6UsEZa6/1478-mno-prevent-duplicate-requests-part-2) - Despite there being code to look for the existence of `ExtraMobileDataRequests` for the same name & number (within the scope of school, RB, mobile network etc) we're still seeing a lot of duplicates making it through to the MNOs. This is causing them wasted time & frustration.
On a closer look, the code that normalises the phone number was running `before_save`, which is called _after_ validation. So if a user submits a phone number with spaces in, the first will be normalised on save, then the second will still pass validation as it's only looking for the exact phone number as entered, not the normalised version.
Change the normalising hook to `before_validation`
Add a spec for this behaviour
=> [1478] fix edge case allowing duplicating ExtraMobileDataRequests

app/controllers/support/zendesk_statistics_controller.rb, app/policies/support_policy.rb, app/services/zendesk_macro_export_service.rb, app/services/zendesk_service.rb, app/views/support/home/show.html.erb, app/views/support/zendesk_statistics/_macros.html.erb, app/views/support/zendesk_statistics/index.html.erb, config/locales/en.yml, config/routes.rb, config/settings.yml, spec/controllers/support/zendesk_statistics_controller_spec.rb, spec/services/zendesk_macro_export_service_spec.rb
Originally this feature was developed using the nodejs API client but seeing as more people are requesting this information and finding it useful, it seems like a good feature to include in the service itself so that any support agents could export this live data from Zendesk without asking me to run it for them.
- Add a new section at the bottom of the support agent home page
- Clicking the heading fetches and downloads the latest macro data
=> Allow support agents to export zendesk macro data

Procfile, app.json, app/controllers/sign_in_tokens_controller.rb, app/services/feature_flag.rb, app/services/personas/support_user.rb, app/services/personas/trust_with_schools.rb, lib/tasks/personas.rake, spec/features/signing_in_as_different_types_of_user_spec.rb
-  https://trello.com/c/cNeHTPti/1597-add-personas-to-heroku-environments-for-user-testing
- Modify heroku setup to start sidekiq worker. Since I added the flash messaging afterwards this change isn't actually needed but I decided to leave it as it maybe useful in the future.
- Heroku nows loads test personas into the database
- Users can then login as these personas in the heroku review apps
- Sign in links are then presented back as flash messages
- View the review app of this PR https://dfe-ghwt-pr-1313.herokuapp.com/
- Sign in as the different 3 personas `support.user.1@example.com`, `school.user.1@example.com`, `trust.user.1@example.com`
=> [1597] Add test personas for heroku

app/views/pages/how_to_access_the_get_help_with_technology_service.html.erb, app/views/pages/what_to_do_if_you_cannot_get_laptops_tablets_or_internet_access_from_dfe.html.erb, app/views/sign_in_tokens/email_not_recognised.html.erb, app/views/sign_in_tokens/sign_in_only.html.erb, config/locales/en.yml, config/routes.rb
[Trelllo card](https://trello.com/c/YGRbFY6Q/1405-support-users-who-cannot-sign-in-to-the-service)
The support team have data on high volumes of request coming from users who can't access the service.
Improve content to give clarity to the existing sign-in flow.
Adds a page to give guidance for users who could have an account but don't
Adds a page for users who can't access the service.
Sign in using an email address that the service doesn't recognise.
=> Guidance for people who don't have access to or cant use our service

app/models/user.rb, spec/models/user_spec.rb
- https://trello.com/c/SSUuQz97/1613-deleted-users-causing-referential-integrity-issues-in-email-audits
- When a user is destroyed, also destroy their `email_audits`
- Otherwise null pointers will cause certain pages to not load
- Find or create a user with an email audit
- Destroy the user
- Their email audits should also be removed from the database
=> [1613] email audits destroyed along with user

app/views/pages/computers_for_kids_privacy_notice.html.erb, app/views/shared/_privacy_notice_text.html.erb, spec/features/view_pages_spec.rb
- https://trello.com/c/BZGUxBqV/1621-add-test-for-guidance-pages
- Add missing test coverage for static pages
- Pages were missing `<h1>`
- Therefore heading levels have been slightly tweaked
- all static pages covered by tests
- all static load and look correct
=> [1621] Test and tweak static pages

app/controllers/school/internet/mobile/bulk_requests_controller.rb, app/controllers/school/internet/mobile/extra_data_requests_controller.rb, app/controllers/school/internet/mobile/manual_requests_controller.rb, app/models/extra_mobile_data_request.rb, app/models/mobile_network.rb, app/models/school.rb, app/views/school/home/show.html.erb, app/views/school/internet/home/show.html.erb, app/views/school/internet/mobile/bulk_requests/new.html.erb, app/views/school/internet/mobile/manual_requests/new.html.erb, app/views/school/welcome_wizard/what_happens_next.html.erb, app/views/shared/internet/_mno_guidance.html.erb, app/views/shared/internet/_mno_information.html.erb, app/views/support/schools/show.html.erb, spec/controllers/school/internet/mobile/bulk_requests_controller_spec.rb, spec/controllers/school/internet/mobile/extra_data_requests_controller_spec.rb, spec/controllers/school/internet/mobile/manual_requests_controller_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb, spec/services/extra_data_request_spreadsheet_importer_spec.rb
- https://trello.com/c/LlvyVpmg/1548-mno-rollout-to-fe-by-weds-17th
- Adds MNO to FEs
- `School#hide_mno?` has now been re-purposed. Previously these schools could not see the MNO, they now can. Instead the flag is used to determine if only a subset of mobile networks are permitted
- On manual requests remove excluded networks for FE
- On bulk upload show errors if user attempt to upload FE excluded network. we should be rejected and not persisted 
- Probably want to side by side compare current school journey vs FE journey
- For FE flag is `hide_mno` set to true. as there are some FE with `hide_mno` false as they have under 16s
- Perform manual request
- School journey should see all available networks
- FE journey should see all networks minus giffgaff and o2
- Perform bulk upload
- …
=> [1548] FE MNO

app/views/pages/how_to_access_the_get_help_with_technology_service.html.erb
Link on app/views/pages/how_to_access_the_get_help_with_technology_service.html.erb is a mail to but the contact form is now the default way for users to contact us' – @Lloyd-K 
Link goes to the contact form.
visit /how-to-access-the-get-help-with-technology-service
=> changes link from mail:to to support_path

app/views/layouts/page_with_toc.html.erb, spec/features/start_journey_spec.rb
https://trello.com/c/WFtlnHwp/1611-check-metadata-on-platforms-and-edtech-guidance-pages
Two of our second level pages had missing page titles which is why they were only displaying the service name in the tab.
Visit the following links and the browser tab copy should mirror the h1 copy
- https://dfe-ghwt-pr-1353.herokuapp.com/digital-platforms
- https://dfe-ghwt-pr-1353.herokuapp.com/EdTech-demonstrator-programme
=> Add missing page titles to two second level pages

Makefile
[Trello card 1617](https://trello.com/c/A4R5tPm1/1617-provide-an-easier-way-to-scp-files-from-instances) - it's currently awkward transferring files to and from server instances (e.g. for exported data dumps). This can lead to insecure workarounds which are best avoided. 
Add `upload` and `download` Makefile tasks, which use `scp` to transfer files to & from named container instances
```
make dev upload LOCAL_PATH=/some/local/file REMOTE_PATH=/tmp/
make dev download LOCAL_PATH=/tmp/ REMOTE_PATH=/some/remote/filepath
make prod download  LOCAL_PATH=/tmp/ REMOTE_PATH=/some/remote/filepath INSTANCE=2 PROCESS=web
```
=> [1617] add upload & download Makefile tasks

app/components/extra_mobile_data_request_status_component.rb, app/components/extra_mobile_data_request_status_details_component.html.erb, app/models/extra_mobile_data_request.rb, config/locales/en.yml, spec/controllers/mno/extra_mobile_data_requests_controller_spec.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb
[Trello card 1634](https://trello.com/c/why6PX23/1634-add-a-new-status-for-extramobiledatarequest-problemduplicate) - We've had a lot of duplicate requests in the system, due at least in part to a bug fixed in #1329. I've removed most of the duplicate requests where it was clear which ones should be kept and which deleted, but there will still be some (around a couple of hundred) where it was not clear. 
MNOs have been using various statuses for the duplicates - some `problem_no_match_for_number`, some `problem_ineligible`, some `problem_other`, etc - but it would be much clearer for everyone involved if they had an explicit `duplicate` status to use for them.
Add `problem_duplicate` status to `ExtraMobileDataRequests`
Needs content review from @Lloyd-K or @emmajhf 
Screenshots:
=> [1634] add duplicate status for ExtraMobileDataRequests

app/helpers/view_helper.rb, app/models/school.rb, app/models/school_link.rb, app/services/school_update_service.rb, app/views/support/responsible_bodies/show.html.erb, app/views/support/schools/show.html.erb, config/locales/en.yml, db/migrate/20210224145258_create_school_links.rb, db/schema.rb, spec/helpers/view_helper_spec.rb, spec/services/school_update_service_spec.rb, spec/views/support/schools/show.html.erb_spec.rb
- https://trello.com/c/A7CZ5t0K/1449-support-improvement-link-predecessor-and-successor-schools
- Adds a new model `Relation` and table 'relations'
- This stores relationships between schools from GIAS
- These are added when a school is opened from the web interface which hooks into the service objects
- Added a new tab when support views a school. this shows the related schools 
No related schools
A closed school
Opened school
- Open a school. best option is academisation which closes another school in the process
- View the closed school
- Should link to new school
- View new school
- Should link to old school
=> [1449] Opening schools adds related schools

app/jobs/notify_computacenter_of_latest_change_for_user_job.rb, app/models/computacenter/service_now_user_import_api/import_user_change_request.rb, app/models/computacenter/user_change.rb, app/models/computacenter/user_change_generator.rb, app/services/create_user_service.rb, app/services/feature_flag.rb, db/migrate/20210211092428_add_rb_user_to_user_change.rb, db/schema.rb, spec/models/computacenter/service_now_user_import_api/import_user_change_request_spec.rb
[Trello card](https://trello.com/c/EWxSCmOl/1410-investigate-putting-an-rb-access-flag-on-all-sat-users)
[Part 1 PR](https://github.com/DFE-Digital/get-help-with-tech/pull/1288)
Part 2 to tie in passing the `rb_level_access` flag to Computacenter to indicate that a user should have RB level access at Techsource.
There is no front-end exposure of this attribute so far. I think this might get complex as we expose and edit user info in several places so it will need design/content input. The value is also dependent on the `orders_devices` value as it will only be passed to CC when that is set and the user has a techsource account and has seen the privacy statement.
Adds the `cc_rb_user` and `original_cc_rb_user` to the `Computacenter::UserChange` model
Passes that value to the CC API with …
=> 1410 rb access flag for cc part 2

app/controllers/support/users_controller.rb, spec/controllers/support/users_controller_spec.rb
- https://trello.com/c/ZYKzLXeR/1655-when-deleting-a-user-ensure-they-cannot-order
- On soft deleting users set `orders_device` to false
- This is so they do not contribute to the count of TechSource accounts per org
- This way should they be re-instated they do not automatically go back into the pool of TechSource accounts causing too many accounts per org
- Soft delete a user that can order devices
- Should set their `deleted_at` timestamp and toggle `orders_devices` to false
=> [1655] On deleting user, orders_devices => false

db/migrate/20210302150630_add_excluded_fe_network.rb, db/schema.rb
- https://trello.com/c/aaURe4i9/1638-tidy-up-mno-fe-only-providers-to-user-db-flag
- Related to https://github.com/DFE-Digital/get-help-with-tech/pull/1308#discussion_r583609455
- This adds a column so certain networks can be flagged for FE exclusion
- This is a 2 part change
- Second change will hook this in once data is in place
n/a
=> [1638] Add flag for excluded FE mobile networks

app/models/preorder_information.rb, spec/models/preorder_information_spec.rb, spec/services/school_order_state_and_cap_update_service_spec.rb, spec/support/school_creator.rb
This method would progress statuses of PreorderInformation when a school had ordered _some_ of its devices. This PR fixes a bug where we weren't taking into account router devices.
=> Fix infer_status to accommodate coms devices

.rspec_parallel
- Uneven parallel test run times compared to each thread/process
- Add `.rspec_parallel`
- Logs runtime to file so future run times should be more even
- Run the tests in parallel
- Test run times should be more even and therefore hopefully overall quicker
=> Add .rspec_parallel to even test run times

app/models/extra_mobile_data_request.rb, spec/models/extra_mobile_data_request_spec.rb
[Trello card](https://trello.com/c/DVJGycEu/1643-link-account-type-status-into-duplicate-requests-for-data-increase) - currently, when a user is entering an `ExtraMobileDataRequest` (or several), the `contract_type` is not taken into account. This means that if a user initially put in the wrong contract_type, the system will not let them resubmit with the correct contract_type
.
Include `contract_type` in the check for whether an ExtraMobileDataRequest has already been made.
=> [1634] add contract_type to the check for ExtraMobileDataRequest uniqueness

app/views/school/devices/can_order.html.erb, app/views/school/devices/can_order_awaiting_techsource.html.erb, app/views/school/devices/cannot_order.html.erb, app/views/school/devices/school_can_order_user_cannot.html.erb, app/views/shared/_stock_levels.html.erb
To prepare for limited stock, we need to rewrite these sections to:
- make it clear what device types are out of stock, or low on stock
- provide easy access to information about different device types (but not necessarily recommend any alternatives)
- be transparent about devices that will come back into stock
- soften language about being certain what device types are needed (as their first and second choices may be unavailable)
=> [1590] Re-write 'stock availability' and 'before you order' content

app/services/allocations_exporter.rb, spec/services/allocations_exporter_spec.rb
- https://trello.com/c/EHwrsQLG/1628-list-of-fe-providers-on-the-service
- After a school search when exporting data to csv include router data
- Sign in as support agent
- Perform a schools search with multiple schools preferably with combination of devices and router allocations, in and out of virtual pools
- Export the data to csv
- Should see router data along with device data
=> [1628] Include routers in allocations csv export

app/controllers/support/responsible_bodies_controller.rb, app/views/support/responsible_bodies/show.html.erb, spec/controllers/support/responsible_bodies_controller_spec.rb, spec/features/support/viewing_responsible_body_info_spec.rb, spec/page_objects/support/responsible_body_page.rb, spec/views/support/responsible_bodies/show.html.erb_spec.rb
[Trello card](https://trello.com/c/nbI7zpoQ/1568-do-not-show-closed-schools-in-schools-list-for-rbs-might-be-virtual-cap-related)
Do not include closed schools in the school list shown in the RB view of the support area. As an aid for support, I've moved closed schools into a separate table under the list of open schools with some additional tags to indicate whether the school is (still) in the RBs virtual cap pool or not and whether there are any users still associated with the school.
Remove closed schools from current list of RB's schools
Add closed schools under the school list
Added indicator tags to show whether the school is still in the virtual cap pool and/or still has users still associated with it.
The Allocation, Cap and Devices Ordered are the 'raw' values not the virtual cap …
=> Split closed schools off into separate table for support RB view

app/helpers/view_helper.rb, app/services/feature_flag.rb, app/views/responsible_body/devices/home/tell_us.html.erb, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, app/views/responsible_body/devices/orders/cannot_order_yet.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb, app/views/school/devices/cannot_order.html.erb, app/views/school/welcome_wizard/order_your_own.html.erb, app/views/school/welcome_wizard/techsource_account.html.erb, config/locales/en.yml, spec/features/responsible_body/ordering_devices_in_pool_spec.rb, spec/features/responsible_body/ordering_devices_spec.rb, spec/features/school/order_devices_spec.rb
Make it the default, and remove older alternatives.
We will not be going back to an Education Settings approach based on partial closures.
Part of https://trello.com/c/xCvrbaea/1561-service-updates-preparing-for-school-reopening
=> [1561] Remove schools_closed_for_national_lockdown flag

app/models/mobile_network.rb, app/views/shared/mno_offer_details/_smarty.html.erb, app/views/shared/mno_offer_details/_three.html.erb
- https://trello.com/c/vvjcnuzc/1667-add-three-and-smarty-to-fe-extension-for-mno-offer
- Copy changes to enable Three and SMARTY as FE mnos
- No longer exclude Three and SMARTY as FE mnos
- Guidance should now list Three and SMARTY as FE mnos
=> [1667] Add three and smarty as FE mno

app/components/support/gias/school_details_component.rb, spec/components/support/gias/school_details_component_spec.rb
[Trello card](https://trello.com/c/vUnEnAPE/1557-gias-updates-should-show-link-to-datastage-successor-from-predecessor-when-successor-has-already-been-added-and-is-on-the-servic) Fix for issue when viewing a closed school, if there is a successor the 'View' link is to the staged 'Schools to add' school even if that school has already been added and is not in the schools to add list.
Fix links so if school already exists in service it is used instead of staged version.
Slightly complex to set up, you need:
- a school that has been created in your local db
- a school that can be the predecessor of that school that exists in your local db
- DataStage versions of both schools (one with status 'open' one with status 'closed')
- DataStage::SchoolLink set up associated with the closed school as …
=> Fix issue with link when school exists

app/views/responsible_body/donated_devices/interest/opted_in.html.erb
For RBs the opted in confirmation page is one level deeper, coming off the "Get laptops" page
=> Add missing breadcrumb from Daily Mail opted in page

app/components/device_count_component.rb, app/views/responsible_body/devices/schools/show.html.erb
Remove the "Order" button from school pages for responsible bodies that have devolved ordering to schools.
Also update the prefix to highlight that "they" ordered, rather than the RB
| Before | After |
|--|--|
|![Screen Shot 2021-03-03 at 16 43 39](https://user-images.githubusercontent.com/319055/109840506-19f26800-7c40-11eb-8800-90378bb9df63.png)|![Screen Shot 2021-03-03 at 16 43 16](https://user-images.githubusercontent.com/319055/109840501-1828a480-7c40-11eb-8d6f-1fa9f7468a38.png)|
=> Do not show order action on devolved schools page

app/helpers/view_helper.rb, app/views/responsible_body/internet/mobile/manual_requests/new.html.erb
These have come about from having two templates for pages that are otherwise essentially the same.
- Add missing note about FE to the RB form
- Remove hint text from list of networks from the RB form
| Before | After |
|--|--|
|![Screen Shot 2021-03-03 at 15 13 25](https://user-images.githubusercontent.com/319055/109826972-3f2ca980-7c33-11eb-8fc1-54364e2d4140.png)|![Screen Shot 2021-03-03 at 15 13 36](https://user-images.githubusercontent.com/319055/109826968-3dfb7c80-7c33-11eb-9c90-5eefc11884be.png)|
=> Fix inconsistencies between school and RB MNO form

app/components/support/school_details_summary_list_component.rb
- https://trello.com/c/U8kj33G3/1019-school-summary-list-contact-key-incorrect
- Do not use contact title for headteacher simply use `Headteacher`
- View a school with headteacher contact with a custom title
- Should show `Headteacher` not custom title
=> [1019] Fix headteacher key in summary list

app/models/mobile_network.rb, spec/features/school/extra_mobile_data_requests_spec.rb, spec/services/extra_data_request_spreadsheet_importer_spec.rb
- https://trello.com/c/aaURe4i9/1638-tidy-up-mno-fe-only-providers-to-user-db-flag
- Refactor hard coded FE mobile networks
- Instead use a flag from the database which has already been put in place
- There should be no behavioural change of the app
=> [1638] Refactor out hard coded FE mobile networks

app/helpers/view_helper.rb, app/views/layouts/application.html.erb, app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb, app/views/shared/_link_to_survey.html.erb, app/views/support_tickets/thank_you.html.erb, app/webpacker/styles/application.scss, config/locales/en.yml, spec/views/layouts/multipage_guide.html.erb_spec.rb
https://trello.com/c/Dupc9WB4/1646-create-access-to-evaluation-survey-in-the-account-and-at-the-end-of-the-contact-form
- Change phase banner copy and link to survey if the user is signed in
- Display the survey link on the School/RB home page when the user signs in
- Display the survey link on the contact form thank you page if the user is signed in
- Visit https://dfe-ghwt-pr-1363.herokuapp.com/
- Login as `school.user.1@example.com`, `trust.user.1@example.com` and `support.user.1@example.com`
**As a school/trust user**
- User home page should include a sidebar asking the user for feedback and include a link to the survey.
- Phase banner should be updated to  use the new feedback copy and should link to the survey
- Go to "Contact us" link in the footer and submit a query (don't worry …
=> Add feedback copy and link to survey

app/views/layouts/application.html.erb
A recent change has resulted in a [build failure on `main`](https://github.com/DFE-Digital/get-help-with-tech/runs/2032233362?check_suite_focus=true) with this error:
```
rake aborted!
ActionView::Template::Error: undefined method `persisted?' for nil:NilClass
/var/www/get-help-with-tech/app/views/layouts/application.html.erb:63
```
On investigation, it's because the current_user is nil when running the rake task to pre-render the 429 error page to a flat file, and new code in application.html does not account for this.
Add a check to `layouts/application.html` for whether there is a signed in user
```
$ bundle exec rake release:render_429_to_file
```
You should see something like:
```
Rendered 9889 bytes to (...)/public/429.html
```
...and not an error
```
=> fix issue pre-rendering 429.html in production build

app/services/school_update_service.rb, spec/services/school_update_service_spec.rb
Problem was seen when rebuilding dev database that the `SchoolUpdateService` was not correctly looking up / mapping the `responsible_body_name` from the school to create and this was causing errors to be raised.
Use the `DataStage::School#responsible_body` method to correctly map the `responsible_body_name`
=> Fix issue with finding RBs with mapped names

app/services/school_update_service.rb, spec/services/school_update_service_spec.rb
[Trello](https://trello.com/c/CVq8JC4o/1569-prevent-gias-updates-from-add-closing-schools-where-virtual-caps-are-involved)
We haven't worked out how to deal with removing schools from virtual cap pools so prevent the GIAS updates from moving allocation from predecessor school when adding a successor school if predecessor is in a virtual cap pool.
Prevents moving any remaining allocation from school being closed to new school in `SchoolUpdateService`
Some setup needed:
* A new school to be added in DataStage
* A predecessor in the DataStage that should be closed
* The corresponding active (predecessor) school with a some remaining allocation in a virtual pool
Adding the new school via `SchoolUpdateService#create_school!` should not move any of the predecessor school's remaining allocation …
=> Prevent allocation change during gias update when in virtual cap pool

Procfile, app.json
[Trello card 1669](https://trello.com/c/iYPafQTH/1669-remove-the-worker-from-heroku-which-runs-overnight-jobs-to-import-school-data-from-gias) When a Heroku review app lives for more than a few hours, it can
trigger the overnight GIAS updates. This brings in up to 70k rows
to the DB, and triggers warnings from Heroku about the database
size exceeding the maximum available on the free plan.
Since we are now flashing login token links to the user on Heroku,
there's no reason that we can think of for actually keeping the
worker process for review apps.
Remove the worker process.
Click around the review app for this PR, make sure it works
=> [1669] Disable worker in Heroku review apps

app/components/extra_mobile_data_request_status_details_component.html.erb, app/views/shared/mno_offer_details/_three.html.erb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb
- https://trello.com/c/zMgcRTLQ/1614-mno-service-and-ghwt-guidance-content-changes-for-requests-with-ineligible-other-problem-and-unavailable-status
- Copy changes around MNO error statuses
- No typos
=> [1614] MNO status copy tweaks

app/views/support_tickets/academy_details.html.erb, app/views/support_tickets/check_your_request.html.erb, app/views/support_tickets/college_details.html.erb, app/views/support_tickets/contact_details.html.erb, app/views/support_tickets/describe_yourself.html.erb, app/views/support_tickets/local_authority_details.html.erb, app/views/support_tickets/school_details.html.erb, app/views/support_tickets/support_details.html.erb, app/views/support_tickets/support_needs.html.erb
Firstly when this change went in the documentation was misinterupted
and the option should have been set to false. According to the
documentation now prevent double click submits are enabled by default (top of page).
https://govuk-form-builder.netlify.app/form-elements/submit/
https://govuk-form-builder.netlify.app/form-elements/submit/#input-erb-generating-a-submit-button-without-double-click-prevention
Thank you @asmega for picking up on this bug. 👍
=> Fix prevent double click submits

app/views/responsible_body/devices/orders/specific_circumstances.html.erb, app/views/school/devices/cannot_order_as_reopened.html.erb
These pages shouldn't be seen by schools, but just in case – remove references to reporting closures.
=> [1631] Remove references to closures and self-isolating groups

app/models/extra_mobile_data_request.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb, spec/models/extra_mobile_data_request_spec.rb, spec/services/extra_data_request_spreadsheet_importer_spec.rb, spec/shared/filling_in_forms.rb
- https://trello.com/c/AGdMGI1F/1661-investigate-sample-spreadsheet-rows-present-as-extramobiledatarequests
- Spreadsheet uploads with example number are rejected
- Validations added so users can see the problem to rectify
- Sign in as school or RB
- Download the MNO template spreadsheet
- Change the name of the example user in the template spreadsheet and upload
- Should see validation error message about example number
=> [1661] Reject example mobile number

app/controllers/application_controller.rb, app/controllers/responsible_body/internet/home_controller.rb, app/controllers/responsible_body/internet/mobile/extra_data_requests_controller.rb, app/models/responsible_body.rb, app/views/responsible_body/home/show.html.erb, spec/features/responsible_body/home_spec.rb
LAs, even those that have devolved to all schools, must sometimes request mobile data on behalf of students not in school. For example – pupils who aren't in a mainstream school as they're awaiting an EHCP.
=> Enable MNO offer for all local authorities

app.json
Heroku was failing to build review apps:
This was introduced from a recent change we made to this file to remove the worker from heroku review apps (9818facafdbe910eaa8253a45130542b0a080dd5)
- Review apps should work (Visit https://dfe-ghwt-pr-1404.herokuapp.com/)
=> Fixes malformed app.json for heroku review apps

app.json
- Deploying to heroku without redis causes the app to raise errors when it attempts to write to redis which is not present
This reverts commit 9818facafdbe910eaa8253a45130542b0a080dd5.
- Heroku redis is needed so jobs can be written to storage
- The app expects redis to be present so jobs can be written otherwise errors occur
- The worker itself will not run so none of these jobs will be executed
- Able to sign into review app successfully
- Prior to this change it throws an error
=> Revert remove redis from heroku

app/controllers/mno/extra_mobile_data_requests_controller.rb, app/views/mno/extra_mobile_data_requests/index.html.erb, config/routes.rb
[Trello card](https://trello.com/c/sUXFoyqW/1407-can-the-index-findrequests-method-in-mnoextramobiledatarequestcontroller-be-more-dry)
Address an issue found during a [PR review](https://github.com/DFE-Digital/get-help-with-tech/pull/1190) that we didn't have time to fix at the time.
Refactor the `ExtraMobileDataRequestController` to make it more DRY. Incorporate the `find_requests` method into the `index` method to remove a bunch of duplication
The functionality to be able to search, view and update `ExtraMobileDataRequest`s as a MNO user should be the same.
=> Refactored find_requests method into the index method

app/services/personas/pentest_users.rb, lib/tasks/pentest_users.rake, spec/services/personas/pentest_users_spec.rb
We last had a pentest 6 months ago, at which point I created users manually. We're setting up for the next test, and the work involved in identifying appropriate organisations to link the users to has been fiddly enough that I don't want to do this manually every time.   
Add a rake task to create users of all required flavours given a name and email address.
`rake db:create_pentest_users NAME="Jane Doe" EMAIL_ADDRESS=jane.doe@example.com`
It will create users with suffixes of `+school`, `+responsible_body` etc, and return their suffixed email addresses.
If it can't find suitable schools or responsible bodies to link them to, it will raise an error and create nothing.
=> add task to create users for pentest

app/models/extra_mobile_data_request.rb, db/migrate/20210315133435_add_normalised_name_to_extra_mobile_data_requests.rb, db/migrate/20210315133757_populate_extra_mobile_data_requests_normalised_name.rb, db/schema.rb, spec/models/extra_mobile_data_request_spec.rb
[Trello card 1686](https://trello.com/c/y6UnyaGS/1686-store-and-detect-duplication-of-normalised-accountholdername-on-extramobiledatarequest) -  we're currently only looking for _exact_ matches of account_holder_name exactly as it was entered. In analysis for the first official publication of our success metrics, we found lots of closely-related names in the dataset - some all in upper or lower case vs mixed case, some with a middle name or title, or a dot after 'Mr.' vs not, etcetc . 
We should be able to help the situation by running a simple normalisation process.
* Migration to add the field `normalised_name` to `ExtraMobileDataRequest`
* Add a method to normalise the name on validation
* Change the current check for existing `account_holder_name` to instead check `normalised_name`
* …
=> [1686] store & detect duplication of normalised name for ExtraMobileDataRequests

db/migrate/20210315133757_populate_extra_mobile_data_requests_normalised_name.rb
The migration to populate `ExtraMobileDataRequest.normalised_name` is taking too long to run on prod, and this makes releases fail. 
Make the migration a no-op - I'll run the one-of operations from the console
=> remove body of migration that blocks releases

Makefile, README.md
For a while now, we've had the convenient command `make (env) ssh` for sshing to the first web process, but if you want to connect to a different instance and/or process, you have to run the more verbose `make (env) set_cf_target  && cf ssh (fully-scoped app name) --process (process) -i (instance)`.
Recently I added the `make (env) upload|download` tasks which support `PROCESS`and `INSTANCE` parameters - we should add the same support to the ssh command.
* support the same `PROCESS` and `INSTANCE` parameters that we allow in `make (env) upload|download`
* explicitly tell you which instance and process you're connecting to, to prevent confusion
* document the new parameters in  /README.md and remove some now-redundant lines
* also add documentation for the `make (env) upload|download` …
=> Allow ssh-ing to a specific PROCESS & INSTANCE from make

.rubocop.yml, app/controllers/notify_callbacks_controller.rb, app/controllers/support/email_audits_controller.rb, app/mailers/can_order_devices_mailer.rb, app/mailers/log_email_delivery_observer.rb, app/models/email_audit.rb, app/policies/email_audit_policy.rb, app/views/support/email_audits/index.html.erb, app/views/support/home/show.html.erb, config/locales/en.yml, config/routes.rb, config/settings.yml, db/migrate/20210304153213_add_gov_notify_id_to_email_audits.rb, db/schema.rb, spec/controllers/notify_callbacks_controller_spec.rb, spec/mailers/can_order_devices_mailer_spec.rb, spec/mailers/log_email_delivery_observer_spec.rb
- https://trello.com/c/w2iRzC2P/1668-spike-store-status-of-email-notifications-sent
- When sending emails via notify we attach attach a reference on the api call which is the `id` of the `EmailAudit`
- When notify sends back the callback sometime in the future it includes the above reference
- We then link the above reference to an existing `EmailAudit` and update the status
- Some emails we send do not create an `EmailAudit`
- In these cases when notify hits the callback endpoint we will create a new `EmailAudit`
- NOTE: Notify will also send us callbacks for emails sent via there web interface so any failed batched jobs will now be recorded by our app 
- Find a school with users and make them able to order, this should send an email
- Check `EmailAudit` table, …
=> [1668] Enable tracking of notify emails

app/components/device_count_component.html.erb, app/components/device_count_component.rb, spec/components/device_count_component_spec.rb
- https://trello.com/c/szUJw8JR/1720-do-not-show-0-of-0-routers-or-0-routers-available-when-the-org-has-no-router-allocation
- Do not show any zero allocations for the device count component
before
after
- Login as school user that can order
- Give them a zero device allocation
- Should not see `0 of 0`
- Give then a non zero router allocation
- Should continue to not see `0 of 0`
=> [1720] Hide 0 allocation on device count component

app/components/nav_component.rb, app/views/devices_guidance/how_to_order.html.erb, app/views/devices_guidance/index.html.erb, app/views/guide_to_collecting_mobile_information/_guide_contents.html.erb, app/views/layouts/_service_link.html.erb, app/views/layouts/multipage_guide.html.erb, app/views/layouts/page_with_toc.html.erb, app/views/pages/about_increasing_mobile_data.html.erb, app/views/pages/choosing_help_with_internet_access.html.erb, app/views/pages/how_request_4g_routers.html.erb, app/views/pages/how_to_access_the_get_help_with_technology_service.html.erb, app/views/pages/internet_access.html.erb, app/views/pages/what_to_do_if_you_cannot_get_laptops_tablets_or_internet_access_from_dfe.html.erb, app/views/support_tickets/academy_details.html.erb, app/views/support_tickets/check_your_request.html.erb, app/views/support_tickets/college_details.html.erb, app/views/support_tickets/contact_details.html.erb, app/views/support_tickets/describe_yourself.html.erb, app/views/support_tickets/local_authority_details.html.erb, app/views/support_tickets/parent_support.html.erb, app/views/support_tickets/school_details.html.erb, app/views/support_tickets/start.html.erb, app/views/support_tickets/support_details.html.erb, app/views/support_tickets/support_needs.html.erb, app/views/support_tickets/thank_you.html.erb, config/routes.rb
Pretty minor changes and might be easier to review per commit. Majority file changes relate to the refactoring of the `guidance_page_path` to `root_path
Visit https://dfe-ghwt-pr-1432.herokuapp.com/ and try login as 
- `support.user.1@example.com`
- `school.user.1@example.com`
- `trust.user.1@example.com`
You should not see the "Guidance" link in the header and click on the service name should take you to the service home page.
=> 1733 remove guidance link from header

app/controllers/support/remaining_device_counts_controller.rb, app/jobs/update_remaining_devices_job.rb, app/models/remaining_device_count.rb, app/services/remaining_devices_calculator.rb, config/routes.rb, config/sidekiq.yml, db/migrate/20210312133156_create_remaining_device_counts.rb, db/schema.rb, spec/factories/remaining_device_counts.rb, spec/factories/schools.rb, spec/models/remaining_device_count_spec.rb, spec/services/remaining_devices_calculator_spec.rb
[Trello card](https://trello.com/c/NBVc0nsi/1684-build-view-on-unclaimed-devices-count-per-day)
Record and display daily totals of unclaimed devices.
__NOTE__: the view of the unclaimed devices is not included in this PR, it will be done as part of the updates to the performance dashboard
Adds a new table/model `RemainingDeviceCount` to record daily totals
Adds `RemainingDevicesCalculator` service to calculate the totals
Adds `UpdateRemainingDevicesJob` which is scheduled to record the daily total at 11:55pm
Adds ability to download a CSV of all `RemainingDeviceCount` records
The current unclaimed totals can be retrieved via `RemainingDevicesCalculator.new.current_unclaimed_totals`. This returns a `RemainingDeviceCount` instance that has not been persisted.
There are no safe guards to …
=> [1684] Build view of unclaimed devices count per day

app/controllers/responsible_body/donated_devices/interest_controller.rb, app/controllers/school/donated_devices/interest_controller.rb, app/models/donated_device_request.rb, db/migrate/20210317122937_add_completed_at_to_donated_devices.rb, db/schema.rb, spec/controllers/responsible_body/donated_devices/interest_controller_spec.rb, spec/controllers/school/donated_devices/interest_controller_spec.rb, spec/models/donated_device_request_spec.rb
- https://trello.com/c/6qIGYe5w/1742-add-completed-at-time-to-donated-device-requests
- This is part 1 of 2 changes in order to provide continuity of service
- First part...
- Add `completed_at` column on `DonatedDeviceRequest` and index it
- This is set to the time when the user completes the request
- Second part will involve the following...
- Data migration to backfill `completed_at` on previous requests based on `created_at`
- 2 changes to `DonatedDeviceRequestsExporter`
- `created_at` value will use `completed_at` instead
- ordering of requests will now use `completed_at`
- Sign in as school or rb user
- Create a new donated device request
- `completed_at` should be populated with the current time
=> [1742] Add completed_at on DonatedDeviceRequest

app/services/donated_device_requests_exporter.rb, spec/factories/donated_device_requests.rb, spec/services/donated_device_requests_exporter_spec.rb
- https://trello.com/c/6qIGYe5w/1742-add-completed-at-time-to-donated-device-requests
- Part 2 of 2
- Part 1 can be found in 2d5e22849a766b40ca02fc0e56a18f13c34e6fe5
- CSV `created_at` value is now `completed_at` to better reflect when request was made
- Change order of donated device requests order by `completed_at`
- Caveats of this fix is if the user changes an existing request it will be bump other requests to the bottom so may cause a record to be consumed again
- Sign in as school user 1
- Start the donated device request process but do not finish
- Sign in as school user 2
- Start the donated device request process and finish
- Sign in as school user 1
- Finish the donated device request process
- Download CSV export
- User 2 request should come first then user 1
=> [1742] Change DonatedDeviceRequest csv order

app/views/responsible_body/donated_devices/interest/opted_in.html.erb, app/views/school/donated_devices/interest/opted_in.html.erb, app/views/shared/_sim_offer.html.erb
Once users have opted into the Daily Mail offer, we include a nudge about a similar offer that's making Vodafone SIM cards available to schools.
We've kept this in the Daily Mail section to keep it clear that this is not a DfE offer.
https://trello.com/c/jsmJNLjm
=> Add Vodafone SIM offer to Daily Mail opted-in page

app/controllers/notify_callbacks_controller.rb, app/views/support/email_audits/index.html.erb, spec/controllers/notify_callbacks_controller_spec.rb
- https://trello.com/c/w2iRzC2P/1668-spike-store-status-of-email-notifications-sent
- Notify callback populates `email_address` field on the audit
- link to user from the email audits index page view
```
curl --header "Content-Type: application/json" \
--header "Authorization: Bearer password" \
--request POST \
--data '{"id":"GUID","reference":"EMAIL_AUDIT_ID","to":"EMAIL_ADDRESS","status":"delivered","notification_type":"email"}' \
http://localhost:3000/notify_callbacks
```
- Use the above for an email address of user that exists, otherwise it is discarded
- `email_address` field should be populated
- View email audits index view
- Should be able to click thru on audit to user page
=> [1668] Email audit tweaks

app/models/extra_mobile_data_request.rb, app/models/reportable_event.rb, db/migrate/20210317144941_add_reportable_events.rb, db/schema.rb, spec/models/extra_mobile_data_request_spec.rb, spec/models/reportable_event_spec.rb
Full context is in the [Trello card](https://trello.com/c/bl6bdgcM/1708-improve-the-way-we-report-on-significant-events-by-recording-them-as-reportable-events) - TL;DR is that when we're running reports, we can't rely on current status & updated_at as a reliable indicator of _when_ the current status was set. We need a better way of recording reportable events.
* Add reportable_events table and `ReportableEvent` model class
* Record `completion` events for `ExtraMobileDataRequests`
I'd like to run this as-is on production for a few days, just to double-check that the events are being recorded reliably when triggered by all known methods. Once we're happy that that's the case, I can add a migration to backfill completion events for the existing data, switch over the ad-hoc reporting code …
=> [1708] add reportable_events table & record EMDR completions

app/webpacker/styles/components/_start-page-banner.scss
https://user-images.githubusercontent.com/3441519/111643173-a5e6c100-87f6-11eb-923e-676d00e10877.mp4
https://user-images.githubusercontent.com/3441519/111643119-9a939580-87f6-11eb-94a1-55d5c3177e56.mp4
=> Focussed links on the start page banner have low contrast

app/services/remaining_devices_calculator.rb
https://ukgovernmentdfe.slack.com/archives/C01A7DVKE9J/p1616090224032500?thread_ts=1616089945.032200&cid=C01A7DVKE9J
The unclaimed devices calculation was not working as expected. Not 100% sure why, maybe a cartesian product issue when the SQL is generated.
Expanding the query to be more explicit results in the correct values when tested on the console in production.
Refactored the queries in `RemainingDevicesCalculator`
The refactored queries now produce the same result as hand crafted SQL on the prod rails console.
```
[1] pry(main)> SchoolDeviceAllocation
.std_device
.joins(school: :preorder_information)
.where(preorder_information: { who_will_order_devices: 'school' })
.where(school: { status: 'open'})
.sum('cap - devices_ordered')
=> 10155                          
[2] pry(main)> …
```
=> Refactored query into longer form as something wasn't calculating right

app/policies/impersonation_policy.rb, spec/views/support/users/show.html.erb_spec.rb
- https://trello.com/c/bJGKdBhW/1725-roll-out-impersonation-to-all-support-agents
- Impersonation available to all support users minus computacenter users
- Sign in as support user that is not third line
- Should be able to impersonate a user
- Sign in as a computacenter user with support capabilities
- Should not be able to impersonate someone
=> [1725] Give impersonation to all support users

config/initializers/rack_throttle.rb, config/settings.yml
[Trello card 1759](https://trello.com/c/kd2X19Xi/1759-check-that-rate-limiting-is-working-as-expected) - The pen test identified that the rate-limiting we have in place is not quite working as expected. The `rack-throttle` gem applies the limits at the `Rack::Middleware` layer, and the default configuration is to track limits in memory - which means that the thresholds are effectively per-container-instance as well as per-client per-second.  
Also, it looks like the paths for `sign-in` and `tokens` have changed since the rate-limiting was put in place, so the specific limits for generating and validating sign-in tokens were being ignored.
* allow `rack-throttle` to track limits in redis if it's configured, falling back to in-memory for local dev. This should give us true …
=> [1759] allow rack-throttle to use Redis & update sign-in paths

app/controllers/guides_for_parents_carers_students_controller.rb, app/views/devices_guidance/index.html.erb, app/views/guides_for_parents_carers_students/index.html.erb, app/views/layouts/multipage_guide.html.erb, app/views/pages/home_page.html.erb, config/locales/en.yml, config/routes.rb, spec/features/start_journey_spec.rb, spec/page_objects/guides_for_parents_carers_students/index_page.rb, spec/page_objects/pages/home_page.rb
We are restructuring the device guidance page and one of the changes is to remove this from the device guidance page and make it more prominent on the home page.
- build a second-level page for the guides
- Add a copy & link to the home page which will take the user to the new  to the new page
- Remove the heading copy relating to this guidance from the existing device guidance page
Visit https://dfe-ghwt-pr-1448.herokuapp.com/ to see the changes
=> Add "Guides for parents, carers & students" page

app/components/support/school_details_summary_list_component.rb, app/controllers/support/schools/opt_outs_controller.rb, app/form_objects/support/opt_out_form.rb, app/models/school.rb, app/models/school_can_order_devices_notifications.rb, app/views/support/schools/opt_outs/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20210318130347_add_opted_out_at_to_schools.rb, db/schema.rb, spec/controllers/support/schools/opt_outs_controller_spec.rb, spec/features/support/schools/opt_out_spec.rb, spec/models/school_can_order_devices_notifications_spec.rb
- https://trello.com/c/DegS78mW/1736-create-a-flag-in-service-to-not-contact-users-who-told-us-they-do-not-need-devices
- Added db column `opted_out_at` on `School`
- Support users can opt a school out of comms which will set the above value
- They can also remove the value to opt them back in
- `SchoolCanOrderDevicesNotifications` takes the above value into consideration and will not send any notifications if set
Support school show page when opted in (default state)
Change page on default state (opted in and about to opt them out)
Support school show page when opted out
- Find a school
- Should be opted in
- Opt them out
- Should be opted out
- Change order state so they get a nudge email
- Should no longer receive a nudge email
=> [1736] Support can opt school out of notifications

app/controllers/responsible_body/internet/base_controller.rb, app/models/responsible_body.rb, app/models/user.rb, app/services/personas/pentest_users.rb, app/services/personas/trust_with_schools.rb, spec/controllers/responsible_body/internet/mobile/extra_data_requests_controller_spec.rb, spec/factories/responsible_bodies.rb, spec/factories/users.rb, spec/features/responsible_body/extra_mobile_data_requests_spec.rb, spec/features/responsible_body/home_spec.rb, spec/features/responsible_body/submitting_a_spreadsheet_request_spec.rb, spec/features/responsible_body/submitting_an_extra_mobile_data_request_spec.rb, spec/features/support/viewing_service_performance_spec.rb, spec/services/personas/pentest_users_spec.rb
- https://trello.com/c/2EGJW2DV/1754-remove-inconnectivitypilot
- Remove any code using `in_connectivity_pilot` as it is no longer used or needed
- The db column has not been deleted but can be deleted once all code using it has been removed
- Sign in as centrally ordering RB
- Regardless of `in_connectivity_pilot` state should see internet access section
=> [1754] Remove in_connectivity_pilot code

db/migrate/20210323112956_rm_rb_connectivity_pilot.rb, db/schema.rb
- https://trello.com/c/2EGJW2DV/1754-remove-inconnectivitypilot
- From production:
```
ResponsibleBody.pluck(:in_connectivity_pilot).uniq
=> [true]
```
- Migration to remove db column
- No longer used therefore can be safely deleted
- Column is removed and app works as expected
=> [1754] Remove in_connectivity_pilot column

spec/support/controller_helper.rb
[Trello card](https://trello.com/c/xkJrktMj/1768-fix-intermittent-spec-failure-on-ci-in-schoolscontrollerspecrb) - we've recently been seeing an intermittent spec failure in `spec/controllers/schools_controller_spec.rb:29`. [Example failed run](https://github.com/DFE-Digital/get-help-with-tech/runs/2166825974?check_suite_focus=true#step:16:1919). We've also seen it in users_controller_spec.rb. The failure has been seen on several different PRs, and always goes away when re-run.
I have not been able to reproduce the failure locally yet, but on inspection the most likely mechanism I can see for this is that the `sign_in_as` method doesn't clear out the session. So there may be an  `impersonated_user_id` that just occasionally gets persisted between specs due to either a timing issue or some …
=> [1768] fix intermittent CI spec failure in schools_controller_spec

app/controllers/support/email_audits_controller.rb, app/models/email_audit.rb, app/views/support/email_audits/index.html.erb, app/views/support/home/show.html.erb, config/locales/en.yml, spec/controllers/support/email_audits_controller_spec.rb
- https://trello.com/c/4p5Bo5nW/1778-tweak-email-audits-to-show-only-problematic-emails
- Only show emails with delivery issues
- As we don't care about emails that were sent successfully
- Also added `Sent at` so triage is easier
- Sign as support user
- View email audits
- Should only show problematic ones
=> [1778] Email audits only shows problematic emails

app/components/support/percentage_tile_component.html.erb, app/components/support/percentage_tile_component.rb, app/helpers/view_helper.rb, app/models/school_device_allocation.rb, app/models/support/service_performance.rb, app/views/support/service_performance/_devices.html.erb, app/views/support/service_performance/_mobile_data_requests.html.erb, app/views/support/service_performance/_routers.html.erb, app/views/support/service_performance/_sign_ins.html.erb, app/views/support/service_performance/_who_orders.html.erb, app/views/support/service_performance/index.html.erb, app/webpacker/styles/_card.scss, config/locales/en.yml, spec/factories/schools.rb, spec/features/support/viewing_service_performance_spec.rb
[Trello card](https://trello.com/c/YqzQCGGs/1721-build-the-service-dashboard)
Implement the redesign of the service performance dashboard
New service performance dashboard.
There is a lot of complexity in here, switching between queries about devolved schools to responsible body's centrally managed schools, so checking the values displayed against the your local data, one tab at a time, is probably the way to review this.
=> 1721 build the service dashboard

app/models/local_authorities_in_england_register.rb
[Trello card](https://trello.com/c/1pnxPVA4/1766-find-an-alternative-authoritative-list-of-local-authorities-in-england) - The Register of Local Authorities in England, from which we were pulling an authoritative list of English LAs for import into the service, no longer exists. [The GOV.UK Registers service has been shut down, and all data moved to the National Archives and/or Github](https://dataingovernment.blog.gov.uk/2021/02/18/new-guidance-for-publishing-data/).  
Update the URL used to pull in the data to point to the cached copy in the National Web Archives - this means we do not need to make any other changes to the import code, as the format is exactly the same as before.
`bundle exec rake import:local_authorities_in_england`
=> [1766] use the national web archives cache of the local authorities register

Dockerfile
- https://trello.com/c/ygU488Vz/1785-fix-blocking-mimemagic-issue
- We need to install a gem via git as the source version includes a dependency with licensing issue
- In order to achieve this the docker image now needs git as a dependency
- `docker build .` succeeds
=> [1785] Add git so gems via git can be installed

app/components/support/school_details_summary_list_component.rb, app/controllers/support/schools_controller.rb, spec/components/support/school_details_summary_list_component_spec.rb
- https://trello.com/c/nc73aLHo/1710-expose-shipto-and-soldto-for-support
- Expose CC sold and ship to in support when viewing a school
When data not set
When data is set
- Should see ship and sold to values
=> [1710] Expose CC ship and sold to in support

app/models/support/service_performance.rb
The service performance page displays different device remaining totals to the `RemainingDeviceCount` list. This is because the `allocation` value has been used in the performance figures and the `cap` value in the remaining devices calculation and also closed schools are not included in the `RemainingDeviceCount` figures.
Use `cap` figures in calculations for remaining devices
Use the sum of separate devolved + managed schools totals to align with `RemainingDeviceCount` (managed has to consider closed schools, devolved calc does not)
=> Align totals in performance page using cap instead of allocation

app/controllers/mno/extra_mobile_data_requests_controller.rb, spec/controllers/mno/extra_mobile_data_requests_controller_spec.rb, spec/controllers/mno/extra_mobile_data_requests_csv_update_controller_spec.rb, spec/services/extra_mobile_data_request_status_importer_spec.rb
[Trello card](https://trello.com/b/JOgdYLg8/team-board-ghwt-service-team) - we have `after_save` hooks in place to record completion events when an `ExtraMobileDataRequest` is updated to `complete`. However, the most common usage pattern is  `bulk_update` which uses `update_all` to update many records at once in pure SQL, bypassing ActiveRecord hooks - so we're not actually recording events yet.
* Make the bulk_update method update the individual records one-by-one (there can never be more than 100 records per page, so this should not be too much of an overhead)
* Add explicit controller/service-level tests for correct behaviour 
* Log in as a user with a non-nil mobile_network_id, and some requests present on that MobileNetwork (you can use the `FakeDataService` to generate some if …
=> [1788] fix issue with ReportableEvents not being recorded

Gemfile, Gemfile.lock
Couldn't get `rails` commands to work with current version of `http-parser` on newer Apple Silicon.
Update `http-parser` version.
https://github.com/cotag/http-parser/issues/12
=> Specify version to allow development on M1 Apple Silicon

app/views/school/users/index.html.erb, app/views/school/welcome_wizard/will_other_order.html.erb, app/views/shared/_invite_someone_who_can.html.erb, config/locales/en.yml, spec/features/school/navigate_school_welcome_wizard_spec.rb
Context:
https://trello.com/c/V2czUlbD/1760-notify-or-display-a-privacy-notice-when-a-new-user-has-been-added
Because we sometimes send an invited user’s details to TechSource before they have signed-in and seen the privacy policy we need the inviting user to show the privacy policy to the invited user before they invite them.
Manage users:
School wizard flow (if ordering is devolved to the school and user has TechSource account):
We might want to consider removing the option to add a user from the school wizard flow because it doesn't seem likely a user will speak to the person they're inviting mid-flow.
=> Message telling users to get permission before inviting someone

app/controllers/sign_in_tokens_controller.rb, app/views/layouts/application.html.erb, spec/features/sign_in_token_behaviour_spec.rb
[Trello card](https://trello.com/c/yOWUsU32/1798-fix-undefined-method-isresponsiblebodyuser-for-nilnilclass) - there's some occasional edge case that results in an error on the sign_in_token sent page, whereby the user has a valid session but no `current_user`. On investigation, I found that this can happen when a user signs in successfully, but then goes back to the "Check your email" / sign-in token sent page. That page is uses the token given on the URL to assign `@current_user`, as there is no valid session yet, but if the user goes _back_ to an already-user token sent page, the token will not be valid anymore. 
Stop this edge case throwing an error
Add a spec example for it
Try signing in, then using your browser back button to go back to the 'Check your email' page.
It should not …
=> [1798] fix undefined method is_responsible_body_user? for nil

README.md
We added a ! to `SchoolUpdateService#create_school` in #1265. This PR updates the documentation to reflect that.
=> Update school staging instructions

Gemfile, Gemfile.lock, README.md
While on-boarding the new devs, it struck me that it would be useful to be able to generate Entity Relationship Diagrams on-demand.
* Add the `rails-erd` gem in development
* Add brief instructions to README.md
Review the `Generating an Entity Relationship Diagram` section in the README
Follow the instructions
If you get an ERD out of it, it's worked :)
=> Add rails-erd gem for drawing entity relationship diagrams

app/models/computacenter/tech_source.rb
https://trello.com/c/HTbLpJG3/1715-techsource-planned-maintenance-outages
Updated the maintenance banner start and end time to reflect the upcoming maintenance for Computacenter
=> Add maintenance banner for first weekend of April 2021

Gemfile, Gemfile.lock, app/controllers/support/service_performance_controller.rb, app/form_objects/support/request_completions_form.rb, app/models/support/service_performance.rb, app/views/support/service_performance/_mobile_data_requests.html.erb, spec/factories/reportable_events.rb, spec/features/support/viewing_service_performance_spec.rb, spec/models/support/service_performance_spec.rb
[Trello card](https://trello.com/c/AA7dPOWD/1821-add-ability-to-query-for-extramobiledatarequest-completions-up-to-a-given-date-time-to-support-ui) - now that we have an agreed monthly schedule for reporting MNO request completions, and we also have a working method of recording completions in a separate table as they happen, we can and should add the ability to query for completions between dates into the support UI. 
* Add a bit of UI to `/support/performance` to explicitly display the completions
* Add a form for querying between dates, tucked away behind a summary/details component until you need it
You will need some `ReportableEvent` records, with `event_name: 'completion'` and `record_type: 'ExtraMobileDataRequest'`
The easiest way is to generate some `ExtraMobileDataRequest` …
=> [1821] allow support to query ExtraMobileDataRequest completions

app/components/responsible_body/pooled_device_count_component.html.erb, app/controllers/component_preview_controller.rb, config/application.rb, spec/components/previews/email_audit_list_component_preview.rb, spec/components/previews/nav_component_preview.rb, spec/components/previews/nav_component_preview/computacenter_user.html.erb, spec/components/previews/nav_component_preview/support_user.html.erb, spec/components/previews/next_school_link_component_preview.rb, spec/components/previews/pooled_device_count_component_preview.rb, spec/components/previews/school_preorder_status_tag_component_preview.rb, spec/components/previews/start_page_banner_component_preview.rb, spec/components/previews/summary_list_component_preview.rb, spec/components/previews/tab_component_preview.rb, spec/components/previews/tile_component_preview.rb
- https://trello.com/c/yIXkXW6J/1689-add-previews-of-view-components-in-various-states
- Adds preview functionality of view components in various states
- Some components have been missed out as they seem to only add wrapping divs and having the previews don't seem to offer much value. We probably want to cull superfluous components first then add previews for the remaining components
Added component list
Example component preview
- Visit http://localhost:3000/rails/view_components/
- Click on previews to view components in various states
=> [1689] Add component previews

app/services/school_order_state_and_cap_update_service.rb, spec/services/school_order_state_and_cap_update_service_spec.rb
- https://trello.com/c/c8nB3ikw/1238-allow-bulk-opening-page-to-work-with-many-thousands-of-urns
- Can disable notifications in `SchoolOrderStateAndCapUpdateService`
- Code review
=> [1238] Can disable notifications in update service

app.json, app/components/computacenter/tech_source_maintenance_banner_component.html.erb, app/components/computacenter/tech_source_maintenance_banner_component.rb, app/models/computacenter/tech_source.rb, app/services/feature_flag.rb, app/views/responsible_body/devices/orders/cannot_order_anymore.html.erb, app/views/responsible_body/devices/orders/order_devices.html.erb, app/views/responsible_body/devices/orders/specific_circumstances.html.erb, app/views/school/devices/can_order.html.erb, app/views/school/devices/can_order_awaiting_techsource.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb, app/views/school/devices/school_can_order_user_cannot.html.erb, app/views/shared/_techsource_unavailable_banner.html.erb, config/application.rb, config/environments/development.rb, spec/components/previews/computacenter/tech_source_maintenance_banner_component_preview.rb, spec/components/previews/computacenter/tech_source_maintenance_banner_component_spec.rb, spec/controllers/techsource_launcher_controller_spec.rb, spec/features/techsource_availability_for_responsible_body_spec.rb, spec/features/techsource_availability_for_school_spec.rb
- Enabled view components preview for review apps (thanks @asmega)
- Adds new component for TechSource Maintenance banner
- Refactors existing feature and fixes two bugs identified
Sign in as `trust.user.1@example.com` and visit https://dfe-ghwt-pr-1533.herokuapp.com/responsible-body/devices/order-devices. You should see the banner telling the user that techsource will not be available.
=> 1715 techsource planned maintenance outages

spec/controllers/techsource_launcher_controller_spec.rb, spec/features/techsource_availability_for_responsible_body_spec.rb, spec/features/techsource_availability_for_school_spec.rb, spec/spec_helper.rb
Specs which used the Timecop gem had there own `after` hooks to make sure `Timecop.return` was used so system time changes didn't bleed into other specs. 
This PR adds a global `before` hook so `Timecop.return` is always called so nobody has to remember to do it themselves anymore. 
This commit has been manually verified to work with RSpec features as well as unit specs.
Adds global `before` hook. Having this in a `before` hook is safer than having it in an `after` hook because an `after` hook isn't guaranteed to be run (when a spec errors).
There are some calls to `Timecop.return` which are kept in because they're called multiple times in the middle of a spec to set and reset specific behaviour.
=> Add global `Timecop.return` hook

app/controllers/schools_controller.rb, app/views/schools/index.html.erb, config/locales/en.yml, spec/features/signing_in_as_different_types_of_user_spec.rb
Text on the 'Your Organisations' page was seen as being too terse.
Apply updated text
https://ghwt-prototype.herokuapp.com/your-organisations
=> Updated text on 'Your Organisations' page to be less terse

Gemfile
Now that `Gemfile.lock` is updated, we don't have to provide this within the `Gemfile`. This makes previous PR (#1491) equivalent to `bundle update http` as per Phil Lee's suggestion. 
Not having a new version of `http-parser` meant the app wouldn't work on newer Apple Silicon M1 CPUs. This is a rework of https://github.com/DFE-Digital/get-help-with-tech/pull/1491 
Get reference to `http-parser` gem out of `Gemfile`
=> Remove reference to `http-parser` gem in `Gemfile`

Gemfile.lock, spec/components/previews/email_audit_list_component_preview.rb
- Switch from FactoryBot to OpenStruct
Visit https://dfe-ghwt-pr-1554.herokuapp.com/rails/view_components/email_audit_list_component/default, pages loads and displays an example of the component being used
=> Fix Email audit component preview

app/views/layouts/guidance_pages.html.erb, config/locales/en.yml
Visit https://dfe-ghwt-pr-1546.herokuapp.com/devices/resolve-issues-with-4g-wireless-routers and 
https://dfe-ghwt-pr-1546.herokuapp.com/devices/preparing-4g-wireless-routers.
Both pages should have a breadcrumb that links to "Internet access" and when its clicked, should take the user back to the "Internet access" page
=> Fix 4g guidance page breadcrumbs

.github/workflows/promote-build.yml
[Trello Card](https://trello.com/c/0CviAv3T/1855-allow-builds-to-be-promoted-between-environments-via-github-actions) - See if we can get Github Actions to perform build promotion for us, to remove the need for all devs to have individual write permissions on the Dockerhub repository.
Add a workflow for promoting builds
This should be invokable from the Github "Actions" tab on the repo once it's on `main`
=> [1588] add promote-build workflow

app/mailers/computacenter_mailer.rb, spec/mailers/computacenter_mailer_spec.rb
- https://trello.com/c/KbFsgMk6/1837-computercenter-require-a-shipto-but-their-api-returns-success-for-cap-updates-without-a-shipto
- Error would happen when new school or rb has been added
- And we set the allocation/cap
- But computacenter has not set soldTo or shipTo yet
- When we personalisation for `ComputacenterMailer` we send a placeholder string `Not set` instead of `nil` which `Notify` does not accept
- This way at last computacenter will receive the email with some values missing rather than no email at all
- Also this will not cause an error on our side
- Create a new school sans `computacenter_reference`
- Make the school have a cap and allocation greater than zero and able to order
- Should see the mailer being sent with placeholder values
=> [1837] Fix ComputacenterMailer error

Gemfile, Gemfile.lock
Allows `save_and_open_page` to open system browser window when added within specs. This makes the process of 
seeing the situation within a browser easier.
* Add `launchy` gem
* Reorder `test` block alphabetically
=> Add `launchy` gem and reorder gems in `test` block alphabetically

app/views/support_tickets/start.html.erb
- Email address needs to use `mailto:`
=> Fix support email on "Get support" page

app/models/local_authority.rb, app/services/interstitial_picker.rb, app/services/personas/la_funded_place.rb, app/views/interstitials/_la_funded_rb_user.html.erb, lib/tasks/personas.rake, spec/services/interstitial_picker_spec.rb
- https://trello.com/c/utboJcpf/1777-add-state-funded-pupils-interstitial-for-rb-la-users
- https://trello.com/c/DrBn6QSl/1776-switch-off-state-funded-pupils-interstitial-for-rb-la-users-no-earlier-than-1-week-after-the-last-user-added
- Show a slightly different interstitial for an LA user that also has access to an LA funded place
- For both the above user type and direct LA funded place users interstitial now only show if the allocation has devices available
- Added personas for ISS journeys
- Converted `la_funded_place` method to `has_one`
- Visit https://dfe-ghwt-pr-1574.herokuapp.com
- Sign in as `la.funded.user.1@example.com` should be possible
- Sign in as `la.user.1@example.com` should now see slightly different interstitial screen
- ISS Interstitial screens should also no longer …
=> [1777] ISS LA user interstitial

app/models/extra_mobile_data_request.rb, app/services/exporters/mno_requests_csv.rb, db/migrate/20210416125638_add_extra_mobile_data_request_hashed_name_and_number.rb, db/migrate/20210416132319_populate_hashed_columns_on_extra_mobile_data_request.rb, db/schema.rb, spec/models/extra_mobile_data_request_spec.rb
[Trello card](https://trello.com/c/YMBvNnni/1707-add-hashed-name-normalised-name-number-fields-to-the-anonymised-dataset-of-extramobiledatarequests-in-the-admin-ui) - the first time we generated an official number of completions by a certain date for the analysts, they asked for a dataset of all ExtraMobileDataRequests so that they could answer any future FOI requests or ministerial questions themselves, as their name would be on the published figure. We eventually agreed that an anonymised dataset would be ok if we hashed the personally-identifying fields - they would have unique references, but could never go back from the hashed values to the plain-text values. This took some time and manual effort, if they ask for similar datasets in future it should be automated as much as possible. …
=> [1707] add hashed name and number fields to anonymised EMDR dataset download

.github/workflows/promote-build.yml, README.md
In the promote Github Action it's not clear with our production environment is called `production` or `prod`. The correct one is `prod` and whilst there seems to be no way to constrain users to this, this PR adds descriptive text to inform users of this instead. 
* Fix URL typo in README
* Add text to Github Action description to prompt users to use the correct environments
=> Promote git action text update

app/controllers/sign_in_tokens_controller.rb, app/views/shared/_flash_message.html.erb, spec/features/signing_in_as_different_types_of_user_spec.rb
Make the sign-in link feature an actual clickable link
Put the sign-in link into `flash[:sign_in_link]` instead of `flash[:success]` and handle as a special case to render the html link.
with `FEATURES_display_sign_in_token_links: active` when you sign in you will see a 'Click to sign-in` link instead of the URL in the flash message.
=> Make sign-in link feature an actual link

app/views/support/schools/search.html.erb, app/views/support/users/responsible_body/edit.html.erb, app/views/support/users/schools/index.html.erb, app/views/support/users/schools/new.html.erb, app/views/support/users/schools/search_again.html.erb, app/views/support_tickets/academy_details.html.erb, app/views/support_tickets/local_authority_details.html.erb, app/webpacker/packs/application.js, app/webpacker/scripts/responsible-bodies-autocomplete.js, app/webpacker/scripts/school-autocomplete.js
- https://trello.com/c/I5p4VO2m/1422-autocomplete-and-javascript-initialisers-should-be-thru-data-attributes-not-hardcoded-ids
- Autocomplete components were initialised via hard coded selectors within javascript
- Autocomplete for schools and RBs are setup via data attributes
- Configuration of school autocomplete is now via data attributes
- This should make the autocomplete components a bit more reusable without having to modify the javascript
- Existing autocompletes on the site continue to work
- Support user searching for an organisation
- Support user searching for an schools via rb and state
- Editing a user and changing schools
- Editing a user and changing rbs
- Create support ticket as LA
- Create support ticket as an academy
=> [1422] Remove hardcoded autocomplete javascript

package.json
For our review apps, we had the node engine version set to `>12.0`.
This meant that up until recently our review apps were using a newer nodejs
version compared to our local dev setup. We only spotted this issues today
after v16 of nodejs was released yesterday and Heroku tried to use that
but all our review apps started failing as a result of our dependency not
being compatible with v16.
For the time being we will stay on v12 but we should look to update to
latest LTS version which at the time is v14. This is a bigger task because
we need to ensure our docker image is pulling in the correct version of node
and some other checking is required.
- Review apps are deployed successfully
- v.12 is being used on heroku
Heroku logs found below for the review app generated from this PR.
``` …
```
=> Set node use to v12 for heroku

app/controllers/techsource_launcher_controller.rb, app/views/techsource_launcher/unavailable.html.erb, spec/controllers/techsource_launcher_controller_spec.rb
When a TechSource maintenance period was active we were displaying the hardcoded string that `You will be able to order devices when it reopens on Saturday 28 November` which is wrong.
https://trello.com/c/d7XZ7U4y
Dynamically set the end of the maintenance period (and include the time)
=> Remove hard-coded date string

app/views/devices_guidance/device_specification.md, app/webpacker/styles/application.scss
- Fix table columns on guidance page for 6 columns 
- Make each col span 16%
- https://dfe-ghwt-pr-1597.herokuapp.com/devices/device-specification
- Spacing on table should be improved
=> [1888] Make table cols equal width

app/controllers/school/devices_controller.rb, app/controllers/school/home_controller.rb, app/controllers/school/la_funded_places_chromebooks_controller.rb, app/controllers/school/la_funded_places_controller.rb, app/form_objects/chromebook_information_form.rb, app/helpers/view_helper.rb, app/models/la_funded_place.rb, app/models/local_authority.rb, app/models/preorder_information.rb, app/models/school_device_allocation.rb, app/views/school/home/show_la_funded_place.html.erb, app/views/school/la_funded_places/laptop_types.html.erb, app/views/school/la_funded_places/order.html.erb, app/views/school/la_funded_places/show.html.erb, app/views/school/la_funded_places_chromebooks/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/features/computacenter/download_csv_files_spec.rb, spec/features/ordering_for_la_funded_devices_spec.rb, spec/features/responsible_body/providing_a_schools_preorder_information_spec.rb, spec/features/school/change_chromebook_information_spec.rb, spec/features/school/navigate_school_welcome_wizard_spec.rb, spec/features/signing_in_as_different_types_of_user_spec.rb, spec/features/support/editing_chromebook_details_for_a_school_spec.rb, spec/form_objects/chromebook_information_form_spec.rb, spec/models/preorder_information_spec.rb
[Trello card](https://trello.com/c/xppMclNt/1769-order-flow-for-iss)
Order flow for state-funded pupils in independent settings
Added pages for device ordering flow for `LaFundedPlace` type `School`
__Setup__
1. Add a `LaFundedPlace` school to a LocalAuthority e.g.
```ruby
my_la_funded_place = LocalAuthority.first.create_la_funded_places!(urn: 999000, device_allocation: 10)
```
2. Add a user to the school
```ruby
my_la_funded_place.users << my_user
```
3. Up the device cap to the allocation amount
```ruby
my_la_funded_place.std_device_allocation.update!(cap: 10)
```
4. Set the new school to order 
```ruby
my_la_funded_place.can_order!
```
5. Sign-in as the user associated with the school (and choose the school after sign-in if necessary)
6. The journey starts at the home page for the …
=> [1769] Order flow for ISS

app/controllers/support/privileged_users_controller.rb, app/form_objects/support/privileged_user_form.rb, app/models/user.rb, app/policies/privileged_user_policy.rb, app/views/support/home/show.html.erb, app/views/support/privileged_users/index.html.erb, app/views/support/privileged_users/new.html.erb, app/views/support/privileged_users/show.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/support/privileged_users_controller_spec.rb, spec/form_objects/support/privileged_user_form_spec.rb, spec/models/user_spec.rb, spec/views/support/home/show.html.erb_spec.rb
- https://trello.com/c/lkhFVwWu/1712-third-line-support-can-add-other-support-users
- Save the need for a developer to onboard additional support users
- Third line support users can:
- view privileged users: support users, computacenter users and mno users
- can also add other support users - these are restricted to certain domains for the email addresses
- revoke all privileges of one of these users
New section on support homepage 
Index view
Adding another user
- Sign in as non third line support
- Cannot see or access this areas
- Sign in as third line support
- Should be able to see and access new area
- Can see existing privileged users
- Can add privileged users
- Can remove privileges of users
=> [1712] Support interface to add support users

README.md
`README.md` was missing instructions on how to run RSpec in parallel without running entire suite
Add instructions to run RSpec in parallel on spec directories or individual spec files
=> Update README to say how to run spec files or spec directories in parallel

Gemfile, Gemfile.lock, config/initializers/sidekiq.rb
Seeing these errors in the output:
* `The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
* `WARNING: Sidekiq::Web.sessions= is no longer relevant and will be removed in Sidekiq 7.0. /Users/nigellowry/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/web.rb:75:in `set'`
* `WARNING: Sidekiq::Web.session_secret= is no longer relevant and will be removed in Sidekiq 7.0. /Users/nigellowry/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/web.rb:75:in `set'`
Remove the Sidekiq …
=> Remove warnings

app/views/devices_guidance/how_to_order_laptops_for_independent_special_schools.html.erb, app/views/devices_guidance/how_to_order_laptops_for_social_care_leavers.html.erb, app/views/devices_guidance/index.html.erb, config/routes.rb
- Add two links to devices guidance page to link to two new how to order pages for ISS and SC
- Add new view on how to order for Social care leavers
- Add new view on how to order for ISS
- Visit https://dfe-ghwt-pr-1613.herokuapp.com/devices
- Visit https://dfe-ghwt-pr-1613.herokuapp.com/devices/how-to-order-laptops-for-social-care-leavers
- Visit https://dfe-ghwt-pr-1613.herokuapp.com/devices/how-to-order-laptops-for-independent-special-schools
=> Add "how to order" page for social care leavers and ISS

Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/test.rb, config/initializers/content_security_policy.rb
To investigate potential performance improvements we can use these tools in development and test environments.
Add the following gems:
Development:
- rack-mini-profiler
- memory_profiler
- flamegraph
- stackprof
Development and test:
- bullet
Start in the development environment locally and there will be a floating widget at the top left of the browser page.
Check log/bullet.log for N+1 queries.
=> Add performance profiling tools for dev and test

.github/dependabot.yml
- To keep docker manifest up-to-date
- Add docker to dependabot manifest
- Dependabot manifest should be valid
=> add docker to dependabot manifest

app/jobs/allocation_job.rb, spec/factories/school_device_allocations.rb, spec/factories/schools.rb, spec/jobs/allocation_job_spec.rb
Negative values in bulk allocation should not reduce allocation below devices_ordered or zero.
When negative delta values are passed allocations will be reduce to the max of new_allocation, devices_ordered or zero.
Using the bulk updater add negative values that will reduce the allocation below devices_ordered. The allocation will be equal to devices_ordered.
=> Handle negative values in the bulk allocation update

app/views/school/devices/can_order.html.erb, app/views/school/home/show_la_funded_place.html.erb, spec/features/ordering_for_la_funded_devices_spec.rb
- https://trello.com/c/1bXvq7Wn/1937-scl-incorrect-homepage
- Incorrect school name for SCL homepage
- This allows for ISS and SCL to use LA funded homepage
ISS homepage
SCL homepage
- Sign in as ISS user
- homepage should show correct school name
- Sign in as SCL user
- homepage should show correct school name
=> [1937] LA funded place shows school name

app/controllers/responsible_body/devices/change_who_will_order_controller.rb, app/controllers/responsible_body/devices/chromebook_information_controller.rb, app/controllers/responsible_body/devices/schools_controller.rb, app/controllers/responsible_body/devices/who_to_contact_controller.rb, app/controllers/support/addresses_controller.rb, app/controllers/support/schools/devices/allocation_controller.rb, app/controllers/support/schools/devices/change_who_will_order_controller.rb, app/controllers/support/schools/devices/chromebooks_controller.rb, app/controllers/support/schools/devices/order_status_controller.rb, app/controllers/support/schools/opt_outs_controller.rb, app/controllers/support/schools_controller.rb, app/controllers/support/users/schools_controller.rb, app/controllers/support/users_controller.rb, app/form_objects/school_search_form.rb, app/form_objects/support/school_suggestion_form.rb, app/models/allocation_batch_job.rb, app/models/school.rb, spec/models/school_spec.rb
[Trello card](https://trello.com/c/PmWLwSX0/1932-iss-school-show-page-displays-an-error-in-production)
Errors in production search from support area.
Use the scopes that include handling `provision_urn` for school searches
This does not include the multi-URN search from the support area and that is a much more complex change and probably not required for these specialised school instances.
Should be able to search for a ISSnnn style URN from support area.
=> [1932] Prevent errors when using ISS and SCL 'urns' in support area

app/jobs/allocation_job.rb
Bulk updater was set to use devices_ordered as the lower bound, but it should use raw_devices_ordered
Use raw_devices_ordered as the lower bound in the bulk updater
=> Bulk updater should use raw devices ordered

app/jobs/apply_staged_attribute_changes_to_trusts_job.rb, app/services/trust_update_service.rb, config/sidekiq.yml, db/migrate/20210506113406_apply_staged_trust_attribute_changes.rb, db/schema.rb
Full context is on [Trello card 1955](https://trello.com/c/hfWrhp57/1955-82-new-trusts-exposed-without-addresses). A quick summary:
- We have lots of Trusts with no address.
- The addresses have been pulled through from GIAS and are present in the staged data, but have not been propagated to the actual Trust records
- The code to propagate the changes is already written, but has never been wired up to a job, so it has never been called. 
Add migration to one-off-update all Trusts, and job to make sure future updates are propagated
First, stage the updates with `StageTrustDataJob.new.perform`
Check your local database count of `Trust.where(address_1: nil).count`
Run the migration
Check your local database count of `Trust.where(address_1: nil).count` again - it should have decreased (note: …
=> [1955] fix Trusts with nil addresses

docs/restoring_the_database_from_a_snapshot.md
We recently tried restoring the database on staging to a backup - it worked fine, but I wanted to record exactly the steps involved, as some are specific to our service and not part of the GOV.UK PaaS documentation.
Add a doc describing the process
=> [321] add doc describing how to restore DB

app/services/healthcheck_service.rb
The `/healthcheck.json` endpoint only shows the status of the database service, and does not include redis
Add a redis status check
Hit '/healthcheck.json` - you should see something like this:
(screenshot from localhost - if you're on a deployed container, the git variables will also be populated)
=> add redis status to the healthcheck JSON

app/controllers/school/details_controller.rb, app/policies/school/details_policy.rb, app/views/school/home/show_la_funded_place.html.erb, config/locales/en.yml, spec/policies/school/details_policy_spec.rb
It doesn't make sense to show the "Check your details" section for LA-funded places
https://trello.com/c/s5zR0VHK
Stop showing this to those on the LA-funded route. Stop access to the controller action via Pundit authorisation.
=> Stop showing "Check your details" to LA funded places

Gemfile, Gemfile.lock
rexml is a a bundled gem and not a default gem in Ruby 3
Can easily proved on a Rails console to quickly check...
If not added to Gemfile
```
> Hash.from_xml("<xml></xml>") 
You don't have rexml installed in your application. Please add it to your Gemfile and run bundle install
LoadError: cannot load such file -- rexml/document
from /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require'
```
Expected...
```
> Hash.from_xml("<xml></xml>")
=> {"xml"=>nil}
```
=> Add rexml to Gemfile, Ruby 3 rexml is not default

app/services/trust_update_service.rb, docs/support/sync_closed_trusts.md, spec/factories/responsible_bodies.rb, spec/services/trust_update_service_spec.rb
PROPOSAL 2 - dealing with Trust closures
Initial naive proposal was https://github.com/DFE-Digital/get-help-with-tech/pull/1710 
- Auto close trusts if safe to do so
- `def close_trusts(last_update)` - This can be used directly in the console with a very old date in the past to retroactively close all Trusts that should be closed due to closed trusts not being synced.
TODO:
- ~~Tests~~
- ~~Sentry notification and logging~~
=> Auto close trust from GIAS if trust has no schools

app/controllers/application_controller.rb, spec/features/signing_in_as_different_types_of_user_spec.rb
This call to Sentry doesn't work as the update from Raven isn't backwards compatible with the params passed in.
Updated to use scope and also add test coverage.
=> Use Sentry scopes

app/form_objects/support/allocation_form.rb, app/services/allocation_updater.rb, app/views/support/schools/devices/allocation/edit.html.erb, config/locales/en.yml, spec/features/support/adjusting_a_schools_allocation_spec.rb, spec/form_objects/support/allocation_form_spec.rb, spec/services/allocation_updater_spec.rb
… for schools that are not in a virtual cap pool.
https://trello.com/c/LcUxgM3W/1967-reducing-allocation-for-a-single-school-is-rejected
Before these changes, reducing allocations could cause an error due to the underlying `cap` value not being adjusted to match, in time for the model validation to hit.
Note: I've gone for a "light touch" fix here that doesn't attempt to change too much – there's a longer term piece required for refactoring + code consolidation + potential fixes, later on, after we figure out / confirm what the intended product design for allocations and vcap pools is moving forward.
Changes here:
- Allow allocations to be decreased, but only for schools that are not in a virtual cap pool.
- For schools that are in a virtual cap pool, we a) show a warning message in the …
=> Tactical fix to allow allocations to be decreased

app/views/support/schools/show.html.erb
https://trello.com/c/PJkbX8Ow/1227-show-the-urn-on-the-school-page-in-support
The school's page on the support portal does not currently show the URN (or equivalent) for that school.
Show the URN (or equivalent) next to the school's name, just like on the list of schools on the responsible body page.
Check that the URN is being shown for schools when you click through to the school's page on the support portal.
=> Show the school's URN (or equivalent) on the support page

app/components/device_count_component.rb, app/components/responsible_body/pooled_device_count_component.rb, app/concerns/device_count.rb, app/controllers/responsible_body/devices/orders_controller.rb, app/helpers/view_helper.rb, app/models/computacenter/api/cap_usage_update.rb, app/models/responsible_body.rb, app/models/school.rb, app/models/school_device_allocation.rb, app/models/school_welcome_wizard.rb, app/views/responsible_body/devices/orders/_place_order_for_virtual_pool.html.erb, app/views/responsible_body/devices/schools/index.html.erb, app/views/responsible_body/devices/schools/order_devices.html.erb, app/views/school/devices/can_order.html.erb, spec/features/responsible_body/ordering_devices_spec.rb, spec/models/responsible_body_spec.rb, spec/models/school_device_allocation_spec.rb, spec/models/virtual_cap_pool_spec.rb
`devices_available_to_order` and `available_devices_count` have the same intent, but different implementations.
`available_devices_count` has a minimum value of zero and so is the preferred implementation. However the name `devices_available_to_order` is more descriptive.
1. Switch the single use of `devices_available_to_order` over to `available_devices_count`
2. Remove the `devices_available_to_order` method from the code-base
3. Rename `available_devices_count` to `devices_available_to_order`
4. Rename `has_devices_available_to_order?` to `devices_available_to_order?`
All specs should pass
=> 2055 refactor differing implementations for returning the number of devices available to order

app/controllers/computacenter/multi_domain_chromebooks_iss_scl_controller.rb, app/models/responsible_body.rb, app/views/computacenter/home/show.html.erb, app/views/computacenter/multi_domain_chromebooks_iss_scl/index.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/schools.rb, spec/features/computacenter/chromebook_domains_iss_scl.rb, spec/features/computacenter/download_csv_files_spec.rb
Add a new section to list ISS and SCL provisions and their respective Responsible Bodies that needs to highlight the possibility that multiple chromebook domains are required.
Any ISS or SCL that has said `yes` or `i_dont_know` for Chromebooks is listed essentially.
=> New section in /computacenter for ISS/SCL Chromebook domains

app/models/computacenter/tech_source.rb
Adds next TechSource outage window for banner
https://trello.com/c/p4mnd1ng
Add outage period for between 6pm on Friday 11 June and 8pm on Sunday 13 June.
=> Add next TechSource outage window

app/jobs/allocation_job.rb, spec/jobs/allocation_job_spec.rb
Negative deltas were not considered at all in the project from the beginning. We have an urgent need to reduce allocations across thousands of objects.
Expand the scope of the `AllocationJob` specs to cover more complex cases.
Refactoring of the AllocationJob to show the intent more clearly.
Focus on the correctness of the `AllocationJob` specs. The specs should be refactored in a subsequent PR. This could not be done for this PR because of time pressure.
The immediate use case will be to pass a zero delta and `order_state` = `cannot_order` to thousands of `School` objects today.
=> Update specs for allocation job and refactor job

app/controllers/school/devices_controller.rb
Sentry: https://sentry.io/organizations/dfe-get-help-with-tech/issues/2445734273/?project=5320558&referrer=slack
Provide value for `@responsible_body` for partial. This fixes two code paths. The three other routes to this partial seem to already be providing `@responsible_body` in their controllers
=> Provide value for `@responsible_body` for partial

app/services/feature_flag.rb
Need feature flag for 30 Jun service changes. Content designers will need to check this flag to switch between the different behaviours when the service is closed for ordering.
Add feature flag called `summer_ordering_pause`
=> Add feature flag for 30 Jun order closing

app/services/trust_update_service.rb, spec/services/trust_update_service_spec.rb
User Sentry context so we don't lose the skipped trust_ids if multiple errors are aggregated.
=> User Sentry context to pass the skipped trust_ids and not the error

app/models/support/service_performance.rb, app/models/support/service_performance/device_counts.rb, app/views/support/service_performance/_devices.html.erb, config/locales/en.yml, spec/models/support/service_performance_spec.rb
<https://trello.com/c/sJVeOtqL/2085-performance-dashboard-improvements>
This adds new sections for open vs. closed and devolved vs. centrally managed schools. These sections show counts for:
- Devices available
- Devices shipped
- Devices remaining (excl. over-ordered)
- Devices over-ordered
---
---
---
**TODO**
- ~~Consider adding caching~~
=> [2085] Add more segmented device stats on the "service performance" dashboard

app/services/feature_flag.rb
Remove feature flag because we've abandoned this approach
Remove `summer_ordering_pause` feature flag
=> Remove `summer_ordering_pause` feature flag

app/components/computacenter/tech_source_out_of_stock_component.html.erb, app/components/computacenter/tech_source_out_of_stock_component.rb, app/views/responsible_body/devices/orders/cannot_order_anymore.html.erb, app/views/responsible_body/devices/orders/order_devices.html.erb, app/views/responsible_body/devices/orders/specific_circumstances.html.erb, app/views/school/devices/can_order.html.erb, app/views/school/devices/can_order_awaiting_techsource.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb, app/views/school/devices/school_can_order_user_cannot.html.erb, app/views/school/la_funded_places/order.html.erb, app/views/school/la_funded_places/show.html.erb, spec/components/computacenter/tech_source_out_of_stock_component_spec.rb
https://trello.com/c/6pG15Rvh
Show maintenance banner in those places where the TechSource outage banner is shown
=> 2144 stop ordering laptops banner

app/views/devices_guidance/about_the_offer.md, app/views/devices_guidance/device_allocations.md, app/views/devices_guidance/device_distribution_and_ownership.md, app/views/devices_guidance/device_specification.md, app/views/devices_guidance/index.html.erb, app/views/guide_to_collecting_mobile_information/_guide_contents.html.erb, app/views/pages/internet_access.html.erb, app/views/pages/what_to_do_if_you_cannot_get_laptops_tablets_or_internet_access_from_dfe.html.erb, config/locales/en.yml
This is part of the overall service closure work for the 30th of June 2021.
The closure of the service creates the requirement for some content to be rephrased in the past tense and other sections to be completely removed.
A high level Google Doc with links to amended pages can be found here: [Content updates for pausing ordering | June 2021](https://docs.google.com/document/d/1ulzlIfkfXiIgZSwemjmJa3uyfkJyhy8mf9QkaMe_2XA/edit#heading=h.91ktmv50h3uo)
https://get-help-with-tech.education.gov.uk/devices
should match
https://docs.google.com/document/d/138wfOMQx1mP1KLRgRz8Go7AN9VWfT349h02C0FtX5zg/edit?usp=sharing
https://get-help-with-tech.education.gov.uk/devices/about-the-offer
should match
https://docs.google.com/document/d/1I8c8JaUkI1E4velkJN3VVK6V_DLfRd93p0fZVnBltO4/edit?usp=sharing …
=> 2150 update guidance content device

app/views/schools/index.html.erb
Before: 
You have access to manage ordering on behalf of more than one organisation.
After:
You have access to more than one organisation.
=> updates content to remove mention of ordering

config/routes.rb, spec/features/huawei_password_spec.rb, spec/features/mno/extra_mobile_data_requests_spec.rb, spec/features/ordering_for_la_funded_devices_spec.rb, spec/features/responsible_body/devices_setup_spec.rb, spec/features/responsible_body/donated_devices_spec.rb, spec/features/responsible_body/ordering_devices_in_pool_spec.rb, spec/features/responsible_body/ordering_devices_spec.rb, spec/features/responsible_body/viewing_your_schools_spec.rb, spec/features/school/change_chromebook_information_spec.rb, spec/features/school/extra_mobile_data_requests_spec.rb, spec/features/school/order_devices_spec.rb, spec/features/session_behaviour_spec.rb, spec/features/techsource_availability_for_responsible_body_spec.rb, spec/features/techsource_availability_for_school_spec.rb, spec/features/view_pages_spec.rb
<https://trello.com/c/MOtq9f0w/2168-archive-pages>
Key assumption: this is different to the public pages archival work in that these are likely to come back – routes-wise – in it's current form. Thus, what I've done is:
- Marked each of these routes with a `constraints: -> { false }` to disable them
- This results in a 404 page for each of these routes (which I've tested manually)
- I've kept ALL underlying code…
- … and disabled _any_ test that fails as a result (but kept the code intact for these tests)
=> [2168] Archiving many *logged in* pages

app/views/errors/not_found.html.erb
https://trello.com/c/euhWUmqz
Because we have retired pages from the service, we anticipate a small bump in users hitting the 'page not found page'. Looking at it, we could make it more helpful by sign-posting the user to the homepage.
Adds 'Go to the Get help with technology homepage to see guidance or sign in.' With a link to the homepage.
View a page that isn't there
=> adds homepage link to page not found

app/components/computacenter/tech_source_maintenance_banner_component.rb, app/controllers/techsource_launcher_controller.rb, app/models/computacenter/tech_source.rb, spec/components/previews/computacenter/tech_source_maintenance_banner_component_spec.rb, spec/controllers/techsource_launcher_controller_spec.rb, spec/models/computacenter/tech_source_spec.rb
https://trello.com/c/EpcohVyD
Allows multiple TechSource outages to be input at once, rather than having separate deployment cycle for each.
Turn single value into array
=> 1841 multiple techsource outages

app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb, spec/features/responsible_body/home_spec.rb, spec/features/school/view_school_details_spec.rb
Even if the RB/School has not ordered show the option to manage users.
=> Always Access Support Portal section even when not ordered

app/components/computacenter/tech_source_maintenance_banner_component.rb, app/controllers/techsource_launcher_controller.rb, app/models/computacenter/tech_source.rb, app/models/supplier_outage.rb, db/migrate/20210726110031_create_supplier_outages.rb, db/schema.rb, spec/components/previews/computacenter/tech_source_maintenance_banner_component_spec.rb, spec/controllers/techsource_launcher_controller_spec.rb, spec/factories/supplier_outages.rb, spec/models/computacenter/tech_source_spec.rb, spec/models/supplier_outage_spec.rb
https://trello.com/c/b82716oi
Allow TechSource outages to be specified through database operations on the Rails production console. 
Currently there's only one supplier but in the future instead of a `SupplierOutage`, different suppliers could have many `Outage`s.
New outages can be managed in the database with:
```ruby
SupplierOutage.create!(start_at: Time.zone.parse('1 Jan 2021 10:00am'), end_at: Time.zone.parse('1 Jan 2021 11:00am'))
```
Move outages to database model `SupplierOutage`
=> Add `SupplierOutage` model

spec/factories/school_device_allocations.rb, spec/features/computacenter/techsource_spec.rb, spec/features/responsible_body/ordering_via_a_school_spec.rb, spec/models/preorder_information_spec.rb, spec/models/user_can_order_devices_notifications_spec.rb
Many of our flaky specs were due to the allocations factory having a random factor which:
* sometimes created a coms allocation, sometimes created a device allocation; and
* used random number generation which occasionally fell foul of cap and allocation constraints.
* Remove random element
* Remove duplicate trait
=> Make factory sane

app/views/responsible_body/home/_closed_banner.html.erb, app/views/school/home/_closed_banner.html.erb, spec/features/responsible_body/home_spec.rb, spec/features/school/view_school_details_spec.rb
No need to remind users that they haven't ordered.
=> Remove not ordered blurb, add missing tests for 4G blurb

app/services/stage_trust_data.rb, app/services/trust_upsert_service.rb, spec/services/stage_trust_data_spec.rb, spec/services/trust_upsert_service_spec.rb
On the periodic import of GIAS trusts csv file sometimes new trusts are coming. Even though we are currently staging them, we are not creating the Trust entries associated.
Create/update our Trust entries with any trust coming from GIAS on csv import.
- New service _TrustUpsertService_ created to mirror any GIAS trust into our own Trust table.
- I think the new service above also covers the job done by _ApplyStagedAttributeChangesToTrustsJob_. Thoughts?
- Tests on _stage_trust_data.rb_ updated accordingly and partially moved to the new service tests suite.
=> 2208: add trusts when importing them from GIAS

app/jobs/computacenter_historical_asset_import_job.rb, spec/jobs/computacenter_historical_asset_import_job_spec.rb
`ActiveJob` to import a CSV file of assets. This uses an `ActiveJob` because of how long it takes to run.
=> Add job for importing CC assets

app/controllers/support/users_controller.rb, app/services/delete_user_service.rb, spec/controllers/support/users_controller_spec.rb, spec/services/delete_user_service_spec.rb
Reduce the number of soft-deleted users in the system.
When deleting users check if they have a TS account confirmed, if not hard-delete otherwise soft-delete as a precaution for now.
- Added a service just for deletion, everything else kept the same
- Removed dependency of extra mobile requests to be deleted as they should be retained
=> Hard delete users without TS confirmed account

app/components/support/user_preview_summary_list_component.rb, app/controllers/responsible_body/users_controller.rb, app/controllers/school/users_controller.rb, app/controllers/support/responsible_bodies_controller.rb, app/controllers/support/schools_controller.rb, spec/components/support/user_preview_summary_list_component_spec.rb, spec/features/responsible_body/manage_users_spec.rb, spec/features/school/manage_users_spec.rb, spec/features/support/managing_schools_spec.rb, spec/features/support/viewing_responsible_body_info_spec.rb, spec/features/support/viewing_service_performance_spec.rb
Deleted users should only be visible to support section only, normal users shouldn't see any soft-deleted users.
* In support - added extra "Deleted: Yes" row to indicate deleted users for support reasons.
=> Bugfix: Soft-deleted users only visible to support section only

app/controllers/assets_controller.rb, app/models/asset.rb, app/views/assets/index.html.erb, app/views/assets/show.html.erb, config/routes.rb, spec/controllers/assets_controller_spec.rb
Expose `Asset` `index` and `show` views so they can be tested on `staging` and potentially `prod`.
Some specs for the controller were already out of date, and are already covered by the specs for `Asset.owned_by`, so I changed them just to check it calls `Asset.owned_by`.
=> Expose asset routes

app/components/support/school_details_summary_list_component.rb, app/controllers/support/schools/responsible_body_controller.rb, app/form_objects/support/school/change_responsible_body_form.rb, app/models/school.rb, app/policies/school_policy.rb, app/services/change_school_responsible_body_service.rb, app/views/support/schools/responsible_body/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/controllers/support/schools/responsible_body_controller_spec.rb, spec/features/support/schools/change_responsible_body_spec.rb, spec/form_objects/support/school/change_responsible_body_form_spec.rb, spec/page_objects/support/schools/responsible_body/edit_page.rb, spec/policies/school_policy_spec.rb, spec/services/change_school_responsible_body_service_spec.rb
Support third line users need to be able to manually move a school to a new Responsability Body. 
Add a row in the school show details view displaying the school current responsability body and a cta to change it.
User story: [GIAS - Move school to a new RB (RFQ-11)](https://trello.com/c/AyCdWd53)
=> 2315: change school responsible body

app/services/create_user_service.rb, spec/services/create_user_service_spec.rb
It's possible that someone invites a user that is soft-deleted, if that is the case, re-instate the user and invite them.
=> Undelete soft-deleted users on invite

app/controllers/assets_controller.rb, app/models/asset.rb, spec/controllers/assets_controller_spec.rb, spec/models/asset_spec.rb
Records when an asset has first been shown (which acts a proxy for a DfE statistic.)
https://trello.com/c/01Tm1uXh
Records first time an asset's `show` view has been called.
=> 2309 record asset view

app/models/asset.rb, spec/models/asset_spec.rb
Was raising an error if user didn't represent a school or an RB. 
https://trello.com/c/QGIOpJhU
Now it just returns the empty relation `Asset.none` to be safe.
=> Change to return no assets instead of raising error

app/controllers/assets_controller.rb, spec/controllers/assets_controller_spec.rb
Only count asset as viewed if it's not been viewed by a support user (last minute requirement)
https://trello.com/c/01Tm1uXh
=> Only count asset as seen if by non-support user

app/components/support/school_details_summary_list_component.rb, app/controllers/support/schools/headteacher_controller.rb, app/form_objects/support/school/change_headteacher_form.rb, app/models/school.rb, app/policies/school_policy.rb, app/services/change_school_headteacher_service.rb, app/views/support/schools/headteacher/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/controllers/support/schools/headteacher_controller_spec.rb, spec/features/support/schools/change_headteacher_spec.rb, spec/form_objects/support/school/change_headteacher_form_spec.rb, spec/page_objects/support/schools/headteacher/edit_page.rb, spec/policies/school_policy_spec.rb, spec/services/change_school_headteacher_service_spec.rb
Headteacher details of a school can't be changed
- Add link to change headteacher details to the headteacher row when displaying details of a school in support area.
- Allow third line users to edit a school headteacher details
- When the school has no SchoolContacts are all, display a form to create a new headteacher contact
- When the school has a non-headteacher contact associated, display a form filled with their data to set it as headteacher
- When the school already has a headteacher associated, display a form pre-filled with their data to allow details changes.
- The form shows errors when new details don´t  pass validations.
See card [GIAS - Ability to update Headteacher details in /support](https://trello.com/c/lNUYeULi)
=> 2210: update school headteacher

app/models/asset.rb, spec/models/asset_spec.rb
The FactoryBot build method was actually creating `Asset` records instead of just building them.
Just set value instead of calling `update!`.
=> Fix FactoryBot `Asset` build problem

app/views/guide_to_resetting_windows_laptops_and_tablets/reset_the_bios_password.html.erb
Exception raised in Sentry. [see here](https://sentry.io/organizations/dfe-get-help-with-tech/issues/2608380031/?project=5320558&referrer=slack)
Version 2.x of govuk-components has renamed some of the keyword args in AccordionComponent and _:title_ (the one causing this error) is one of them. [See this PR](https://github.com/DFE-Digital/govuk-components/commit/043afc2ec5ed3dbd8b5883b65d5f646655c7248d#)
Rename _:title_ argument to its new name _: heading_text_
[2190: View Component deprecation warnings](https://trello.com/c/2pqveqrU)
=> 2190: upgrade accordion section arg names

app/views/layouts/application.html.erb, app/views/support_tickets/thank_you.html.erb
The new version of govuk-components has renamed a couple of args to initialize a PanelComponent. 
This is raising an exception on our code. See [sentry](https://sentry.io/organizations/dfe-get-help-with-tech/issues/2617817186/?project=5320558)
Rename _:title_ and _:body_ params when initializing the *GovukComponent::PanelComponent* on *thank_you.html* view
See card [2404](https://trello.com/c/zqiEp5Sv)
=> 2404: rename args to PanelComponent and NotificationBannerComponent

app/services/create_user_service.rb, spec/services/create_user_service_spec.rb
The shovel `<<` throws a PG index duplicate entry error, so we should check before shovelling a school in.
=> Skip invite if user already belongs to the school

app/form_objects/support/school/change_responsible_body_form.rb, app/models/preorder_information.rb, app/models/responsible_body.rb, app/models/school.rb, app/models/virtual_cap_pool.rb, app/services/change_school_responsible_body_service.rb, app/services/timeline/school.rb, spec/components/display_devices_ordered_component_spec.rb, spec/form_objects/support/school/change_responsible_body_form_spec.rb, spec/models/responsible_body_spec.rb, spec/models/virtual_cap_pool_spec.rb, spec/services/change_school_responsible_body_service_spec.rb, spec/services/timeline/school_spec.rb, spec/support/school_creator.rb
See [card 2109: Totals wrong for responsible body virtual pool](https://trello.com/c/WBc27VQn)
- Add tests to make sure recomputing pool allocations is done properly
- Remove school from pool when it leaves a responsible body. Recompute rb remaining allocations
- Add school to pool when it is moved to a different responsible body. Recompute rb new allocations
=> 2109: add/remove school from rb pools when it changes responsible body

app/models/user.rb, spec/services/delete_user_service_spec.rb
Issue: Can cause a foreign key error if a user is invited and destroyed.
Solution: Nullify the invited user but keep the wizard as it belongs to another user.
=> Nullify invited_user_id from the SchoolWelcomeWizard when destroying a user

config/manifests/dev-manifest.yml
The automated process to deploy the dev env to cf is reporting failures. All the failures that we have seen have been due to timeouts.
The dev env manifest had set the value of `health-check-invocation-timeout` to 10. The default is 60.
The dev env manifest has set the value of `health-check-invocation-timeout` to the default of 60.
`health-check-invocation-timeout` = 60 for the dev cf env.
[health_check_timeout](https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html#health_check_timeout)
=> Set cf health-check-invocation-timeout to default

config/manifests/dev-manifest.yml
The automated process to deploy the dev env to cf is reporting failures. All the failures that we have seen have been due to timeouts.
The dev env manifest had not set the value of timeout for the web app.
The dev env manifest has set the value of timeout to 120 for the web app.
timeout = 120 for the web app in dev cf env.
[app-manifest-specification](https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#the-app-manifest-specification)
=> Add 2 min timeout for dev env deployment

app/concerns/csv_value_sanitiser.rb, app/controllers/viewed_assets_controller.rb, app/models/asset.rb, app/views/viewed_assets/new.html.erb, config/routes.rb, lib/datetime_period.rb, spec/concerns/csv_value_sanitiser_spec.rb, spec/controllers/viewed_assets_controller_spec.rb, spec/lib/datetime_period_spec.rb, spec/models/asset_spec.rb
https://trello.com/c/7nZxVgYn
Unfortunately I couldn't find a way to print the error messages if the date range is wrong because of redirect errors, etc. Freddie's said this is acceptable. The UX is that if there's something wrong with the date range, the CSV download button just does nothing. 
Rather than leave the error messaging half-finished, it makes no attempt to print the error messages *at all*.
=> Export CSV of assets first viewed during date range

config/routes.rb, spec/features/devices_guidance_spec.rb
Access to missing image assets in `public/devices` hits the `DevicesGuidanceController` and bubbles up a `not_found` call, however since `png` is not a format with a template to render this causes an exception.
Given if an image were present it shouldn't hit the controller in the first place.
At the top of the routes file, catch any png/jpg files to devices/ and forward to default Error controller to return a 404 and not raise a template exception
The last 4 GETs to should be `match`.
=> Access to missing images in publis/devices return 404s

app/views/responsible_body/devices/orders/cannot_order_anymore.html.erb, app/views/responsible_body/devices/orders/order_devices.html.erb, app/views/responsible_body/devices/orders/specific_circumstances.html.erb, app/views/school/devices/can_order.html.erb, app/views/school/devices/can_order_awaiting_techsource.html.erb, app/views/school/devices/can_order_for_specific_circumstances.html.erb, app/views/school/devices/school_can_order_user_cannot.html.erb, app/views/school/la_funded_places/order.html.erb, app/views/school/la_funded_places/show.html.erb, config/routes.rb, spec/features/school/order_devices_spec.rb
Re-enable ordering page for Schools.
This is simply to reinstate the current page as is for review, copy changes for the new service will be new PRs.
Fixed weird error for `Computacenter::TechSourceMaintenanceBannerComponent.new` requiring 1 param.
=> Order devices page for a school

.github/workflows/build-push-and-deploy-preview-container.yml, .github/workflows/build.yml, config/manifests/preview-manifest.yml
The `reopening` branch will be used to manage all changes related to reopening the service.
PRs should be checked against the specs.
Mergers into the `reopening` branch should be automatically pushed to the `preview` app on PaaS.
Updated the `build` GitHub action to run on PRs on the `reopening` branch.
Added the `build-push-deploy-preview-conatiner` GitHub action to deploy the `reopening` branch changes to the `preview` app on PaaS.
Check that the specs are run on the new PR.
After merger check that the `preview` app on PaaS is updated.
=> Add GitHub action for mergers into reopening branch

.github/workflows/build-push-and-deploy-preview-container.yml
There is an error in the preview deploy GitHub action during the retrieval of the Docker image ID
```
/home/runner/work/_temp/8a10a5af-ffca-4eee-b9ac-25fe92a6c085.sh: command substitution: line 5: syntax error near unexpected token `docker'
/home/runner/work/_temp/8a10a5af-ffca-4eee-b9ac-25fe92a6c085.sh: command substitution: line 5: `shell (docker pull dfedigital/get-help-with-tech-dev:preview > /dev/null) && docker images dfedigital/get-help-with-tech-dev:preview -q)'
```
Simplified the command
Test for success or failure on merge into `reopening`
=> Fix retrieval of Docker image ID in GH action

.github/workflows/build-push-and-deploy-preview-container.yml
The docker image is built and pushed to dockerhub correctly, but the deploy fails.
The target app name in the cf command has been changed to `-preview`
Deploy and check `healthcheck.json`
=> Fix target cf app name for preview env

.github/workflows/build-push-and-deploy-preview-container.yml
The `cf push` command did not correctly use the `docker_image_id`. It always pushed `dfedigital/get-help-with-tech-dev:latest`, however we want to push `dfedigital/get-help-with-tech-dev:preview`.
For simplicity we will use the simpler `cf push` command with the `--docker-image` param specifying the `preview` tag and without a manifest.
Deploy and check the `commit_sha` on [healthcheck.json](https://get-help-with-tech-preview.london.cloudapps.digital/healthcheck.json).
Cross check with the reopening branch on [GitHub](https://github.com/DFE-Digital/get-help-with-tech/tree/reopening) or check the `preview` tagged image on [DockerHub](https://hub.docker.com/r/dfedigital/get-help-with-tech-dev/tags?page=1&ordering=last_updated) and look for line 48 `ENV GIT_COMMIT_SHA=`
=> Simplify CF push command

app/components/tranche_allocation_component.html.erb, app/components/tranche_allocation_component.rb, app/components/tranche_allocation_component_factory.rb, app/controllers/application_controller.rb, app/models/school.rb, app/services/trust_update_service.rb, app/views/responsible_body/home/show.html.erb, app/views/school/home/show.html.erb, spec/components/tranche_allocation_component_factory_spec.rb, spec/components/tranche_allocation_component_spec.rb, spec/features/responsible_body/home_spec.rb, spec/features/school/view_school_details_spec.rb, spec/services/trust_update_service_spec.rb
https://trello.com/c/4K84Z98e
https://trello.com/c/bV64QkKj
`configure_scope` vs `with_scope`: https://docs.sentry.io/platforms/ruby/guides/rack/enriching-events/scopes/
=> 2372 and 2373 display allocation component

config/manifests/preview-manifest.yml
The magic authentication link does not work in the preview environment.
`GHWT__HOSTNAME_FOR_URLS: preview-get-help-with-tech.education.gov.uk`
In the manifest we have set:
`GHWT__HOSTNAME_FOR_URLS: get-help-with-tech-preview.london.cloudapps.digital`
Deploy and sign in on the `preview` env.
=> Fix magic link for preview env authentication

app/controllers/assets_controller.rb, app/models/asset.rb, app/views/assets/index.html.erb, lib/search_serial_number_parser.rb, spec/controllers/assets_controller_spec.rb, spec/lib/search_serial_number_parser_spec.rb, spec/models/asset_spec.rb
https://trello.com/c/v6vdcPH4
Spotted a bug where single serial number didn't work if there was leading or trailing whitespace. Also it was telling all users they could do a multiple search in all cases, even if they couldn't
=> Make asset serial number search case-insensitive

app/models/school.rb, app/services/allocation_over_order_reverting_service.rb
- fix method call: replace `quantity.negative` with `quantity.negative?`
- add  methods to school that return  full raw allocation numbers info.
- refactor scope
- rename `give_back_cap_across_virtual_cap_pool` method
=> fix over order reverting bug

app/controllers/computacenter/api/cap_usage_controller.rb, app/models/computacenter/api/cap_usage_update.rb, app/models/computacenter/api/cap_usage_update_batch.rb, app/models/computacenter/api/cap_usage_update_payload.rb, app/models/computacenter/devices_ordered_update.rb, db/migrate/20211106171214_create_cap_usage_update_payload.rb, db/migrate/20211107180047_add_cap_usage_update_payload_id_to_devices_ordered_update.rb, db/schema.rb, spec/controllers/computacenter/api/cap_usage_controller_spec.rb, spec/features/api/cap_usage_bulk_update_spec.rb, spec/models/computacenter/api/cap_usage_update_spec.rb
Doesn't interfere with the process just store the XML payloads and keep track of status and completion.
Todo:
=> Store batch xml payloads

app/models/responsible_body.rb, app/services/allocation_over_order_reverting_service.rb, app/services/update_school_devices_service.rb, spec/services/update_school_devices_service_spec.rb
1.- Our system:
```
school A: allocation: 100,  cap: 100, ordered: 0
school B:  allocation: 100,  cap: 100, ordered: 0
total vcap: allocation: 200, cap: 200, ordered: 0 
```
We report CC:
```
school A: cap: 200
school B: cap: 200
```
2.- Over order happen: CC tell us schoolB ordered 400
Our system: (borrow 100 from school A and borrow 200 from nowhere)
```
school A: allocation: 100,  cap: 0, ordered: 0
school B:  allocation: 100,  cap: 400, ordered: 400
total vcap: allocation: 200, cap: 400, ordered: 400
```
We report CC:
```
school A: cap: 0
school B: cap: 400
```
3.- Over order cancellation happen: CC tell us schoolB ordered 200 instead of 400
Our system: (retuns the stolen cap (100) to school A and return 100 to nowhere)
```
school A: allocation: 100,  cap: 100, ordered: 0
school B: …
```
=> First return cap borrowed from nowhere and then cap borrowed from vcap sibblings

app/form_objects/support/allocation_form.rb, app/form_objects/support/enable_orders_form.rb, app/jobs/allocation_job.rb, app/models/cap_change.rb, app/models/computacenter/api/cap_usage_update.rb, app/models/responsible_body.rb, app/models/school.rb, app/services/allocation_over_order_reverting_service.rb, app/services/allocation_over_order_service.rb, app/services/import_device_allocations_service.rb, app/services/school_update_service.rb, app/services/update_school_devices_service.rb, spec/controllers/support/schools/devices/order_status_controller_spec.rb, spec/factories/schools.rb, spec/features/support/viewing_responsible_body_info_spec.rb, spec/form_objects/support/allocation_form_spec.rb, spec/jobs/allocation_job_spec.rb, spec/jobs/calculate_vcap_job_spec.rb, spec/models/cap_change_spec.rb, spec/models/responsible_body_spec.rb, spec/services/allocation_over_order_service_spec.rb, spec/services/cap_update_notifications_service_spec.rb, spec/services/device_supplier/export_allocations_service_spec.rb, spec/services/update_school_devices_service_spec.rb
Allocation numbers of schools in vcaps need adjustment not only when a school allocation numbers change but also when a school is added or removed to/from a vcap to another, a school changes rb, a school changes who will order devices, etc.
This leads us to think the adjustments of cap should be done at vcap level (when recomputing vcaps) rather than when updating school allocations (UpdateSchoolDeviceService).
This should avoid automatically some of the defects we had been having these days in some cases of over ordering and rollbacks, schools in and out of vcaps, vcaps with some schools that can order and some not, ...
This PR:
- moves the lend/borrowing cap mechanism inside vcaps 
- automatically rebalance vcaps over order numbers whenever the vcap numbers need recalculation
- Register …
=> Improve over orders

app/models/responsible_body.rb, app/models/school.rb, app/services/allocation_over_order_reverting_service.rb, app/services/allocation_over_order_service.rb, spec/models/responsible_body_spec.rb
After Friday observation of the status of all the schools and vcaps about routers I realized we could improve the over orders algorithm on schools set to cannot_order: we should return their reclaimed vcap first thing when balancing over order caps and should not reclaim their available cap when over orders happen. 
The changes described above and some tests to confirm this was actually needed.
=> clean over order reclaimed cap from schools that cannot order in vcap asap

app/models/responsible_body.rb, app/models/school.rb, app/services/update_school_devices_service.rb, spec/controllers/support/schools/devices/order_status_controller_spec.rb, spec/form_objects/support/allocation_form_spec.rb, spec/form_objects/support/school/change_responsible_body_form_spec.rb
Users keep ordering the full allocation of a vcap besides we are sending CC a cap lower than that due to schools that cannot_order.
At the same time, on Friday I found an rb that placed not only an over-order for routers but on a school in the vcap that cannot_order.
This PR will not send CapUpdateCall records to CC api for schools in a vcap that cannot_order.
At least this should prevent orders placed on such schools and maybe this also helps to reduce the number of over-orders in Techsource.
After we put this live we should go to the console and send records to CC api for these schools so they receive 0 devices available
=> do not notify CC devices for schools that cannot order in vcaps

app/models/user.rb, app/services/device_supplier/export_users_service.rb, spec/models/user_spec.rb, spec/services/device_supplier/export_users_service_spec.rb
An rb user who is also an FE College user appeard in the suplier export to only have the rb sold_to
RB users will also list associated school sold_tos
Specs were added to cover the exact scenario
=> Add multiple sold_tos for rb users

app/controllers/computacenter/home_controller.rb, app/models/computacenter/responsible_body_urns.rb, app/views/computacenter/home/show.html.erb, spec/models/computacenter/responsible_body_urns_spec.rb
The device supplier was receiving new rbs to create even when said rbs had zero schools
Update the filter for relevant rbs to also omit rbs with zero schools
Check the supplier portal to ensure that only rbs with associated schools appear in the list
=> Hide rbs with zero schools

app/form_objects/support/bulk_allocation_form.rb, spec/fixtures/files/allocation_upload.csv, spec/form_objects/support/bulk_allocation_form_spec.rb
[Card](https://trello.com/c/jdjjt0oq): allow absolute allocations to be uploaded
Add an alternative new column "allocation" to bulk allocation csv files to set absolute allocation values as opposed to deltas.
A mix of delta and absolute allocation schools are allowed in the same file.
If a school has both set, delta allocation will be ignored and absolute allocation will prevail.
=> Add absolute allocation column to allocation bulk upload csv files

.github/workflows/build-push-and-deploy-preview-container.yml, .github/workflows/build.yml
In the buildup to the winter 2021 reopening of the service we used branch named `reopening` to automatically run the test suite and deploy to a `preview` environment.
Rename `reopening` to `preview` in the GH workflows.
Create a `preview` branch and see that the test suite runs and the `preview` env is deployed.
The `preview` env is configured in [config/manifests/preview-manifest.yml](https://github.com/DFE-Digital/get-help-with-tech/blob/main/config/manifests/preview-manifest.yml).
=> Rename reopening branch for automation to preview

README.md, app/components/site_banner_component.html.erb, app/components/site_banner_component.rb, app/controllers/application_controller.rb, app/models/site.rb, app/views/layouts/application.html.erb, config/settings.yml, spec/components/site_banner_component_spec.rb, spec/features/site_banner_spec.rb
For the upcoming Christmas period a site wide banner is required to notify site visitors that deliveries will be paused.
The optional env var `GHWT__SITE_BANNER_MESSAGE` can be used to set the text for a site wide banner message.
In local dev launch the app with the env var present:
`GHWT__SITE_BANNER_MESSAGE=hello bundle exec rails s`
=> Add a site wide banner

.rubocop.yml, app/services/feature_flag.rb, lib/rubocop/cop/lint/unknown_feature_flag.rb, spec/controllers/support/users_controller_spec.rb, spec/lib/rubocop/cop/lint/unknown_feature_flag_spec.rb, spec/support/rubocop.rb
Some envars to enable/disable legacy feature flags still exist on all enviroments.
When we undefine a feature flag, the code calling it must be refactored as well.
- Rubocop custom cop to detect when code is still checking the status of feature flags that have been removed.
- Review all FEATURES_* envars in the existing environments to remove the legacy ones.
- A single list of feature flag keys is enough to cope with our needs. Temporary list is not needed anymore.
=> 2371 clean feature flags

app/controllers/support/users_controller.rb, app/views/support/users/search.html.erb, config/routes.rb, spec/features/support/exporting_users_spec.rb, spec/page_objects/support/users/search_page.rb
Support want the ability to export only school and rb users
Add a checkbox to the support export users form
=> Add a tick box for support audit export users

app/controllers/support/users_controller.rb, app/models/user.rb, spec/features/support/exporting_users_spec.rb
The non-audit user export includes soft-deleted users.
Add the `not_deleted` scope to the query.
Check the non-audit user export for soft-deleted users.
=> Fix inclusion of deleted users in non-audit export

app/controllers/support/users_controller.rb, app/models/responsible_body.rb, app/models/user.rb, app/views/support/schools/results.html.erb, spec/features/support/searching_schools_spec.rb
Given a batch of schools there is no method of retrieving related email addresses. This is required for the custom emails sent via Notify in the lead up to service closure.
Add a `Download users as CSV` button to `Search for multiple schools by URN or UKPRN` results page.
=> Support scoped export users by schools

app/controllers/support/schools_controller.rb, app/services/allocations_exporter.rb, app/views/support/home/schools.html.erb
Support require a periodical export of all school allocations.
Add a button in the support area to download all school allocations as a csv file.
=> Add button to export all allocations

Gemfile, Gemfile.lock, app/form_objects/support/bulk_allocation_form.rb, app/jobs/bulk_allocation_job.rb, config/manifests/dev-manifest.yml, config/manifests/preview-manifest.yml, config/manifests/prod-manifest.yml, config/manifests/staging-manifest.yml, config/settings.yml, spec/controllers/support/schools/devices/order_status_controller_spec.rb, spec/features/support/schools/bulk_upload_allocation_spec.rb, spec/form_objects/support/bulk_allocation_form_spec.rb, spec/jobs/bulk_allocation_job_spec.rb, spec/support/aws_s3_helper.rb
Tranches uploaded by a support user needs to made accessible to Sidekiq to read and process them. 
Govuk Paas allows the use of S3 as a backend service for our apps. 
- Added [aws-s3-bucket service](https://docs.cloud.service.gov.uk/deploying_services/s3/#amazon-s3) manually to our apps in all envs
- Bind services - apps in the manifest files.
- Change the logic of bulk allocation uploads to write and read the user file to/from S3.
I would like to isolate S3 stuff into our own wrapper class so the entities using it (`BulkAllocationForm`  and `BulkAllocationJob`) don't have to deal with the S3 client itself. 
Due to deadline restrictions I will leave it for the future.
=> 2674: store tranche files into S3 to be able to share them with Sidekiq

app/form_objects/support/bulk_allocation_form.rb, app/jobs/bulk_allocation_job.rb, config/initializers/aws_s3.rb, config/settings.yml, lib/v_cap_services_config.rb, spec/controllers/support/schools/devices/order_status_controller_spec.rb, spec/form_objects/support/bulk_allocation_form_spec.rb, spec/support/aws_s3_helper.rb
Adding and binding aws-s3-bucket service to the app automatically adds some envars but we still need to explicitly initialiase the client from those envars.
=> 2674: initialize AWS S3 explicitly from automatic envars

app/controllers/support/allocation_batch_jobs_controller.rb, app/views/support/allocation_batch_jobs/show.html.erb
- Rename var to be different to the existing @jobs instance var.
- Add @batch_id instance var to be used by the template so it gets displayed even when jobs have not started execution yet.
=> 2674: little refactor

app/controllers/school/users_controller.rb, app/controllers/support/users_controller.rb, app/policies/school_policy.rb, app/services/create_user_service.rb, app/views/school/users/edit.html.erb, app/views/school/users/new.html.erb, app/views/school/welcome_wizard/will_other_order.html.erb, app/views/shared/_school_user_form.html.erb, app/views/support/users/edit.html.erb, app/views/support/users/new.html.erb, spec/features/support/inviting_school_users_spec.rb
Extension of a previous [PR](https://github.com/DFE-Digital/get-help-with-tech/pull/2468) to:
- exclude the order_devices field from the form when inviting a user to a school centrally managed by its rb.
- ignore the orders_devices param in the update action for a non-order-devices-eligible school user.
- set a false default value on orders_devices property for non-order-devices-eligible users invited to a school.
=> 2755: ignore orders_devices param for not eligible users

app/services/create_user_service.rb
[Card](https://trello.com/c/mBOeEHcN)
When a school user is invited to join GHwT, devolve management to the school only if it is not already set.
=> 2790: devolve management only to schools with no who_will_order_devices set

app/components/responsible_body/school_details_summary_list_component.rb, app/components/school/school_details_summary_list_component.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/features/responsible_body/devices_setup_spec.rb, spec/features/support/changing_who_will_order_devices_for_a_school_spec.rb
I merged this [PR](https://github.com/DFE-Digital/get-help-with-tech/pull/2507) into preview instead of main by mistake.
This PR will revert the changes to disable support user permissions to edit school details.
These changes should go straight into main and not preview.
=> 2816: revert disable support user permissions to edit school details

app/components/responsible_body/school_details_summary_list_component.rb, app/components/school/school_details_summary_list_component.rb, app/controllers/school/base_controller.rb, app/policies/school_policy.rb, spec/components/responsible_body/school_details_summary_list_component_spec.rb, spec/components/school/school_details_summary_list_component_spec.rb, spec/components/support/school_details_summary_list_component_spec.rb, spec/controllers/support/schools/headteacher_controller_spec.rb, spec/controllers/support/schools/responsible_body_controller_spec.rb, spec/controllers/support/schools_controller_spec.rb, spec/features/responsible_body/devices_setup_spec.rb, spec/features/support/addresses_spec.rb, spec/features/support/adjusting_a_schools_allocation_spec.rb, spec/features/support/adjusting_a_schools_router_allocation_spec.rb, spec/features/support/changing_who_will_order_devices_for_a_achool_spec.rb, spec/features/support/enabling_orders_for_a_school_spec.rb, spec/features/support/managing_schools_spec.rb, spec/features/support/schools/change_headteacher_spec.rb, spec/features/support/schools/change_responsible_body_spec.rb, spec/features/support/schools/opt_out_spec.rb, spec/policies/school_policy_spec.rb, spec/support/summary_list_helper.rb
[Disable support user permissions to update school details](https://trello.com/c/2NTw6Oxc)
=> 2816: disable support user permissions to edit school details

app/controllers/support_ticket/base_controller.rb
There is an edge case in a support form when a user clears their session information (cookies etc) before submitting the form.
We will force creation of a session before trying to find or create a support ticket based on a session_id.
1.  Visit the support form at /get-support/support-details.
2. Clear session info from the browser.
3. Complete the form and submit.
4. There should be a session_id value stored in the new SupportTicket record.
=> 2835 support form issue

spec/features/support_ticket/create_support_ticket_spec.rb, spec/page_objects/support_ticket/check_your_request_page.rb, spec/page_objects/support_ticket/contact_details_page.rb, spec/page_objects/support_ticket/describe_yourself_page.rb, spec/page_objects/support_ticket/get_support_page.rb, spec/page_objects/support_ticket/school_details_page.rb, spec/page_objects/support_ticket/support_details_page.rb, spec/page_objects/support_ticket/support_needs_page.rb, spec/page_objects/support_ticket/thank_you_page.rb
The support form is missing end-to-end specs
Added basic spec covering the end-to-end creation and submission of a request using the support form
Only specs added, but the journey can be followed at /get-support
=> Add support form specs

app/controllers/errors_controller.rb, spec/controllers/errors_controller_spec.rb
The service is throwing an exception everytime the forbidden template needs to be rendered.
[Card](https://trello.com/c/ryjJWYcP)
- Redefine the controller action following Rails conventions. 
- Add a couple of tests to make sure no exception is raised and the template is rendered successfully.
=> 2891: fix error when rendering the forbidden template

app/views/assets/show.html.erb, spec/features/assets/show_spec.rb
[Card](https://trello.com/c/RjYliEYs)
Don´t display asset tag on asset details view
=> 2898: do not display asset tag on asset details view

app/components/nav_component.rb, config/routes.rb, spec/controllers/computacenter/api/cap_usage_controller_spec.rb, spec/features/api/cap_usage_bulk_update_spec.rb, spec/features/computacenter/api_tokens_behaviour_spec.rb, yarn.lock
- Disable routes to manage api tokens to our API
- Remove menu entry for CC users to be able to manage GHwT api tokens
- Skip related test cases.
Also as part of [card 2901](https://trello.com/c/jmgnCfAy), via console, I have:
-  removed the environment variable with the url to the CC API endpoint to update settings cap so requests no longer get sent when any cap changes happens in GHwT.
- revoked all ApiToken entries to GHwT API so requests to GHwT API are no longer accepted.
=> 2901: disable api comms with CC

app/controllers/orders_controller.rb, app/models/computacenter/order_report.rb, app/models/computacenter/raw_order_map.rb, app/models/responsible_body.rb, app/models/school.rb, app/models/user.rb, app/policies/computacenter/order_policy.rb, app/services/computacenter/export_orders_service.rb, app/services/computacenter/export_orders_to_file_service.rb, app/views/orders/index.html.erb, config/routes.rb, db/migrate/20220509152332_change_shipto_and_soldto_to_be_string_in_computacenter_orders.rb, db/migrate/20220510115957_add_index_on_order_date_on_computacenter_orders.rb, db/schema.rb, spec/controllers/orders_controller_spec.rb, spec/factories/computacenter/orders.rb, spec/factories/computacenter/raw_orders.rb, spec/factories/responsible_bodies.rb, spec/factories/schools.rb, spec/features/orders/index_spec.rb, spec/models/computacenter/raw_order_map_spec.rb, spec/models/responsible_body_spec.rb, spec/models/user_spec.rb, spec/policies/computacenter/order_policy_spec.rb, spec/services/computacenter/convert_raw_orders_service_spec.rb, spec/services/computacenter/export_orders_to_file_service_spec.rb
Users should be able to view and download orders associated with the schools and responsible bodies that they manage.
Add a view to expose orders for a users related schools and responsible bodies.
check `/orders`
=> Add order views

app/controllers/orders_controller.rb
On the orders view the export button only exports the current page of orders
Update the code so the export covers all orders in scope
Visit `/orders` and click export and ensure the csv has all orders.
=> Fix orders bug that limits to page results

app/controllers/orders_controller.rb, app/models/computacenter/order.rb, app/views/orders/index.html.erb, spec/controllers/orders_controller_spec.rb, spec/models/computacenter/order_spec.rb
The `/orders` index should not show returns.
Add a scope `is_not_return` to the `Order` model and apply it in the Orders controller.
Check the `/orders` page as admin and ensure returns are not listed. Returns will typically have negative quantity values.
=> Limit order index to exclude returns

app/controllers/orders_controller.rb, app/policies/computacenter/order_policy.rb, spec/controllers/orders_controller_spec.rb, spec/features/orders/index_spec.rb, spec/policies/computacenter/order_policy_spec.rb
Support users should be able to view the correct subset of orders whilst impersonating
Add the impersonated user to the scope in the Orders controller
Impersonate a user and visit `/orders`
=> Scope orders to impersonated user

app/models/computacenter/order_report.rb, app/views/orders/index.html.erb, spec/services/computacenter/export_orders_to_file_service_spec.rb
Use quantity completed instead of ordered in the orders view and export
Add `quantity_completed` as the preferred value when dealing with quantities for the orders view and export.
Orders view should now have the heading `Devices delivered`
=> Use quantity completed instead of ordered

app/jobs/bulk_restricted_device_password_emailing_job.rb, app/models/responsible_body.rb, app/models/school.rb, db/migrate/20220523064229_index_responsible_bodies_by_name.rb, db/schema.rb, spec/jobs/bulk_restricted_device_password_emailing_job_spec.rb, spec/models/responsible_body_spec.rb, spec/models/school_spec.rb
- Add offset to BulkRestrictedDevicePasswordEmailingJob so we can first notify passwords to a few schools/rbs and then the rest
- Order schools/rbs to be notified by name instead of created_at
- Add missing index by order to ResponsibleBody
=> 2923: add offset to bulk closure password notification job

config/sidekiq.yml
Currently `default` queue in sidekiq has top priority and no job in the rest of queues will be executed until it is fully empty. Similarly the `mailer` queue has full priority over `scheduler`: hierarchical definition.
This makes sometimes the `mailer` queue to acummulate thousands of pending emails and the `scheduler` queue to acummulate pending repetitive scheduled jobs.
Better make them all be served in parallel with weighted priorities.
=> add weights to sidekiq queues to make them all be served in parallel.

app/services/session_service.rb, config/sidekiq.yml
emails with links for users to log into the system are sometimes delayed or stuck if heavy jobs are running in all the background workers
Create a top priority queue named :login and enqueue all login email jobs in that queue so a login link email will always be delivered first when a worker becomes free.
=> deliver login emails with top priority
